In [1]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Draw
from IPython.display import display

In [2]:
gen_sam_all_0223 = pd.read_csv("../data/generated/sam_gen_0223.csv")
gen_sam_all_2024 = pd.read_csv("../data/generated/gen_sam_all.csv")
gen_sam_all = pd.concat([gen_sam_all_2024, gen_sam_all_0223])
gen_sam_all_drop = gen_sam_all.drop_duplicates(keep='first', subset='smiles').reset_index(drop=True)
print(gen_sam_all_drop.shape)

(193438, 6)

In [3]:
gen_sam_all_drop.reset_index(drop=True, inplace=True)
print(gen_sam_all_drop.shape)

(193438, 6)

Substructures matching

In [4]:
#按骨架核心分类
df_copy = gen_sam_all_drop.copy()

df_1 = pd.DataFrame(columns=df_copy.columns)
df_2 = pd.DataFrame(columns=df_copy.columns)
df_3 = pd.DataFrame(columns=df_copy.columns)
df_4 = pd.DataFrame(columns=df_copy.columns)
df_5 = pd.DataFrame(columns=df_copy.columns)
df_6 = pd.DataFrame(columns=df_copy.columns)
df_7 = pd.DataFrame(columns=df_copy.columns)

# 链状
for index, row in df_copy.iterrows():
    smiles = row['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        ring_info = mol.GetRingInfo()
        num_rings = ring_info.NumRings()
        if num_rings == 0:
            df_1 = pd.concat([df_1, pd.DataFrame([row])], ignore_index=True)
            df_copy.drop(index, inplace=True)

# 萘酰胺
patt_1 = Chem.MolFromSmiles('O=C1NC(=O)C2=CC=CC3=C2C1=CC=C3')
for index, row in df_copy.iterrows():
    smiles = row['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
       print(f"Invalid SMILES: {smiles}")
       continue  # 跳过这一行
    if mol.HasSubstructMatch(patt_1):
        df_2 = pd.concat([df_2, pd.DataFrame([row])], ignore_index=True)
        df_copy.drop(index, inplace=True)

# 三苯胺
patt_2 = Chem.MolFromSmiles('C1=CC=C(C=C1)N(C1=CC=CC=C1)C1=CC=CC=C1')
for index, row in df_copy.iterrows():
    smiles = row['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
       print(f"Invalid SMILES: {smiles}")
       continue  # 跳过这一行
    if mol.HasSubstructMatch(patt_2):
        df_3 = pd.concat([df_3, pd.DataFrame([row])], ignore_index=True)
        df_copy.drop(index, inplace=True)

# 咔唑
patt_3 = Chem.MolFromSmiles('N1C2=C(C=CC=C2)C2=C1C=CC=C2')
for index, row in df_copy.iterrows():
    smiles = row['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
       print(f"Invalid SMILES: {smiles}")
       continue  # 跳过这一行
    if mol.HasSubstructMatch(patt_3):
        df_4 = pd.concat([df_4, pd.DataFrame([row])], ignore_index=True)
        df_copy.drop(index, inplace=True)

# 联噻吩
patt_4 = Chem.MolFromSmiles('S1C=CC=C1C1=CC=CS1')
for index, row in df_copy.iterrows():
    smiles = row['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
       print(f"Invalid SMILES: {smiles}")
       continue  # 跳过这一行
    if mol.HasSubstructMatch(patt_4):
        df_5 = pd.concat([df_5, pd.DataFrame([row])], ignore_index=True)
        df_copy.drop(index, inplace=True)

# 单环
for index, row in df_copy.iterrows():
    smiles = row['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
       print(f"Invalid SMILES: {smiles}")
       continue  # 跳过这一行
    if mol is not None:
        ring_info = mol.GetRingInfo()
        num_rings = ring_info.NumRings()
        if num_rings == 1:
            df_6 = pd.concat([df_6, pd.DataFrame([row])], ignore_index=True)
            df_copy.drop(index, inplace=True)

# 其他
df_7 = df_copy.copy()

[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 13 C, 4, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 14 C, 4, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 14 C, 4, is greater than permitted
[12:39:44] Explicit valence for atom # 13 C, 4, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:44] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:39:46] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:39:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:47] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:39:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:47] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:39:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:49] Explicit valence for atom # 41 P, 7, is greater than permitted
[12:39:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:49] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:39:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:49] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:39:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:50] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:39:50] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:39:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:51] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:39:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:39:51] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C(Cl)=C(Cl)C(Cl)=C1Cl
Invalid SMILES: O=[PH]1(O)(O)SC(C(F)(F)F)=C1Cl
Invalid SMILES: O=P(=O)(O)(O)c1ccc(C(F)(F)F)cc1
Invalid SMILES: O=[PH](O)(O)=C1SC(Cl)=C1Cl
Invalid SMILES: N#Cc1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=C1SC(C(F)(F)F)=C1F
Invalid SMILES: O=[PH](O)(O)=C1SC(F)(F)C(F)(F)C1(F)F
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C(F)(F)F)=C1
Invalid SMILES: O=[PH](O)(O)=C1C(F)C(F)(F)C1(F)F
Invalid SMILES: O=[PH](O)(O)=C1C(F)C(F)(F)C(F)(F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)CCN1C=CC=CC1
Invalid SMILES: O=P(=O)(O)(O)c1ccncc1
Invalid SMILES: O=P(=O)(O)(O)CCNc1ncc[nH]1
Invalid SMILES: O=C(O)[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)F)NC(F)(F)C(F)(F)C(F)(F)C(F)(F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)c1cc[nH]c1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(F)C(F)(F)C(F)(F)C(F)(F)F)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(Cl)C(Cl)=C1Cl
Invalid SMILES: O=P(=O)(O)(O)c1ccc(Cl)cc1
Invalid SMILES: O=P(=O)(O)(O)Cn1ccnc1
Invalid SMILES: O=C(O)Nc1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=[N+]([O-])c1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(N(F)CC(F)(F)F)C=C1
Invalid SMILES: Cn1cncc1P(=O)(=O)(O)O
Invalid SMILES: O=[PH](=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1cn(C(F)(F)F)cn1
Invalid SMILES: O=P(=O)(O)(O)c1ncc[nH]1
Invalid SMILES: O=P(=O)(O)(O)c1c[nH]cn1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(Nc2ncc[nH]2)cc1
Invalid SMILES: O=P(=O)(O)(O)CCN(CCO)Cc1nccn1C(F)(F)F
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccncc1
Invalid SMILES: O=[PH](O)(O)=C1C=CN=C1
Invalid SMILES: O=P(=O)(O)(O)CCN1CC=CC1
Invalid SMILES: O=P(=O)(O)(O)CCn1ccnc1
Invalid SMILES: N#CN(F)C1=C(P(=O)(=O)(O)O)C=C1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C=C/C=C/C(F)(F)F)N1
Invalid SMILES: O=P(=O)(O)(O)CNc1ncc[nH]1
Invalid SMILES: O=P(=O)(O)(O)NCCNc1ncc[nH]1
Invalid SMILES: O=P(=O)(O)(O)c1ccccc1
Invalid SMILES: O=C(O)NC1=C(CP(=O)(=O)(O)O)C=C1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1nccn1C(F)(F)F
Invalid SMILES: N#Cc1ccc([PH](=O)(O)(O)O)cc1
Invalid SMILES: O=CN(F)c1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)F)NC(F)(F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)c1cn(C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)C(F)(F)C(F)(F)F)cn1
Invalid SMILES: N#Cc1ccc(CP(=O)(=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccncc1
Invalid SMILES: O=P(=O)(O)(O)c1cc[nH]c1C(F)(F)F
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)F)N=C1
Invalid SMILES: O=[PH](O)(O)(O)CCN1CC=CC1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2cccc(F)c2)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)C(F)(F)C(F)(F)F)N1
Invalid SMILES: Nc1[nH]c(OCP(=O)(=O)(O)O)nc1C(F)(F)F
Invalid SMILES: O=P(=O)(O)(O)c1nc(C(F)(F)F)c[nH]1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccncc1
Invalid SMILES: O=CN(F)C1=C(P(=O)(=O)(O)O)C=C1
Invalid SMILES: O=P(=O)(O)(O)C1=CC=C1
Invalid SMILES: O=P(=O)(O)(O)c1ccccn1
Invalid SMILES: O=C1CCCN1CCP(=O)(=O)(O)O
Invalid SMILES: O=C(CCNc1ncc[nH]1)[PH](=O)(O)(O)Cl
Invalid SMILES: O=P(=O)(O)(O)C1=C(c2ccccc2Nc2cc[nH]c2)C=C1
Invalid SMILES: N#CC1=C(P(=O)(=O)(O)O)C=C1
Invalid SMILES: O=P(=O)(O)(O)CCN1CCOCC1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1nc(O)c(C(F)(F)F)n1C(F)(F)F
Invalid SMILES: Cn1nccc1CN(CCO)CP(=O)(=O)(O)O
Invalid SMILES: O=C(CCN1CC=CC1)[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1ccc(Br)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)c1ccc(C(F)(F)C(F)(F)F)cc1
Invalid SMILES: O=C(c1ccccc1)[PH](=O)(O)(O)O
Invalid SMILES: N#Cc1ccc(C[PH](=O)(O)(O)O)cc1
Invalid SMILES: O=C1NC(C(F)(F)F)=C(P(=O)(=O)(O)O)C1(F)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccccc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc[nH]1
Invalid SMILES: O=P(=O)(O)(O)CCNc1nc(C(F)(F)F)c[nH]1
Invalid SMILES: O=[PH](O)(O)(O)C(O)=C1N=CC(O)=N1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(F)=C1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=N/C=C\c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1
Invalid SMILES: O=[PH]1(O)(O)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccccc1O
Invalid SMILES: O=P(=O)(O)(O)c1cc(O)c(O)c(O)c1
Invalid SMILES: O=[PH](O)(O)=C1C=C=C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=Cc1cc(O)c(O)c(O)c1
Invalid SMILES: O=P(=O)(O)(O)NCc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=C1C(F)=C=C=C1F
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C(Cl)=CC(Cl)=C1Cl
Invalid SMILES: O=[PH](O)(O)=C1C=CC=CC1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccccc1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccccc1O
Invalid SMILES: O=Cc1c(O)c(O)c(O)c(O)c1P(=O)(=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1cc(O)ccc1O
Invalid SMILES: O=P(=O)(O)(O)Nc1c(F)c(F)c(F)c(F)c1F
Invalid SMILES: O=[PH](O)(O)=C1C=CC(F)(F)C=C1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(F)cc1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ncccc1O
Invalid SMILES: O=[PH](O)(O)(O)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=N1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2cccs2)s1
Invalid SMILES: O=P(=O)(O)(O)C=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=P(=O)(O)(O)C(=Cc1ccc(-c2cccs2)s1)c1cccs1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=C(O)C(=C/C=C\c1ccc(-c2cccs2)s1)P(=O)(=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)CCNc1sc(-c2cccs2)cc1C(F)(F)F
Invalid SMILES: O=P(=O)(O)(O)C(=Cc1ccc(-c2cccs2)s1)c1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=P(=O)(O)(O)CC=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(c1cccs1)c1cccs1
Invalid SMILES: O=P(=O)(O)(O)c1c(F)sc(-c2cccs2)c1F
Invalid SMILES: O=C(O)C(=Cc1ccc(-c2cccs2)s1)P(=O)(=O)(O)O
Invalid SMILES: O=C(O)c1cc(-c2cccs2)sc1P(=O)(=O)(O)O
Invalid SMILES: O=S(=O)(O)c1sc(-c2cccs2)c(P(=O)(=O)(O)O)c1Cl
Invalid SMILES: O=[PH](O)(O)(F)c1ccc(-c2cccs2)s1
Invalid SMILES: O=C(F)c1ccc(C(=C/C=C\C=C\C(F)(F)F)[PH](=O)(O)(O)O)cc1
Invalid SMILES: Nc1sc(-c2cccs2)c(C(=O)O)c1P(=O)(=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1sc(-c2sc(F)c(F)c2F)c(F)c1F
Invalid SMILES: O=P(=O)(O)(O)CCNc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(-c2cccs2)cc1
Invalid SMILES: O=P(=O)(O)(O)/C=C/c1ccc(-c2cccs2)s1
Invalid SMILES: O=C(O)C(=C/C=C\c1ccc(-c2cccs2)s1)[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)CCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C1c2ccccc2-c2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Cc2ccccc21
Invalid SMILES: O=[PH]1(O)(O)c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccc(Br)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Sc2cc(Br)ccc21
Invalid SMILES: O=P(O)(O)CCN1c2ccccc2[CH2+]c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=c1[nH]c2ccccc2c2ccccc12
Invalid SMILES: O=P(O)(O)CCN1c2ccc(Br)cc2[CH2+]c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=C1Nc2ccccc2[SiH-]c2ccccc21
Invalid SMILES: O=[PH](O)(O)=NCN1c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(O)(O)CCN1c2ccc(Br)cc2[CH2+]c2ccc(Br)cc21
Invalid SMILES: O=P(O)(O)CCN1c2ccccc2[CH2+]c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Sc2ccccc21

[12:40:47] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:40:47] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:40:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:47] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:48] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2cccc3cccc1c23
Invalid SMILES: O=C1c2ccccc2[PH](=O)(O)(O)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CCCCOc1cc2c(c3ccccc13)Sc1ccc(O)cc1S2
Invalid SMILES: O=[PH]1(O)(O)c2ccccc2Sc2c1sc1ccccc21
Invalid SMILES: O=[PH](O)(O)=C1c2c(sc3ccccc23)-c2sc3ccccc3c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2cc(Br)ccc2c2c3cc(S(=O)(=O)O)ccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3ccccc3ccc21
Invalid SMILES: Cn1c2ccccc2c2cc(C=CC=[PH](=O)(O)O)ccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1cccc(N(c2ccccc2)c2ccccc2)c1
Invalid SMILES: O=P(=O)(O)(O)CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)CP(=O)(=O)(O)O
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1cccc(N(c2ccccc2)c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)(O)CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(CCCP(=O)(=O)(O)O)N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(CCCP(=O)(=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(C#N)=C(CP(=O)(=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)CC1=C(N(c2ccccc2)c2ccccc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-n2c3ccccc3c3ccccc32)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-n2c3ccccc3c3cc(Br)ccc32)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc2c1c1ccccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)(O)C1CN2CCC(CCO)(CC2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc3c4c(c2)CCCN4CCC3)s1
Invalid SMILES: O=[PH]1(O)(O)CN2CCC(CCO)(CC2)c2cc(-c3cccs3)ccc21
Invalid SMILES: O=P(=O)(O)(O)C1CCCN2CCCC3=C2C(O)(c2cccs2)CCN3CC1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2cc3c4c(c2)CCCN4CCC3)s1
Invalid SMILES: O=[PH]1(O)(O)CCC2=C(C1)c1ccc(cc1)N2CCC1=CC=C1
Invalid SMILES: O=P(=O)(O)(O)C1C=CC2CCN(C1)C(N1CCC3=CCC1=C3)C2
Invalid SMILES: O=[PH]1(O)(O)CN2CCC(O)(CCO)CC2c2cc(-c3cccs3)ccc21
Invalid SMILES: O=[PH](O)(O)(c1cc2c3c(c1)CCCN3CCC2)c1cccs1
Invalid SMILES: O=[PH]1(O)(O)C=C2CCCN3CCCC(=C23)C=C1c1cccs1
Invalid SMILES: O=[PH]1(O)(O)CCN2CCC(O)(CC1)c1cc3ccsc3cc12
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)sc1c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2c(c3ccccc31)-c1ccccc1Sc1ccccc1-2
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)sc1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3sc4ccccc4c3ccc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)oc1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCc1ccc2c(c1)sc1c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccccc2c2sc3ccccc3c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2sc3ccccc3c21
Invalid SMILES: Cn1c2c3ccc(C=C=[PH](=O)(O)O)cc3c1=c1ccccc1=c1ccccc1=2
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c3ccccc4ccccc4c-3c2c1
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccccc3c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccc(O)cc3c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)-c1c-2c2ccccc2c2ccccc12
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21

[12:40:49] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:40:49] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc(C3CCCCC3)c3cccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)c2cccc3c(C4CCCCC4)ccc1c23

[12:40:49] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:40:49] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:40:49] Explicit valence for atom # 4 P, 7, is greater than permitted

Invalid SMILES: O=C1C(=[PH](=O)(O)O)C(=O)c2ccc(-c3cccc(O)c3)c3cccc1c23
Invalid SMILES: O=C1NC(=O)c2cccc3c(-c4ccc(O)cc4)ccc(c23)C(=O)C1=[PH](=O)(O)O
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc(-c3ccccc3)c3cccc1c23

[12:40:50] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: O=C1C(=[PH](=O)(O)O)N(C(F)(F)F)C(=O)c2ccc(-c3ccc(O)cc3)c3cccc1c23

[12:40:52] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:40:52] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc2c3c(ccc(CNP(=O)(=O)(O)O)c13)C(=O)N(CCc1ccncc1)C2=O
Invalid SMILES: O=C1c2cccc3cccc(c23)C(NP(=O)(=O)(O)O)C(=O)N1CCc1ccncc1

[12:40:55] Explicit valence for atom # 21 P, 7, is greater than permitted

Invalid SMILES: O=C(O)CNc1cc2c3c(c(NCO)cc4c3c1C(=O)C(=[PH](=O)(O)O)NC4=O)C(=O)N(CO)C2=O

[12:40:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:56] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:58] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cccc2c3c(ccc12)=CC=c1ccccc1=c1ccccc1=3
Invalid SMILES: O=C(CCCCC=[PH](=O)(O)O)OC1=CC=c2ccc3c4c(ccc(c24)=C1)=c1ccccc1=CC=3
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: N#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(CP(=O)(=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccc(O)cc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc3c(c2)-c2cc(-c4ccccc4)ccc2-3)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(-c3cccc4nsnc34)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2cccc3nsnc23)cc1
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc(N(c2ccccc2)c2ccc(-c3cccc4nsnc34)cc2)cc1

[12:40:58] Explicit valence for atom # 4 P, 7, is greater than permitted

Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc3c4c(ccc1c24)C(=O)N(c1ccccc1)C3=O

[12:41:00] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:41:00] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:00] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:00] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:00] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:41:00] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: COc1ccc(N(c2ccc(C=CC=[PH](=O)(O)O)cc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)c3nsnc23)cc1
Invalid SMILES: COc1ccc(N(c2ccc(C=CC=[PH](=O)(O)O)cc2)c2ccc(-c3ccc(-c4ccccc4)cc3)c3nsnc23)cc1
Invalid SMILES: O=[PH](O)(O)=CCSc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)c3nsnc23)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=CC2)c2ccc(-c3ccc(-c4ccc5[nH]snc4-5)cc3)cc2)=C1

[12:41:03] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: O=c1c(=[PH](=O)(O)O)c(=O)c2ccc3c4ccc5c(=O)n(CO)c(=O)c6ccc(c7ccc1c2c73)c4c65

[12:41:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:07] Explicit valence for atom # 41 P, 7, is greater than permitted
[12:41:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:07] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:41:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:07] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:41:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:08] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:41:08] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:41:08] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:08] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:08] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:08] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 40 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:12] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:41:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:12] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:41:13] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:41:13] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:41:16] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:41:20] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:41:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:23] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:41:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:24] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)s3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc3[nH]c4ccc(N(c5ccccc5)c5ccccc5)cc4c3c2)cc1
Invalid SMILES: N#CC(C#N)=Cn1c2ccc(N(c3ccccc3)c3ccccc3)cc2c2cc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)ccc21
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: C=CCN(C1=CC=C1)c1ccc(-c2ccc(-c3ccc(N(C4=CC=CCC4)c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(Oc3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: CCC(C#N)=Cc1ccc(N2C=CC([PH](=O)(O)(O)CC(C)(C)C)=CC=C2c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccc(C4=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=C1SC(=[PH](=O)(O)O)SC1=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C1C(=Cc2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)SC(=[PH](=O)(O)O)N1C(=S)CO
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3cccc(-c4ccccc4)c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-n3c4ccc(-c5ccccc5)cc4c4cc(-c5ccccc5)ccc43)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(-c3ccc4c(c3)sc3cc5ccc3[nH]cccccc3cccccc4n35)cc2)cc1
Invalid SMILES: O=C(C1=CC=C1)C1=CC(NC2=CC=C2)=C2C=C(O1)c1cc(OCCCP(=O)(=O)(O)O)ccc12
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21
Invalid SMILES: O=P(=O)(O)(O)CCCCCn1c2ccccc2c2c3ccccc3ccc21
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)[nH]c1c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=Cc1cc2c(cc1O)[nH]c1ccccc12
Invalid SMILES: O=P(=O)(O)(O)Nc1ccc2c(c1)[nH]c1ccccc12
Invalid SMILES: COc1cc2[nH]c3ccccc3c2cc1PC=CC=[PH](=O)(O)O
Invalid SMILES: O=P1(O)(O)=CC=C(n2c3ccccc3c3ccccc32)C=C1
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2ccccc21
Invalid SMILES: O=P(O)(O)CCN1c2cccc(c2)-c2cc(C=[PH](=O)(O)O)ccc21
Invalid SMILES: O=P(=O)(O)(O)n1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1cc2c(cc1O)[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)[nH]c1ccccc12
Invalid SMILES: O=P(=O)(O)(O)CCCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Br)cc2ncc=2c1
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Cl)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCSc1ccc2c(c1)Nc1cc(Br)ccc1S2
Invalid SMILES: O=P(=O)(O)(O)CCN1c2ccc(Cl)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccc(Br)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(S(=O)(=O)O)cc2Sc2ccc(S(=O)(=O)O)cc21
Invalid SMILES: O=[PH](O)(O)=CN1c2ccccc2Sc2cc(Br)ccc21
Invalid SMILES: O=C(O)c1ccc2c(c1)N(P(=O)(=O)(O)O)c1ccccc1S2
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2ccc(Cl)cc21
Invalid SMILES: O=[PH](O)(O)=CN1c2ccc(Br)cc2Sc2ccc(Cl)cc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2cc(Br)c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=C1Nc2ccc(S(=O)(=O)O)cc2Sc2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3ccccc3Nc3ccccc32)cc1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)n1c2ccccc2c2cc(Cl)ccc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=c1[nH]c2ccc(Br)cc2c2ccc(Br)cc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccc(Br)cc2c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1cc2n[nH]c3ccccc3c-2n1
Invalid SMILES: O=P(O)(O)CCn1c2ccc(P(=O)(=O)(O)O)cc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=C3C(O)=CC(O)=C32)cc1
Invalid SMILES: O=C(C=[PH](=O)(O)O)OCCOC(=O)n1c2ccccc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccc(Br)cc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc(Br)ccc21
Invalid SMILES: N#CC(C#N)=Cc1ccc2c(c1)c1cc(Br)ccc1n2CC=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccc(N(C4=CC=CC4)c4ccccc4)cc3)cc(=[PH](=O)(O)O)s2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C(C(F)(F)F)OC=C2)C2=CC=c3c2cccc3=CC=C2PC=CC3=CC=CC=CCC=CN32)=C1
Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc(-c3ccc([PH](=O)(=O)O)c4nsnc34)cc2)c2ccccc12
Invalid SMILES: O=[PH](O)(O)=c1cc(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)cc(C2=CC=C2)s1
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=C(O)C1=Cc2ccc(c3c(ccc4ccc-4cccc(=CC=CC4=C=C4)n2C2=CCC(=[PH](=O)(O)O)C=C2)C=3)OC1
Invalid SMILES: O=C(O)c1ccc(C#P(=O)(O)O)cc1N(c1ccccc1)c1ccc(-c2ccc(P(=O)(O)O)c3nsnc23)cc1
Invalid SMILES: O=C1C=C2C(N(c3ccccc3)c3ccc(-c4ccc(P(=O)(O)O)c5nsnc45)cc3)=CC=C(C#P(=O)(O)O)C12
Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc(-c3ccc([PH](=O)(=O)O)c4nsnc34)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(F)cc4)cc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2F)c2nsnc12
Invalid SMILES: O=[IH](O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)=C(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC(c4ccc(N=CC5=C=CC5)cc4)C=C3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=Cc1cccs1
Invalid SMILES: O=P(=O)(O)(O)c1cccs1
Invalid SMILES: O=P(=O)(O)(O)c1cscc1Br
Invalid SMILES: O=S(=O)(O)c1ccc(P(=O)(=O)(O)O)s1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C(Cl)(Cl)Cl)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=C/C=C/C(C(F)(F)F)=CS1
Invalid SMILES: O=[PH](O)(O)=CC(C1=CC=C1)=C1C=CC(c2ccc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=CO1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(C2=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccccc2)cc1
Invalid SMILES: N#CCCCCCCCCCC(C#N)C=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N2C=CC=CC2)cc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C(c3ccc(-c4ccccc4)cc3)C2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CC(=CC=C1C=C(O)c2ccc(cc2)O1)C1=CC(c2ccc(-c3ccccc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccc(C4=CC=CC4)cc3)c3ccc(-c4ccccc4)cc3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=CC4)cc3)cc2)cc(C2=CC=C2)c1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(N(C2=CC=C(c3ccccc3)C=CC=C2)c2ccc(C3=CC=C3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccc(C4=CC=C4)cc3)c3ccc(C4=CC=CC4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CCC(C1=C=CC=C1)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)=CO1
Invalid SMILES: O=[PH](O)(O)=CC(=CC=C1C=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1)c1ccc(C2=CCC=C2)cc1
Invalid SMILES: O=C(O)C(=Cc1ccc(N(c2ccc(-c3ccccc3)cc2)c2ccc(-c3ccccc3)cc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C2)c(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=C=C4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(C=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)=CCO1)C1=C=CCC=C1
Invalid SMILES: O=[PH](O)(O)=CC(O)=C1C=CC(N(c2ccc(C3=CC=C(C4=CC=CC4)C3)cc2)c2ccc(-c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(c2ccccc2)=C1)c1ccccc1)C1=CC=CC(N(c2ccccc2)c2ccccc2)C=C1
Invalid SMILES: O=C(O)c1ccc(C(=Cc2ccc(-c3ccc(N(C4=CC=C4)c4ccccc4)cc3)cc2)C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CPC(=Cc1ccc(C2=CC=C(C3=CC=CCC3)C=CC=C2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccccc3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(-c3ccc(C=CC=[PH](=O)(O)O)cc3)s2)s1)C(=O)O
Invalid SMILES: O=C(O)c1cccc(-c2ccc(C=[PH](=O)(O)O)s2)c1
Invalid SMILES: O=C(O)C1=CPC2=CC3=C(C=CC=CC=C2C3)N(c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(c4ccccc4)=CC=CC=C3)c2)cc1
Invalid SMILES: O=C(O)C(=C1C=C(C2=CC(=[PH](=O)(O)O)C=C2)C1)c1ccc(-c2ccccc2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(=CC(F)(F)F)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1-c1ccc(C2=CCC=C2)cc1
Invalid SMILES: N#Cc1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)s3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC(C2=CC=C(C3=CC=C=C3)[IH]C=C2)=CC(c2cccc(C3=CC=C3)c2)=CC=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(C3=CC(F)=CC(C4=CC=C4)C=C3)c(F)c2)cc1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(-c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3F)cc2)C=CP1
Invalid SMILES: O=C(O)C1=C(C2=CCC=C2)C=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CC=CC4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC=C(c4ccccc4)C=CC3)c2)cc1
Invalid SMILES: O=C1C=CC1=CC=C1C=CC1=C1C(Cl)=C1SC1=C(S(=O)(=O)O)C(Cl)=CC1=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccccc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(C2=CC(c3ccccc3)=CC(c3ccccc3)=CC=C2)c1
Invalid SMILES: O=C(O)C1=CC=C(c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)CC=C1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(Cl)C(c2ccc(C3=CC=CC(Cl)C=C3)c(F)c2)S1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3cc(F)cs3)c(F)c2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(F)c(F)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC=C(C4=CC=C=C4)C=CC3)c2)cc1
Invalid SMILES: O=C(O)C1=CC(=[PH](=O)(O)O)S1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(C3=CC(F)=CC(F)C=C3)c(F)c2)cc1
Invalid SMILES: O=[PH](O)(O)=c1cc(-c2ccc(C(F)(F)F)cc2)sc(-c2ccc(C3=CC=C3)s2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CC=C4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC=CC(C4=CC=C4)=CC3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CCC=C4)cc3)c2)s1
Invalid SMILES: O=C(O)c1cccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)c1
Invalid SMILES: O=C(O)c1cc(C2=CCC2=CC=CC2C=CCCN2C2=CC=C2)cc(-c2ccc(C=[PH](=O)(O)O)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC=C(C4=CC=C4)C=CC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=C(c2ccc(O)c(Cl)c2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=CC3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccc(-c3ccc(C=[PH](=O)(O)O)cc3)s2)s1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(-c2ccc(-c3ccc(C(=O)O)s3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=C3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C=CC=CC(C4=CC=CCC4)=CC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=C(c3ccc(-c4ccccc4)s3)C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C=CC=CC(c4ccccc4)=CC3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(F)=CC(C4=CC=C4)C=C3)s2)cc1
Invalid SMILES: O=C(O)C1=CCC=C(N(c2ccccc2)c2ccc(-c3ccc(C=[PH](=O)(O)O)s3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N(c3ccccc3)c3ccccc3)c2)cc1
Invalid SMILES: O=C(O)C(=O)Sc1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-n3cccc(O)c4ccc3cc4)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(NC2=CC(c3ccc(C4=CC=C4)cc3)C=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC=C(PC3=CC=C3)C=CC(C3=CC=CC=CC3)=C2)s1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-c2ccc(-c3cccs3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc(C2=CC=CC2)cc(-c2ccc(-c3ccccc3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC=CC(c4ccccc4)=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC4=CC=C3C=CC=C4)c2)cc1
Invalid SMILES: O=C(F)C1=CN(c2ccc(-c3ccc(C=[PH](=O)(O)O)s3)cc2)C=CC=CC=C[IH]1
Invalid SMILES: O=C[IH]C1=CC=C2C=Cc3c(ccc(C(=O)O)ccc(C4=CC(=[PH](=O)(O)O)C=C4)cc32)C1=O
Invalid SMILES: O=C(O)C1=C(C2=CC=CC(C3=CC=CC3)C=C2)C=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(F)(F)C=C3)c2)cc1
Invalid SMILES: O=C(O)C=C1C=CC(c2ccc(C=[PH](=O)(O)O)cc2)=CC(C2=CC=C(C3=CC=C=C3)[IH]C=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(PC3=CC=CC3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(Cl)cc2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CCC=C3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC(C2=C(C3=CC=C3)C=CC2)=C(c2ccc(F)cc2)[IH]C=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(-c3cccc(F)c3)c(F)c2)s1
Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(C3=CC=C=C3)c3ccccc3)cc2)S1
Invalid SMILES: O=Cc1ccc(-c2ccc(-c3ccc(PC=[PH](=O)(O)O)cc3)s2)s1
Invalid SMILES: O=C(O)C1=CN(c2ccc(C3=CC(=[PH](=O)(O)O)S3)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(-c4ccccc4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C(F)(F)F)c2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CC=C(c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3C3=CC=C3)CC=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(C(=O)O)[IH]C=C(c4ccc(C5=CCC=C5)cc4)C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=CC3)cc(-c3ccc(C4=CC=CC(C5=CC=CC5)C=C4)cc3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC(C5=CC=C(C6=CC=C6)C5)C=C4)=C3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=C1CC=C(C2=C=CC=C2)C=C(c2ccc(-c3ccc(-c4ccc(-c5ccccc5)cc4)cc3)cc2)S1
Invalid SMILES: O=[PH](O)(O)=C1C=C[IH]C(c2ccc(C3=CC=C(c4ccc(C5=CC=C=C5)[pH]4)C=CC3)cc2)=C(C2=CC=CC2)S1
Invalid SMILES: O=C(O)c1cc(C=[PH](=O)(O)O)cc(-c2ccc(C3=CC=CC(c4ccc(C5=CC=CCC=C5)cc4)C=C3)cc2)c1
Invalid SMILES: O=C(O)C(=C1CC(=[PH](=O)(O)O)S1)c1ccc(-c2ccc(-c3ccccc3)s2)s1
Invalid SMILES: O=C(O)c1ccn(-c2ccc(C3=CP(=O)(O)(O)=CC(c4ccc(C5=CC=C5)cc4)=C3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(c4ccc(-c5ccccc5)cc4)C=CC=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CC=C(C3=CC=C(C=[PH](=O)(O)O)C=C(c4ccc(C(=O)O)cc4)S3)CP2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=C3)cc(-c3ccc(C4=CC=C(C5=CC=C5)PC=C4)cc3)c2)cc1
Invalid SMILES: O=C(F)C(=C1C=C(C2=CC(=[PH](=O)(O)O)C=C2)C1)c1ccc(-c2ccc(Cl)cc2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)c(C3=CC(C4=CC(n5cccc5O)CC=C4)C=C3)s2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3cc(F)cc(-c4ccc(N(C5=CC=C5)C5=CC=CC5)cc4)c3)c2)cc1
Invalid SMILES: O=CC1=CC=C(c2ccc(-c3ccc(C4C=CC(c5ccc(C=[PH](=O)(O)O)cc5)=C4)cc3F)cc2)C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccc(C4=CCC=C(C5=CC=C5)PC=C4)cc3)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(-c3cccc(-c4ccc(C=[PH](=O)(O)O)cc4)c3)cc2O)cc1
Invalid SMILES: O=C(O)c1cc(-c2ccc(C=[PH](=O)(O)O)cc2)cc(-c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)c1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(-c3cc(C4=CCC=C4)cc(-c4ccc(C=[PH](=O)(O)O)cc4)c3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(=[PH](=O)(O)O)sc2-c2cccc(-c3ccc(C4=CC=C4)c(F)c3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=CC=CC=C3)cc(-c3ccc(C4=CCC=C4)cc3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC=C(n5cccc5)C(F)C=C4)PC=C3)s2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2sc(C=[PH](=O)(O)O)cc2C2=CC(C3=CC=C(c4ccc(C5=CC=C5)cc4)C3)=CC2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(C4=CC=C(C5=CC=C5)C4)C=CC3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc(c1)-c1ccc(cc1)-c1ccc(cc1)-c1ccc(cc1)-c1ccc(cc1)C=CCC=CC=C2
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=CC3=CC(c4ccc(C5=CC=C5)cc4)=C2C=CC=C3O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(O)c(-c3ccc(-c4ccc(Cl)cc4)s3)c(C3=CCC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2=CC(c3ccc(C4=CC(C5=CC=C5)PC=C4)c(F)c3)C=C2)=C1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(-c3ccc(C4=CC=C(C5=CC=C5)BC=C4)cc3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(-c4ccc(P)cc4)cc3)cc(-c3cccc(O)c3)c2)cc1
Invalid SMILES: N#Cc1ccc(-c2ccc(C(C(=O)O)=C3C=C(C4=CC(=[PH](=O)(O)O)C=C4)C=C3O)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccccc3C3=CC=C(C4=CC=CC4)PC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(F)c2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C2)cc(-c2ccc(C3=CC(C4=CC=C(C5=CC=C5)C4)C=C3)cc2O)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccccc3C3=CCC=C(C4=CC=C4)PC=C3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(C3=CC=CCC=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)c(F)c3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(c4ccc(C5=CC=C5)cc4)PC3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc(C2=CC=C=C2)cc(-c2ccc(C3=CC=C(C4=CCC=C4)C=CC3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(C4=CCC=C4)C=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1
Invalid SMILES: O=P1(O)(O)=CC(c2ccccc2)=CC(c2ccc(N(C3=CC=CC(C4=CC=C4)C=C3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3cccc(-c4ccc(C5=CCC=C5)cc4)c3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC(c4ccc(C5=CC=C5)cc4)C=CC=C3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(C3=CC=C(c4ccc(C5=CC=C5)cc4)C=CC=C3)cc2)c(C2=CC=C2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(F)=C(c3ccc(-c4ccccc4)s3)C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3cccc(-c4ccccc4)c3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccccc3)c2)cc1C1=CC=C(C2=CC=C(C3=CC=C3)C2)C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=CC3)C=CC(c3ccc(-c4ccc(-c5ccccc5)cc4)cc3)=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(c2ccc(C3=CC=C3)cc2)SC(C2=CC=C(c3ccccc3)C=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC(C4=CCC=C4)=C3)cc2)c(-c2ccc(C3=CCC=C3)cc2)c1
Invalid SMILES: O=C(O)c1ccc(C2=CP(=O)(O)(O)=CC(C3=CC(C4=CC(c5ccc(C(=O)O)cc5)C=C4)C=C3)=C2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CC(C=[PH](=O)(O)O)=CC=C(c3ccc(-c4ccc(C5=CC=C5)cc4)s3)S2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=C3)C=CC(c3ccc(C4=CC=C(C5=CC=CCC5)PS4)cc3)=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C3=CC(c4ccc5c(c4)CC5=CC=C4C=CC=C4)=C3)ccc(=[PH](=O)(O)O)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(c4ccc(-n5ccc(O)c5)cc4)=C3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(C4=CC=C4)cc3)cc(-c3ccc(C4=CCC=C4)cc3)c2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC(F)C(F)=C(F)C4=C(F)C4=CC=C4)=CC3)s2)cc1
Invalid SMILES: O=C(O)C1=C(C2=CC(c3ccc(C4=CC=C4)cc3)=C2)C=C(c2ccc(C=[PH](=O)(O)O)s2)C=C[IH]1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(F)=CC(F)C3=CC=C3CC3=C(F)C3=CC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(F)=C(c4ccc(C5=CC=C5)cc4)[IH]C=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(F)=C(C4=CC=C(N=C(O)C5=CC=C5)C4)CC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC(F)=C(c4ccc(C5=CC=C5)cc4)C=CC3)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CP(=O)(O)(O)=CC(C3=CC(C4=CC=C(C5=CC=CCC=C5)C(C5=CC=C5)CC4)=CC3)=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(C4=CC=C4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)ccc2C2=CC=C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(C4=CCC=C(C5=CC=C5)C=C4)cc3)c(C3=CC=CCC3)c2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccc(-c4ccc(C5=CC=C=C5)cc4)c(F)c3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(C3=CCC=CC3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=C(C4=CC(F)C(F)=C(C5=CC=C5)N4)C=C3)s2)cc1

[12:41:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:30] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:41:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:31] Explicit valence for atom # 48 P, 7, is greater than permitted
[12:41:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:31] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:31] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:41:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:32] Explicit valence for atom # 42 P, 7, is greater than permitted
[12:41:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 47 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 2 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 42 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 52 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:41:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 42 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 42 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 46 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:41:34] Explicit valence for atom # 48 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 2 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 48 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:41:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:36] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:41:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:36] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:41:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:41:37] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:39] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:40] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:41:41] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:41:41] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:41:41] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:41:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:41:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:41] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC1=C(O)C1=CC(=CC=C1C=CC=C1O)c1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)c1ccccc1
Invalid SMILES: C=CC(=CC(=C1C=CC(O)=C1)c1ccc(N(C2=CC=C2)C2=CC=CC(c3ccc(N(C4=CCC=C4)C4=CC=C=CC4)cc3)C=C2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(c2ccccc2)c2ccccc2)=C1)c1ccccc1)N(C1=CCC=C1)C1=CC=CC1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)C2=CC(c3ccc(N(C4=CC=C4)C4=CC=CC4)cc3)C=C2)C=CCO1
Invalid SMILES: O=P1(O)(O)=CC=C(N(C2=CC=C=C2)c2ccc(N(C3=CC=CC(C4=CC=C4)C3)c3ccccc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=C3)c3ccc(-c4ccc(N(C5=CC=C5)C5=CC=C5)cc4)cc3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1cccc(N(c2ccccc2)c2ccccc2)c1)c1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)C2=CC=CC2)cc1
Invalid SMILES: O=C1C=CC(N(C2=CC=CC=CC=C2)c2ccc(-n3cccc3)cc2)C=CC(=CC(C=[PH](=O)(O)O)c2ccccc2)O1
Invalid SMILES: O=[PH](O)(O)=CC(=C1C=CC(N(c2ccccc2)c2ccc(O)cc2)=C1)c1ccc(N(C2=CC=CC2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3n2C(=CC=C2C=CC2=CC=C=CC1=CC=C1C=CCC=C1)C=CC=CC=3
Invalid SMILES: O=[PH](O)(O)=CC1=CC=c2ccc3n2C(=CC=c2ccc(n2C2=CC=CCC2)=CC=CC=C=CC1)C=CC=CC=c1ccccc1=CC=3
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C3C=CC(=C3)c3ccc(cc3)N3CC3=CC=CCC2=CC=c2ccc3n2C(=CC=CC=CC=C1)C=CCC=3
Invalid SMILES: O=[PH](O)(O)=Cc1cccccccccc2c3oc(c(n(C4=CC=CC4)c4ccc(cc4)c4cccc(c1)c4)=CC=3)=CC=C2
Invalid SMILES: O=[PH](O)(O)=CC1=CC(=C2C=CC(N(c3ccccc3)c3ccccc3)=C2)C2=CC=C(CC2)C2=CC=C(C=CC3(O)C=C=CN1C=CCC=C3)CC=C2
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC=CC=C2)C2=CC=CC2)=C1)c1ccc(N2C=CC=CC2)cc1)C1=CC=C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C2)c2ccc(N(C3=CC=C=C3)c3ccc(C4=CC=CC4)cc3)cc2)=CC1
Invalid SMILES: O=C(O)C(C=C1C=CC(c2cccc(N(c3ccccc3)c3ccc(N(C4=CC=C=C4)c4ccccc4)cc3)c2)=C1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=CCC=C2)C2=CC=CC2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(C=C1C=CC(N(C2=CC=C(C3=CC=C=C3)C=CC=C2)c2ccc(C3=CC=C=C3)cc2)=C1)C1=CC=C=CC1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(C2=CC(C3=CCC=C3)C=C2)N(c2ccc(N(c3ccccc3)c3ccccc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2cccc(N(C3=CC=C=C3)c3ccc(-c4ccc(-c5ccc(C6=CC=C6)cc5)cc4)cc3)c2)=CC1
Invalid SMILES: N#CC(C#N)C=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: N#C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2C=CC=CC=C=CC=C3C=CC=CC=C4C5=CCC=CC6=CC=C(C=CC2=CC=C3O6)N45)=CC1
Invalid SMILES: O=P(=O)(O)(O)C1=CC=C(N2C=C=CC=CCC=CC=c3ccc(n3C3=CC=CC3)=CC=C3C(OC4=CC=CC4)=CC=C32)C=C(O)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccccc2c(ccc3oc(c1)=C3)OC1=CC=C(Oc3ccccc3)N3C(=CC=CCC=CC=2)C=CC=C13
Invalid SMILES: N#CC[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)C=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1)=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC1=CC(=CC=C(OC2=CC=C(Oc3ccccc3)N(C3=CC=C3)CC=C2)C2=CC=C2)O1)N1C=C=CCCCC=CC1
Invalid SMILES: N#CCCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=C(Oc3ccc(N(C4=CC=C=C4)C4=CC=C4)cc3)N3C=CCC=C=CC=C3C1)O2
Invalid SMILES: O=[PH](O)(O)(c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1)n1cccc1
Invalid SMILES: C=CCCC(=CC1=CC(=CC=C2C=C=CCC=C=C=C3CC=CC=C4C=CCC=C5C=CC(=CC=C6OC3=CC=C6O2)N4N5c2ccccc2)O1)C=[PH](=O)(O)O
Invalid SMILES: N#CC(C#N)C=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Oc1cc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)ccc1O
Invalid SMILES: O=P(=O)(O)(O)Oc1cc(N(c2ccccc2)c2ccccc2)ccc1Oc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(C#N)C=CC1=CC=CC=CC(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)=C1
Invalid SMILES: N#CCCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: O=CC[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P1(O)(O)=CC=C(O)C(N(C2=C=C=CC2)C2=CC=C3OC4=CC=C5OC4=CC=CC5=CC=C4C=CC4=CC=CCC=CC=C32)=C1
Invalid SMILES: N#CCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)CC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C=CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC=C3Oc4ccc(cc4)N(c4ccccc4)C2=CC=CC2=CC=CCC=CC=C(C=CC1O)N23
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1)C=C1C=CC=CC1
Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: N#CCCCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)N(c1ccccc1)c1ccc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: N#CCCCCCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CCC=CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccccccc2cccccc3cccc4c(Oc5ccccc5)ccc4oc(ccc4cc(c1)o4)n23
Invalid SMILES: N#CC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)C=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)CC=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1C#P(=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=CC(=C1C=CC=C1)N(C1=CC=CC=CC=C1)C1=CCC=C1)n1cccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1c2c3ccccccccc(n1-3)C=CC=CC=C1C=CC=CC=c3ccc(n31)=CC2)C1=CC=C=C1
Invalid SMILES: O=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=C3OC4=CC=C(Oc5ccccc5)C(=CC=C4)C3=CC=c3ccc4n3C(=CCC=C=C=CC=C1)C=CC=CC=4)O2
Invalid SMILES: O=CC(=O)C(=O)C=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=c3oc4c5n(c(cccccc3=CC=CC=CC=CC1)C=CC=5)C(Oc1ccccc1)=CC=4)O2
Invalid SMILES: N#CC(=CC(=C1C=CC(N(C2=CC=C2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CCC=C1)C1=CC=CC1)C1=CC=C=C1
Invalid SMILES: N#CCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P1(O)(O)=CC=C(O)C(n2cccccccc3c(Oc4ccc(N(C5=CC=C5)c5ccccc5)cc4)ccc2-3)C=C1
Invalid SMILES: O=P(=O)(O)(O)C(=Cc1cc(O)cc2ccc(Oc3ccccc3)c3ccccccc-3n12)N1C=C=CC1
Invalid SMILES: O=P1(O)(O)=CC(C2=CC=C=C2)=CC(N(C2=CC=C(C3=CC=C3)OC3=CC=C(C=CC=C3)C=C2)c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC1=c2ccc(n2N(C2=CC=C2)C2=CC=CC2)=CC=C2OC3=CC=C(C=CC=CC(O)=CC=C2C=C1)C=CC=C3
Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CCC=C1)=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1
Invalid SMILES: O=P(O)(O)#Cc1cc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(O)CCC=Cc1c(CCC=[PH](=O)(O)O)c(-c2ccccc2)cc2c3cc(-c4ccccc4)ccc3n(-c3ccccc3)c12
Invalid SMILES: O=[PH](O)(O)=CCc1cc2c(cc1-c1ccccc1)c1cc(-c3ccccc3)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc2c(c1)c1cc(-c3ccccc3)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc(-c3ccccc3)cc2c2ccc(-c3ccccc3)cc21
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-n2c3ccc(-c4ccccc4)cc3c3cc(-c4ccccc4)ccc32)cc1
Invalid SMILES: O=Cc1c(CCC=[PH](=O)(O)O)c(-c2ccccc2)cc2c3cc(-c4ccccc4)ccc3n(-c3ccccc3)c12
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1cc(Cl)ccc1n2-c1ccccc1
Invalid SMILES: N#CC(=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1)C(=O)O
Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=P1(O)(O)=Cc2c(n(-c3ccccc3)c3ccccc23)C=C1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(-n2c3ccccc3c3ccccc32)cc1
Invalid SMILES: O=P(O)(O)c1ccc(N2C=CC3=CC4=C2C3=C2C=CC=C[PH]24(=O)O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccc(Cl)cc1
Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)PCC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2c(N(c3ccccc3)c3ccccc3)cccc2[nH]1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#CPC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=CC=CC=C2)C2=CC=CC2)cc1)PC=[PH](=O)(O)O
Invalid SMILES: N#CPC1=CC=C(N(c2ccccc2)c2cccc(C=[PH](=O)(O)O)c2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CBC(C#P(=O)(O)O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#C/C(C#P(=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)C=CC=C1)C1=CC(=[PH](=O)(O)O)C=C1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(F)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=C=C2)c2ccccc2)cc1)C(=O)OCC=[PH](=O)(O)O
Invalid SMILES: N#CC1=C=CC=C(N(C2=CC=C(C(=O)O)OC=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=C(O)C1=Cc2ccc(n(-c3ccc(C=[PH](=O)(O)O)cc3)ccccc2=O)C=C1
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1cccc[pH]c(C2=CC=C=C2)cc1
Invalid SMILES: N#CPC(=Cc1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=C/C(=C\c1ccc(O)cc1)c1ccc(N(C2=CC=C=C2)c2ccccc2)cc1
Invalid SMILES: N#CPN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(C2=CC=C2)cc1
Invalid SMILES: N#CC(=CPc1ccc(N(C2=CC=CC=CC=C2)c2ccccc2)cc1)OCC=[PH](=O)(O)O
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C\c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: O=P(O)(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(O)cc2)cc1
Invalid SMILES: O=C(F)c1ccc(N(C2=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: N#Cc1ccc(=[PH](=O)(O)O)cc(N(C2=CC=C2)c2ccccc2)c1
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=C(C(=O)F)C=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cc1)C(=O)O
Invalid SMILES: N#Cc1ccc(N(C2=CC=C(C(=O)O)C=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C(=O)F)C2=CC(=[PH](=O)(O)O)C=C2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C(C=C(O)O)/C=C\C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CCPC1=CC=CC2=CC=CC=CC(=CC=C3C=CC=CC=CC=CP3)N21
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: N#CPc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=Pc1ccccc2ccc(c1)-c1ccc(cc1)C=CC=CC=CN2c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=CC2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(C3=CC(F)=C3)cc2)[PH]2=CC=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(N(C2=CC=CSC=C2)c2ccc(O)cc2)c1
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(C2=CC=C2)cc1
Invalid SMILES: N#CPC(C#P(=O)(O)O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CCC(C=C(C#N)C#N)=Nc1cc(C=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: N#[PH]c1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(F)c1ccc(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)cccco1
Invalid SMILES: N#CPN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: N#[PH]N(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: Nc1cc(C=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=P(O)(O)Cc1ccc(N(c2ccccc2)c2ccc([PH](=O)(O)(O)O)cc2)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)C1=CCC(=[PH](=O)(O)O)C=C1
Invalid SMILES: N#CN(C1=CC=C(C(=O)O)[IH]C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#Cc1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(C=C(CF)C(=O)O)cc2)cc1
Invalid SMILES: O=C(F)C1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=CC2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)OCC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: Nc1cc(PC=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(N(c2ccccc2)c2ccc(O)cc2)c1
Invalid SMILES: N#[PH]C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C2)c2cccc(C=[PH](=O)(O)O)c2)cccco1
Invalid SMILES: N#CPN(c1ccccc2cc(cc1)C=CC=CC=CP2)c1ccc(PC=[PH](=O)(O)O)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(PC=[PH](=O)(O)O)cc1
Invalid SMILES: O=C(F)c1ccc(N(C2=CC=C=C2)c2ccc(PC=[PH](=O)(O)O)cc2)ccc([PH](=O)O)oc1
Invalid SMILES: O=[PH](O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(O)cc2)cc1
Invalid SMILES: N#CBC(=Cc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=C/C(=C\c1ccc(O)cc1)c1ccc(N(PC2=CC=C2)c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)C2=CC(=[PH](=O)(O)O)C=C2)C=CO1
Invalid SMILES: N#CBN(C1=CC=C(c2cccs2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#Cc1cc(C=[PH](=O)(O)O)cc(N(c2ccccc2)c2ccccc2)c1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH](=O)O)C=CC=C1
Invalid SMILES: O=C(F)C1=CC=C(N(c2ccc(PC=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)C=CC=C1
Invalid SMILES: O=C(F)C1=CC(c2ccccc2)=CC=C(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)C=C[IH]1
Invalid SMILES: N#C/C(=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1)PC=[PH](=O)(O)O
Invalid SMILES: O=C(O)C1=CC(C2=CC=C2)=CC=C(N(C2=C=C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Br)cc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccc(C=[PH](=O)(O)O)cc2)c2ccc([PH](=O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N2C3=CC=C(C=CO3)/C=C(/C=[PH](=O)(O)O)PC=C=CC=Cc3ccc2cc3)C=CC=C1
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C/c1ccc(N(C2=CC=CC2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)c1ccc(N(C2=CC=C(C3=CC=C3)C=CC=C2)C2=CC(=[PH](=O)(O)O)C=C2)cc1
Invalid SMILES: N#CPC1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#CC1=CC=C(C=[PH](=O)(O)O)C=CC(N(C2=CC=CC2)c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(COC(=O)c1ccc(N(c2ccccc2)N(c2ccccc2)c2ccccc2)cc1)OCC=[PH](=O)(O)O
Invalid SMILES: O=P(O)(O)c1ccc(N(C2=CC=NC2=[PH](=O)(O)O)c2ccc(O)cc2)cc1
Invalid SMILES: N#CP/C(C=[PH](=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-n2c3ccccc3c3ccccc32)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)c1ccc(-c2cccc(O)c2)cc1
Invalid SMILES: O=Pc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC(c3ccc(C4=CC=C4)cc3)=C2)c2ccc(O)cc2)=C1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccccc1
Invalid SMILES: O=P1(O)(O)=CC=C(N(C2=CC=CC(c3ccc(O)cc3)C=C2)C2=CC=C(c3ccccc3)OC=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC=C3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=C=C1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC=CC3)cc2)=C1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C2)C2=CC(c3ccc(-c4ccccc4)cc3)=CC=C(C=[PH](=O)(O)O)C=C2)cccco1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(N(C2=CC=C(c3ccccc3)OC=C2)c2ccc(C3=CC=C3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(N(C2=CCC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccccc3)cc2)cccco1
Invalid SMILES: N#Cc1ccc(C(C=[PH](=O)(O)O)=C2C=CC(N(c3ccccc3)c3ccccc3)=CO2)cc1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccccc1
Invalid SMILES: N#Cc1ccc(C(=Cc2ccc(N(c3ccccc3)c3ccccc3)cc2)C=[PH](=O)(O)O)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=C(O)C=[PH](=O)(O)O)C=C2)c2ccc(C3=CC=C3)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)C=CO1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(C2=CC=CC2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(PC=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C(c3ccccc3)OC=C2)c2ccc(C3=CC=C3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=CC(O)C=C1
Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1)C(F)(F)F
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: N#CC(=Pc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1)C(=O)O
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)c1cccc(O)c1
Invalid SMILES: N#CC(=CC(O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)=C1)C(=O)O
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(C(=O)O)cc3)cc2)C=CO1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=C=CC=C2)C2=CC=C(c3ccccc3)OC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(O)cc1)c1ccc(N(C2=CC=C2)C2=CC=CC(c3ccccc3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPC1=CC=C(N(C2=CC=CC=CC=C2)c2ccccc2)OC=C1)c1ccc(C2=CC=C2)cc1

[12:43:09] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: O=C(O)CCn1cc(-c2ccc(C=[PH](=O)(O)O)cc3c4cccn4c4ccc(cc4)c=3c2)ccc1=O

[12:43:31] Explicit valence for atom # 24 P, 7, is greater than permitted

Invalid SMILES: O=C1c2ccc3c4c(ccc1c24)C(=O)N(Cc1ccc(O)cc1)C(=[PH](=O)(O)O)C(=O)N(Cc1ccncc1)C3=O

[12:43:35] Explicit valence for atom # 36 P, 7, is greater than permitted

Invalid SMILES: O=Cn1c(=O)c2ccc3c(=O)n(Cc4ccccc4)c(=O)n(Cc4ccncc4)c(=O)c4c(C=CC=[PH](=O)(O)O)cc(c1=O)c2c34

[12:43:39] Explicit valence for atom # 28 P, 7, is greater than permitted

Invalid SMILES: O=c1c2ccc3c(=O)n(-c4ccc(O)cc4)c2c3ccn1-c1ccc(C(=CC=[PH](=O)(O)O)C2=CC=C2)cc1

[12:43:39] Explicit valence for atom # 28 P, 7, is greater than permitted

Invalid SMILES: O=c1c2ccc3c(=O)n(-c4ccc(O)cc4)c(=O)c-3c3ccc(c(=O)n1CC=[PH](=O)(O)O)c2cc3P

[12:43:40] Explicit valence for atom # 27 P, 7, is greater than permitted

Invalid SMILES: O=c1c2ccc3c(=O)n(-c4cccc(O)c4)c(=O)c4ccc(c(=O)n1CC=[PH](=O)(O)O)c3c24

[12:43:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:40] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:43:40] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:43:40] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:43:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:40] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:43:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:41] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:43:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:41] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:43:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:42] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:43:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:42] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:43:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:42] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:43:42] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:43:42] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:43:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:45] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:43:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:47] Explicit valence for atom # 47 P, 7, is greater than permitted
[12:43:47] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:43:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:47] Explicit valence for atom # 48 P, 7, is greater than permitted
[12:43:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:47] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:43:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:47] Explicit valence for atom # 46 P, 7, is greater than permitted
[12:43:47] Explicit valence for atom # 48 P, 7, is greater than permitted
[12:43:48] Explicit valence for atom # 47 P, 7, is greater than permitted
[12:43:48] Explicit valence for atom # 49 P, 7, is greater than permitted
[12:43:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:48] Explicit valence for atom # 48 P, 7, is greater than permitted
[12:43:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:48] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:43:48] Explicit valence for atom # 47 P, 7, is greater than permitted
[12:43:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:48] Explicit valence for atom # 47 P, 7, is greater than permitted
[12:43:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 38 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 41 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 41 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 40 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:49] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:43:50] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:43:50] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:43:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:50] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:43:50] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:43:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 44 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 40 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 38 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:43:51] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 38 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 41 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 40 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 44 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 43 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 40 P, 7, is greater than permitted
[12:43:52] Explicit valence for atom # 39 P, 7, is greater than permitted
[12:43:53] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:53] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:55] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 40 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(C(F)(F)F)cn1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CN=C1
Invalid SMILES: N#Cc1cccc(=[PH](=O)(O)O)cc1
Invalid SMILES: O=Cc1cncc(C=CC=[PH](=O)(O)O)c1O
Invalid SMILES: N#Cc1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)(CCCCn1ccnc1)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=c1cccc(C(F)(F)F)cc1C(F)(F)F
Invalid SMILES: O=C1CC=CC(=[PH](=O)(O)O)C=CC(C(F)(F)F)=CO1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(S)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(CCO)CCO)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(CCO)CCCCO)cc1
Invalid SMILES: O=[PH](O)(O)(c1nccn1Cc1c[nH]cn1)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2cccs2)S1
Invalid SMILES: N#CC(C#N)=Cc1ccc(-c2ccc(C=[PH](=O)(O)O)s2)s1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(S)cc1
Invalid SMILES: O=c1ccc(C=[PH](=O)(O)O)c(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=c1cccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc(-c2cccs2)cc1
Invalid SMILES: N#CC1=CC=C(C=[PH](=O)(O)O)c2ccccc2S1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(-c3ccccc3)cc2)c[nH]1
Invalid SMILES: O=[PH](O)(O)=Cc1ccccc1-c1cccs1
Invalid SMILES: O=Cc1ccc(-c2ccc(PC=[PH](=O)(O)O)s2)s1
Invalid SMILES: O=[PH](O)(O)=CPc1sc(-c2cccs2)cc1O
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)N=C(c2ccccc2)S1
Invalid SMILES: O=C(Cl)c1cc(-c2ccc(C3=CC=C3)cc2)sc(=[PH](=O)(O)O)c1Cl
Invalid SMILES: Nc1cc(-c2cccs2)sc1C=CC=[PH](=O)(O)O
Invalid SMILES: O=Cc1ccc(-c2ccc(C=[PH](=O)(O)O)s2)s1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)sc1c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=c1ccc2c3ccc(c2s1)Sc1ccccc1-3
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)sc1c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2sc3c4ccccc4sc3c2c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)sc1c3ccc(Cl)cc3sc21
Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc3[nH]c4ccc(-c5ccc([PH](=O)(=O)O)cc5)cc4c3c2)cc1
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc(-c3ccccc3)cc2c2cc(-c3ccccc3)ccc21
Invalid SMILES: O=[PH](O)(O)=CCCCCn1c2ccc(-c3ccccc3)cc2c2cc(-c3ccccc3)ccc21
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: CC(=CC(C1=CC=C=C(C2=CC=C=CC=C2)C=C1)=C1C=CC(c2ccc(N(C3=CC=CCC3)c3ccc(C4=CC=C4)cc3)cc2)=C1)C=[PH](=O)(O)O
Invalid SMILES: C=CC(C=[PH](=O)(O)O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(-c4ccc(N(C5=CC=C=C=C5)C5=CC=CC=CC5)cc4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: CC(=CC1=CC1=CC=c1ccc(=CC=C2C=CC2=CC=CC=C2CC2=CC=C2C=CC(=O)N2C2=CCC=C2)n1C=C=CC1=C=CCS1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC2=CC=c2ccc3n2N2C(=CC=C=CC=CC1)CC=CC=C2CCC=CC=C1C=CC1=CC=3
Invalid SMILES: O=C(O)C1=COC(=CC(=CC=[PH](=O)(O)O)C2=CC(C3=CC=CCC=C3)C=CC=C(c3ccc4n5c(ccccccc35)C4)C=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=CCCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC2=CC=c2ccc3n2N(C=C=CC=c2ccoc2=CC=C2C=CC2=CC=3)CC=CC=CC=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3n2C(=CC=C2CC=CC(N(C4=CC=C4)C4=CC=CC4)=CC=C2C=CC1)C=CC=CC=3
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC2=CC3=CC=CCC=CC=C4C=CC(C=C5C=CC5=CC=C21)N43)C1C=CC=C1)N(C1=C=C=CC=C1)C1=CC=CC1
Invalid SMILES: CC=C1C=C=CC=CC=C2CC=CC=C3C=CC=CC=C4C=CC(C=CC=C5C=CC5=CC=c5ccc(n52)=CC=C2C=C2C=C(C=[PH](=O)(O)O)C=C1)N34
Invalid SMILES: C=CC(=Cc1c(=CC=C2C=C=C=C2)cccccc2n3c(ccc3ccc3cccccc4ccc(ccc5ccc15)n34)=CCC=C2)C=[PH](=O)(O)O
Invalid SMILES: CC(=CC1=CC1=CC=c1ccc2n1C=C=CC=CCC=C=c1ccc(n1-c1ccccc1)=CC=C1C=CC1=CC=C1C=CC1=CC=2)C=[PH](=O)(O)O
Invalid SMILES: CC(=CC(C1=CC=C(c2ccc(N(C3=C=CCC=C=C3)C3CC=C=C=CC3)cc2)C1)=C1C=CC=C(c2cccc(C3=CC=CC3)c2)C=C1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc-2ccc2ccc3n2c(ccc2ccc(cccccc4ccc1C=C=C4)n2C1=CC=C1)C=CCC=C1C=CC1=CC=3
Invalid SMILES: CCC(=CC(C1=CC2C=C=CC=CC=CN(C3=C=CCC=C3)c3ccc(cc3)-c3ccc(cc3)C(=C2)C=C1)=C1C=CC(C(=O)O)=CO1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC1=CC(=C2C=CC(N(C3=CC=C(c4ccccc4)C=CC=C3)c3ccc(N(C4=CCC=C4)c4ccccc4)cc3)=C2)C=CC=C=C=C1
Invalid SMILES: O=[PH](O)(O)=CC=CC1=C(O)C1=CC=c1ccc2ccc3ccc3ccc3ccc3ccc3ccc(cccccccccn12)n3C1=CCC=CC1
Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccc(C=[PH](=O)(O)O)cc5)cc4)cc3)cc2)cc1
Invalid SMILES: C=CC=C=CC(=CC1=CC1=Cc1cccc2ccc3c(ccc4c(ccc(N(C5=CC=C=C5)C5=CC=C5)ccccn12)CO4)C=C3)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC1C=C=CC=CN(C2=CC=C=CCC=C2)c2ccc(cc2)-c2ccc(cc2)N(c2ccccc2)c2ccc(cc2)C2=CCOC(=C1)C=C2
Invalid SMILES: CC(=CC1=C2C=CC(=C2)c2ccc(cc2)N(C2=CC=C2)c2ccc(cc2)N(C2=CC=CCC2)C2=C(C=C=C2)CC=CC=CC=C=C1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=CCC=C=C3)c3ccc(-c4ccc(-c5ccc(C6=CC=C6)cc5)cc4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CC(c2ccc(C3=CC=CCC3)cc2)C=CC1)=C1C=CC(c2ccccc2)=C1)c1ccccc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C(=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1)CC(=O)O
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C=O)C(=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1)CCC=O
Invalid SMILES: N#CC(C(=O)C=O)C(C=O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C4=CC=C(c5ccccc5)C=CC3=CC=C(c3ccccc3)C=C4)cc2)cc1
Invalid SMILES: N#CC(C=O)=CC(C=O)=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)c2)cc1
Invalid SMILES: N#CC(C#N)C(=CC1=CC=C(c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)C1)C(=O)C=O
Invalid SMILES: O=CCC(C=O)=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=CC=[PH](=O)(O)O)cc4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccc(N(C3=CC=CC(c4ccc(C5=CC=C5)cc4)C=C3)c3ccccc3)cc2)S1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=C=C3)c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=CC1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccc(C=O)cc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4C=O)cc3)cc2)cc1
Invalid SMILES: N#CC(=CC1=CC=C(c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)C1)C(=O)C=O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2O)cc1
Invalid SMILES: O=CCOc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)c2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccccc2)cc1N(c1ccc(-c2ccccc2)cc1)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3cccc(-c4ccc(F)cc4)c3)cc2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(C2=CC=C3C=CC(c4ccccc4)=CC=C(C=C2)N3c2ccc(-c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=NN(c2ccccc2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccccc2C(F)(F)c2ccc(F)cc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Cc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(N2c3ccccc3Cc3ccccc32)C=C(Br)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C3=CC2=C(Br)C=C3)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(O)c2c1ccc1cccnc12
Invalid SMILES: O=[PH](O)(O)=Cc1ccnc2cc(Cl)ccc12
Invalid SMILES: O=[PH](O)(O)=CCc1cc2c3ccccc3sc2c2c1[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2c3sc4ccccc4c3ccc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc3c(cc21)sc1ccccc13
Invalid SMILES: O=C=CC1C=C2C(=C1c1c3cc(n1CC[PH](=O)(O)(O)O)-c1c-3n(CCCP(=O)(O)O)c3ccccc13)N2CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3ccc-3c(N3C=CCC=C3)c3cc4n(CCC[PH](=O)(O)(O)O)c3c-4c21
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C13CC=C=CC(C(NCCP(=O)(O)O)=C1c1[nH]c4ccccc4c1-2)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=C1c2c(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c2[nH]c2ccccc23)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=c1c2ccc(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c4ccc4n(CCCP(=O)(O)O)c23)n1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1C(NCC[PH](=O)(O)(O)O)=C1c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CC[PH](=O)(O)(O)O)C3=CC3)c3cc4n(CCCI(=O)(O)O)c3c-4c21
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1C=CC(=C3C=CC=C4C2=C3N4CCC[PH](=O)(O)(O)O)N(C2=C=C2)C1
Invalid SMILES: NC1=C2C(NCC[PH](=O)(O)(O)O)=C2c2[nH]c3ccccc3c2-c2c1c1ccccc1n2CCCP(=O)(O)O
Invalid SMILES: Cn1c2ccccc2c2c1c1c3ccccc3n(C=O)c1c1c3ccccc3n(P(=O)(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(C(=C3CC=N3)N1CCC[PH](=O)(O)(O)O)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CCC3=C1C(NCC[PH](=O)(O)(O)O)=C3c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C1C=CC=CC(=N3)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C=CC=C1C(=C3CN3CCC[PH](=O)(O)(O)O)n3c1c-2c1ccccc13
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c4c(c5c(n4CCC[PH](=O)(O)(O)O)C=C5)c4c(c5ccccc5n4CCCP(=O)(O)O)c31)CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CCc3c-2c2c(n3CCC[PH](=O)(O)(O)O)C=CC(C=C2)C1=C1CN1CCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=C3C=NC(S3)C2=C(C2=CCC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(c21)C(=C1C=CC=C1)N4CCC[PH](=O)(O)(O)O)C1C=C=C1C1(O)C=CC1=N3
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1c3nc(C4C=CC=C4)c-2c(c3=CC2=CC=C2)n1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(c3[nH]c4ccccc4c3-2)C2(C=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CC[PH](=O)(O)(O)O)C=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc2c(c1)[nH]c1c3ccccc3c3c4ccccc([nH]c23)c41
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(C3=CC(=N1)N3CCC[PH](=O)(O)(O)O)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c3c4c(c(c5c(c1=3)=C5NCC[PH](=O)(O)(O)O)NCC=CC=CC=2)c1ccccc1n4CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CCC[PH](=O)(O)(O)O)C=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c1c1c3ccccc3n(CC[PH](=O)(O)(O)O)c1c1c3ccccc3n(CCCP(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(ccn4CCC[PH](=O)(O)(O)O)c21)C1=CC=C(C=CC1)N3C1CCCC1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CC[PH](=O)(O)(O)O)CC=C4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCC=C1NC1=C1c2c(n(CCCP(=O)(O)O)c3ccccc23)C2=C(C=C2C2CCCC=N2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ncccc2c2cccc3c(NCC[PH](=O)(O)(O)O)c-3c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCN1C2=CC=Cc3c1c2c1c(c3N(CC[PH](=O)(O)(O)O)C2C=CC=C2)c2ccccc2n1CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CCP(=O)(O)O)C3=CCC=C3)c3c4c(c21)C(=CC=C3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(ccn3CCC[PH](=O)(O)(O)O)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CCC[PH](=O)(O)(O)O)CC=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccc3cc2c2cc(C4C=CC=C4)c(cc21)n(CC[PH](=O)(O)(O)O)c1ccc3=1
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C(=C1C=CC1)N(CCC[PH](=O)(O)(O)O)C1=C(C=CCC=C1)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c4c5c(n(CCC[PH](=O)(O)(O)O)c4c3n(CCCP(=O)(O)O)c2c2ccccc21)C5
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ncccc5c4c21)C(=C1C=N1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCC=NC1=c2cc3n(CCC[PH](=O)(O)(O)O)c2=C3c2c(c3ccccc3n2CCCP(=O)(O)O)-c2ncccc21
Invalid SMILES: O=c1c2c3[nH]c4ccccc4c3c3c(c4ccccc4n3CCCP(=O)(O)O)c2[nH]c2ccc-2n1CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCN1C(=C2CN2CCC[PH](=O)(O)(O)O)c2c1c1c(c3c4ccccc4n(CCCP(=O)(O)O)c23)N=CCC=C1
Invalid SMILES: O=P(O)(O)CCCN1C2=CC=CC3C(=C4C(=C41)c1c2c2ccccc2n1CCCP(=O)(O)O)C1=NC(CCCC1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCN1C(=C2C=CCC=C2)C1=C1C=CCC=Cc2c3c1n(CCC[PH](=O)(O)(O)O)c2-c1c-3n(CCCP(=O)(O)O)c2ccccc12
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)[PH](=O)(O)(O)CC=CN3
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)[PH](=O)(O)(O)CCN3
Invalid SMILES: O=C1c2c(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c2[nH]c2ccccc23)N1CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(c3ccccc3N(CCCC[PH](=O)(O)(O)O)SN1)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCN1C(=C2C=CC=C2)c2c1c1c3ccccc3n(CC[PH](=O)(O)(O)O)c1c1c3ccccc3n(CCCP(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3ncc(c4[nH]c5ccccc5c4c21)c1c3n1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c1c1c3ccc4c(ccn4CC4=CCC=C4)c1n(CCC[PH](=O)(O)(O)O)c32
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC(C3=C4C=C=CC3N4CC[PH](=O)(O)(O)O)=C(CN1)c1ccccc1-2
Invalid SMILES: O=P(O)(O)CCCN1c2c(c3c(c4ccccc4n3CCC[PH](=O)(O)(O)O)c3c2c2ccccc2n3CCCP(=O)(O)O)C12C=CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=Cc1c-2c(C2=CC=CC3N=CC23)n2c1P(=O)(O)(O)(O)CCC2
Invalid SMILES: O=P(O)(O)CCCNC1=C2C1=C(NCC[PH](=O)(O)(O)O)c1c(n(CCCP(=O)(O)O)c3ccccc13)-c1c2[nH]c2ccccc12
Invalid SMILES: O=P(O)(O)CCCCCn1c2ccc3c2c2c(ccn2CCC[PH](=O)(O)(O)O)c2c(c4ccccc4n2CCCP(=O)(O)O)c31
Invalid SMILES: O=P(O)(O)CCCn1c2cccc3c(C=C4C=CC5C(=C4)N5CC[PH](=O)(O)(O)O)c(c1-3)-c1c-2c2ccccc2n1CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CCC[PH]3=CC=C3)C3=CCC=C=C3)c3c4c(c21)C(=CC=CC3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3[nH]c4c(n(CCC[PH](=O)(O)(O)O)c5ccccc5c3c3[nH]c5ccccc5c3c21)=CC=4
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=CC1C=N1)N3CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1NC3=C(CC=CC3)C2=C(C2=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=[PH](O)CCNC1=C2C(NCC[PH](=O)(O)(O)O)=C2c2[nH]c3ccccc3c2-c2c1c1ccccc1n2CCCP(=O)(O)O
Invalid SMILES: Nc1c2c(NCCC[PH](=O)(O)(O)O)c3c-2n2c(cccc4c5ccccc5n(CCCP(=O)(O)O)c4c1-3)CCCCC2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=CC1C=N1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1cc(c1NCC[PH](=O)(O)(O)O)-c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c1c1c4ccccc4n(CCC[PH](=O)(O)(O)O)c1c1c4ccccc4n(CCCP(=O)(O)O)c31)C=C2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)CN3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c4c(ccn4CCC[PH](=O)(O)(O)O)c4c(c5ccccc5n4CCCP(=O)(O)O)c31)CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1c3c-2c(n1CCC[PH](=O)(O)(O)O)C(=C1N=C1C1C=CC=CC1)C=CC=C3
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=C1CC=NS1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C(N(CCO)C1=CC1)=C1C(NCC[PH](=O)(O)(O)O)=C1c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2cc3c1=C2c1c(c2ccccc2n1CCCP(=O)(O)O)C=C=C1CN(CC[PH](=O)(O)(O)O)C=31
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1NC1=C1C2=C(C2=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccc2c2c1c1c(NCC[PH](=O)(O)(O)O)c-1cc1c3ccccc3n(CCCP(=O)(O)O)c12
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c4c5c(c6c(c(c(c21)C=CP(O)CC5)n3CCC[PH](=O)(O)(O)O)=CCC=6)N4
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1C=NC3C=CC=C4NC4=C4C2=C(C1=CC=C3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(c21)=C4N(CCP(=O)(O)O)C1=CC=C1)C=C=CC1C=3N1CC[PH](=O)(O)(O)O
Invalid SMILES: Nc1c2cccc3n(CCCP(=O)(O)O)c-2c-3c2c(c3ccccc3n2CCCP(=O)(O)O)c2c1c1c(n2C[PH](=O)(O)(O)O)C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)C=C1
Invalid SMILES: N#CC1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(c2ccccc2)=CS1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)S1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=C(C(=O)O)C=C1
Invalid SMILES: N#Cc1ccc(C2=CC(=CC=[PH](=O)(O)O)C=C2)cc1
Invalid SMILES: N#CC1=CC=CC(c2ccc(C=[PH](=O)(O)O)cc2)=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2=CC=C(c3ccccc3)C=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CC(c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C2=CC=C=CC=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=c1ccc(C(F)(F)F)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(C2=CC=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: N#CC1=CC=C(C2=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(C#CC=[PH](=O)(O)O)cc2)cc1)C(=O)O
Invalid SMILES: O=P1(O)(O)=CC=C(c2ccc(-c3ccccc3)cc2)C=C1
Invalid SMILES: N#CC1=CC=C(C2=CC=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc([IH]C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#Cc1ccc(=[PH](=O)(O)O)cc(-c2ccccc2)c1
Invalid SMILES: N#Cc1ccc(-c2ccc(=[PH](=O)(O)O)cc(C(=O)O)c2)cc1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C2=CC=C(C(F)(F)F)C=CC=C2)C=C1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=C=C1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)C1C=CCC(=C1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)n1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=CC1
Invalid SMILES: O=P(O)(O)CCCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=CC1
Invalid SMILES: O=C(CCCn1c2ccccc2c2cc3c(cc21)Nc1ccccc1N3CCCCCO)OCCC=[PH](=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)C1C=CC(=C1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)On1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCCC[PH](=O)(O)(O)O
Invalid SMILES: N#CC(O)=Cn1c2ccccc2c2cc3c(cc21)c1ccccc1n3P(=O)(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)-c1cccc(c1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=[PH](O)(O)=CC=CCc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=[PH](O)(O)=CCc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccc3c4ccccc4[nH]c3c21
Invalid SMILES: O=[PH](O)(O)=CCn1c2c(c3ccccc31)C=Cc1ccccc1N2
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccccc2c2c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)[nH]c1c3ccccc3[nH]c21
Invalid SMILES: O=P(=O)(O)(O)Oc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc2c(c1)[nH]c1c3ccccc3[nH]c21
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCCCCCO
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c4ccccc4n(CC[PH](=O)(O)(O)O)c3cc21
Invalid SMILES: O=C(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc4n(C5=CC=CC5)cccc3-4)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(-c2ccc(N(C3=CC=C(c4ccccc4)PC=C3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(N4C=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC=C1)c1ccc(N(C2=CC=C2)c2ccc(-c3ccccc3)cc2)cc1)c1ccccc1
Invalid SMILES: O=P(O)(O)#CC(CO)=C1C=CC(c2ccc(N(C3=CC=C(C4=CC=C(c5ccccc5)CC=C4)CC=C3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccccc2)cc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccc4cc3-c3ccccc3N4)cc2)c2c1=CC=2
Invalid SMILES: O=[PH](O)(O)=CC(=C[IH]c1ccc(-c2ccc(-c3cccc(C4=CC=C=C4)c3)cc2)cc1)N1C=CC=C(O)C1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=CC1)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(N4C=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2c1[nH]c1ccccc12

[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)c1ccc(C(F)(F)C(F)(F)F)cc1
Invalid SMILES: O=C(c1ccccc1)[PH](=O)(O)(O)O
Invalid SMILES: N#Cc1ccc(C[PH](=O)(O)(O)O)cc1
Invalid SMILES: O=C1NC(C(F)(F)F)=C(P(=O)(=O)(O)O)C1(F)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccccc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc[nH]1
Invalid SMILES: O=P(=O)(O)(O)CCNc1nc(C(F)(F)F)c[nH]1
Invalid SMILES: O=[PH](O)(O)(O)C(O)=C1N=CC(O)=N1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(F)=C1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=N/C=C\c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1
Invalid SMILES: O=[PH]1(O)(O)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccccc1O
Invalid SMILES: O=P(=O)(O)(O)c1cc(O)c(O)c(O)c1
Invalid SMILES: O=[PH](O)(O)=C1C=C=C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=Cc1cc(O)c(O)c(O)c1
Invalid SMILES: O=P(=O)(O)(O)NCc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=C1C(F)=C=C=C1F
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C(Cl)=CC(Cl)=C1Cl
Invalid SMILES: O=[PH](O)(O)=C1C=CC=CC1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccccc1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccccc1O
Invalid SMILES: O=Cc1c(O)c(O)c(O)c(O)c1P(=O)(=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1cc(O)ccc1O
Invalid SMILES: O=P(=O)(O)(O)Nc1c(F)c(F)c(F)c(F)c1F
Invalid SMILES: O=[PH](O)(O)=C1C=CC(F)(F)C=C1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(F)cc1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ncccc1O
Invalid SMILES: O=[PH](O)(O)(O)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=N1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2cccs2)s1
Invalid SMILES: O=P(=O)(O)(O)C=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=P(=O)(O)(O)C(=Cc1ccc(-c2cccs2)s1)c1cccs1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=C(O)C(=C/C=C\c1ccc(-c2cccs2)s1)P(=O)(=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)CCNc1sc(-c2cccs2)cc1C(F)(F)F
Invalid SMILES: O=P(=O)(O)(O)C(=Cc1ccc(-c2cccs2)s1)c1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=P(=O)(O)(O)CC=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(c1cccs1)c1cccs1
Invalid SMILES: O=P(=O)(O)(O)c1c(F)sc(-c2cccs2)c1F
Invalid SMILES: O=C(O)C(=Cc1ccc(-c2cccs2)s1)P(=O)(=O)(O)O
Invalid SMILES: O=C(O)c1cc(-c2cccs2)sc1P(=O)(=O)(O)O
Invalid SMILES: O=S(=O)(O)c1sc(-c2cccs2)c(P(=O)(=O)(O)O)c1Cl
Invalid SMILES: O=[PH](O)(O)(F)c1ccc(-c2cccs2)s1
Invalid SMILES: O=C(F)c1ccc(C(=C/C=C\C=C\C(F)(F)F)[PH](=O)(O)(O)O)cc1
Invalid SMILES: Nc1sc(-c2cccs2)c(C(=O)O)c1P(=O)(=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1sc(-c2sc(F)c(F)c2F)c(F)c1F
Invalid SMILES: O=P(=O)(O)(O)CCNc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(-c2cccs2)cc1
Invalid SMILES: O=P(=O)(O)(O)/C=C/c1ccc(-c2cccs2)s1
Invalid SMILES: O=C(O)C(=C/C=C\c1ccc(-c2cccs2)s1)[PH](=O)(O)(O)O

[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 13 C, 4, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 14 C, 4, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 14 C, 4, is greater than permitted
[12:43:56] Explicit valence for atom # 13 C, 4, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:43:56] Explicit valence for atom # 8 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C1c2ccccc2-c2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Cc2ccccc21
Invalid SMILES: O=[PH]1(O)(O)c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccc(Br)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Sc2cc(Br)ccc21
Invalid SMILES: O=P(O)(O)CCN1c2ccccc2[CH2+]c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=c1[nH]c2ccccc2c2ccccc12
Invalid SMILES: O=P(O)(O)CCN1c2ccc(Br)cc2[CH2+]c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=C1Nc2ccccc2[SiH-]c2ccccc21
Invalid SMILES: O=[PH](O)(O)=NCN1c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(O)(O)CCN1c2ccc(Br)cc2[CH2+]c2ccc(Br)cc21
Invalid SMILES: O=P(O)(O)CCN1c2ccccc2[CH2+]c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Sc2ccccc21
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2cccc3cccc1c23
Invalid SMILES: O=C1c2ccccc2[PH](=O)(O)(O)c2ccccc21

[12:43:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:57] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCCOc1cc2c(c3ccccc13)Sc1ccc(O)cc1S2
Invalid SMILES: O=[PH]1(O)(O)c2ccccc2Sc2c1sc1ccccc21
Invalid SMILES: O=[PH](O)(O)=C1c2c(sc3ccccc23)-c2sc3ccccc3c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2cc(Br)ccc2c2c3cc(S(=O)(=O)O)ccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3ccccc3ccc21
Invalid SMILES: Cn1c2ccccc2c2cc(C=CC=[PH](=O)(O)O)ccc21

[12:43:57] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:43:58] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccccc1

[12:43:58] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:43:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:43:59] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:43:59] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1cccc(N(c2ccccc2)c2ccccc2)c1

[12:44:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:44:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:01] Explicit valence for atom # 24 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)CP(=O)(=O)(O)O

[12:44:01] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:44:01] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:44:02] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:03] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1cccc(N(c2ccccc2)c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)(O)CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:44:03] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:44:03] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: O=C(CCCP(=O)(=O)(O)O)N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(CCCP(=O)(=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:44:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(O)c1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:44:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:44:05] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:44:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)=C(CP(=O)(=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:44:05] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:05] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:05] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:05] Explicit valence for atom # 16 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CC1=C(N(c2ccccc2)c2ccccc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-n2c3ccccc3c3ccccc32)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1

[12:44:05] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:05] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:05] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:44:05] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:05] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:05] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:05] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-n2c3ccccc3c3cc(Br)ccc32)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc2c1c1ccccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)(O)C1CN2CCC(CCO)(CC2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc3c4c(c2)CCCN4CCC3)s1
Invalid SMILES: O=[PH]1(O)(O)CN2CCC(CCO)(CC2)c2cc(-c3cccs3)ccc21
Invalid SMILES: O=P(=O)(O)(O)C1CCCN2CCCC3=C2C(O)(c2cccs2)CCN3CC1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2cc3c4c(c2)CCCN4CCC3)s1
Invalid SMILES: O=[PH]1(O)(O)CCC2=C(C1)c1ccc(cc1)N2CCC1=CC=C1
Invalid SMILES: O=P(=O)(O)(O)C1C=CC2CCN(C1)C(N1CCC3=CCC1=C3)C2
Invalid SMILES: O=[PH]1(O)(O)CN2CCC(O)(CCO)CC2c2cc(-c3cccs3)ccc21

[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1cc2c3c(c1)CCCN3CCC2)c1cccs1
Invalid SMILES: O=[PH]1(O)(O)C=C2CCCN3CCCC(=C23)C=C1c1cccs1
Invalid SMILES: O=[PH]1(O)(O)CCN2CCC(O)(CC1)c1cc3ccsc3cc12
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)sc1c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2c(c3ccccc31)-c1ccccc1Sc1ccccc1-2
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)sc1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3sc4ccccc4c3ccc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)oc1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCc1ccc2c(c1)sc1c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccccc2c2sc3ccccc3c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2sc3ccccc3c21
Invalid SMILES: Cn1c2c3ccc(C=C=[PH](=O)(O)O)cc3c1=c1ccccc1=c1ccccc1=2
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c3ccccc4ccccc4c-3c2c1
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccccc3c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccc(O)cc3c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)-c1c-2c2ccccc2c2ccccc12
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc(C3CCCCC3)c3cccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)c2cccc3c(C4CCCCC4)ccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)C(=O)c2ccc(-c3cccc(O)c3)c3cccc1c23
Invalid SMILES: O=C1NC(=O)c2cccc3c(-c4ccc(O)cc4)ccc(c23)C(=O)C1=[PH](=O)(O)O
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc(-c3ccccc3)c3cccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)N(C(F)(F)F)C(=O)c2ccc(-c3ccc(O)cc3)c3cccc1c23

[12:44:06] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc2c3c(ccc(CNP(=O)(=O)(O)O)c13)C(=O)N(CCc1ccncc1)C2=O
Invalid SMILES: O=C1c2cccc3cccc(c23)C(NP(=O)(=O)(O)O)C(=O)N1CCc1ccncc1
Invalid SMILES: O=C(O)CNc1cc2c3c(c(NCO)cc4c3c1C(=O)C(=[PH](=O)(O)O)NC4=O)C(=O)N(CO)C2=O
Invalid SMILES: O=[PH](O)(O)=Cc1cccc2c3c(ccc12)=CC=c1ccccc1=c1ccccc1=3

[12:44:06] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:44:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(CCCCC=[PH](=O)(O)O)OC1=CC=c2ccc3c4c(ccc(c24)=C1)=c1ccccc1=CC=3
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)cc1

[12:44:07] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)cc1

[12:44:10] Explicit valence for atom # 22 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1

[12:44:13] Explicit valence for atom # 22 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1O

[12:44:14] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1

[12:44:14] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1

[12:44:19] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1

[12:44:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1

[12:44:23] Explicit valence for atom # 22 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(CP(=O)(=O)(O)O)cc3)cc2)cc1

[12:44:23] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1

[12:44:24] Explicit valence for atom # 20 P, 7, is greater than permitted

Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1)C(F)(F)F

[12:44:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccc(O)cc2)c2ccc(-c3ccccc3)cc2)cc1

[12:44:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:26] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccc(-c2ccccc2)cc1

[12:44:26] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc3c(c2)-c2cc(-c4ccccc4)ccc2-3)cc1

[12:44:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:27] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(-c3cccc4nsnc34)cc2)cc1

[12:44:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12

[12:44:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2cccc3nsnc23)cc1

[12:44:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:44:28] Explicit valence for atom # 4 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)Oc1ccc(N(c2ccccc2)c2ccc(-c3cccc4nsnc34)cc2)cc1
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc3c4c(ccc1c24)C(=O)N(c1ccccc1)C3=O

[12:44:34] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: COc1ccc(N(c2ccc(C=CC=[PH](=O)(O)O)cc2)c2ccc(-c3ccccc3)cc2)cc1

[12:44:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1

[12:44:49] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1

[12:44:50] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)c3nsnc23)cc1

[12:44:52] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: COc1ccc(N(c2ccc(C=CC=[PH](=O)(O)O)cc2)c2ccc(-c3ccc(-c4ccccc4)cc3)c3nsnc23)cc1

[12:44:53] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCSc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)c3nsnc23)cc1

[12:44:54] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=CC2)c2ccc(-c3ccc(-c4ccc5[nH]snc4-5)cc3)cc2)=C1

[12:44:54] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: O=c1c(=[PH](=O)(O)O)c(=O)c2ccc3c4ccc5c(=O)n(CO)c(=O)c6ccc(c7ccc1c2c73)c4c65

[12:44:57] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)s3)s2)cc1

[12:45:07] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc3[nH]c4ccc(N(c5ccccc5)c5ccccc5)cc4c3c2)cc1

[12:45:07] Explicit valence for atom # 41 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)=Cn1c2ccc(N(c3ccccc3)c3ccccc3)cc2c2cc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)ccc21

[12:45:14] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1

[12:45:16] Explicit valence for atom # 33 P, 7, is greater than permitted

Invalid SMILES: C=CCN(C1=CC=C1)c1ccc(-c2ccc(-c3ccc(N(C4=CC=CCC4)c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1

[12:45:16] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:45:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(Oc3ccccc3)cc2)cc1

[12:45:27] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:45:33] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:45:40] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: CCC(C#N)=Cc1ccc(N2C=CC([PH](=O)(O)(O)CC(C)(C)C)=CC=C2c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1

[12:45:45] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)Cc1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccc(C4=CC=CC4)cc3)cc2)cc1

[12:45:50] Explicit valence for atom # 4 P, 7, is greater than permitted

Invalid SMILES: O=C1SC(=[PH](=O)(O)O)SC1=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:45:53] Explicit valence for atom # 34 P, 7, is greater than permitted

Invalid SMILES: O=C1C(=Cc2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)SC(=[PH](=O)(O)O)N1C(=S)CO

[12:46:02] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3cccc(-c4ccccc4)c3)cc2)cc1

[12:46:07] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-n3c4ccc(-c5ccccc5)cc4c4cc(-c5ccccc5)ccc43)cc2)cc1

[12:46:23] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1

[12:46:24] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:46:32] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(-c3ccc4c(c3)sc3cc5ccc3[nH]cccccc3cccccc4n35)cc2)cc1

[12:46:33] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:46:33] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(C1=CC=C1)C1=CC(NC2=CC=C2)=C2C=C(O1)c1cc(OCCCP(=O)(=O)(O)O)ccc12
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21

[12:46:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCCCCn1c2ccccc2c2c3ccccc3ccc21
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)[nH]c1c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=Cc1cc2c(cc1O)[nH]c1ccccc12
Invalid SMILES: O=P(=O)(O)(O)Nc1ccc2c(c1)[nH]c1ccccc12
Invalid SMILES: COc1cc2[nH]c3ccccc3c2cc1PC=CC=[PH](=O)(O)O
Invalid SMILES: O=P1(O)(O)=CC=C(n2c3ccccc3c3ccccc32)C=C1
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2ccccc21
Invalid SMILES: O=P(O)(O)CCN1c2cccc(c2)-c2cc(C=[PH](=O)(O)O)ccc21
Invalid SMILES: O=P(=O)(O)(O)n1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1cc2c(cc1O)[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)[nH]c1ccccc12

[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Br)cc2ncc=2c1
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Cl)cc2Oc2cc(Br)ccc21

[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCSc1ccc2c(c1)Nc1cc(Br)ccc1S2
Invalid SMILES: O=P(=O)(O)(O)CCN1c2ccc(Cl)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccc(Br)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(S(=O)(=O)O)cc2Sc2ccc(S(=O)(=O)O)cc21
Invalid SMILES: O=[PH](O)(O)=CN1c2ccccc2Sc2cc(Br)ccc21
Invalid SMILES: O=C(O)c1ccc2c(c1)N(P(=O)(=O)(O)O)c1ccccc1S2
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2ccc(Cl)cc21
Invalid SMILES: O=[PH](O)(O)=CN1c2ccc(Br)cc2Sc2ccc(Cl)cc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2cc(Br)c(Br)cc21

[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 22 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1Nc2ccc(S(=O)(=O)O)cc2Sc2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3ccccc3Nc3ccccc32)cc1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)n1c2ccccc2c2cc(Cl)ccc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=c1[nH]c2ccc(Br)cc2c2ccc(Br)cc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccc(Br)cc2c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1cc2n[nH]c3ccccc3c-2n1
Invalid SMILES: O=P(O)(O)CCn1c2ccc(P(=O)(=O)(O)O)cc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=C3C(O)=CC(O)=C32)cc1
Invalid SMILES: O=C(C=[PH](=O)(O)O)OCCOC(=O)n1c2ccccc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccc(Br)cc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc(Br)ccc21
Invalid SMILES: N#CC(C#N)=Cc1ccc2c(c1)c1cc(Br)ccc1n2CC=[PH](=O)(O)O

[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:34] Explicit valence for atom # 16 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccc(N(C4=CC=CC4)c4ccccc4)cc3)cc(=[PH](=O)(O)O)s2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C(C(F)(F)F)OC=C2)C2=CC=c3c2cccc3=CC=C2PC=CC3=CC=CC=CCC=CN32)=C1
Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc(-c3ccc([PH](=O)(=O)O)c4nsnc34)cc2)c2ccccc12

[12:46:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1cc(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)cc(C2=CC=C2)s1
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=C(O)C1=Cc2ccc(c3c(ccc4ccc-4cccc(=CC=CC4=C=C4)n2C2=CCC(=[PH](=O)(O)O)C=C2)C=3)OC1
Invalid SMILES: O=C(O)c1ccc(C#P(=O)(O)O)cc1N(c1ccccc1)c1ccc(-c2ccc(P(=O)(O)O)c3nsnc23)cc1
Invalid SMILES: O=C1C=C2C(N(c3ccccc3)c3ccc(-c4ccc(P(=O)(O)O)c5nsnc45)cc3)=CC=C(C#P(=O)(O)O)C12
Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc(-c3ccc([PH](=O)(=O)O)c4nsnc34)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)c2nsnc12

[12:46:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(F)cc4)cc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2F)c2nsnc12
Invalid SMILES: O=[IH](O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)=C(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC(c4ccc(N=CC5=C=CC5)cc4)C=C3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=Cc1cccs1
Invalid SMILES: O=P(=O)(O)(O)c1cccs1

[12:46:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1cscc1Br
Invalid SMILES: O=S(=O)(O)c1ccc(P(=O)(=O)(O)O)s1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C(Cl)(Cl)Cl)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=C/C=C/C(C(F)(F)F)=CS1

[12:46:36] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(C1=CC=C1)=C1C=CC(c2ccc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=CO1

[12:46:38] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(C2=CC=C2)cc1

[12:46:46] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccccc2)cc1

[12:46:49] Explicit valence for atom # 40 P, 7, is greater than permitted

Invalid SMILES: N#CCCCCCCCCCC(C#N)C=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1

[12:46:51] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccccc4)cc3)cc2)cc1

[12:46:52] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N2C=CC=CC2)cc1

[12:46:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:46:55] Explicit valence for atom # 30 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C(c3ccc(-c4ccccc4)cc3)C2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1

[12:46:57] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccc(-c3ccccc3)cc2)cc1

[12:46:58] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)cc(-c2ccccc2)c1

[12:46:58] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC=C1C=C(O)c2ccc(cc2)O1)C1=CC(c2ccc(-c3ccccc3)cc2)C=C1

[12:47:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccc(C4=CC=CC4)cc3)c3ccc(-c4ccccc4)cc3)cc2)=CC1

[12:47:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=CC4)cc3)cc2)cc(C2=CC=C2)c1

[12:47:02] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:03] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(N(C2=CC=C(c3ccccc3)C=CC=C2)c2ccc(C3=CC=C3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=C1

[12:47:08] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:08] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccc(C4=CC=C4)cc3)c3ccc(C4=CC=CC4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc(-c2ccccc2)c1

[12:47:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCC(C1=C=CC=C1)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)=CO1

[12:47:17] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC=C1C=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1)c1ccc(C2=CCC=C2)cc1

[12:47:18] Explicit valence for atom # 37 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C(=Cc1ccc(N(c2ccc(-c3ccccc3)cc2)c2ccc(-c3ccccc3)cc2)cc1)C=[PH](=O)(O)O

[12:47:19] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C2)c(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=C=C4)cc3)cc2)cc1

[12:47:20] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(C=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)=CCO1)C1=C=CCC=C1

[12:47:20] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(O)=C1C=CC(N(c2ccc(C3=CC=C(C4=CC=CC4)C3)cc2)c2ccc(-c3ccccc3)cc2)=C1

[12:47:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1

[12:47:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1

[12:47:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(c2ccccc2)=C1)c1ccccc1)C1=CC=CC(N(c2ccccc2)c2ccccc2)C=C1

[12:47:26] Explicit valence for atom # 33 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(C(=Cc2ccc(-c3ccc(N(C4=CC=C4)c4ccccc4)cc3)cc2)C=[PH](=O)(O)O)cc1

[12:47:30] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:47:30] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:47:31] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#CPC(=Cc1ccc(C2=CC=C(C3=CC=CCC3)C=CC=C2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccccc3)=CC(c3ccccc3)=CC=C2)cc1

[12:47:31] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(-c3ccc(C=CC=[PH](=O)(O)O)cc3)s2)s1)C(=O)O

[12:47:31] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:47:31] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:47:31] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1cccc(-c2ccc(C=[PH](=O)(O)O)s2)c1
Invalid SMILES: O=C(O)C1=CPC2=CC3=C(C=CC=CC=C2C3)N(c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(c4ccccc4)=CC=CC=C3)c2)cc1

[12:47:32] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C(=C1C=C(C2=CC(=[PH](=O)(O)O)C=C2)C1)c1ccc(-c2ccccc2)s1

[12:47:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:33] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(=CC(F)(F)F)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1-c1ccc(C2=CCC=C2)cc1

[12:47:33] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:47:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:33] Explicit valence for atom # 20 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)s3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC(C2=CC=C(C3=CC=C=C3)[IH]C=C2)=CC(c2cccc(C3=CC=C3)c2)=CC=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(C3=CC(F)=CC(C4=CC=C4)C=C3)c(F)c2)cc1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(-c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3F)cc2)C=CP1

[12:47:33] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:47:33] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=C(C2=CCC=C2)C=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CC=CC4)cc3)c2)cc1

[12:47:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:33] Explicit valence for atom # 26 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC=C(c4ccccc4)C=CC3)c2)cc1
Invalid SMILES: O=C1C=CC1=CC=C1C=CC1=C1C(Cl)=C1SC1=C(S(=O)(=O)O)C(Cl)=CC1=[PH](=O)(O)O

[12:47:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:34] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccccc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(C2=CC(c3ccccc3)=CC(c3ccccc3)=CC=C2)c1
Invalid SMILES: O=C(O)C1=CC=C(c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)CC=C1

[12:47:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(Cl)C(c2ccc(C3=CC=CC(Cl)C=C3)c(F)c2)S1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3cc(F)cs3)c(F)c2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(F)c(F)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC=C(C4=CC=C=C4)C=CC3)c2)cc1

[12:47:34] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:47:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC(=[PH](=O)(O)O)S1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(C3=CC(F)=CC(F)C=C3)c(F)c2)cc1
Invalid SMILES: O=[PH](O)(O)=c1cc(-c2ccc(C(F)(F)F)cc2)sc(-c2ccc(C3=CC=C3)s2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CC=C4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC=CC(C4=CC=C4)=CC3)c2)cc1

[12:47:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:34] Explicit valence for atom # 18 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CCC=C4)cc3)c2)s1
Invalid SMILES: O=C(O)c1cccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)c1

[12:47:35] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:47:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:35] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:47:35] Explicit valence for atom # 15 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1cc(C2=CCC2=CC=CC2C=CCCN2C2=CC=C2)cc(-c2ccc(C=[PH](=O)(O)O)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC=C(C4=CC=C4)C=CC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=C(c2ccc(O)c(Cl)c2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=CC3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccc(-c3ccc(C=[PH](=O)(O)O)cc3)s2)s1

[12:47:35] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:47:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(-c2ccc(-c3ccc(C(=O)O)s3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=C3)=CC(c3ccccc3)=CC=C2)cc1

[12:47:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C=CC=CC(C4=CC=CCC4)=CC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=C(c3ccc(-c4ccccc4)s3)C2)cc1

[12:47:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:36] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:47:36] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:47:36] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C=CC=CC(c4ccccc4)=CC3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(F)=CC(C4=CC=C4)C=C3)s2)cc1
Invalid SMILES: O=C(O)C1=CCC=C(N(c2ccccc2)c2ccc(-c3ccc(C=[PH](=O)(O)O)s3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N(c3ccccc3)c3ccccc3)c2)cc1

[12:47:36] Explicit valence for atom # 20 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C(=O)Sc1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1

[12:47:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:36] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-n3cccc(O)c4ccc3cc4)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(NC2=CC(c3ccc(C4=CC=C4)cc3)C=CC=C2)cc1

[12:47:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:37] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC=C(PC3=CC=C3)C=CC(C3=CC=CC=CC3)=C2)s1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-c2ccc(-c3cccs3)s2)cc1

[12:47:37] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cc(C2=CC=CC2)cc(-c2ccc(-c3ccccc3)cc2)c1

[12:47:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:37] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:47:37] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC=CC(c4ccccc4)=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC4=CC=C3C=CC=C4)c2)cc1
Invalid SMILES: O=C(F)C1=CN(c2ccc(-c3ccc(C=[PH](=O)(O)O)s3)cc2)C=CC=CC=C[IH]1
Invalid SMILES: O=C[IH]C1=CC=C2C=Cc3c(ccc(C(=O)O)ccc(C4=CC(=[PH](=O)(O)O)C=C4)cc32)C1=O

[12:47:38] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:47:38] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=C(C2=CC=CC(C3=CC=CC3)C=C2)C=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(F)(F)C=C3)c2)cc1

[12:47:38] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:47:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:38] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C=C1C=CC(c2ccc(C=[PH](=O)(O)O)cc2)=CC(C2=CC=C(C3=CC=C=C3)[IH]C=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(PC3=CC=CC3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(Cl)cc2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CCC=C3)=CC(c3ccccc3)=CC=C2)cc1

[12:47:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:39] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC(C2=C(C3=CC=C3)C=CC2)=C(c2ccc(F)cc2)[IH]C=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(-c3cccc(F)c3)c(F)c2)s1

[12:47:39] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(C3=CC=C=C3)c3ccccc3)cc2)S1

[12:47:39] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:47:39] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:47:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:39] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(-c3ccc(PC=[PH](=O)(O)O)cc3)s2)s1
Invalid SMILES: O=C(O)C1=CN(c2ccc(C3=CC(=[PH](=O)(O)O)S3)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(-c4ccccc4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C(F)(F)F)c2)cc1

[12:47:39] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:47:40] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:47:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:40] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(C2=CC=C(c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3C3=CC=C3)CC=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(C(=O)O)[IH]C=C(c4ccc(C5=CCC=C5)cc4)C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=CC3)cc(-c3ccc(C4=CC=CC(C5=CC=CC5)C=C4)cc3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC(C5=CC=C(C6=CC=C6)C5)C=C4)=C3)s2)cc1

[12:47:40] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1CC=C(C2=C=CC=C2)C=C(c2ccc(-c3ccc(-c4ccc(-c5ccccc5)cc4)cc3)cc2)S1

[12:47:41] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=C[IH]C(c2ccc(C3=CC=C(c4ccc(C5=CC=C=C5)[pH]4)C=CC3)cc2)=C(C2=CC=CC2)S1

[12:47:41] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:47:41] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1cc(C=[PH](=O)(O)O)cc(-c2ccc(C3=CC=CC(c4ccc(C5=CC=CCC=C5)cc4)C=C3)cc2)c1
Invalid SMILES: O=C(O)C(=C1CC(=[PH](=O)(O)O)S1)c1ccc(-c2ccc(-c3ccccc3)s2)s1

[12:47:41] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccn(-c2ccc(C3=CP(=O)(O)(O)=CC(c4ccc(C5=CC=C5)cc4)=C3)cc2)c1

[12:47:41] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(c4ccc(-c5ccccc5)cc4)C=CC=C3)c2)cc1

[12:47:42] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:47:42] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(C2=CC=C(C3=CC=C(C=[PH](=O)(O)O)C=C(c4ccc(C(=O)O)cc4)S3)CP2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=C3)cc(-c3ccc(C4=CC=C(C5=CC=C5)PC=C4)cc3)c2)cc1

[12:47:42] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:47:42] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:47:42] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(F)C(=C1C=C(C2=CC(=[PH](=O)(O)O)C=C2)C1)c1ccc(-c2ccc(Cl)cc2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)c(C3=CC(C4=CC(n5cccc5O)CC=C4)C=C3)s2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3cc(F)cc(-c4ccc(N(C5=CC=C5)C5=CC=CC5)cc4)c3)c2)cc1

[12:47:43] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=CC1=CC=C(c2ccc(-c3ccc(C4C=CC(c5ccc(C=[PH](=O)(O)O)cc5)=C4)cc3F)cc2)C1

[12:47:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:43] Explicit valence for atom # 21 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccc(C4=CCC=C(C5=CC=C5)PC=C4)cc3)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(-c3cccc(-c4ccc(C=[PH](=O)(O)O)cc4)c3)cc2O)cc1

[12:47:44] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1cc(-c2ccc(C=[PH](=O)(O)O)cc2)cc(-c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)c1

[12:47:44] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:47:44] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2ccc(-c3cc(C4=CCC=C4)cc(-c4ccc(C=[PH](=O)(O)O)cc4)c3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(=[PH](=O)(O)O)sc2-c2cccc(-c3ccc(C4=CC=C4)c(F)c3)c2)cc1

[12:47:45] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=CC=CC=C3)cc(-c3ccc(C4=CCC=C4)cc3)c2)cc1

[12:47:45] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:47:45] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:47:45] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC=C(n5cccc5)C(F)C=C4)PC=C3)s2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2sc(C=[PH](=O)(O)O)cc2C2=CC(C3=CC=C(c4ccc(C5=CC=C5)cc4)C3)=CC2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(C4=CC=C(C5=CC=C5)C4)C=CC3)c2)cc1

[12:47:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:45] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc(c1)-c1ccc(cc1)-c1ccc(cc1)-c1ccc(cc1)-c1ccc(cc1)C=CCC=CC=C2
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=CC3=CC(c4ccc(C5=CC=C5)cc4)=C2C=CC=C3O)cc1

[12:47:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:46] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(O)c(-c3ccc(-c4ccc(Cl)cc4)s3)c(C3=CCC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2=CC(c3ccc(C4=CC(C5=CC=C5)PC=C4)c(F)c3)C=C2)=C1

[12:47:46] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:47:46] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(-c3ccc(C4=CC=C(C5=CC=C5)BC=C4)cc3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(-c4ccc(P)cc4)cc3)cc(-c3cccc(O)c3)c2)cc1

[12:47:46] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:47:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:46] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(-c2ccc(C(C(=O)O)=C3C=C(C4=CC(=[PH](=O)(O)O)C=C4)C=C3O)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccccc3C3=CC=C(C4=CC=CC4)PC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(F)c2)cc1

[12:47:47] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C2)cc(-c2ccc(C3=CC(C4=CC=C(C5=CC=C5)C4)C=C3)cc2O)c1

[12:47:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:48] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccccc3C3=CCC=C(C4=CC=C4)PC=C3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(C3=CC=CCC=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)c(F)c3)c2)cc1

[12:47:48] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(c4ccc(C5=CC=C5)cc4)PC3)c2)cc1

[12:47:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:48] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cc(C2=CC=C=C2)cc(-c2ccc(C3=CC=C(C4=CCC=C4)C=CC3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(C4=CCC=C4)C=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1

[12:47:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:49] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC(c2ccccc2)=CC(c2ccc(N(C3=CC=CC(C4=CC=C4)C=C3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3cccc(-c4ccc(C5=CCC=C5)cc4)c3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC(c4ccc(C5=CC=C5)cc4)C=CC=C3)cc2)cc1

[12:47:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:49] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(C3=CC=C(c4ccc(C5=CC=C5)cc4)C=CC=C3)cc2)c(C2=CC=C2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(F)=C(c3ccc(-c4ccccc4)s3)C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3cccc(-c4ccccc4)c3)c2)cc1

[12:47:49] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:47:49] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccccc3)c2)cc1C1=CC=C(C2=CC=C(C3=CC=C3)C2)C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=CC3)C=CC(c3ccc(-c4ccc(-c5ccccc5)cc4)cc3)=C2)cc1

[12:47:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:50] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(c2ccc(C3=CC=C3)cc2)SC(C2=CC=C(c3ccccc3)C=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC(C4=CCC=C4)=C3)cc2)c(-c2ccc(C3=CCC=C3)cc2)c1

[12:47:50] Explicit valence for atom # 9 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(C2=CP(=O)(O)(O)=CC(C3=CC(C4=CC(c5ccc(C(=O)O)cc5)C=C4)C=C3)=C2)cc1

[12:47:50] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(C2=CC(C=[PH](=O)(O)O)=CC=C(c3ccc(-c4ccc(C5=CC=C5)cc4)s3)S2)cc1

[12:47:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:51] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:47:51] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:47:51] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=C3)C=CC(c3ccc(C4=CC=C(C5=CC=CCC5)PS4)cc3)=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C3=CC(c4ccc5c(c4)CC5=CC=C4C=CC=C4)=C3)ccc(=[PH](=O)(O)O)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(c4ccc(-n5ccc(O)c5)cc4)=C3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(C4=CC=C4)cc3)cc(-c3ccc(C4=CCC=C4)cc3)c2)s1

[12:47:51] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:47:51] Explicit valence for atom # 26 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC(F)C(F)=C(F)C4=C(F)C4=CC=C4)=CC3)s2)cc1
Invalid SMILES: O=C(O)C1=C(C2=CC(c3ccc(C4=CC=C4)cc3)=C2)C=C(c2ccc(C=[PH](=O)(O)O)s2)C=C[IH]1

[12:47:51] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:47:51] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(F)=CC(F)C3=CC=C3CC3=C(F)C3=CC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)c2)cc1

[12:47:51] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(F)=C(c4ccc(C5=CC=C5)cc4)[IH]C=C3)c2)cc1

[12:47:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:52] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:47:52] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(F)=C(C4=CC=C(N=C(O)C5=CC=C5)C4)CC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC(F)=C(c4ccc(C5=CC=C5)cc4)C=CC3)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CP(=O)(O)(O)=CC(C3=CC(C4=CC=C(C5=CC=CCC=C5)C(C5=CC=C5)CC4)=CC3)=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(C4=CC=C4)cc3)c2)cc1

[12:47:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:47:52] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)ccc2C2=CC=C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(C4=CCC=C(C5=CC=C5)C=C4)cc3)c(C3=CC=CCC3)c2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccc(-c4ccc(C5=CC=C=C5)cc4)c(F)c3)c2)cc1

[12:47:53] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(C3=CCC=CC3)c2)cc1

[12:47:53] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=C(C4=CC(F)C(F)=C(C5=CC=C5)N4)C=C3)s2)cc1

[12:47:53] Explicit valence for atom # 15 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccc(C=[PH](=O)(O)O)cc3)cc(-c3ccc(C4=CC=CC4)cc3)c2)cc1

[12:47:55] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC(c2ccccc2)=C(c2ccc(N(c3ccccc3)c3ccc(N(C4=CC=C4)c4ccccc4)cc3)cc2)C=C1

[12:48:09] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC(c2ccc(N(C3=CC=C=C3)C3=CC=CC3)cc2)=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1

[12:48:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cc(-c2ccc(N(C3=CC=C3)C3=CCC=C=C3)cc2)cc(-c2ccc(N(C3=CC=C=C3)c3ccccc3)cc2)c1

[12:48:12] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)(C2=CC=C2)C=CC(c2ccc(N(C3=CC=CC3=CC=C3C=CN3c3ccccc3)c3ccccc3)cc2)=C1

[12:48:13] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1SC2=C3C(=CC=c4ccc(n4C4=CC=C4)=CC=CC=CC=C2)CC=CC=C2C=CC=CC=c4ccc(n42)=CC=C31

[12:48:17] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC(N(C2=CCC=C2)C2=CC=CC2)=C(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)C=C1

[12:48:24] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(C3=CCC=C(N(C4=CC=CC4)C4=CC=CC4)C=C3)c3ccccc3)cc2)C=C1c1ccccc1

[12:48:26] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC=C(C2=CC(N(C=C3CC=CC3)C3=CCC=C3)=CC(c3ccc(N(C4=CC=C=C4)C4=CC(O)C=CC4)cc3)C=C2)C=C1

[12:48:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(c3ccccc3)c3ccc(N(C4=CC=C4)C4=CC=CC4)cc3)cc2)C=C(C2=CC=CC2)C1

[12:48:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=Cc2cccccccc3ccc(ccc4cccccc5c(ccc6ccc6ccc1c24)OC5)n3C1=CC=C1

[12:48:30] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(C1=CC=CC1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(N4C=CC=CC4)cc3)cc2)cc1

[12:48:32] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC2=c3c1ccc1ccc4n1c(cccccc3=CC=c1ccc(n1C1=CC=C1)=CC=CC=CC=C=C2)C=CC=CC=4

[12:48:41] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1cc(-c2cccc(N(C3=CC=CC3)c3ccccc3)c2)cc(-c2ccc(N(C3=CC=C3)c3ccccc3)cc2)s1

[12:48:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:48:46] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-n4c5ccccc5c5ccccc54)s3)s2)cc1
Invalid SMILES: N#Cc1ccc(C=[PH](=O)(O)O)cc1-c1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)s2)s1

[12:48:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:48:46] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-n4c5ccccc5c5ccccc54)cc3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC=C2)c(-c2ccc(-c3ccc(-n4c5ccccc5c5ccccc54)s3)s2)c1

[12:48:47] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC(C3=CCC=C3)C2)C2=CC21

[12:48:50] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)CC1=CCC1=CC=C1

[12:48:56] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH]1(O)(O)CCC(c2ccc(N(c3ccccc3)c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)CC1

[12:48:57] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)CC1

[12:49:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCCC2)C2=CC1=CC2

[12:49:01] Explicit valence for atom # 38 P, 7, is greater than permitted

Invalid SMILES: O=C1C(c2ccc(N(c3ccccc3)c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)CCC[PH]1(=O)(O)O

[12:49:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH]1(O)(O)CCCC(F)(c2ccc(N(c3ccccc3)c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)CC1

[12:49:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCCC2(F)C2=CC=C2)CC1

[12:49:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)C2=CC1=CCc1cccc2c1

[12:49:07] Explicit valence for atom # 36 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(N(c2ccc(C=O)cc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccc(C#P(=O)(O)O)cc5)cc4)CCCCC3)cc2)cc1

[12:49:09] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)C2=CC=C21

[12:49:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(c1ccc(N(C2=C=C2)c2ccccc2)cc1)c1ccc(N(C2=CCC=C2)c2ccc(-c3ccccc3)cc2)cc1

[12:49:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)CC1=CC1=CC=C1

[12:49:14] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccccc5)cc4)CCCC3)cc2)cc1

[12:49:19] Explicit valence for atom # 35 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(N(c2ccc(Cl)cc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccc(C#P(=O)(O)O)cc5)cc4)CCCCC3)cc2)cc1

[12:49:19] Explicit valence for atom # 34 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccc(C#P(=O)(O)O)cc5)cc4)CCCC3)cc2)cc1

[12:49:22] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:49:22] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:49:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#CC1=CC(=CC=[PH](=O)(O)O)C=C1
Invalid SMILES: N#CC1=CC=CC(=CC=[PH](=O)(O)O)C=C1
Invalid SMILES: O=[PH](O)(O)=CC=CPc1ccc(Br)cc1

[12:49:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:22] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:49:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CPc1ccc(C(F)(F)F)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C(F)(F)F)C=C1
Invalid SMILES: O=Nc1ccc(/C=C/C=[PH](=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1ccc(Br)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C(F)(F)F)cc1
Invalid SMILES: O=[PH](O)(O)=CC=CPc1ccccc1Br
Invalid SMILES: O=[PH](O)(O)=c1ccc(C(F)(F)F)cc(C(F)(F)F)c1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CS1

[12:49:22] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:49:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(C#P(=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1c(F)c(F)c(F)c(F)c1F
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(Br)cc1
Invalid SMILES: N#CC1=CC(O)=CC(=CC=[PH](=O)(O)O)C=C1
Invalid SMILES: N#CC1=C=CC=CC(C=CC=[PH](=O)(O)O)=C1
Invalid SMILES: O=[PH](O)(O)=C/C=C\c1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(C(F)(F)F)=C1
Invalid SMILES: O=Cc1ccc(C=CC=[PH](=O)(O)O)cc1
Invalid SMILES: N#CC(Cl)=CC=C1C(=CC=[PH](=O)(O)O)C=CC1=CC(=CCO)C(=O)O

[12:49:23] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:49:23] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(/C=C\C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc(PC=CC=[PH](=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Cl)cc1
Invalid SMILES: O=[PH](O)(O)=CC=CPc1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CPC=CPc1cccc(N(CCO)CCO)c1
Invalid SMILES: N#CC(C#N)=Cc1ccc(/C=C/C=[PH](=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C/C=C\c1c(F)c(F)c(F)c(F)c1F

[12:49:24] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C=C2)c2ccc(N(c3ccc(C4=CC=C=C4)cc3)c3ccc(C4=CC=C4)cc3)cc2)=CC1

[12:49:24] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(C3=CCC=C3)c3nsnc23)cc(-c2ccc(N(C3=CC=C=C3)C3=CC=C3)cc2)c1

[12:49:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C=C2)cc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)c1

[12:49:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=C(N(c2ccc(O)cc2)c2ccc(N(C3=CC=C=C3)C3=CC=CC3)cc2)C=C(C2=CC=CCC=C2)CC1

[12:49:33] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: O=CC1=CC(=[PH](=O)(O)O)NC1=CPc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12

[12:49:36] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: O=c1cccc2c3ccc(n12)Cc1c(ccc(=[PH](=O)(O)O)[nH]c1=S)-c1ccc(cc1)N3C1=CC=C1

[12:49:54] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)c2cccc(O)c2)cc1)C1=CCC=CC=C1

[12:49:54] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1cccc(-c2ccc(N(C3=CC=CC3)c3ccc(C4=CC=C4)cc3)cc2)c1)c1ccccc1

[12:49:59] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2CC=CC=C=CC3=CC=C3c3ccc(cc3)N(c3ccc(-c4ccccn4)cc3)c3ccc2cc3)=CC1

[12:50:06] Explicit valence for atom # 49 P, 7, is greater than permitted

Invalid SMILES: CCC(=CC(=C1C=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1)c1ccc(N2C=C=CC=CC=CC=C3C=CC=C32)cc1)C=[PH](=O)(O)O

[12:50:10] Explicit valence for atom # 33 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC=C2C=CC(O)=CC=C3C=CC3=CC=c3ccccc3=CC=C3C=C(C=C(C=[PH](=O)(O)O)CC=CC=C1)N23

[12:50:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3ccc4ccccc4cccc(n23)=CC=c2ccc3n2C(=C=CC=CC=C=C1)CC=CC=CC=3

[12:50:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)c2ccccc2)cc1

[12:50:37] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)C2=CC=C2)cc1

[12:50:40] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:50:50] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CC=CC(c2ccccc2)C=C1)=C1C=CC(N(C2=CC=CC=CC=C2)C2=CC=C2)=CC1)N1C=CC=CC=C=CC1

[12:50:59] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(N(c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)c2ccc(N(C3=C=CCC3)c3ccccc3)cc2)=C1

[12:50:59] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC=C(c2ccc(N(C3=CC=C=C3)c3ccc(-c4ccc(N(C5=CC=C5)c5ccccc5O)cc4)cc3)cc2)C=C1

[12:51:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:51:01] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(N(CC=[PH](=O)(O)O)C2=CC(C3=CC=C=C3)C=CC=C(c3ccc(N(C4=CC=CC4)c4ccccc4)cc3)C=C2)cc1

[12:51:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C3C=CC(=C3)N(c3ccccc3)c3ccc(cc3)N(c3ccccc3)C3=CC=C(C=CC=CC2C=CC=CCC=C=CC=C1)C3

[12:51:13] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC1=C(O)C1=CC(=CC=C1C=CC=C1O)c1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)c1ccccc1

[12:51:23] Explicit valence for atom # 48 P, 7, is greater than permitted

Invalid SMILES: C=CC(=CC(=C1C=CC(O)=C1)c1ccc(N(C2=CC=C2)C2=CC=CC(c3ccc(N(C4=CCC=C4)C4=CC=C=CC4)cc3)C=C2)cc1)C=[PH](=O)(O)O

[12:51:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:51:27] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(c2ccccc2)c2ccccc2)=C1)c1ccccc1)N(C1=CCC=C1)C1=CC=CC1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)C2=CC(c3ccc(N(C4=CC=C4)C4=CC=CC4)cc3)C=C2)C=CCO1

[12:51:27] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC=C(N(C2=CC=C=C2)c2ccc(N(C3=CC=CC(C4=CC=C4)C3)c3ccccc3)cc2)C=C1

[12:51:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:51:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:51:32] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=C3)c3ccc(-c4ccc(N(C5=CC=C5)C5=CC=C5)cc4)cc3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1cccc(N(c2ccccc2)c2ccccc2)c1)c1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)C2=CC=CC2)cc1

[12:51:33] Explicit valence for atom # 31 P, 7, is greater than permitted

Invalid SMILES: O=C1C=CC(N(C2=CC=CC=CC=C2)c2ccc(-n3cccc3)cc2)C=CC(=CC(C=[PH](=O)(O)O)c2ccccc2)O1

[12:51:39] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=C1C=CC(N(c2ccccc2)c2ccc(O)cc2)=C1)c1ccc(N(C2=CC=CC2)c2ccccc2)cc1

[12:51:40] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3n2C(=CC=C2C=CC2=CC=C=CC1=CC=C1C=CCC=C1)C=CC=CC=3

[12:51:44] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC=c2ccc3n2C(=CC=c2ccc(n2C2=CC=CCC2)=CC=CC=C=CC1)C=CC=CC=c1ccccc1=CC=3

[12:51:48] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C3C=CC(=C3)c3ccc(cc3)N3CC3=CC=CCC2=CC=c2ccc3n2C(=CC=CC=CC=C1)C=CCC=3

[12:51:50] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cccccccccc2c3oc(c(n(C4=CC=CC4)c4ccc(cc4)c4cccc(c1)c4)=CC=3)=CC=C2

[12:51:50] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC(=C2C=CC(N(c3ccccc3)c3ccccc3)=C2)C2=CC=C(CC2)C2=CC=C(C=CC3(O)C=C=CN1C=CCC=C3)CC=C2

[12:51:52] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC=CC=C2)C2=CC=CC2)=C1)c1ccc(N2C=CC=CC2)cc1)C1=CC=C=C1

[12:51:52] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C2)c2ccc(N(C3=CC=C=C3)c3ccc(C4=CC=CC4)cc3)cc2)=CC1

[12:51:54] Explicit valence for atom # 42 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C(C=C1C=CC(c2cccc(N(c3ccccc3)c3ccc(N(C4=CC=C=C4)c4ccccc4)cc3)c2)=C1)C=[PH](=O)(O)O

[12:51:55] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=CCC=C2)C2=CC=CC2)cc1

[12:52:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(C=C1C=CC(N(C2=CC=C(C3=CC=C=C3)C=CC=C2)c2ccc(C3=CC=C=C3)cc2)=C1)C1=CC=C=CC1

[12:52:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(C2=CC(C3=CCC=C3)C=C2)N(c2ccc(N(c3ccccc3)c3ccccc3)cc2)C=C1

[12:52:08] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2cccc(N(C3=CC=C=C3)c3ccc(-c4ccc(-c5ccc(C6=CC=C6)cc5)cc4)cc3)c2)=CC1

[12:52:16] Explicit valence for atom # 47 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)C=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O

[12:52:16] Explicit valence for atom # 2 P, 7, is greater than permitted
[12:52:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:16] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:17] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)C=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:17] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2C=CC=CC=C=CC=C3C=CC=CC=C4C5=CCC=CC6=CC=C(C=CC2=CC=C3O6)N45)=CC1
Invalid SMILES: O=P(=O)(O)(O)C1=CC=C(N2C=C=CC=CCC=CC=c3ccc(n3C3=CC=CC3)=CC=C3C(OC4=CC=CC4)=CC=C32)C=C(O)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccccc2c(ccc3oc(c1)=C3)OC1=CC=C(Oc3ccccc3)N3C(=CC=CCC=CC=2)C=CC=C13
Invalid SMILES: N#CC[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:18] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:18] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)C=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:18] Explicit valence for atom # 42 P, 7, is greater than permitted
[12:52:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:18] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: N#CC(c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1)=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC1=CC(=CC=C(OC2=CC=C(Oc3ccccc3)N(C3=CC=C3)CC=C2)C2=CC=C2)O1)N1C=C=CCCCC=CC1
Invalid SMILES: N#CCCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:19] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=C(Oc3ccc(N(C4=CC=C=C4)C4=CC=C4)cc3)N3C=CCC=C=CC=C3C1)O2
Invalid SMILES: O=[PH](O)(O)(c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1)n1cccc1

[12:52:19] Explicit valence for atom # 52 P, 7, is greater than permitted
[12:52:19] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: C=CCCC(=CC1=CC(=CC=C2C=C=CCC=C=C=C3CC=CC=C4C=CCC=C5C=CC(=CC=C6OC3=CC=C6O2)N4N5c2ccccc2)O1)C=[PH](=O)(O)O
Invalid SMILES: N#CC(C#N)C=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:19] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)Oc1cc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)ccc1O

[12:52:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:20] Explicit valence for atom # 42 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)Oc1cc(N(c2ccccc2)c2ccccc2)ccc1Oc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(C#N)C=CC1=CC=CC=CC(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)=C1

[12:52:20] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:52:20] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#CCCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:21] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:52:21] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: N#CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:21] Explicit valence for atom # 42 P, 7, is greater than permitted
[12:52:21] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: O=CC[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC=C(O)C(N(C2=C=C=CC2)C2=CC=C3OC4=CC=C5OC4=CC=CC5=CC=C4C=CC4=CC=CCC=CC=C32)=C1

[12:52:22] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:52:22] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:52:22] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:52:22] Explicit valence for atom # 8 P, 7, is greater than permitted

Invalid SMILES: N#CCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)CC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C=CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:22] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:52:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC=C3Oc4ccc(cc4)N(c4ccccc4)C2=CC=CC2=CC=CCC=CC=C(C=CC1O)N23

[12:52:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:22] Explicit valence for atom # 46 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1)C=C1C=CC=CC1
Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O

[12:52:24] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: N#CCCCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:24] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:52:24] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)N(c1ccccc1)c1ccc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: N#CCCCCCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:24] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:25] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: N#CCC=CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cccccccc2cccccc3cccc4c(Oc5ccccc5)ccc4oc(ccc4cc(c1)o4)n23

[12:52:26] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:52:26] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:52:26] Explicit valence for atom # 48 P, 7, is greater than permitted

Invalid SMILES: N#CC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)C=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)CC=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1C#P(=O)(O)O

[12:52:27] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC(=CC(=C1C=CC=C1)N(C1=CC=CC=CC=C1)C1=CCC=C1)n1cccc1)c1ccccc1

[12:52:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:27] Explicit valence for atom # 2 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1c2c3ccccccccc(n1-3)C=CC=CC=C1C=CC=CC=c3ccc(n31)=CC2)C1=CC=C=C1
Invalid SMILES: O=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:28] Explicit valence for atom # 48 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=C3OC4=CC=C(Oc5ccccc5)C(=CC=C4)C3=CC=c3ccc4n3C(=CCC=C=C=CC=C1)C=CC=CC=4)O2
Invalid SMILES: O=CC(=O)C(=O)C=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O

[12:52:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[12:52:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=c3oc4c5n(c(cccccc3=CC=CC=CC=CC1)C=CC=5)C(Oc1ccccc1)=CC=4)O2

[12:52:28] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:52:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#CC(=CC(=C1C=CC(N(C2=CC=C2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CCC=C1)C1=CC=CC1)C1=CC=C=C1

[12:52:29] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:52:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#CCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P1(O)(O)=CC=C(O)C(n2cccccccc3c(Oc4ccc(N(C5=CC=C5)c5ccccc5)cc4)ccc2-3)C=C1

[12:52:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C(=Cc1cc(O)cc2ccc(Oc3ccccc3)c3ccccccc-3n12)N1C=C=CC1

[12:52:30] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC(C2=CC=C=C2)=CC(N(C2=CC=C(C3=CC=C3)OC3=CC=C(C=CC=C3)C=C2)c2ccccc2)=C1

[12:52:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:30] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=c2ccc(n2N(C2=CC=C2)C2=CC=CC2)=CC=C2OC3=CC=C(C=CC=CC(O)=CC=C2C=C1)C=CC=C3
Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CCC=C1)=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1
Invalid SMILES: O=P(O)(O)#Cc1cc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)ccc1N(c1ccccc1)c1ccccc1

[12:52:31] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:52:31] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)CCC=Cc1c(CCC=[PH](=O)(O)O)c(-c2ccccc2)cc2c3cc(-c4ccccc4)ccc3n(-c3ccccc3)c12
Invalid SMILES: O=[PH](O)(O)=CCc1cc2c(cc1-c1ccccc1)c1cc(-c3ccccc3)ccc1n2-c1ccccc1

[12:52:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:31] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1ccc2c(c1)c1cc(-c3ccccc3)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc(-c3ccccc3)cc2c2ccc(-c3ccccc3)cc21
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-n2c3ccc(-c4ccccc4)cc3c3cc(-c4ccccc4)ccc32)cc1

[12:52:32] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: O=Cc1c(CCC=[PH](=O)(O)O)c(-c2ccccc2)cc2c3cc(-c4ccccc4)ccc3n(-c3ccccc3)c12

[12:52:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:32] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:52:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:32] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1cc(Cl)ccc1n2-c1ccccc1
Invalid SMILES: N#CC(=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1)C(=O)O
Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=P1(O)(O)=Cc2c(n(-c3ccccc3)c3ccccc23)C=C1

[12:52:33] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CBc1ccc2c(c1)c1ccccc1n2-c1ccccc1

[12:52:33] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(-n2c3ccccc3c3ccccc32)cc1

[12:52:34] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:52:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)c1ccc(N2C=CC3=CC4=C2C3=C2C=CC=C[PH]24(=O)O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccc(Cl)cc1

[12:52:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:34] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)PCC=C1

[12:52:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cc2c(N(c3ccccc3)c3ccccc3)cccc2[nH]1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:52:35] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:52:35] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1

[12:52:36] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:52:36] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:52:36] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:52:36] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: N#CPC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=CC=CC=C2)C2=CC=CC2)cc1)PC=[PH](=O)(O)O
Invalid SMILES: N#CPC1=CC=C(N(c2ccccc2)c2cccc(C=[PH](=O)(O)O)c2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1

[12:52:36] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1

[12:52:37] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CBc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:52:38] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:52:38] Explicit valence for atom # 4 P, 7, is greater than permitted

Invalid SMILES: N#CBC(C#P(=O)(O)O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#C/C(C#P(=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:52:38] Explicit valence for atom # 21 P, 7, is greater than permitted

Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)C=CC=C1)C1=CC(=[PH](=O)(O)O)C=C1

[12:52:39] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:52:39] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:52:39] Explicit valence for atom # 27 P, 7, is greater than permitted

Invalid SMILES: O=C(F)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=C=C2)c2ccccc2)cc1)C(=O)OCC=[PH](=O)(O)O

[12:52:40] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:52:40] Explicit valence for atom # 15 P, 7, is greater than permitted

Invalid SMILES: N#CC1=C=CC=C(N(C2=CC=C(C(=O)O)OC=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=C(O)C1=Cc2ccc(n(-c3ccc(C=[PH](=O)(O)O)cc3)ccccc2=O)C=C1

[12:52:40] Explicit valence for atom # 8 P, 7, is greater than permitted

Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1cccc[pH]c(C2=CC=C=C2)cc1

[12:52:41] Explicit valence for atom # 26 P, 7, is greater than permitted

Invalid SMILES: N#CPC(=Cc1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)C=[PH](=O)(O)O

[12:52:41] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C/C(=C\c1ccc(O)cc1)c1ccc(N(C2=CC=C=C2)c2ccccc2)cc1

[12:52:42] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:52:42] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:52:42] Explicit valence for atom # 4 P, 7, is greater than permitted

Invalid SMILES: N#CPN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(C2=CC=C2)cc1
Invalid SMILES: N#CC(=CPc1ccc(N(C2=CC=CC=CC=C2)c2ccccc2)cc1)OCC=[PH](=O)(O)O
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C\c1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:52:42] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:52:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:43] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: O=P(O)(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(O)cc2)cc1

[12:52:43] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:52:43] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: O=C(F)c1ccc(N(C2=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: N#Cc1ccc(=[PH](=O)(O)O)cc(N(C2=CC=C2)c2ccccc2)c1

[12:52:44] Explicit valence for atom # 25 P, 7, is greater than permitted

Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=C(C(=O)F)C=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cc1)C(=O)O

[12:52:44] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:52:44] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:52:44] Explicit valence for atom # 25 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(N(C2=CC=C(C(=O)O)C=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C(=O)F)C2=CC(=[PH](=O)(O)O)C=C2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C(C=C(O)O)/C=C\C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CO1

[12:52:44] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:52:45] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:52:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:45] Explicit valence for atom # 8 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CCPC1=CC=CC2=CC=CC=CC(=CC=C3C=CC=CC=CC=CP3)N21
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1

[12:52:45] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:52:45] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:52:45] Explicit valence for atom # 25 P, 7, is greater than permitted

Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O

[12:52:45] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: N#CPc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=Pc1ccccc2ccc(c1)-c1ccc(cc1)C=CC=CC=CN2c1ccc(C=[PH](=O)(O)O)cc1

[12:52:46] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:52:46] Explicit valence for atom # 18 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=CC2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1

[12:52:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:46] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:46] Explicit valence for atom # 4 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(C3=CC(F)=C3)cc2)[PH]2=CC=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(N(C2=CC=CSC=C2)c2ccc(O)cc2)c1
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:52:47] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:52:47] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(C2=CC=C2)cc1
Invalid SMILES: N#CPC(C#P(=O)(O)O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:52:47] Explicit valence for atom # 15 P, 7, is greater than permitted

Invalid SMILES: N#CCC(C=C(C#N)C#N)=Nc1cc(C=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1

[12:52:47] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:52:47] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:52:47] Explicit valence for atom # 9 P, 7, is greater than permitted

Invalid SMILES: N#[PH]c1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(F)c1ccc(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)cccco1
Invalid SMILES: N#CPN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1

[12:52:47] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:52:48] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:52:48] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:52:48] Explicit valence for atom # 20 P, 7, is greater than permitted

Invalid SMILES: N#[PH]N(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: Nc1cc(C=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=P(O)(O)Cc1ccc(N(c2ccccc2)c2ccc([PH](=O)(O)(O)O)cc2)cc1

[12:52:48] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:52:48] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:52:48] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)C1=CCC(=[PH](=O)(O)O)C=C1
Invalid SMILES: N#CN(C1=CC=C(C(=O)O)[IH]C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#Cc1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(C=C(CF)C(=O)O)cc2)cc1

[12:52:48] Explicit valence for atom # 20 P, 7, is greater than permitted

Invalid SMILES: O=C(F)C1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=CC2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1

[12:52:48] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:52:49] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:52:49] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:52:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:49] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:52:49] Explicit valence for atom # 18 P, 7, is greater than permitted

Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)OCC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: Nc1cc(PC=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(N(c2ccccc2)c2ccc(O)cc2)c1
Invalid SMILES: N#[PH]C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C2)c2cccc(C=[PH](=O)(O)O)c2)cccco1

[12:52:49] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:52:49] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: N#CPN(c1ccccc2cc(cc1)C=CC=CC=CP2)c1ccc(PC=[PH](=O)(O)O)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(PC=[PH](=O)(O)O)cc1

[12:52:49] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: O=C(F)c1ccc(N(C2=CC=C=C2)c2ccc(PC=[PH](=O)(O)O)cc2)ccc([PH](=O)O)oc1

[12:52:49] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:52:49] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:52:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:50] Explicit valence for atom # 16 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(O)cc2)cc1
Invalid SMILES: N#CBC(=Cc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=C/C(=C\c1ccc(O)cc1)c1ccc(N(PC2=CC=C2)c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)C2=CC(=[PH](=O)(O)O)C=C2)C=CO1

[12:52:50] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:52:50] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:52:50] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: N#CBN(C1=CC=C(c2cccs2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#Cc1cc(C=[PH](=O)(O)O)cc(N(c2ccccc2)c2ccccc2)c1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH](=O)O)C=CC=C1

[12:52:50] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:52:50] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:52:50] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:52:50] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=C(F)C1=CC=C(N(c2ccc(PC=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)C=CC=C1
Invalid SMILES: O=C(F)C1=CC(c2ccccc2)=CC=C(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)C=C[IH]1
Invalid SMILES: N#C/C(=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1)PC=[PH](=O)(O)O
Invalid SMILES: O=C(O)C1=CC(C2=CC=C2)=CC=C(N(C2=C=C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=C1

[12:52:50] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Br)cc1N(c1ccccc1)c1ccccc1

[12:52:51] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:52:51] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:52:51] Explicit valence for atom # 4 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC=C(N(c2ccc(C=[PH](=O)(O)O)cc2)c2ccc([PH](=O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N2C3=CC=C(C=CO3)/C=C(/C=[PH](=O)(O)O)PC=C=CC=Cc3ccc2cc3)C=CC=C1
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C/c1ccc(N(C2=CC=CC2)c2ccccc2)cc1

[12:52:51] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:52:51] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:52:51] Explicit valence for atom # 20 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)c1ccc(N(C2=CC=C(C3=CC=C3)C=CC=C2)C2=CC(=[PH](=O)(O)O)C=C2)cc1
Invalid SMILES: N#CPC1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1

[12:52:51] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:52:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:51] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:52:52] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:52:52] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: N#CC1=CC=C(C=[PH](=O)(O)O)C=CC(N(C2=CC=CC2)c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(COC(=O)c1ccc(N(c2ccccc2)N(c2ccccc2)c2ccccc2)cc1)OCC=[PH](=O)(O)O
Invalid SMILES: O=P(O)(O)c1ccc(N(C2=CC=NC2=[PH](=O)(O)O)c2ccc(O)cc2)cc1
Invalid SMILES: N#CP/C(C=[PH](=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:52:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:52:52] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-n2c3ccccc3c3ccccc32)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)cc2)cc1

[12:52:54] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccccc2)cc1

[12:52:55] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)c1ccc(-c2cccc(O)c2)cc1

[12:52:57] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:52:57] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=Pc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC(c3ccc(C4=CC=C4)cc3)=C2)c2ccc(O)cc2)=C1

[12:52:57] Explicit valence for atom # 22 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)cc1

[12:52:58] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccccc1

[12:53:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:01] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC=C(N(C2=CC=CC(c3ccc(O)cc3)C=C2)C2=CC=C(c3ccccc3)OC=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1

[12:53:01] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC=C3)cc2)=CC1

[12:53:02] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=C=C1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1

[12:53:02] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1

[12:53:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC=CC3)cc2)=C1

[12:53:07] Explicit valence for atom # 31 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C2)C2=CC(c3ccc(-c4ccccc4)cc3)=CC=C(C=[PH](=O)(O)O)C=C2)cccco1

[12:53:07] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)=C1

[12:53:08] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(N(C2=CC=C(c3ccccc3)OC=C2)c2ccc(C3=CC=C3)cc2)cc1

[12:53:10] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1

[12:53:12] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(N(C2=CCC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccccc3)cc2)cccco1

[12:53:12] Explicit valence for atom # 8 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(C(C=[PH](=O)(O)O)=C2C=CC(N(c3ccccc3)c3ccccc3)=CO2)cc1

[12:53:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:13] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CBc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1

[12:53:15] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccccc1

[12:53:16] Explicit valence for atom # 28 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(C(=Cc2ccc(N(c3ccccc3)c3ccccc3)cc2)C=[PH](=O)(O)O)cc1

[12:53:16] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=C(O)C=[PH](=O)(O)O)C=C2)c2ccc(C3=CC=C3)cc2)C=CC=C1

[12:53:16] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1

[12:53:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:18] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)C=CO1

[12:53:19] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(C2=CC=CC2)cc1

[12:53:19] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:53:19] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(PC=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C(c3ccccc3)OC=C2)c2ccc(C3=CC=C3)cc2)=C1

[12:53:19] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=CC(O)C=C1

[12:53:20] Explicit valence for atom # 24 P, 7, is greater than permitted

Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1)C(F)(F)F

[12:53:22] Explicit valence for atom # 22 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1

[12:53:24] Explicit valence for atom # 24 P, 7, is greater than permitted

Invalid SMILES: N#CC(=Pc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1)C(=O)O

[12:53:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)c1cccc(O)c1

[12:53:25] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:53:25] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: N#CC(=CC(O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)=C1)C(=O)O
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(C(=O)O)cc3)cc2)C=CO1

[12:53:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=C=CC=C2)C2=CC=C(c3ccccc3)OC=C2)=C1

[12:53:26] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(O)cc1)c1ccc(N(C2=CC=C2)C2=CC=CC(c3ccccc3)C=C2)cc1

[12:53:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:27] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CPC1=CC=C(N(C2=CC=CC=CC=C2)c2ccccc2)OC=C1)c1ccc(C2=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(O)cc1)c1ccc(N(C2=CC=C2)c2ccc(C3=CC=C3)cc2)cc1

[12:53:27] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(N(c2ccc(C=[PH](=O)(O)O)cc2)c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)cccco1

[12:53:28] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:53:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=CC=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)C=CO1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(N(C2=CC=C2)c2ccc(N(c3ccccc3)c3ccccc3)cc2)=C1

[12:53:29] Explicit valence for atom # 22 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(=[PH](=O)(O)O)ccc3C3=CC=C3)cc2)cc1

[12:53:31] Explicit valence for atom # 25 P, 7, is greater than permitted

Invalid SMILES: N#CC(=CC1=CC=C(c2ccc(N(c3ccccc3)c3ccc(PC=[PH](=O)(O)O)cc3)cc2)C1)C(=O)C=O

[12:53:31] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:53:31] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:53:31] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC=C(N(c2ccc(C3=CC=CC(C4=CC=C=C4)C=C3)cc2)c2cccc(=[PH](=O)(O)O)cc2)C=CO1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(N(C3=CC(=C(O)C=[PH](=O)(O)O)C=C3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=CC(C2=CC=C=C2)C=C1

[12:53:33] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(CC=[PH](=O)(O)O)cc3)cc2)cc1

[12:53:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC(c2ccccc2)C=C1

[12:53:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(C2=CC=C=C2)cc1

[12:53:35] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(N(C2=CCC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccccc3)cc2)cc1

[12:53:36] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: O=C(O)CCn1cc(-c2ccc(C=[PH](=O)(O)O)cc3c4cccn4c4ccc(cc4)c=3c2)ccc1=O

[12:53:38] Explicit valence for atom # 24 P, 7, is greater than permitted

Invalid SMILES: O=C1c2ccc3c4c(ccc1c24)C(=O)N(Cc1ccc(O)cc1)C(=[PH](=O)(O)O)C(=O)N(Cc1ccncc1)C3=O

[12:53:39] Explicit valence for atom # 36 P, 7, is greater than permitted

Invalid SMILES: O=Cn1c(=O)c2ccc3c(=O)n(Cc4ccccc4)c(=O)n(Cc4ccncc4)c(=O)c4c(C=CC=[PH](=O)(O)O)cc(c1=O)c2c34

[12:53:39] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:53:39] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:53:39] Explicit valence for atom # 27 P, 7, is greater than permitted

Invalid SMILES: O=c1c2ccc3c(=O)n(-c4ccc(O)cc4)c2c3ccn1-c1ccc(C(=CC=[PH](=O)(O)O)C2=CC=C2)cc1
Invalid SMILES: O=c1c2ccc3c(=O)n(-c4ccc(O)cc4)c(=O)c-3c3ccc(c(=O)n1CC=[PH](=O)(O)O)c2cc3P
Invalid SMILES: O=c1c2ccc3c(=O)n(-c4cccc(O)c4)c(=O)c4ccc(c(=O)n1CC=[PH](=O)(O)O)c3c24

[12:53:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:40] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(C(F)(F)F)cn1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CN=C1

[12:53:40] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:53:40] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:53:40] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:53:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:40] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#Cc1cccc(=[PH](=O)(O)O)cc1
Invalid SMILES: O=Cc1cncc(C=CC=[PH](=O)(O)O)c1O
Invalid SMILES: N#Cc1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)(CCCCn1ccnc1)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=c1cccc(C(F)(F)F)cc1C(F)(F)F

[12:53:40] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:53:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:40] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C1CC=CC(=[PH](=O)(O)O)C=CC(C(F)(F)F)=CO1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(S)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(CCO)CCO)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(CCO)CCCCO)cc1
Invalid SMILES: O=[PH](O)(O)(c1nccn1Cc1c[nH]cn1)C(F)(F)F

[12:53:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:41] Explicit valence for atom # 15 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2cccs2)S1
Invalid SMILES: N#CC(C#N)=Cc1ccc(-c2ccc(C=[PH](=O)(O)O)s2)s1

[12:53:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:41] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:53:41] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(S)cc1
Invalid SMILES: O=c1ccc(C=[PH](=O)(O)O)c(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=c1cccc(-c2cccs2)s1

[12:53:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:41] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:53:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:41] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc(-c2cccs2)cc1
Invalid SMILES: N#CC1=CC=C(C=[PH](=O)(O)O)c2ccccc2S1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(-c3ccccc3)cc2)c[nH]1
Invalid SMILES: O=[PH](O)(O)=Cc1ccccc1-c1cccs1

[12:53:42] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:53:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:42] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(PC=[PH](=O)(O)O)s2)s1
Invalid SMILES: O=[PH](O)(O)=CPc1sc(-c2cccs2)cc1O
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)N=C(c2ccccc2)S1

[12:53:42] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:53:42] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:53:42] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(Cl)c1cc(-c2ccc(C3=CC=C3)cc2)sc(=[PH](=O)(O)O)c1Cl
Invalid SMILES: Nc1cc(-c2cccs2)sc1C=CC=[PH](=O)(O)O
Invalid SMILES: O=Cc1ccc(-c2ccc(C=[PH](=O)(O)O)s2)s1

[12:53:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:43] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)sc1c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=c1ccc2c3ccc(c2s1)Sc1ccccc1-3
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)sc1c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2sc3c4ccccc4sc3c2c1

[12:53:44] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)sc1c3ccc(Cl)cc3sc21

[12:53:44] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:53:45] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc3[nH]c4ccc(-c5ccc([PH](=O)(=O)O)cc5)cc4c3c2)cc1
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc(-c3ccccc3)cc2c2cc(-c3ccccc3)ccc21

[12:53:45] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCCCn1c2ccc(-c3ccccc3)cc2c2cc(-c3ccccc3)ccc21

[12:53:46] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1

[12:53:50] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1

[12:53:52] Explicit valence for atom # 47 P, 7, is greater than permitted

Invalid SMILES: CC(=CC(C1=CC=C=C(C2=CC=C=CC=C2)C=C1)=C1C=CC(c2ccc(N(C3=CC=CCC3)c3ccc(C4=CC=C4)cc3)cc2)=C1)C=[PH](=O)(O)O

[12:53:52] Explicit valence for atom # 4 P, 7, is greater than permitted

Invalid SMILES: C=CC(C=[PH](=O)(O)O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(-c4ccc(N(C5=CC=C=C=C5)C5=CC=CC=CC5)cc4)cc3)cc2)=C1

[12:53:54] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1

[12:53:56] Explicit valence for atom # 48 P, 7, is greater than permitted

Invalid SMILES: CC(=CC1=CC1=CC=c1ccc(=CC=C2C=CC2=CC=CC=C2CC2=CC=C2C=CC(=O)N2C2=CCC=C2)n1C=C=CC1=C=CCS1)C=[PH](=O)(O)O

[12:53:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:53:59] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC2=CC=c2ccc3n2N2C(=CC=C=CC=CC1)CC=CC=C2CCC=CC=C1C=CC1=CC=3
Invalid SMILES: O=C(O)C1=COC(=CC(=CC=[PH](=O)(O)O)C2=CC(C3=CC=CCC=C3)C=CC=C(c3ccc4n5c(ccccccc35)C4)C=C2)C=C1

[12:54:02] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1

[12:54:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC2=CC=c2ccc3n2N(C=C=CC=c2ccoc2=CC=C2C=CC2=CC=3)CC=CC=CC=CC=C1

[12:54:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3n2C(=CC=C2CC=CC(N(C4=CC=C4)C4=CC=CC4)=CC=C2C=CC1)C=CC=CC=3

[12:54:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:54:09] Explicit valence for atom # 46 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC2=CC3=CC=CCC=CC=C4C=CC(C=C5C=CC5=CC=C21)N43)C1C=CC=C1)N(C1=C=C=CC=C1)C1=CC=CC1
Invalid SMILES: CC=C1C=C=CC=CC=C2CC=CC=C3C=CC=CC=C4C=CC(C=CC=C5C=CC5=CC=c5ccc(n52)=CC=C2C=C2C=C(C=[PH](=O)(O)O)C=C1)N34

[12:54:14] Explicit valence for atom # 48 P, 7, is greater than permitted

Invalid SMILES: C=CC(=Cc1c(=CC=C2C=C=C=C2)cccccc2n3c(ccc3ccc3cccccc4ccc(ccc5ccc15)n34)=CCC=C2)C=[PH](=O)(O)O

[12:54:19] Explicit valence for atom # 47 P, 7, is greater than permitted

Invalid SMILES: CC(=CC1=CC1=CC=c1ccc2n1C=C=CC=CCC=C=c1ccc(n1-c1ccccc1)=CC=C1C=CC1=CC=C1C=CC1=CC=2)C=[PH](=O)(O)O

[12:54:21] Explicit valence for atom # 49 P, 7, is greater than permitted

Invalid SMILES: CC(=CC(C1=CC=C(c2ccc(N(C3=C=CCC=C=C3)C3CC=C=C=CC3)cc2)C1)=C1C=CC=C(c2cccc(C3=CC=CC3)c2)C=C1)C=[PH](=O)(O)O

[12:54:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc-2ccc2ccc3n2c(ccc2ccc(cccccc4ccc1C=C=C4)n2C1=CC=C1)C=CCC=C1C=CC1=CC=3

[12:54:30] Explicit valence for atom # 48 P, 7, is greater than permitted

Invalid SMILES: CCC(=CC(C1=CC2C=C=CC=CC=CN(C3=C=CCC=C3)c3ccc(cc3)-c3ccc(cc3)C(=C2)C=C1)=C1C=CC(C(=O)O)=CO1)C=[PH](=O)(O)O

[12:54:32] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC(=C2C=CC(N(C3=CC=C(c4ccccc4)C=CC=C3)c3ccc(N(C4=CCC=C4)c4ccccc4)cc3)=C2)C=CC=C=C=C1

[12:54:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=CC1=C(O)C1=CC=c1ccc2ccc3ccc3ccc3ccc3ccc3ccc(cccccccccn12)n3C1=CCC=CC1

[12:54:35] Explicit valence for atom # 37 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccc(C=[PH](=O)(O)O)cc5)cc4)cc3)cc2)cc1

[12:54:35] Explicit valence for atom # 47 P, 7, is greater than permitted

Invalid SMILES: C=CC=C=CC(=CC1=CC1=Cc1cccc2ccc3c(ccc4c(ccc(N(C5=CC=C=C5)C5=CC=C5)ccccn12)CO4)C=C3)C=[PH](=O)(O)O

[12:54:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1C=C=CC=CN(C2=CC=C=CCC=C2)c2ccc(cc2)-c2ccc(cc2)N(c2ccccc2)c2ccc(cc2)C2=CCOC(=C1)C=C2

[12:54:36] Explicit valence for atom # 47 P, 7, is greater than permitted

Invalid SMILES: CC(=CC1=C2C=CC(=C2)c2ccc(cc2)N(C2=CC=C2)c2ccc(cc2)N(C2=CC=CCC2)C2=C(C=C=C2)CC=CC=CC=C=C1)C=[PH](=O)(O)O

[12:54:37] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2)cc1

[12:54:41] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=CCC=C=C3)c3ccc(-c4ccc(-c5ccc(C6=CC=C6)cc5)cc4)cc3)cc2)=C1

[12:54:43] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CC(c2ccc(C3=CC=CCC3)cc2)C=CC1)=C1C=CC(c2ccccc2)=C1)c1ccccc1

[12:54:43] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2)cc1

[12:54:47] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:54:47] Explicit valence for atom # 32 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)C(=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1)CC(=O)O
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1

[12:54:49] Explicit valence for atom # 38 P, 7, is greater than permitted

Invalid SMILES: N#CC(C=O)C(=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1)CCC=O

[12:54:55] Explicit valence for atom # 41 P, 7, is greater than permitted

Invalid SMILES: N#CC(C(=O)C=O)C(C=O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1

[12:54:56] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C4=CC=C(c5ccccc5)C=CC3=CC=C(c3ccccc3)C=C4)cc2)cc1

[12:54:56] Explicit valence for atom # 41 P, 7, is greater than permitted
[12:54:56] Explicit valence for atom # 37 P, 7, is greater than permitted

Invalid SMILES: N#CC(C=O)=CC(C=O)=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)c2)cc1
Invalid SMILES: N#CC(C#N)C(=CC1=CC=C(c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)C1)C(=O)C=O

[12:55:01] Explicit valence for atom # 40 P, 7, is greater than permitted

Invalid SMILES: O=CCC(C=O)=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=CC=[PH](=O)(O)O)cc4)cc3)c2)cc1

[12:55:03] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccc(N(C3=CC=CC(c4ccc(C5=CC=C5)cc4)C=C3)c3ccccc3)cc2)S1

[12:55:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=C=C3)c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=CC1

[12:55:05] Explicit valence for atom # 34 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccc(C=O)cc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4C=O)cc3)cc2)cc1

[12:55:06] Explicit valence for atom # 34 P, 7, is greater than permitted

Invalid SMILES: N#CC(=CC1=CC=C(c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)C1)C(=O)C=O

[12:55:10] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2O)cc1

[12:55:15] Explicit valence for atom # 35 P, 7, is greater than permitted

Invalid SMILES: O=CCOc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1

[12:55:20] Explicit valence for atom # 33 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)c2)cc1

[12:55:21] Explicit valence for atom # 36 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccccc2)cc1N(c1ccc(-c2ccccc2)cc1)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1

[12:55:24] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3cccc(-c4ccc(F)cc4)c3)cc2)cc1

[12:55:26] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:55:26] Explicit valence for atom # 34 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(C2=CC=C3C=CC(c4ccccc4)=CC=C(C=C2)N3c2ccc(-c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1

[12:55:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC=NN(c2ccccc2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccccc2C(F)(F)c2ccc(F)cc21

[12:55:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Cc2cc(Br)ccc21

[12:55:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(N2c3ccccc3Cc3ccccc32)C=C(Br)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C3=CC2=C(Br)C=C3)cc1

[12:55:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(O)c2c1ccc1cccnc12
Invalid SMILES: O=[PH](O)(O)=Cc1ccnc2cc(Cl)ccc12

[12:55:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:29] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:55:29] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 44 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 40 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1cc2c3ccccc3sc2c2c1[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2c3sc4ccccc4c3ccc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc3c(cc21)sc1ccccc13
Invalid SMILES: O=C=CC1C=C2C(=C1c1c3cc(n1CC[PH](=O)(O)(O)O)-c1c-3n(CCCP(=O)(O)O)c3ccccc13)N2CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3ccc-3c(N3C=CCC=C3)c3cc4n(CCC[PH](=O)(O)(O)O)c3c-4c21
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C13CC=C=CC(C(NCCP(=O)(O)O)=C1c1[nH]c4ccccc4c1-2)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=C1c2c(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c2[nH]c2ccccc23)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=c1c2ccc(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c4ccc4n(CCCP(=O)(O)O)c23)n1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1C(NCC[PH](=O)(O)(O)O)=C1c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CC[PH](=O)(O)(O)O)C3=CC3)c3cc4n(CCCI(=O)(O)O)c3c-4c21

[12:55:30] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 38 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 33 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1C=CC(=C3C=CC=C4C2=C3N4CCC[PH](=O)(O)(O)O)N(C2=C=C2)C1
Invalid SMILES: NC1=C2C(NCC[PH](=O)(O)(O)O)=C2c2[nH]c3ccccc3c2-c2c1c1ccccc1n2CCCP(=O)(O)O
Invalid SMILES: Cn1c2ccccc2c2c1c1c3ccccc3n(C=O)c1c1c3ccccc3n(P(=O)(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(C(=C3CC=N3)N1CCC[PH](=O)(O)(O)O)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CCC3=C1C(NCC[PH](=O)(O)(O)O)=C3c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C1C=CC=CC(=N3)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C=CC=C1C(=C3CN3CCC[PH](=O)(O)(O)O)n3c1c-2c1ccccc13
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c4c(c5c(n4CCC[PH](=O)(O)(O)O)C=C5)c4c(c5ccccc5n4CCCP(=O)(O)O)c31)CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CCc3c-2c2c(n3CCC[PH](=O)(O)(O)O)C=CC(C=C2)C1=C1CN1CCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=C3C=NC(S3)C2=C(C2=CCC=C2)N1CCC[PH](=O)(O)(O)O

[12:55:30] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 38 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 41 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(c21)C(=C1C=CC=C1)N4CCC[PH](=O)(O)(O)O)C1C=C=C1C1(O)C=CC1=N3
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1c3nc(C4C=CC=C4)c-2c(c3=CC2=CC=C2)n1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(c3[nH]c4ccccc4c3-2)C2(C=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CC[PH](=O)(O)(O)O)C=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc2c(c1)[nH]c1c3ccccc3c3c4ccccc([nH]c23)c41
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(C3=CC(=N1)N3CCC[PH](=O)(O)(O)O)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c3c4c(c(c5c(c1=3)=C5NCC[PH](=O)(O)(O)O)NCC=CC=CC=2)c1ccccc1n4CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CCC[PH](=O)(O)(O)O)C=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c1c1c3ccccc3n(CC[PH](=O)(O)(O)O)c1c1c3ccccc3n(CCCP(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(ccn4CCC[PH](=O)(O)(O)O)c21)C1=CC=C(C=CC1)N3C1CCCC1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CC[PH](=O)(O)(O)O)CC=C4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCC=C1NC1=C1c2c(n(CCCP(=O)(O)O)c3ccccc23)C2=C(C=C2C2CCCC=N2)N1CCC[PH](=O)(O)(O)O

[12:55:30] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 40 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 44 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 27 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ncccc2c2cccc3c(NCC[PH](=O)(O)(O)O)c-3c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCN1C2=CC=Cc3c1c2c1c(c3N(CC[PH](=O)(O)(O)O)C2C=CC=C2)c2ccccc2n1CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CCP(=O)(O)O)C3=CCC=C3)c3c4c(c21)C(=CC=C3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(ccn3CCC[PH](=O)(O)(O)O)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CCC[PH](=O)(O)(O)O)CC=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccc3cc2c2cc(C4C=CC=C4)c(cc21)n(CC[PH](=O)(O)(O)O)c1ccc3=1
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C(=C1C=CC1)N(CCC[PH](=O)(O)(O)O)C1=C(C=CCC=C1)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c4c5c(n(CCC[PH](=O)(O)(O)O)c4c3n(CCCP(=O)(O)O)c2c2ccccc21)C5
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ncccc5c4c21)C(=C1C=N1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCC=NC1=c2cc3n(CCC[PH](=O)(O)(O)O)c2=C3c2c(c3ccccc3n2CCCP(=O)(O)O)-c2ncccc21
Invalid SMILES: O=c1c2c3[nH]c4ccccc4c3c3c(c4ccccc4n3CCCP(=O)(O)O)c2[nH]c2ccc-2n1CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCN1C(=C2CN2CCC[PH](=O)(O)(O)O)c2c1c1c(c3c4ccccc4n(CCCP(=O)(O)O)c23)N=CCC=C1
Invalid SMILES: O=P(O)(O)CCCN1C2=CC=CC3C(=C4C(=C41)c1c2c2ccccc2n1CCCP(=O)(O)O)C1=NC(CCCC1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCN1C(=C2C=CCC=C2)C1=C1C=CCC=Cc2c3c1n(CCC[PH](=O)(O)(O)O)c2-c1c-3n(CCCP(=O)(O)O)c2ccccc12
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)[PH](=O)(O)(O)CC=CN3

[12:55:30] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:55:30] Explicit valence for atom # 15 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)[PH](=O)(O)(O)CCN3
Invalid SMILES: O=C1c2c(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c2[nH]c2ccccc23)N1CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(c3ccccc3N(CCCC[PH](=O)(O)(O)O)SN1)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCN1C(=C2C=CC=C2)c2c1c1c3ccccc3n(CC[PH](=O)(O)(O)O)c1c1c3ccccc3n(CCCP(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3ncc(c4[nH]c5ccccc5c4c21)c1c3n1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c1c1c3ccc4c(ccn4CC4=CCC=C4)c1n(CCC[PH](=O)(O)(O)O)c32
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC(C3=C4C=C=CC3N4CC[PH](=O)(O)(O)O)=C(CN1)c1ccccc1-2
Invalid SMILES: O=P(O)(O)CCCN1c2c(c3c(c4ccccc4n3CCC[PH](=O)(O)(O)O)c3c2c2ccccc2n3CCCP(=O)(O)O)C12C=CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=Cc1c-2c(C2=CC=CC3N=CC23)n2c1P(=O)(O)(O)(O)CCC2
Invalid SMILES: O=P(O)(O)CCCNC1=C2C1=C(NCC[PH](=O)(O)(O)O)c1c(n(CCCP(=O)(O)O)c3ccccc13)-c1c2[nH]c2ccccc12

[12:55:30] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 43 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 37 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCCCn1c2ccc3c2c2c(ccn2CCC[PH](=O)(O)(O)O)c2c(c4ccccc4n2CCCP(=O)(O)O)c31
Invalid SMILES: O=P(O)(O)CCCn1c2cccc3c(C=C4C=CC5C(=C4)N5CC[PH](=O)(O)(O)O)c(c1-3)-c1c-2c2ccccc2n1CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CCC[PH]3=CC=C3)C3=CCC=C=C3)c3c4c(c21)C(=CC=CC3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3[nH]c4c(n(CCC[PH](=O)(O)(O)O)c5ccccc5c3c3[nH]c5ccccc5c3c21)=CC=4
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=CC1C=N1)N3CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1NC3=C(CC=CC3)C2=C(C2=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=[PH](O)CCNC1=C2C(NCC[PH](=O)(O)(O)O)=C2c2[nH]c3ccccc3c2-c2c1c1ccccc1n2CCCP(=O)(O)O
Invalid SMILES: Nc1c2c(NCCC[PH](=O)(O)(O)O)c3c-2n2c(cccc4c5ccccc5n(CCCP(=O)(O)O)c4c1-3)CCCCC2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=CC1C=N1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1cc(c1NCC[PH](=O)(O)(O)O)-c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c1c1c4ccccc4n(CCC[PH](=O)(O)(O)O)c1c1c4ccccc4n(CCCP(=O)(O)O)c31)C=C2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)CN3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c4c(ccn4CCC[PH](=O)(O)(O)O)c4c(c5ccccc5n4CCCP(=O)(O)O)c31)CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1c3c-2c(n1CCC[PH](=O)(O)(O)O)C(=C1N=C1C1C=CC=CC1)C=CC=C3
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=C1CC=NS1)N3CCC[PH](=O)(O)(O)O

[12:55:31] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 40 P, 7, is greater than permitted
[12:55:31] Explicit valence for atom # 39 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C(N(CCO)C1=CC1)=C1C(NCC[PH](=O)(O)(O)O)=C1c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2cc3c1=C2c1c(c2ccccc2n1CCCP(=O)(O)O)C=C=C1CN(CC[PH](=O)(O)(O)O)C=31
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1NC1=C1C2=C(C2=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccc2c2c1c1c(NCC[PH](=O)(O)(O)O)c-1cc1c3ccccc3n(CCCP(=O)(O)O)c12
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c4c5c(c6c(c(c(c21)C=CP(O)CC5)n3CCC[PH](=O)(O)(O)O)=CCC=6)N4
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1C=NC3C=CC=C4NC4=C4C2=C(C1=CC=C3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(c21)=C4N(CCP(=O)(O)O)C1=CC=C1)C=C=CC1C=3N1CC[PH](=O)(O)(O)O
Invalid SMILES: Nc1c2cccc3n(CCCP(=O)(O)O)c-2c-3c2c(c3ccccc3n2CCCP(=O)(O)O)c2c1c1c(n2C[PH](=O)(O)(O)O)C1

[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)C=C1
Invalid SMILES: N#CC1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(c2ccccc2)=CS1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)S1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=C(C(=O)O)C=C1

[12:55:34] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(C2=CC(=CC=[PH](=O)(O)O)C=C2)cc1
Invalid SMILES: N#CC1=CC=CC(c2ccc(C=[PH](=O)(O)O)cc2)=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2=CC=C(c3ccccc3)C=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CC(c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C2=CC=C=CC=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=c1ccc(C(F)(F)F)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(C2=CC=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: N#CC1=CC=C(C2=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(C#CC=[PH](=O)(O)O)cc2)cc1)C(=O)O
Invalid SMILES: O=P1(O)(O)=CC=C(c2ccc(-c3ccccc3)cc2)C=C1

[12:55:34] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#CC1=CC=C(C2=CC=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc([IH]C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#Cc1ccc(=[PH](=O)(O)O)cc(-c2ccccc2)c1
Invalid SMILES: N#Cc1ccc(-c2ccc(=[PH](=O)(O)O)cc(C(=O)O)c2)cc1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C2=CC=C(C(F)(F)F)C=CC=C2)C=C1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=C=C1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)C1C=CCC(=C1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)n1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13

[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 25 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=CC1
Invalid SMILES: O=P(O)(O)CCCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=CC1
Invalid SMILES: O=C(CCCn1c2ccccc2c2cc3c(cc21)Nc1ccccc1N3CCCCCO)OCCC=[PH](=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)C1C=CC(=C1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)On1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCCC[PH](=O)(O)(O)O
Invalid SMILES: N#CC(O)=Cn1c2ccccc2c2cc3c(cc21)c1ccccc1n3P(=O)(=O)(O)O

[12:55:34] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)-c1cccc(c1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=[PH](O)(O)=CC=CCc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=[PH](O)(O)=CCc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccc3c4ccccc4[nH]c3c21
Invalid SMILES: O=[PH](O)(O)=CCn1c2c(c3ccccc31)C=Cc1ccccc1N2
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccccc2c2c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)[nH]c1c3ccccc3[nH]c21
Invalid SMILES: O=P(=O)(O)(O)Oc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc2c(c1)[nH]c1c3ccccc3[nH]c21

[12:55:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:35] Explicit valence for atom # 26 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCCCCCO
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c4ccccc4n(CC[PH](=O)(O)(O)O)c3cc21

[12:55:36] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc4n(C5=CC=CC5)cccc3-4)cc2)cc1

[12:55:36] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21

[12:55:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:37] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(-c2ccc(N(C3=CC=C(c4ccccc4)PC=C3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1

[12:55:37] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1

[12:55:38] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(N4C=CC=CC4)cc3)cc2)cc1

[12:55:38] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC=C1)c1ccc(N(C2=CC=C2)c2ccc(-c3ccccc3)cc2)cc1)c1ccccc1

[12:55:38] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#CC(CO)=C1C=CC(c2ccc(N(C3=CC=C(C4=CC=C(c5ccccc5)CC=C4)CC=C3)c3ccccc3)cc2)=C1

[12:55:39] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1

[12:55:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:39] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccccc2)cc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccc4cc3-c3ccccc3N4)cc2)c2c1=CC=2

[12:55:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:40] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=C[IH]c1ccc(-c2ccc(-c3cccc(C4=CC=C=C4)c3)cc2)cc1)N1C=CC=C(O)C1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=CC1)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(N4C=CC=CC4)cc3)cc2)cc1

[12:55:40] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2c1[nH]c1ccccc12

[12:55:41] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1c2ccccc3n4c(ccc4ccc4ccc-4ccc12)=CC=CCC=CC=3)NC1=CC=CC1

[12:55:41] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)cc1)c1ccccc1

[12:55:42] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#CC1C=C2C(=CC=C3C=CC3=CC=CC=CC=NSN1)N(C1=CC=C1)c1ccc(cc1)-c1ccc2cc1

[12:55:43] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1

[12:55:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:44] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCPCOC(=CC=C1C=CC(N(c2ccccc2)c2ccc3cccccc2-3)=C1)c1ccc(N=C2CC=CC2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPC1=CC=C(c2ccc(N(C3=CC=C3)C3=CC=C3)cc2)OCC=C1)c1ccc(N(C2=CC=C=C=C2)c2ccccc2)cc1

[12:55:45] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4cc3-c3ccccc3N4)cc2)cc1

[12:55:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:45] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)c2c1C=C2
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21

[12:55:46] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(-c2ccc(N(C3=CC=C=C(C4=C=CC=C4)C=C3)C3=CC=CC3)cc2)cc1)C1=CC=C=C1

[12:55:47] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC2=CC=C(C=C1)N1C=CCC=CC=CC=C21

[12:55:47] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(N(C4=CC=C4)C4=CC=CCC=C4)cc3)cc2)cc1

[12:55:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:48] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc2ccc2ccccc3cccccc(ccc4ccc4cccccc1=CC1=CC=CC=CC1)n32
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)c2ccccc12

[12:55:49] Explicit valence for atom # 40 P, 7, is greater than permitted

Invalid SMILES: O=C(CCCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21)OCC#P(=O)(O)O

[12:55:52] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3cc(Cl)ccc3Sc3ccc(Cl)cc32)cc1

[12:55:53] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3ccccc3Sc3ccccc32)cc1

[12:55:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:54] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1Sc2ccccc2N(c2ccccc2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2c3ccccc3Sc3ccccc32)=C1

[12:55:55] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)Sc1ccccc1N2c1ccccc1

[12:55:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:55:58] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc2c(c1)Sc1ccccc1N2c1ccc(Br)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)N(c1ccccc1)c1ccccc1S2

[12:55:58] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CSc1ccc2c(c1)N(c1ccccc1)c1ccccc1S2

[12:56:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)Sc1ccccc1N2c1ccc(F)cc1

[12:56:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)Sc1cc(Cl)ccc1N2c1ccccc1

[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:01] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C(Cl)=C(Cl)C(Cl)=C1Cl
Invalid SMILES: O=[PH]1(O)(O)SC(C(F)(F)F)=C1Cl
Invalid SMILES: O=P(=O)(O)(O)c1ccc(C(F)(F)F)cc1
Invalid SMILES: O=[PH](O)(O)=C1SC(Cl)=C1Cl
Invalid SMILES: N#Cc1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=C1SC(C(F)(F)F)=C1F
Invalid SMILES: O=[PH](O)(O)=C1SC(F)(F)C(F)(F)C1(F)F
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C(F)(F)F)=C1
Invalid SMILES: O=[PH](O)(O)=C1C(F)C(F)(F)C1(F)F
Invalid SMILES: O=[PH](O)(O)=C1C(F)C(F)(F)C(F)(F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)CCN1C=CC=CC1
Invalid SMILES: O=P(=O)(O)(O)c1ccncc1
Invalid SMILES: O=P(=O)(O)(O)CCNc1ncc[nH]1
Invalid SMILES: O=C(O)[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)F)NC(F)(F)C(F)(F)C(F)(F)C(F)(F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)c1cc[nH]c1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(F)C(F)(F)C(F)(F)C(F)(F)F)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(Cl)C(Cl)=C1Cl
Invalid SMILES: O=P(=O)(O)(O)c1ccc(Cl)cc1
Invalid SMILES: O=P(=O)(O)(O)Cn1ccnc1
Invalid SMILES: O=C(O)Nc1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=[N+]([O-])c1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(N(F)CC(F)(F)F)C=C1
Invalid SMILES: Cn1cncc1P(=O)(=O)(O)O
Invalid SMILES: O=[PH](=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1cn(C(F)(F)F)cn1
Invalid SMILES: O=P(=O)(O)(O)c1ncc[nH]1
Invalid SMILES: O=P(=O)(O)(O)c1c[nH]cn1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(Nc2ncc[nH]2)cc1
Invalid SMILES: O=P(=O)(O)(O)CCN(CCO)Cc1nccn1C(F)(F)F
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccncc1
Invalid SMILES: O=[PH](O)(O)=C1C=CN=C1
Invalid SMILES: O=P(=O)(O)(O)CCN1CC=CC1
Invalid SMILES: O=P(=O)(O)(O)CCn1ccnc1
Invalid SMILES: N#CN(F)C1=C(P(=O)(=O)(O)O)C=C1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C=C/C=C/C(F)(F)F)N1
Invalid SMILES: O=P(=O)(O)(O)CNc1ncc[nH]1
Invalid SMILES: O=P(=O)(O)(O)NCCNc1ncc[nH]1
Invalid SMILES: O=P(=O)(O)(O)c1ccccc1
Invalid SMILES: O=C(O)NC1=C(CP(=O)(=O)(O)O)C=C1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1nccn1C(F)(F)F
Invalid SMILES: N#Cc1ccc([PH](=O)(O)(O)O)cc1
Invalid SMILES: O=CN(F)c1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)F)NC(F)(F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)c1cn(C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)C(F)(F)C(F)(F)F)cn1
Invalid SMILES: N#Cc1ccc(CP(=O)(=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccncc1
Invalid SMILES: O=P(=O)(O)(O)c1cc[nH]c1C(F)(F)F
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)F)N=C1
Invalid SMILES: O=[PH](O)(O)(O)CCN1CC=CC1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2cccc(F)c2)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)C(F)(F)C(F)(F)F)N1
Invalid SMILES: Nc1[nH]c(OCP(=O)(=O)(O)O)nc1C(F)(F)F
Invalid SMILES: O=P(=O)(O)(O)c1nc(C(F)(F)F)c[nH]1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccncc1
Invalid SMILES: O=CN(F)C1=C(P(=O)(=O)(O)O)C=C1
Invalid SMILES: O=P(=O)(O)(O)C1=CC=C1
Invalid SMILES: O=P(=O)(O)(O)c1ccccn1
Invalid SMILES: O=C1CCCN1CCP(=O)(=O)(O)O
Invalid SMILES: O=C(CCNc1ncc[nH]1)[PH](=O)(O)(O)Cl
Invalid SMILES: O=P(=O)(O)(O)C1=C(c2ccccc2Nc2cc[nH]c2)C=C1
Invalid SMILES: N#CC1=C(P(=O)(=O)(O)O)C=C1
Invalid SMILES: O=P(=O)(O)(O)CCN1CCOCC1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1nc(O)c(C(F)(F)F)n1C(F)(F)F
Invalid SMILES: Cn1nccc1CN(CCO)CP(=O)(=O)(O)O
Invalid SMILES: O=C(CCN1CC=CC1)[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1ccc(Br)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)c1ccc(C(F)(F)C(F)(F)F)cc1
Invalid SMILES: O=C(c1ccccc1)[PH](=O)(O)(O)O
Invalid SMILES: N#Cc1ccc(C[PH](=O)(O)(O)O)cc1
Invalid SMILES: O=C1NC(C(F)(F)F)=C(P(=O)(=O)(O)O)C1(F)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccccc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc[nH]1
Invalid SMILES: O=P(=O)(O)(O)CCNc1nc(C(F)(F)F)c[nH]1
Invalid SMILES: O=[PH](O)(O)(O)C(O)=C1N=CC(O)=N1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(F)=C1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=N/C=C\c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1
Invalid SMILES: O=[PH]1(O)(O)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccccc1O
Invalid SMILES: O=P(=O)(O)(O)c1cc(O)c(O)c(O)c1
Invalid SMILES: O=[PH](O)(O)=C1C=C=C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=Cc1cc(O)c(O)c(O)c1
Invalid SMILES: O=P(=O)(O)(O)NCc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=C1C(F)=C=C=C1F
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C(Cl)=CC(Cl)=C1Cl
Invalid SMILES: O=[PH](O)(O)=C1C=CC=CC1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccccc1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccccc1O
Invalid SMILES: O=Cc1c(O)c(O)c(O)c(O)c1P(=O)(=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1cc(O)ccc1O
Invalid SMILES: O=P(=O)(O)(O)Nc1c(F)c(F)c(F)c(F)c1F
Invalid SMILES: O=[PH](O)(O)=C1C=CC(F)(F)C=C1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(F)cc1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ncccc1O
Invalid SMILES: O=[PH](O)(O)(O)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=N1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2cccs2)s1
Invalid SMILES: O=P(=O)(O)(O)C=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=P(=O)(O)(O)C(=Cc1ccc(-c2cccs2)s1)c1cccs1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=C(O)C(=C/C=C\c1ccc(-c2cccs2)s1)P(=O)(=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)CCNc1sc(-c2cccs2)cc1C(F)(F)F
Invalid SMILES: O=P(=O)(O)(O)C(=Cc1ccc(-c2cccs2)s1)c1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=P(=O)(O)(O)CC=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(c1cccs1)c1cccs1
Invalid SMILES: O=P(=O)(O)(O)c1c(F)sc(-c2cccs2)c1F
Invalid SMILES: O=C(O)C(=Cc1ccc(-c2cccs2)s1)P(=O)(=O)(O)O
Invalid SMILES: O=C(O)c1cc(-c2cccs2)sc1P(=O)(=O)(O)O
Invalid SMILES: O=S(=O)(O)c1sc(-c2cccs2)c(P(=O)(=O)(O)O)c1Cl
Invalid SMILES: O=[PH](O)(O)(F)c1ccc(-c2cccs2)s1
Invalid SMILES: O=C(F)c1ccc(C(=C/C=C\C=C\C(F)(F)F)[PH](=O)(O)(O)O)cc1
Invalid SMILES: Nc1sc(-c2cccs2)c(C(=O)O)c1P(=O)(=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1sc(-c2sc(F)c(F)c2F)c(F)c1F
Invalid SMILES: O=P(=O)(O)(O)CCNc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(-c2cccs2)cc1
Invalid SMILES: O=P(=O)(O)(O)/C=C/c1ccc(-c2cccs2)s1
Invalid SMILES: O=C(O)C(=C/C=C\c1ccc(-c2cccs2)s1)[PH](=O)(O)(O)O

[12:56:02] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCn1c2ccccc2c2ccccc21

[12:56:03] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)[nH]c1ccccc12

[12:56:03] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:03] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C1c2ccccc2-c2ccccc21

[12:56:03] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:03] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:03] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:03] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:03] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:03] Explicit valence for atom # 13 C, 4, is greater than permitted
[12:56:03] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:03] Explicit valence for atom # 14 C, 4, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Cc2ccccc21
Invalid SMILES: O=[PH]1(O)(O)c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccc(Br)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Sc2cc(Br)ccc21
Invalid SMILES: O=P(O)(O)CCN1c2ccccc2[CH2+]c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=c1[nH]c2ccccc2c2ccccc12
Invalid SMILES: O=P(O)(O)CCN1c2ccc(Br)cc2[CH2+]c2cc(Br)ccc21

[12:56:04] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:04] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:04] Explicit valence for atom # 14 C, 4, is greater than permitted
[12:56:04] Explicit valence for atom # 13 C, 4, is greater than permitted
[12:56:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1Nc2ccccc2[SiH-]c2ccccc21
Invalid SMILES: O=[PH](O)(O)=NCN1c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(O)(O)CCN1c2ccc(Br)cc2[CH2+]c2ccc(Br)cc21
Invalid SMILES: O=P(O)(O)CCN1c2ccccc2[CH2+]c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccccc2Nc2ccccc21

[12:56:04] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:04] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:56:04] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:56:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Sc2ccccc21
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2cccc3cccc1c23
Invalid SMILES: O=C1c2ccccc2[PH](=O)(O)(O)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CCCCOc1cc2c(c3ccccc13)Sc1ccc(O)cc1S2

[12:56:04] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH]1(O)(O)c2ccccc2Sc2c1sc1ccccc21
Invalid SMILES: O=[PH](O)(O)=C1c2c(sc3ccccc23)-c2sc3ccccc3c21

[12:56:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCn1c2cc(Br)ccc2c2c3cc(S(=O)(=O)O)ccc3[nH]c21

[12:56:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3ccccc3ccc21

[12:56:07] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: Cn1c2ccccc2c2cc(C=CC=[PH](=O)(O)O)ccc21

[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:07] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1cccc(N(c2ccccc2)c2ccccc2)c1
Invalid SMILES: O=P(=O)(O)(O)CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)CP(=O)(=O)(O)O
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1cccc(N(c2ccccc2)c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)(O)CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(CCCP(=O)(=O)(O)O)N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(CCCP(=O)(=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(C#N)=C(CP(=O)(=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)CC1=C(N(c2ccccc2)c2ccccc2)C=C1

[12:56:12] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccccc1

[12:56:12] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-n2c3ccccc3c3ccccc32)cc1

[12:56:13] Explicit valence for atom # 16 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1

[12:56:18] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-n2c3ccccc3c3cc(Br)ccc32)cc1

[12:56:18] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)c1ccccc1n2-c1ccccc1

[12:56:19] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1

[12:56:20] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cccc2c1c1ccccc1n2-c1ccccc1

[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(O)C1CN2CCC(CCO)(CC2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc3c4c(c2)CCCN4CCC3)s1
Invalid SMILES: O=[PH]1(O)(O)CN2CCC(CCO)(CC2)c2cc(-c3cccs3)ccc21
Invalid SMILES: O=P(=O)(O)(O)C1CCCN2CCCC3=C2C(O)(c2cccs2)CCN3CC1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2cc3c4c(c2)CCCN4CCC3)s1
Invalid SMILES: O=[PH]1(O)(O)CCC2=C(C1)c1ccc(cc1)N2CCC1=CC=C1
Invalid SMILES: O=P(=O)(O)(O)C1C=CC2CCN(C1)C(N1CCC3=CCC1=C3)C2
Invalid SMILES: O=[PH]1(O)(O)CN2CCC(O)(CCO)CC2c2cc(-c3cccs3)ccc21
Invalid SMILES: O=[PH](O)(O)(c1cc2c3c(c1)CCCN3CCC2)c1cccs1
Invalid SMILES: O=[PH]1(O)(O)C=C2CCCN3CCCC(=C23)C=C1c1cccs1
Invalid SMILES: O=[PH]1(O)(O)CCN2CCC(O)(CC1)c1cc3ccsc3cc12

[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:21] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)sc1c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2c(c3ccccc31)-c1ccccc1Sc1ccccc1-2
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)sc1ccccc12

[12:56:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3sc4ccccc4c3ccc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)oc1ccccc12

[12:56:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1ccc2c(c1)sc1c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccccc2c2sc3ccccc3c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2sc3ccccc3c21

[12:56:23] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:56:23] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: Cn1c2c3ccc(C=C=[PH](=O)(O)O)cc3c1=c1ccccc1=c1ccccc1=2
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c3ccccc4ccccc4c-3c2c1

[12:56:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:23] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccccc3c(Br)cc21

[12:56:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:24] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccc(O)cc3c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)-c1c-2c2ccccc2c2ccccc12
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21

[12:56:24] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:56:24] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:56:24] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:56:24] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:56:24] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:56:24] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:56:24] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:56:24] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:56:24] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:56:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc(C3CCCCC3)c3cccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)c2cccc3c(C4CCCCC4)ccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)C(=O)c2ccc(-c3cccc(O)c3)c3cccc1c23
Invalid SMILES: O=C1NC(=O)c2cccc3c(-c4ccc(O)cc4)ccc(c23)C(=O)C1=[PH](=O)(O)O
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc(-c3ccccc3)c3cccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)N(C(F)(F)F)C(=O)c2ccc(-c3ccc(O)cc3)c3cccc1c23
Invalid SMILES: O=C(O)c1ccc2c3c(ccc(CNP(=O)(=O)(O)O)c13)C(=O)N(CCc1ccncc1)C2=O
Invalid SMILES: O=C1c2cccc3cccc(c23)C(NP(=O)(=O)(O)O)C(=O)N1CCc1ccncc1
Invalid SMILES: O=C(O)CNc1cc2c3c(c(NCO)cc4c3c1C(=O)C(=[PH](=O)(O)O)NC4=O)C(=O)N(CO)C2=O
Invalid SMILES: O=[PH](O)(O)=Cc1cccc2c3c(ccc12)=CC=c1ccccc1=c1ccccc1=3

[12:56:25] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:56:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:25] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:56:26] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:56:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:26] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:56:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:26] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:56:26] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(CCCCC=[PH](=O)(O)O)OC1=CC=c2ccc3c4c(ccc(c24)=C1)=c1ccccc1=CC=3
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: N#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(CP(=O)(=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccc(O)cc2)c2ccc(-c3ccccc3)cc2)cc1

[12:56:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccc(-c2ccccc2)cc1

[12:56:31] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc3c(c2)-c2cc(-c4ccccc4)ccc2-3)cc1

[12:56:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:39] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:56:39] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:56:39] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(-c3cccc4nsnc34)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2cccc3nsnc23)cc1
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc(N(c2ccccc2)c2ccc(-c3cccc4nsnc34)cc2)cc1
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc3c4c(ccc1c24)C(=O)N(c1ccccc1)C3=O
Invalid SMILES: COc1ccc(N(c2ccc(C=CC=[PH](=O)(O)O)cc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1

[12:56:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:43] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:56:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:43] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)c3nsnc23)cc1
Invalid SMILES: COc1ccc(N(c2ccc(C=CC=[PH](=O)(O)O)cc2)c2ccc(-c3ccc(-c4ccccc4)cc3)c3nsnc23)cc1
Invalid SMILES: O=[PH](O)(O)=CCSc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)c3nsnc23)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=CC2)c2ccc(-c3ccc(-c4ccc5[nH]snc4-5)cc3)cc2)=C1
Invalid SMILES: O=c1c(=[PH](=O)(O)O)c(=O)c2ccc3c4ccc5c(=O)n(CO)c(=O)c6ccc(c7ccc1c2c73)c4c65

[12:56:43] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)s3)s2)cc1

[12:56:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:47] Explicit valence for atom # 41 P, 7, is greater than permitted
[12:56:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:47] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:56:47] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:48] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:56:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:48] Explicit valence for atom # 4 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc3[nH]c4ccc(N(c5ccccc5)c5ccccc5)cc4c3c2)cc1
Invalid SMILES: N#CC(C#N)=Cn1c2ccc(N(c3ccccc3)c3ccccc3)cc2c2cc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)ccc21
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: C=CCN(C1=CC=C1)c1ccc(-c2ccc(-c3ccc(N(C4=CC=CCC4)c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(Oc3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: CCC(C#N)=Cc1ccc(N2C=CC([PH](=O)(O)(O)CC(C)(C)C)=CC=C2c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccc(C4=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=C1SC(=[PH](=O)(O)O)SC1=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:56:48] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:56:48] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C1C(=Cc2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)SC(=[PH](=O)(O)O)N1C(=S)CO
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3cccc(-c4ccccc4)c3)cc2)cc1

[12:56:51] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-n3c4ccc(-c5ccccc5)cc4c4cc(-c5ccccc5)ccc43)cc2)cc1

[12:56:53] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:53] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:56:53] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(-c3ccc4c(c3)sc3cc5ccc3[nH]cccccc3cccccc4n35)cc2)cc1

[12:56:54] Explicit valence for atom # 25 P, 7, is greater than permitted

Invalid SMILES: O=C(C1=CC=C1)C1=CC(NC2=CC=C2)=C2C=C(O1)c1cc(OCCCP(=O)(=O)(O)O)ccc12

[12:56:56] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21

[12:57:01] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCCCCn1c2ccccc2c2c3ccccc3ccc21

[12:57:02] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2c3ccccc3ccc21

[12:57:03] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)[nH]c1c3ccccc3ccc21

[12:57:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cc2c(cc1O)[nH]c1ccccc12

[12:57:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)Nc1ccc2c(c1)[nH]c1ccccc12

[12:57:06] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: COc1cc2[nH]c3ccccc3c2cc1PC=CC=[PH](=O)(O)O

[12:57:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC=C(n2c3ccccc3c3ccccc32)C=C1
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2ccccc21

[12:57:07] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:57:07] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCN1c2cccc(c2)-c2cc(C=[PH](=O)(O)O)ccc21
Invalid SMILES: O=P(=O)(O)(O)n1c2ccccc2c2ccccc21

[12:57:08] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C/C=C/c1cc2c(cc1O)[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)[nH]c1ccccc12

[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCCn1c2ccccc2c2ccccc21

[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Br)cc2ncc=2c1
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Cl)cc2Oc2cc(Br)ccc21

[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:09] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCSc1ccc2c(c1)Nc1cc(Br)ccc1S2
Invalid SMILES: O=P(=O)(O)(O)CCN1c2ccc(Cl)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccc(Br)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(S(=O)(=O)O)cc2Sc2ccc(S(=O)(=O)O)cc21
Invalid SMILES: O=[PH](O)(O)=CN1c2ccccc2Sc2cc(Br)ccc21
Invalid SMILES: O=C(O)c1ccc2c(c1)N(P(=O)(=O)(O)O)c1ccccc1S2
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2ccc(Cl)cc21
Invalid SMILES: O=[PH](O)(O)=CN1c2ccc(Br)cc2Sc2ccc(Cl)cc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2cc(Br)c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=C1Nc2ccc(S(=O)(=O)O)cc2Sc2ccccc21

[12:57:12] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3ccccc3Nc3ccccc32)cc1

[12:57:13] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: O=C(OCC=[PH](=O)(O)O)n1c2ccccc2c2cc(Cl)ccc21

[12:57:15] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccc(Br)cc21

[12:57:15] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1[nH]c2ccc(Br)cc2c2ccc(Br)cc12

[12:57:16] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCn1c2ccc(Br)cc2c2cc(Br)ccc21

[12:57:18] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C/C=C/c1cc2n[nH]c3ccccc3c-2n1

[12:57:20] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCn1c2ccc(P(=O)(=O)(O)O)cc2c2ccc(Br)cc21

[12:57:21] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=C3C(O)=CC(O)=C32)cc1

[12:57:22] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:57:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(C=[PH](=O)(O)O)OCCOC(=O)n1c2ccccc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccc(Br)cc2c2ccc(Br)cc21

[12:57:23] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc(Br)ccc21

[12:57:23] Explicit valence for atom # 22 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)=Cc1ccc2c(c1)c1cc(Br)ccc1n2CC=[PH](=O)(O)O

[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 40 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:26] Explicit valence for atom # 33 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccc(N(C4=CC=CC4)c4ccccc4)cc3)cc(=[PH](=O)(O)O)s2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C(C(F)(F)F)OC=C2)C2=CC=c3c2cccc3=CC=C2PC=CC3=CC=CC=CCC=CN32)=C1
Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc(-c3ccc([PH](=O)(=O)O)c4nsnc34)cc2)c2ccccc12
Invalid SMILES: O=[PH](O)(O)=c1cc(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)cc(C2=CC=C2)s1
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=C(O)C1=Cc2ccc(c3c(ccc4ccc-4cccc(=CC=CC4=C=C4)n2C2=CCC(=[PH](=O)(O)O)C=C2)C=3)OC1
Invalid SMILES: O=C(O)c1ccc(C#P(=O)(O)O)cc1N(c1ccccc1)c1ccc(-c2ccc(P(=O)(O)O)c3nsnc23)cc1
Invalid SMILES: O=C1C=C2C(N(c3ccccc3)c3ccc(-c4ccc(P(=O)(O)O)c5nsnc45)cc3)=CC=C(C#P(=O)(O)O)C12
Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc(-c3ccc([PH](=O)(=O)O)c4nsnc34)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(F)cc4)cc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2F)c2nsnc12
Invalid SMILES: O=[IH](O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)=C(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC(c4ccc(N=CC5=C=CC5)cc4)C=C3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=Cc1cccs1
Invalid SMILES: O=P(=O)(O)(O)c1cccs1
Invalid SMILES: O=P(=O)(O)(O)c1cscc1Br
Invalid SMILES: O=S(=O)(O)c1ccc(P(=O)(=O)(O)O)s1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C(Cl)(Cl)Cl)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=C/C=C/C(C(F)(F)F)=CS1
Invalid SMILES: O=[PH](O)(O)=CC(C1=CC=C1)=C1C=CC(c2ccc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=CO1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(C2=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccccc2)cc1
Invalid SMILES: N#CCCCCCCCCCC(C#N)C=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N2C=CC=CC2)cc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C(c3ccc(-c4ccccc4)cc3)C2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CC(=CC=C1C=C(O)c2ccc(cc2)O1)C1=CC(c2ccc(-c3ccccc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccc(C4=CC=CC4)cc3)c3ccc(-c4ccccc4)cc3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=CC4)cc3)cc2)cc(C2=CC=C2)c1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(N(C2=CC=C(c3ccccc3)C=CC=C2)c2ccc(C3=CC=C3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccc(C4=CC=C4)cc3)c3ccc(C4=CC=CC4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CCC(C1=C=CC=C1)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)=CO1
Invalid SMILES: O=[PH](O)(O)=CC(=CC=C1C=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1)c1ccc(C2=CCC=C2)cc1
Invalid SMILES: O=C(O)C(=Cc1ccc(N(c2ccc(-c3ccccc3)cc2)c2ccc(-c3ccccc3)cc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C2)c(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=C=C4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(C=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)=CCO1)C1=C=CCC=C1
Invalid SMILES: O=[PH](O)(O)=CC(O)=C1C=CC(N(c2ccc(C3=CC=C(C4=CC=CC4)C3)cc2)c2ccc(-c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(c2ccccc2)=C1)c1ccccc1)C1=CC=CC(N(c2ccccc2)c2ccccc2)C=C1
Invalid SMILES: O=C(O)c1ccc(C(=Cc2ccc(-c3ccc(N(C4=CC=C4)c4ccccc4)cc3)cc2)C=[PH](=O)(O)O)cc1

[12:57:28] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:57:30] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:57:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:30] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:57:30] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:57:30] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:57:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:30] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:30] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:31] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:57:33] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:34] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:35] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:36] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:37] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:37] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:57:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:38] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#CPC(=Cc1ccc(C2=CC=C(C3=CC=CCC3)C=CC=C2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccccc3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(-c3ccc(C=CC=[PH](=O)(O)O)cc3)s2)s1)C(=O)O
Invalid SMILES: O=C(O)c1cccc(-c2ccc(C=[PH](=O)(O)O)s2)c1
Invalid SMILES: O=C(O)C1=CPC2=CC3=C(C=CC=CC=C2C3)N(c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(c4ccccc4)=CC=CC=C3)c2)cc1
Invalid SMILES: O=C(O)C(=C1C=C(C2=CC(=[PH](=O)(O)O)C=C2)C1)c1ccc(-c2ccccc2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(=CC(F)(F)F)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1-c1ccc(C2=CCC=C2)cc1
Invalid SMILES: N#Cc1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)s3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC(C2=CC=C(C3=CC=C=C3)[IH]C=C2)=CC(c2cccc(C3=CC=C3)c2)=CC=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(C3=CC(F)=CC(C4=CC=C4)C=C3)c(F)c2)cc1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(-c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3F)cc2)C=CP1
Invalid SMILES: O=C(O)C1=C(C2=CCC=C2)C=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CC=CC4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC=C(c4ccccc4)C=CC3)c2)cc1
Invalid SMILES: O=C1C=CC1=CC=C1C=CC1=C1C(Cl)=C1SC1=C(S(=O)(=O)O)C(Cl)=CC1=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccccc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(C2=CC(c3ccccc3)=CC(c3ccccc3)=CC=C2)c1
Invalid SMILES: O=C(O)C1=CC=C(c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)CC=C1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(Cl)C(c2ccc(C3=CC=CC(Cl)C=C3)c(F)c2)S1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3cc(F)cs3)c(F)c2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(F)c(F)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC=C(C4=CC=C=C4)C=CC3)c2)cc1
Invalid SMILES: O=C(O)C1=CC(=[PH](=O)(O)O)S1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(C3=CC(F)=CC(F)C=C3)c(F)c2)cc1
Invalid SMILES: O=[PH](O)(O)=c1cc(-c2ccc(C(F)(F)F)cc2)sc(-c2ccc(C3=CC=C3)s2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CC=C4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC=CC(C4=CC=C4)=CC3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CCC=C4)cc3)c2)s1
Invalid SMILES: O=C(O)c1cccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)c1
Invalid SMILES: O=C(O)c1cc(C2=CCC2=CC=CC2C=CCCN2C2=CC=C2)cc(-c2ccc(C=[PH](=O)(O)O)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC=C(C4=CC=C4)C=CC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=C(c2ccc(O)c(Cl)c2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=CC3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccc(-c3ccc(C=[PH](=O)(O)O)cc3)s2)s1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(-c2ccc(-c3ccc(C(=O)O)s3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=C3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C=CC=CC(C4=CC=CCC4)=CC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=C(c3ccc(-c4ccccc4)s3)C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C=CC=CC(c4ccccc4)=CC3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(F)=CC(C4=CC=C4)C=C3)s2)cc1
Invalid SMILES: O=C(O)C1=CCC=C(N(c2ccccc2)c2ccc(-c3ccc(C=[PH](=O)(O)O)s3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N(c3ccccc3)c3ccccc3)c2)cc1
Invalid SMILES: O=C(O)C(=O)Sc1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-n3cccc(O)c4ccc3cc4)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(NC2=CC(c3ccc(C4=CC=C4)cc3)C=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC=C(PC3=CC=C3)C=CC(C3=CC=CC=CC3)=C2)s1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-c2ccc(-c3cccs3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc(C2=CC=CC2)cc(-c2ccc(-c3ccccc3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC=CC(c4ccccc4)=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC4=CC=C3C=CC=C4)c2)cc1
Invalid SMILES: O=C(F)C1=CN(c2ccc(-c3ccc(C=[PH](=O)(O)O)s3)cc2)C=CC=CC=C[IH]1
Invalid SMILES: O=C[IH]C1=CC=C2C=Cc3c(ccc(C(=O)O)ccc(C4=CC(=[PH](=O)(O)O)C=C4)cc32)C1=O
Invalid SMILES: O=C(O)C1=C(C2=CC=CC(C3=CC=CC3)C=C2)C=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(F)(F)C=C3)c2)cc1
Invalid SMILES: O=C(O)C=C1C=CC(c2ccc(C=[PH](=O)(O)O)cc2)=CC(C2=CC=C(C3=CC=C=C3)[IH]C=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(PC3=CC=CC3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(Cl)cc2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CCC=C3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC(C2=C(C3=CC=C3)C=CC2)=C(c2ccc(F)cc2)[IH]C=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(-c3cccc(F)c3)c(F)c2)s1
Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(C3=CC=C=C3)c3ccccc3)cc2)S1
Invalid SMILES: O=Cc1ccc(-c2ccc(-c3ccc(PC=[PH](=O)(O)O)cc3)s2)s1
Invalid SMILES: O=C(O)C1=CN(c2ccc(C3=CC(=[PH](=O)(O)O)S3)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(-c4ccccc4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C(F)(F)F)c2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CC=C(c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3C3=CC=C3)CC=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(C(=O)O)[IH]C=C(c4ccc(C5=CCC=C5)cc4)C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=CC3)cc(-c3ccc(C4=CC=CC(C5=CC=CC5)C=C4)cc3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC(C5=CC=C(C6=CC=C6)C5)C=C4)=C3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=C1CC=C(C2=C=CC=C2)C=C(c2ccc(-c3ccc(-c4ccc(-c5ccccc5)cc4)cc3)cc2)S1
Invalid SMILES: O=[PH](O)(O)=C1C=C[IH]C(c2ccc(C3=CC=C(c4ccc(C5=CC=C=C5)[pH]4)C=CC3)cc2)=C(C2=CC=CC2)S1
Invalid SMILES: O=C(O)c1cc(C=[PH](=O)(O)O)cc(-c2ccc(C3=CC=CC(c4ccc(C5=CC=CCC=C5)cc4)C=C3)cc2)c1
Invalid SMILES: O=C(O)C(=C1CC(=[PH](=O)(O)O)S1)c1ccc(-c2ccc(-c3ccccc3)s2)s1
Invalid SMILES: O=C(O)c1ccn(-c2ccc(C3=CP(=O)(O)(O)=CC(c4ccc(C5=CC=C5)cc4)=C3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(c4ccc(-c5ccccc5)cc4)C=CC=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CC=C(C3=CC=C(C=[PH](=O)(O)O)C=C(c4ccc(C(=O)O)cc4)S3)CP2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=C3)cc(-c3ccc(C4=CC=C(C5=CC=C5)PC=C4)cc3)c2)cc1
Invalid SMILES: O=C(F)C(=C1C=C(C2=CC(=[PH](=O)(O)O)C=C2)C1)c1ccc(-c2ccc(Cl)cc2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)c(C3=CC(C4=CC(n5cccc5O)CC=C4)C=C3)s2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3cc(F)cc(-c4ccc(N(C5=CC=C5)C5=CC=CC5)cc4)c3)c2)cc1
Invalid SMILES: O=CC1=CC=C(c2ccc(-c3ccc(C4C=CC(c5ccc(C=[PH](=O)(O)O)cc5)=C4)cc3F)cc2)C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccc(C4=CCC=C(C5=CC=C5)PC=C4)cc3)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(-c3cccc(-c4ccc(C=[PH](=O)(O)O)cc4)c3)cc2O)cc1
Invalid SMILES: O=C(O)c1cc(-c2ccc(C=[PH](=O)(O)O)cc2)cc(-c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)c1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(-c3cc(C4=CCC=C4)cc(-c4ccc(C=[PH](=O)(O)O)cc4)c3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(=[PH](=O)(O)O)sc2-c2cccc(-c3ccc(C4=CC=C4)c(F)c3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=CC=CC=C3)cc(-c3ccc(C4=CCC=C4)cc3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC=C(n5cccc5)C(F)C=C4)PC=C3)s2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2sc(C=[PH](=O)(O)O)cc2C2=CC(C3=CC=C(c4ccc(C5=CC=C5)cc4)C3)=CC2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(C4=CC=C(C5=CC=C5)C4)C=CC3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc(c1)-c1ccc(cc1)-c1ccc(cc1)-c1ccc(cc1)-c1ccc(cc1)C=CCC=CC=C2
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=CC3=CC(c4ccc(C5=CC=C5)cc4)=C2C=CC=C3O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(O)c(-c3ccc(-c4ccc(Cl)cc4)s3)c(C3=CCC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2=CC(c3ccc(C4=CC(C5=CC=C5)PC=C4)c(F)c3)C=C2)=C1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(-c3ccc(C4=CC=C(C5=CC=C5)BC=C4)cc3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(-c4ccc(P)cc4)cc3)cc(-c3cccc(O)c3)c2)cc1
Invalid SMILES: N#Cc1ccc(-c2ccc(C(C(=O)O)=C3C=C(C4=CC(=[PH](=O)(O)O)C=C4)C=C3O)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccccc3C3=CC=C(C4=CC=CC4)PC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(F)c2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C2)cc(-c2ccc(C3=CC(C4=CC=C(C5=CC=C5)C4)C=C3)cc2O)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccccc3C3=CCC=C(C4=CC=C4)PC=C3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(C3=CC=CCC=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)c(F)c3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(c4ccc(C5=CC=C5)cc4)PC3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc(C2=CC=C=C2)cc(-c2ccc(C3=CC=C(C4=CCC=C4)C=CC3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(C4=CCC=C4)C=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1
Invalid SMILES: O=P1(O)(O)=CC(c2ccccc2)=CC(c2ccc(N(C3=CC=CC(C4=CC=C4)C=C3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3cccc(-c4ccc(C5=CCC=C5)cc4)c3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC(c4ccc(C5=CC=C5)cc4)C=CC=C3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(C3=CC=C(c4ccc(C5=CC=C5)cc4)C=CC=C3)cc2)c(C2=CC=C2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(F)=C(c3ccc(-c4ccccc4)s3)C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3cccc(-c4ccccc4)c3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccccc3)c2)cc1C1=CC=C(C2=CC=C(C3=CC=C3)C2)C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=CC3)C=CC(c3ccc(-c4ccc(-c5ccccc5)cc4)cc3)=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(c2ccc(C3=CC=C3)cc2)SC(C2=CC=C(c3ccccc3)C=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC(C4=CCC=C4)=C3)cc2)c(-c2ccc(C3=CCC=C3)cc2)c1
Invalid SMILES: O=C(O)c1ccc(C2=CP(=O)(O)(O)=CC(C3=CC(C4=CC(c5ccc(C(=O)O)cc5)C=C4)C=C3)=C2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CC(C=[PH](=O)(O)O)=CC=C(c3ccc(-c4ccc(C5=CC=C5)cc4)s3)S2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=C3)C=CC(c3ccc(C4=CC=C(C5=CC=CCC5)PS4)cc3)=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C3=CC(c4ccc5c(c4)CC5=CC=C4C=CC=C4)=C3)ccc(=[PH](=O)(O)O)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(c4ccc(-n5ccc(O)c5)cc4)=C3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(C4=CC=C4)cc3)cc(-c3ccc(C4=CCC=C4)cc3)c2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC(F)C(F)=C(F)C4=C(F)C4=CC=C4)=CC3)s2)cc1
Invalid SMILES: O=C(O)C1=C(C2=CC(c3ccc(C4=CC=C4)cc3)=C2)C=C(c2ccc(C=[PH](=O)(O)O)s2)C=C[IH]1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(F)=CC(F)C3=CC=C3CC3=C(F)C3=CC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(F)=C(c4ccc(C5=CC=C5)cc4)[IH]C=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(F)=C(C4=CC=C(N=C(O)C5=CC=C5)C4)CC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC(F)=C(c4ccc(C5=CC=C5)cc4)C=CC3)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CP(=O)(O)(O)=CC(C3=CC(C4=CC=C(C5=CC=CCC=C5)C(C5=CC=C5)CC4)=CC3)=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(C4=CC=C4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)ccc2C2=CC=C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(C4=CCC=C(C5=CC=C5)C=C4)cc3)c(C3=CC=CCC3)c2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccc(-c4ccc(C5=CC=C=C5)cc4)c(F)c3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(C3=CCC=CC3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=C(C4=CC(F)C(F)=C(C5=CC=C5)N4)C=C3)s2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccc(C=[PH](=O)(O)O)cc3)cc(-c3ccc(C4=CC=CC4)cc3)c2)cc1
Invalid SMILES: O=P1(O)(O)=CC(c2ccccc2)=C(c2ccc(N(c3ccccc3)c3ccc(N(C4=CC=C4)c4ccccc4)cc3)cc2)C=C1
Invalid SMILES: O=P1(O)(O)=CC(c2ccc(N(C3=CC=C=C3)C3=CC=CC3)cc2)=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cc(-c2ccc(N(C3=CC=C3)C3=CCC=C=C3)cc2)cc(-c2ccc(N(C3=CC=C=C3)c3ccccc3)cc2)c1
Invalid SMILES: O=P1(O)(O)(C2=CC=C2)C=CC(c2ccc(N(C3=CC=CC3=CC=C3C=CN3c3ccccc3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=C1SC2=C3C(=CC=c4ccc(n4C4=CC=C4)=CC=CC=CC=C2)CC=CC=C2C=CC=CC=c4ccc(n42)=CC=C31
Invalid SMILES: O=P1(O)(O)=CC(N(C2=CCC=C2)C2=CC=CC2)=C(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(C3=CCC=C(N(C4=CC=CC4)C4=CC=CC4)C=C3)c3ccccc3)cc2)C=C1c1ccccc1
Invalid SMILES: O=P1(O)(O)=CC=C(C2=CC(N(C=C3CC=CC3)C3=CCC=C3)=CC(c3ccc(N(C4=CC=C=C4)C4=CC(O)C=CC4)cc3)C=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(c3ccccc3)c3ccc(N(C4=CC=C4)C4=CC=CC4)cc3)cc2)C=C(C2=CC=CC2)C1
Invalid SMILES: O=P1(O)(O)=Cc2cccccccc3ccc(ccc4cccccc5c(ccc6ccc6ccc1c24)OC5)n3C1=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC(C1=CC=CC1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(N4C=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=P1(O)(O)=CC2=c3c1ccc1ccc4n1c(cccccc3=CC=c1ccc(n1C1=CC=C1)=CC=CC=CC=C=C2)C=CC=CC=4
Invalid SMILES: O=[PH](O)(O)=c1cc(-c2cccc(N(C3=CC=CC3)c3ccccc3)c2)cc(-c2ccc(N(C3=CC=C3)c3ccccc3)cc2)s1

[12:57:41] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-n4c5ccccc5c5ccccc54)s3)s2)cc1

[12:57:43] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(C=[PH](=O)(O)O)cc1-c1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)s2)s1

[12:57:48] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-n4c5ccccc5c5ccccc54)cc3)s2)cc1

[12:57:50] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC=C2)c(-c2ccc(-c3ccc(-n4c5ccccc5c5ccccc54)s3)s2)c1

[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 38 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:52] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC(C3=CCC=C3)C2)C2=CC21
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)CC1=CCC1=CC=C1
Invalid SMILES: O=[PH]1(O)(O)CCC(c2ccc(N(c3ccccc3)c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)CC1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)CC1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCCC2)C2=CC1=CC2
Invalid SMILES: O=C1C(c2ccc(N(c3ccccc3)c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)CCC[PH]1(=O)(O)O
Invalid SMILES: O=[PH]1(O)(O)CCCC(F)(c2ccc(N(c3ccccc3)c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)CC1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCCC2(F)C2=CC=C2)CC1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)C2=CC1=CCc1cccc2c1
Invalid SMILES: O=Cc1ccc(N(c2ccc(C=O)cc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccc(C#P(=O)(O)O)cc5)cc4)CCCCC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)C2=CC=C21
Invalid SMILES: O=[PH](O)(O)=CC(c1ccc(N(C2=C=C2)c2ccccc2)cc1)c1ccc(N(C2=CCC=C2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)CC1=CC1=CC=C1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccccc5)cc4)CCCC3)cc2)cc1
Invalid SMILES: O=Cc1ccc(N(c2ccc(Cl)cc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccc(C#P(=O)(O)O)cc5)cc4)CCCCC3)cc2)cc1
Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccc(C#P(=O)(O)O)cc5)cc4)CCCC3)cc2)cc1
Invalid SMILES: N#CC1=CC(=CC=[PH](=O)(O)O)C=C1
Invalid SMILES: N#CC1=CC=CC(=CC=[PH](=O)(O)O)C=C1
Invalid SMILES: O=[PH](O)(O)=CC=CPc1ccc(Br)cc1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(C(F)(F)F)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C(F)(F)F)C=C1
Invalid SMILES: O=Nc1ccc(/C=C/C=[PH](=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1ccc(Br)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C(F)(F)F)cc1
Invalid SMILES: O=[PH](O)(O)=CC=CPc1ccccc1Br
Invalid SMILES: O=[PH](O)(O)=c1ccc(C(F)(F)F)cc(C(F)(F)F)c1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CS1
Invalid SMILES: N#Cc1ccc(C#P(=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1c(F)c(F)c(F)c(F)c1F
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(Br)cc1
Invalid SMILES: N#CC1=CC(O)=CC(=CC=[PH](=O)(O)O)C=C1
Invalid SMILES: N#CC1=C=CC=CC(C=CC=[PH](=O)(O)O)=C1
Invalid SMILES: O=[PH](O)(O)=C/C=C\c1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(C(F)(F)F)=C1
Invalid SMILES: O=Cc1ccc(C=CC=[PH](=O)(O)O)cc1
Invalid SMILES: N#CC(Cl)=CC=C1C(=CC=[PH](=O)(O)O)C=CC1=CC(=CCO)C(=O)O
Invalid SMILES: N#Cc1ccc(/C=C\C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc(PC=CC=[PH](=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Cl)cc1
Invalid SMILES: O=[PH](O)(O)=CC=CPc1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CPC=CPc1cccc(N(CCO)CCO)c1
Invalid SMILES: N#CC(C#N)=Cc1ccc(/C=C/C=[PH](=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C/C=C\c1c(F)c(F)c(F)c(F)c1F
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C=C2)c2ccc(N(c3ccc(C4=CC=C=C4)cc3)c3ccc(C4=CC=C4)cc3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(C3=CCC=C3)c3nsnc23)cc(-c2ccc(N(C3=CC=C=C3)C3=CC=C3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C=C2)cc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=C1C=C(N(c2ccc(O)cc2)c2ccc(N(C3=CC=C=C3)C3=CC=CC3)cc2)C=C(C2=CC=CCC=C2)CC1
Invalid SMILES: O=CC1=CC(=[PH](=O)(O)O)NC1=CPc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12

[12:57:52] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: O=c1cccc2c3ccc(n12)Cc1c(ccc(=[PH](=O)(O)O)[nH]c1=S)-c1ccc(cc1)N3C1=CC=C1

[12:57:53] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:53] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:54] Explicit valence for atom # 49 P, 7, is greater than permitted
[12:57:54] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:57:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:55] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:57:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:56] Explicit valence for atom # 48 P, 7, is greater than permitted
[12:57:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:56] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:57:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:56] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:57:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 42 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 47 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 2 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:57] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 42 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 52 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 42 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 42 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 46 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:57:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 48 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 2 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 48 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:57:59] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)c2cccc(O)c2)cc1)C1=CCC=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1cccc(-c2ccc(N(C3=CC=CC3)c3ccc(C4=CC=C4)cc3)cc2)c1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2CC=CC=C=CC3=CC=C3c3ccc(cc3)N(c3ccc(-c4ccccn4)cc3)c3ccc2cc3)=CC1
Invalid SMILES: CCC(=CC(=C1C=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1)c1ccc(N2C=C=CC=CC=CC=C3C=CC=C32)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=C(O)C1=CC=C2C=CC(O)=CC=C3C=CC3=CC=c3ccccc3=CC=C3C=C(C=C(C=[PH](=O)(O)O)CC=CC=C1)N23
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3ccc4ccccc4cccc(n23)=CC=c2ccc3n2C(=C=CC=CC=C=C1)CC=CC=CC=3
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)C2=CC=C2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CC=CC(c2ccccc2)C=C1)=C1C=CC(N(C2=CC=CC=CC=C2)C2=CC=C2)=CC1)N1C=CC=CC=C=CC1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(N(c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)c2ccc(N(C3=C=CCC3)c3ccccc3)cc2)=C1
Invalid SMILES: O=P1(O)(O)=CC=C(c2ccc(N(C3=CC=C=C3)c3ccc(-c4ccc(N(C5=CC=C5)c5ccccc5O)cc4)cc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(N(CC=[PH](=O)(O)O)C2=CC(C3=CC=C=C3)C=CC=C(c3ccc(N(C4=CC=CC4)c4ccccc4)cc3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C3C=CC(=C3)N(c3ccccc3)c3ccc(cc3)N(c3ccccc3)C3=CC=C(C=CC=CC2C=CC=CCC=C=CC=C1)C3
Invalid SMILES: O=[PH](O)(O)=CC(=CC1=C(O)C1=CC(=CC=C1C=CC=C1O)c1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)c1ccccc1
Invalid SMILES: C=CC(=CC(=C1C=CC(O)=C1)c1ccc(N(C2=CC=C2)C2=CC=CC(c3ccc(N(C4=CCC=C4)C4=CC=C=CC4)cc3)C=C2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(c2ccccc2)c2ccccc2)=C1)c1ccccc1)N(C1=CCC=C1)C1=CC=CC1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)C2=CC(c3ccc(N(C4=CC=C4)C4=CC=CC4)cc3)C=C2)C=CCO1
Invalid SMILES: O=P1(O)(O)=CC=C(N(C2=CC=C=C2)c2ccc(N(C3=CC=CC(C4=CC=C4)C3)c3ccccc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=C3)c3ccc(-c4ccc(N(C5=CC=C5)C5=CC=C5)cc4)cc3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1cccc(N(c2ccccc2)c2ccccc2)c1)c1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)C2=CC=CC2)cc1
Invalid SMILES: O=C1C=CC(N(C2=CC=CC=CC=C2)c2ccc(-n3cccc3)cc2)C=CC(=CC(C=[PH](=O)(O)O)c2ccccc2)O1
Invalid SMILES: O=[PH](O)(O)=CC(=C1C=CC(N(c2ccccc2)c2ccc(O)cc2)=C1)c1ccc(N(C2=CC=CC2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3n2C(=CC=C2C=CC2=CC=C=CC1=CC=C1C=CCC=C1)C=CC=CC=3
Invalid SMILES: O=[PH](O)(O)=CC1=CC=c2ccc3n2C(=CC=c2ccc(n2C2=CC=CCC2)=CC=CC=C=CC1)C=CC=CC=c1ccccc1=CC=3
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C3C=CC(=C3)c3ccc(cc3)N3CC3=CC=CCC2=CC=c2ccc3n2C(=CC=CC=CC=C1)C=CCC=3
Invalid SMILES: O=[PH](O)(O)=Cc1cccccccccc2c3oc(c(n(C4=CC=CC4)c4ccc(cc4)c4cccc(c1)c4)=CC=3)=CC=C2
Invalid SMILES: O=[PH](O)(O)=CC1=CC(=C2C=CC(N(c3ccccc3)c3ccccc3)=C2)C2=CC=C(CC2)C2=CC=C(C=CC3(O)C=C=CN1C=CCC=C3)CC=C2
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC=CC=C2)C2=CC=CC2)=C1)c1ccc(N2C=CC=CC2)cc1)C1=CC=C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C2)c2ccc(N(C3=CC=C=C3)c3ccc(C4=CC=CC4)cc3)cc2)=CC1
Invalid SMILES: O=C(O)C(C=C1C=CC(c2cccc(N(c3ccccc3)c3ccc(N(C4=CC=C=C4)c4ccccc4)cc3)c2)=C1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=CCC=C2)C2=CC=CC2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(C=C1C=CC(N(C2=CC=C(C3=CC=C=C3)C=CC=C2)c2ccc(C3=CC=C=C3)cc2)=C1)C1=CC=C=CC1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(C2=CC(C3=CCC=C3)C=C2)N(c2ccc(N(c3ccccc3)c3ccccc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2cccc(N(C3=CC=C=C3)c3ccc(-c4ccc(-c5ccc(C6=CC=C6)cc5)cc4)cc3)c2)=CC1
Invalid SMILES: N#CC(C#N)C=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: N#C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2C=CC=CC=C=CC=C3C=CC=CC=C4C5=CCC=CC6=CC=C(C=CC2=CC=C3O6)N45)=CC1
Invalid SMILES: O=P(=O)(O)(O)C1=CC=C(N2C=C=CC=CCC=CC=c3ccc(n3C3=CC=CC3)=CC=C3C(OC4=CC=CC4)=CC=C32)C=C(O)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccccc2c(ccc3oc(c1)=C3)OC1=CC=C(Oc3ccccc3)N3C(=CC=CCC=CC=2)C=CC=C13
Invalid SMILES: N#CC[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)C=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1)=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC1=CC(=CC=C(OC2=CC=C(Oc3ccccc3)N(C3=CC=C3)CC=C2)C2=CC=C2)O1)N1C=C=CCCCC=CC1
Invalid SMILES: N#CCCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=C(Oc3ccc(N(C4=CC=C=C4)C4=CC=C4)cc3)N3C=CCC=C=CC=C3C1)O2
Invalid SMILES: O=[PH](O)(O)(c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1)n1cccc1
Invalid SMILES: C=CCCC(=CC1=CC(=CC=C2C=C=CCC=C=C=C3CC=CC=C4C=CCC=C5C=CC(=CC=C6OC3=CC=C6O2)N4N5c2ccccc2)O1)C=[PH](=O)(O)O
Invalid SMILES: N#CC(C#N)C=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Oc1cc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)ccc1O
Invalid SMILES: O=P(=O)(O)(O)Oc1cc(N(c2ccccc2)c2ccccc2)ccc1Oc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(C#N)C=CC1=CC=CC=CC(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)=C1
Invalid SMILES: N#CCCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: O=CC[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P1(O)(O)=CC=C(O)C(N(C2=C=C=CC2)C2=CC=C3OC4=CC=C5OC4=CC=CC5=CC=C4C=CC4=CC=CCC=CC=C32)=C1
Invalid SMILES: N#CCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)CC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C=CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC=C3Oc4ccc(cc4)N(c4ccccc4)C2=CC=CC2=CC=CCC=CC=C(C=CC1O)N23
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1)C=C1C=CC=CC1
Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: N#CCCCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)N(c1ccccc1)c1ccc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: N#CCCCCCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CCC=CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccccccc2cccccc3cccc4c(Oc5ccccc5)ccc4oc(ccc4cc(c1)o4)n23
Invalid SMILES: N#CC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)C=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)CC=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1C#P(=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=CC(=C1C=CC=C1)N(C1=CC=CC=CC=C1)C1=CCC=C1)n1cccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1c2c3ccccccccc(n1-3)C=CC=CC=C1C=CC=CC=c3ccc(n31)=CC2)C1=CC=C=C1
Invalid SMILES: O=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=C3OC4=CC=C(Oc5ccccc5)C(=CC=C4)C3=CC=c3ccc4n3C(=CCC=C=C=CC=C1)C=CC=CC=4)O2
Invalid SMILES: O=CC(=O)C(=O)C=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=c3oc4c5n(c(cccccc3=CC=CC=CC=CC1)C=CC=5)C(Oc1ccccc1)=CC=4)O2
Invalid SMILES: N#CC(=CC(=C1C=CC(N(C2=CC=C2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CCC=C1)C1=CC=CC1)C1=CC=C=C1
Invalid SMILES: N#CCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P1(O)(O)=CC=C(O)C(n2cccccccc3c(Oc4ccc(N(C5=CC=C5)c5ccccc5)cc4)ccc2-3)C=C1
Invalid SMILES: O=P(=O)(O)(O)C(=Cc1cc(O)cc2ccc(Oc3ccccc3)c3ccccccc-3n12)N1C=C=CC1
Invalid SMILES: O=P1(O)(O)=CC(C2=CC=C=C2)=CC(N(C2=CC=C(C3=CC=C3)OC3=CC=C(C=CC=C3)C=C2)c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC1=c2ccc(n2N(C2=CC=C2)C2=CC=CC2)=CC=C2OC3=CC=C(C=CC=CC(O)=CC=C2C=C1)C=CC=C3
Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CCC=C1)=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1
Invalid SMILES: O=P(O)(O)#Cc1cc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)ccc1N(c1ccccc1)c1ccccc1

[12:58:02] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=C(O)CCC=Cc1c(CCC=[PH](=O)(O)O)c(-c2ccccc2)cc2c3cc(-c4ccccc4)ccc3n(-c3ccccc3)c12

[12:58:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1cc2c(cc1-c1ccccc1)c1cc(-c3ccccc3)ccc1n2-c1ccccc1

[12:58:15] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1ccc2c(c1)c1cc(-c3ccccc3)ccc1n2-c1ccccc1

[12:58:16] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc(-c3ccccc3)cc2c2ccc(-c3ccccc3)cc21

[12:58:18] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-n2c3ccc(-c4ccccc4)cc3c3cc(-c4ccccc4)ccc32)cc1

[12:58:24] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: O=Cc1c(CCC=[PH](=O)(O)O)c(-c2ccccc2)cc2c3cc(-c4ccccc4)ccc3n(-c3ccccc3)c12

[12:58:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:29] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:58:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1cc(Cl)ccc1n2-c1ccccc1
Invalid SMILES: N#CC(=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1)C(=O)O
Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)c1ccccc1n2-c1ccccc1

[12:58:30] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=Cc2c(n(-c3ccccc3)c3ccccc23)C=C1

[12:58:31] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CBc1ccc2c(c1)c1ccccc1n2-c1ccccc1

[12:58:33] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(-n2c3ccccc3c3ccccc32)cc1

[12:58:38] Explicit valence for atom # 21 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)c1ccc(N2C=CC3=CC4=C2C3=C2C=CC=C[PH]24(=O)O)cc1

[12:58:38] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccc(Cl)cc1

[12:58:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:40] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:58:41] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)PCC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2c(N(c3ccccc3)c3ccccc3)cccc2[nH]1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#CPC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=CC=CC=C2)C2=CC=CC2)cc1)PC=[PH](=O)(O)O
Invalid SMILES: N#CPC1=CC=C(N(c2ccccc2)c2cccc(C=[PH](=O)(O)O)c2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CBC(C#P(=O)(O)O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#C/C(C#P(=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)C=CC=C1)C1=CC(=[PH](=O)(O)O)C=C1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(F)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=C=C2)c2ccccc2)cc1)C(=O)OCC=[PH](=O)(O)O
Invalid SMILES: N#CC1=C=CC=C(N(C2=CC=C(C(=O)O)OC=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=C(O)C1=Cc2ccc(n(-c3ccc(C=[PH](=O)(O)O)cc3)ccccc2=O)C=C1
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1cccc[pH]c(C2=CC=C=C2)cc1
Invalid SMILES: N#CPC(=Cc1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=C/C(=C\c1ccc(O)cc1)c1ccc(N(C2=CC=C=C2)c2ccccc2)cc1
Invalid SMILES: N#CPN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(C2=CC=C2)cc1
Invalid SMILES: N#CC(=CPc1ccc(N(C2=CC=CC=CC=C2)c2ccccc2)cc1)OCC=[PH](=O)(O)O
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C\c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: O=P(O)(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(O)cc2)cc1
Invalid SMILES: O=C(F)c1ccc(N(C2=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: N#Cc1ccc(=[PH](=O)(O)O)cc(N(C2=CC=C2)c2ccccc2)c1
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=C(C(=O)F)C=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cc1)C(=O)O
Invalid SMILES: N#Cc1ccc(N(C2=CC=C(C(=O)O)C=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C(=O)F)C2=CC(=[PH](=O)(O)O)C=C2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C(C=C(O)O)/C=C\C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CCPC1=CC=CC2=CC=CC=CC(=CC=C3C=CC=CC=CC=CP3)N21
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: N#CPc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=Pc1ccccc2ccc(c1)-c1ccc(cc1)C=CC=CC=CN2c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=CC2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(C3=CC(F)=C3)cc2)[PH]2=CC=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(N(C2=CC=CSC=C2)c2ccc(O)cc2)c1
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(C2=CC=C2)cc1
Invalid SMILES: N#CPC(C#P(=O)(O)O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CCC(C=C(C#N)C#N)=Nc1cc(C=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: N#[PH]c1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(F)c1ccc(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)cccco1
Invalid SMILES: N#CPN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: N#[PH]N(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: Nc1cc(C=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=P(O)(O)Cc1ccc(N(c2ccccc2)c2ccc([PH](=O)(O)(O)O)cc2)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)C1=CCC(=[PH](=O)(O)O)C=C1
Invalid SMILES: N#CN(C1=CC=C(C(=O)O)[IH]C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#Cc1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(C=C(CF)C(=O)O)cc2)cc1
Invalid SMILES: O=C(F)C1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=CC2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)OCC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: Nc1cc(PC=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(N(c2ccccc2)c2ccc(O)cc2)c1
Invalid SMILES: N#[PH]C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C2)c2cccc(C=[PH](=O)(O)O)c2)cccco1
Invalid SMILES: N#CPN(c1ccccc2cc(cc1)C=CC=CC=CP2)c1ccc(PC=[PH](=O)(O)O)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(PC=[PH](=O)(O)O)cc1
Invalid SMILES: O=C(F)c1ccc(N(C2=CC=C=C2)c2ccc(PC=[PH](=O)(O)O)cc2)ccc([PH](=O)O)oc1
Invalid SMILES: O=[PH](O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(O)cc2)cc1
Invalid SMILES: N#CBC(=Cc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=C/C(=C\c1ccc(O)cc1)c1ccc(N(PC2=CC=C2)c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)C2=CC(=[PH](=O)(O)O)C=C2)C=CO1
Invalid SMILES: N#CBN(C1=CC=C(c2cccs2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#Cc1cc(C=[PH](=O)(O)O)cc(N(c2ccccc2)c2ccccc2)c1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH](=O)O)C=CC=C1
Invalid SMILES: O=C(F)C1=CC=C(N(c2ccc(PC=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)C=CC=C1
Invalid SMILES: O=C(F)C1=CC(c2ccccc2)=CC=C(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)C=C[IH]1
Invalid SMILES: N#C/C(=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1)PC=[PH](=O)(O)O
Invalid SMILES: O=C(O)C1=CC(C2=CC=C2)=CC=C(N(C2=C=C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Br)cc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccc(C=[PH](=O)(O)O)cc2)c2ccc([PH](=O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N2C3=CC=C(C=CO3)/C=C(/C=[PH](=O)(O)O)PC=C=CC=Cc3ccc2cc3)C=CC=C1
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C/c1ccc(N(C2=CC=CC2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)c1ccc(N(C2=CC=C(C3=CC=C3)C=CC=C2)C2=CC(=[PH](=O)(O)O)C=C2)cc1
Invalid SMILES: N#CPC1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#CC1=CC=C(C=[PH](=O)(O)O)C=CC(N(C2=CC=CC2)c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(COC(=O)c1ccc(N(c2ccccc2)N(c2ccccc2)c2ccccc2)cc1)OCC=[PH](=O)(O)O
Invalid SMILES: O=P(O)(O)c1ccc(N(C2=CC=NC2=[PH](=O)(O)O)c2ccc(O)cc2)cc1
Invalid SMILES: N#CP/C(C=[PH](=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1

[12:58:46] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-n2c3ccccc3c3ccccc32)cc1

[12:58:47] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)cc2)cc1

[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:58:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)c1ccc(-c2cccc(O)c2)cc1
Invalid SMILES: O=Pc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC(c3ccc(C4=CC=C4)cc3)=C2)c2ccc(O)cc2)=C1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccccc1
Invalid SMILES: O=P1(O)(O)=CC=C(N(C2=CC=CC(c3ccc(O)cc3)C=C2)C2=CC=C(c3ccccc3)OC=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC=C3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=C=C1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC=CC3)cc2)=C1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C2)C2=CC(c3ccc(-c4ccccc4)cc3)=CC=C(C=[PH](=O)(O)O)C=C2)cccco1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(N(C2=CC=C(c3ccccc3)OC=C2)c2ccc(C3=CC=C3)cc2)cc1

[12:58:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:58:50] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(N(C2=CCC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccccc3)cc2)cccco1
Invalid SMILES: N#Cc1ccc(C(C=[PH](=O)(O)O)=C2C=CC(N(c3ccccc3)c3ccccc3)=CO2)cc1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccccc1
Invalid SMILES: N#Cc1ccc(C(=Cc2ccc(N(c3ccccc3)c3ccccc3)cc2)C=[PH](=O)(O)O)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=C(O)C=[PH](=O)(O)O)C=C2)c2ccc(C3=CC=C3)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)C=CO1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(C2=CC=CC2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(PC=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C(c3ccccc3)OC=C2)c2ccc(C3=CC=C3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=CC(O)C=C1
Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1)C(F)(F)F
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: N#CC(=Pc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1)C(=O)O
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)c1cccc(O)c1
Invalid SMILES: N#CC(=CC(O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)=C1)C(=O)O
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(C(=O)O)cc3)cc2)C=CO1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=C=CC=C2)C2=CC=C(c3ccccc3)OC=C2)=C1

[12:58:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:51] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(O)cc1)c1ccc(N(C2=CC=C2)C2=CC=CC(c3ccccc3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPC1=CC=C(N(C2=CC=CC=CC=C2)c2ccccc2)OC=C1)c1ccc(C2=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(O)cc1)c1ccc(N(C2=CC=C2)c2ccc(C3=CC=C3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(N(c2ccc(C=[PH](=O)(O)O)cc2)c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)cccco1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=CC=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)C=CO1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(N(C2=CC=C2)c2ccc(N(c3ccccc3)c3ccccc3)cc2)=C1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(=[PH](=O)(O)O)ccc3C3=CC=C3)cc2)cc1
Invalid SMILES: N#CC(=CC1=CC=C(c2ccc(N(c3ccccc3)c3ccc(PC=[PH](=O)(O)O)cc3)cc2)C1)C(=O)C=O
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccc(C3=CC=CC(C4=CC=C=C4)C=C3)cc2)c2cccc(=[PH](=O)(O)O)cc2)C=CO1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(N(C3=CC(=C(O)C=[PH](=O)(O)O)C=C3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=CC(C2=CC=C=C2)C=C1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(CC=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC(c2ccccc2)C=C1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(C2=CC=C=C2)cc1

[12:58:51] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(N(C2=CCC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccccc3)cc2)cc1

[12:58:52] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: O=C(O)CCn1cc(-c2ccc(C=[PH](=O)(O)O)cc3c4cccn4c4ccc(cc4)c=3c2)ccc1=O

[12:58:55] Explicit valence for atom # 24 P, 7, is greater than permitted

Invalid SMILES: O=C1c2ccc3c4c(ccc1c24)C(=O)N(Cc1ccc(O)cc1)C(=[PH](=O)(O)O)C(=O)N(Cc1ccncc1)C3=O

[12:58:55] Explicit valence for atom # 36 P, 7, is greater than permitted

Invalid SMILES: O=Cn1c(=O)c2ccc3c(=O)n(Cc4ccccc4)c(=O)n(Cc4ccncc4)c(=O)c4c(C=CC=[PH](=O)(O)O)cc(c1=O)c2c34

[12:58:56] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:58:56] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:58:56] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:58:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:56] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:58:56] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:58:56] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:58:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:57] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:58:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:57] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:58:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:58] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:58:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:58] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=c1c2ccc3c(=O)n(-c4ccc(O)cc4)c2c3ccn1-c1ccc(C(=CC=[PH](=O)(O)O)C2=CC=C2)cc1
Invalid SMILES: O=c1c2ccc3c(=O)n(-c4ccc(O)cc4)c(=O)c-3c3ccc(c(=O)n1CC=[PH](=O)(O)O)c2cc3P
Invalid SMILES: O=c1c2ccc3c(=O)n(-c4cccc(O)c4)c(=O)c4ccc(c(=O)n1CC=[PH](=O)(O)O)c3c24
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(C(F)(F)F)cn1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CN=C1
Invalid SMILES: N#Cc1cccc(=[PH](=O)(O)O)cc1
Invalid SMILES: O=Cc1cncc(C=CC=[PH](=O)(O)O)c1O
Invalid SMILES: N#Cc1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)(CCCCn1ccnc1)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=c1cccc(C(F)(F)F)cc1C(F)(F)F
Invalid SMILES: O=C1CC=CC(=[PH](=O)(O)O)C=CC(C(F)(F)F)=CO1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(S)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(CCO)CCO)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(CCO)CCCCO)cc1
Invalid SMILES: O=[PH](O)(O)(c1nccn1Cc1c[nH]cn1)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2cccs2)S1
Invalid SMILES: N#CC(C#N)=Cc1ccc(-c2ccc(C=[PH](=O)(O)O)s2)s1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(S)cc1
Invalid SMILES: O=c1ccc(C=[PH](=O)(O)O)c(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=c1cccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc(-c2cccs2)cc1

[12:58:58] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:58:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:58] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:58:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:58:58] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:58:58] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:58:58] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: N#CC1=CC=C(C=[PH](=O)(O)O)c2ccccc2S1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(-c3ccccc3)cc2)c[nH]1
Invalid SMILES: O=[PH](O)(O)=Cc1ccccc1-c1cccs1
Invalid SMILES: O=Cc1ccc(-c2ccc(PC=[PH](=O)(O)O)s2)s1
Invalid SMILES: O=[PH](O)(O)=CPc1sc(-c2cccs2)cc1O
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)N=C(c2ccccc2)S1
Invalid SMILES: O=C(Cl)c1cc(-c2ccc(C3=CC=C3)cc2)sc(=[PH](=O)(O)O)c1Cl
Invalid SMILES: Nc1cc(-c2cccs2)sc1C=CC=[PH](=O)(O)O
Invalid SMILES: O=Cc1ccc(-c2ccc(C=[PH](=O)(O)O)s2)s1

[12:59:00] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:00] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:00] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)sc1c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=c1ccc2c3ccc(c2s1)Sc1ccccc1-3
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)sc1c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2sc3c4ccccc4sc3c2c1

[12:59:01] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)sc1c3ccc(Cl)cc3sc21

[12:59:09] Explicit valence for atom # 21 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc3[nH]c4ccc(-c5ccc([PH](=O)(=O)O)cc5)cc4c3c2)cc1

[12:59:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc(-c3ccccc3)cc2c2cc(-c3ccccc3)ccc21

[12:59:19] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCCCn1c2ccc(-c3ccccc3)cc2c2cc(-c3ccccc3)ccc21

[12:59:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 47 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 48 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 46 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 48 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 47 P, 7, is greater than permitted
[12:59:33] Explicit valence for atom # 49 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 48 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 47 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 47 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 38 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 41 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 41 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 40 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:59:34] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:59:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:35] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:59:35] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:59:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: CC(=CC(C1=CC=C=C(C2=CC=C=CC=C2)C=C1)=C1C=CC(c2ccc(N(C3=CC=CCC3)c3ccc(C4=CC=C4)cc3)cc2)=C1)C=[PH](=O)(O)O
Invalid SMILES: C=CC(C=[PH](=O)(O)O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(-c4ccc(N(C5=CC=C=C=C5)C5=CC=CC=CC5)cc4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: CC(=CC1=CC1=CC=c1ccc(=CC=C2C=CC2=CC=CC=C2CC2=CC=C2C=CC(=O)N2C2=CCC=C2)n1C=C=CC1=C=CCS1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC2=CC=c2ccc3n2N2C(=CC=C=CC=CC1)CC=CC=C2CCC=CC=C1C=CC1=CC=3
Invalid SMILES: O=C(O)C1=COC(=CC(=CC=[PH](=O)(O)O)C2=CC(C3=CC=CCC=C3)C=CC=C(c3ccc4n5c(ccccccc35)C4)C=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=CCCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC2=CC=c2ccc3n2N(C=C=CC=c2ccoc2=CC=C2C=CC2=CC=3)CC=CC=CC=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3n2C(=CC=C2CC=CC(N(C4=CC=C4)C4=CC=CC4)=CC=C2C=CC1)C=CC=CC=3
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC2=CC3=CC=CCC=CC=C4C=CC(C=C5C=CC5=CC=C21)N43)C1C=CC=C1)N(C1=C=C=CC=C1)C1=CC=CC1
Invalid SMILES: CC=C1C=C=CC=CC=C2CC=CC=C3C=CC=CC=C4C=CC(C=CC=C5C=CC5=CC=c5ccc(n52)=CC=C2C=C2C=C(C=[PH](=O)(O)O)C=C1)N34
Invalid SMILES: C=CC(=Cc1c(=CC=C2C=C=C=C2)cccccc2n3c(ccc3ccc3cccccc4ccc(ccc5ccc15)n34)=CCC=C2)C=[PH](=O)(O)O
Invalid SMILES: CC(=CC1=CC1=CC=c1ccc2n1C=C=CC=CCC=C=c1ccc(n1-c1ccccc1)=CC=C1C=CC1=CC=C1C=CC1=CC=2)C=[PH](=O)(O)O
Invalid SMILES: CC(=CC(C1=CC=C(c2ccc(N(C3=C=CCC=C=C3)C3CC=C=C=CC3)cc2)C1)=C1C=CC=C(c2cccc(C3=CC=CC3)c2)C=C1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc-2ccc2ccc3n2c(ccc2ccc(cccccc4ccc1C=C=C4)n2C1=CC=C1)C=CCC=C1C=CC1=CC=3
Invalid SMILES: CCC(=CC(C1=CC2C=C=CC=CC=CN(C3=C=CCC=C3)c3ccc(cc3)-c3ccc(cc3)C(=C2)C=C1)=C1C=CC(C(=O)O)=CO1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC1=CC(=C2C=CC(N(C3=CC=C(c4ccccc4)C=CC=C3)c3ccc(N(C4=CCC=C4)c4ccccc4)cc3)=C2)C=CC=C=C=C1
Invalid SMILES: O=[PH](O)(O)=CC=CC1=C(O)C1=CC=c1ccc2ccc3ccc3ccc3ccc3ccc3ccc(cccccccccn12)n3C1=CCC=CC1
Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccc(C=[PH](=O)(O)O)cc5)cc4)cc3)cc2)cc1
Invalid SMILES: C=CC=C=CC(=CC1=CC1=Cc1cccc2ccc3c(ccc4c(ccc(N(C5=CC=C=C5)C5=CC=C5)ccccn12)CO4)C=C3)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC1C=C=CC=CN(C2=CC=C=CCC=C2)c2ccc(cc2)-c2ccc(cc2)N(c2ccccc2)c2ccc(cc2)C2=CCOC(=C1)C=C2
Invalid SMILES: CC(=CC1=C2C=CC(=C2)c2ccc(cc2)N(C2=CC=C2)c2ccc(cc2)N(C2=CC=CCC2)C2=C(C=C=C2)CC=CC=CC=C=C1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=CCC=C=C3)c3ccc(-c4ccc(-c5ccc(C6=CC=C6)cc5)cc4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CC(c2ccc(C3=CC=CCC3)cc2)C=CC1)=C1C=CC(c2ccccc2)=C1)c1ccccc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C(=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1)CC(=O)O
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C=O)C(=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1)CCC=O
Invalid SMILES: N#CC(C(=O)C=O)C(C=O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C4=CC=C(c5ccccc5)C=CC3=CC=C(c3ccccc3)C=C4)cc2)cc1
Invalid SMILES: N#CC(C=O)=CC(C=O)=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)c2)cc1
Invalid SMILES: N#CC(C#N)C(=CC1=CC=C(c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)C1)C(=O)C=O
Invalid SMILES: O=CCC(C=O)=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=CC=[PH](=O)(O)O)cc4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccc(N(C3=CC=CC(c4ccc(C5=CC=C5)cc4)C=C3)c3ccccc3)cc2)S1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=C=C3)c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=CC1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccc(C=O)cc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4C=O)cc3)cc2)cc1
Invalid SMILES: N#CC(=CC1=CC=C(c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)C1)C(=O)C=O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2O)cc1
Invalid SMILES: O=CCOc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)c2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccccc2)cc1N(c1ccc(-c2ccccc2)cc1)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3cccc(-c4ccc(F)cc4)c3)cc2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(C2=CC=C3C=CC(c4ccccc4)=CC=C(C=C2)N3c2ccc(-c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=NN(c2ccccc2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccccc2C(F)(F)c2ccc(F)cc21

[12:59:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Cc2cc(Br)ccc21

[12:59:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:36] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(N2c3ccccc3Cc3ccccc32)C=C(Br)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C3=CC2=C(Br)C=C3)cc1

[12:59:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:36] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(O)c2c1ccc1cccnc12
Invalid SMILES: O=[PH](O)(O)=Cc1ccnc2cc(Cl)ccc12

[12:59:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:59:45] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1cc2c3ccccc3sc2c2c1[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2c3sc4ccccc4c3ccc21

[12:59:45] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc3c(cc21)sc1ccccc13

[12:59:48] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:59:48] Explicit valence for atom # 33 P, 7, is greater than permitted

Invalid SMILES: O=C=CC1C=C2C(=C1c1c3cc(n1CC[PH](=O)(O)(O)O)-c1c-3n(CCCP(=O)(O)O)c3ccccc13)N2CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3ccc-3c(N3C=CCC=C3)c3cc4n(CCC[PH](=O)(O)(O)O)c3c-4c21

[12:59:48] Explicit valence for atom # 44 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C13CC=C=CC(C(NCCP(=O)(O)O)=C1c1[nH]c4ccccc4c1-2)N3CCC[PH](=O)(O)(O)O

[12:59:50] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:59:50] Explicit valence for atom # 40 P, 7, is greater than permitted

Invalid SMILES: O=C1c2c(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c2[nH]c2ccccc23)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=c1c2ccc(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c4ccc4n(CCCP(=O)(O)O)c23)n1CCC[PH](=O)(O)(O)O

[12:59:50] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1C(NCC[PH](=O)(O)(O)O)=C1c1[nH]c3ccccc3c1-2

[12:59:50] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CC[PH](=O)(O)(O)O)C3=CC3)c3cc4n(CCCI(=O)(O)O)c3c-4c21

[12:59:51] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:59:51] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:59:52] Explicit valence for atom # 29 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1C=CC(=C3C=CC=C4C2=C3N4CCC[PH](=O)(O)(O)O)N(C2=C=C2)C1
Invalid SMILES: NC1=C2C(NCC[PH](=O)(O)(O)O)=C2c2[nH]c3ccccc3c2-c2c1c1ccccc1n2CCCP(=O)(O)O
Invalid SMILES: Cn1c2ccccc2c2c1c1c3ccccc3n(C=O)c1c1c3ccccc3n(P(=O)(=O)(O)O)c21

[12:59:52] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:59:52] Explicit valence for atom # 25 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(C(=C3CC=N3)N1CCC[PH](=O)(O)(O)O)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CCC3=C1C(NCC[PH](=O)(O)(O)O)=C3c1[nH]c3ccccc3c1-2

[12:59:52] Explicit valence for atom # 38 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C1C=CC=CC(=N3)N1CCC[PH](=O)(O)(O)O

[12:59:54] Explicit valence for atom # 27 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C=CC=C1C(=C3CN3CCC[PH](=O)(O)(O)O)n3c1c-2c1ccccc13

[12:59:54] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c4c(c5c(n4CCC[PH](=O)(O)(O)O)C=C5)c4c(c5ccccc5n4CCCP(=O)(O)O)c31)CC=C2

[12:59:56] Explicit valence for atom # 27 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CCc3c-2c2c(n3CCC[PH](=O)(O)(O)O)C=CC(C=C2)C1=C1CN1CCP(=O)(O)O

[12:59:58] Explicit valence for atom # 33 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=C3C=NC(S3)C2=C(C2=CCC=C2)N1CCC[PH](=O)(O)(O)O

[12:59:58] Explicit valence for atom # 30 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(c21)C(=C1C=CC=C1)N4CCC[PH](=O)(O)(O)O)C1C=C=C1C1(O)C=CC1=N3

[12:59:59] Explicit valence for atom # 37 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1c3nc(C4C=CC=C4)c-2c(c3=CC2=CC=C2)n1CCC[PH](=O)(O)(O)O

[13:00:00] Explicit valence for atom # 38 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(c3[nH]c4ccccc4c3-2)C2(C=CC=C2)N1CCC[PH](=O)(O)(O)O

[13:00:00] Explicit valence for atom # 22 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CC[PH](=O)(O)(O)O)C=CC4)c3[nH]c4ccccc4c3c21

[13:00:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc2c(c1)[nH]c1c3ccccc3c3c4ccccc([nH]c23)c41

[13:00:01] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:00:01] Explicit valence for atom # 20 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(C3=CC(=N1)N3CCC[PH](=O)(O)(O)O)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c3c4c(c(c5c(c1=3)=C5NCC[PH](=O)(O)(O)O)NCC=CC=CC=2)c1ccccc1n4CCCP(=O)(O)O

[13:00:02] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CCC[PH](=O)(O)(O)O)C=CC4)c3[nH]c4ccccc4c3c21

[13:00:03] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:00:03] Explicit valence for atom # 25 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c1c1c3ccccc3n(CC[PH](=O)(O)(O)O)c1c1c3ccccc3n(CCCP(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(ccn4CCC[PH](=O)(O)(O)O)c21)C1=CC=C(C=CC1)N3C1CCCC1

[13:00:04] Explicit valence for atom # 22 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CC[PH](=O)(O)(O)O)CC=C4)c3[nH]c4ccccc4c3c21

[13:00:04] Explicit valence for atom # 41 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCC=C1NC1=C1c2c(n(CCCP(=O)(O)O)c3ccccc23)C2=C(C=C2C2CCCC=N2)N1CCC[PH](=O)(O)(O)O

[13:00:06] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:00:06] Explicit valence for atom # 21 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ncccc2c2cccc3c(NCC[PH](=O)(O)(O)O)c-3c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCN1C2=CC=Cc3c1c2c1c(c3N(CC[PH](=O)(O)(O)O)C2C=CC=C2)c2ccccc2n1CCCP(=O)(O)O

[13:00:06] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:00:06] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:00:06] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:00:06] Explicit valence for atom # 28 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CCP(=O)(O)O)C3=CCC=C3)c3c4c(c21)C(=CC=C3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(ccn3CCC[PH](=O)(O)(O)O)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CCC[PH](=O)(O)(O)O)CC=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccc3cc2c2cc(C4C=CC=C4)c(cc21)n(CC[PH](=O)(O)(O)O)c1ccc3=1

[13:00:06] Explicit valence for atom # 25 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C(=C1C=CC1)N(CCC[PH](=O)(O)(O)O)C1=C(C=CCC=C1)c1[nH]c3ccccc3c1-2

[13:00:08] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:00:08] Explicit valence for atom # 35 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c4c5c(n(CCC[PH](=O)(O)(O)O)c4c3n(CCCP(=O)(O)O)c2c2ccccc21)C5
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ncccc5c4c21)C(=C1C=N1)N3CCC[PH](=O)(O)(O)O

[13:00:09] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCC=NC1=c2cc3n(CCC[PH](=O)(O)(O)O)c2=C3c2c(c3ccccc3n2CCCP(=O)(O)O)-c2ncccc21

[13:00:09] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:00:10] Explicit valence for atom # 15 P, 7, is greater than permitted

Invalid SMILES: O=c1c2c3[nH]c4ccccc4c3c3c(c4ccccc4n3CCCP(=O)(O)O)c2[nH]c2ccc-2n1CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCN1C(=C2CN2CCC[PH](=O)(O)(O)O)c2c1c1c(c3c4ccccc4n(CCCP(=O)(O)O)c23)N=CCC=C1

[13:00:10] Explicit valence for atom # 44 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCN1C2=CC=CC3C(=C4C(=C41)c1c2c2ccccc2n1CCCP(=O)(O)O)C1=NC(CCCC1)N3CCC[PH](=O)(O)(O)O

[13:00:10] Explicit valence for atom # 29 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCN1C(=C2C=CCC=C2)C1=C1C=CCC=Cc2c3c1n(CCC[PH](=O)(O)(O)O)c2-c1c-3n(CCCP(=O)(O)O)c2ccccc12

[13:00:11] Explicit valence for atom # 27 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)[PH](=O)(O)(O)CC=CN3

[13:00:13] Explicit valence for atom # 27 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)[PH](=O)(O)(O)CCN3

[13:00:13] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 31 P, 7, is greater than permitted

Invalid SMILES: O=C1c2c(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c2[nH]c2ccccc23)N1CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(c3ccccc3N(CCCC[PH](=O)(O)(O)O)SN1)c1[nH]c3ccccc3c1-2

[13:00:14] Explicit valence for atom # 26 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCN1C(=C2C=CC=C2)c2c1c1c3ccccc3n(CC[PH](=O)(O)(O)O)c1c1c3ccccc3n(CCCP(=O)(O)O)c21

[13:00:15] Explicit valence for atom # 35 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3ncc(c4[nH]c5ccccc5c4c21)c1c3n1CCC[PH](=O)(O)(O)O

[13:00:16] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:00:16] Explicit valence for atom # 28 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c1c1c3ccc4c(ccn4CC4=CCC=C4)c1n(CCC[PH](=O)(O)(O)O)c32
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC(C3=C4C=C=CC3N4CC[PH](=O)(O)(O)O)=C(CN1)c1ccccc1-2

[13:00:16] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:00:17] Explicit valence for atom # 32 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCN1c2c(c3c(c4ccccc4n3CCC[PH](=O)(O)(O)O)c3c2c2ccccc2n3CCCP(=O)(O)O)C12C=CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=Cc1c-2c(C2=CC=CC3N=CC23)n2c1P(=O)(O)(O)(O)CCC2

[13:00:17] Explicit valence for atom # 15 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCNC1=C2C1=C(NCC[PH](=O)(O)(O)O)c1c(n(CCCP(=O)(O)O)c3ccccc13)-c1c2[nH]c2ccccc12

[13:00:19] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCCCn1c2ccc3c2c2c(ccn2CCC[PH](=O)(O)(O)O)c2c(c4ccccc4n2CCCP(=O)(O)O)c31

[13:00:20] Explicit valence for atom # 24 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2cccc3c(C=C4C=CC5C(=C4)N5CC[PH](=O)(O)(O)O)c(c1-3)-c1c-2c2ccccc2n1CCCP(=O)(O)O

[13:00:21] Explicit valence for atom # 43 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CCC[PH]3=CC=C3)C3=CCC=C=C3)c3c4c(c21)C(=CC=CC3)N4CCC[PH](=O)(O)(O)O

[13:00:21] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:00:21] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:00:21] Explicit valence for atom # 34 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3[nH]c4c(n(CCC[PH](=O)(O)(O)O)c5ccccc5c3c3[nH]c5ccccc5c3c21)=CC=4
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=CC1C=N1)N3CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1NC3=C(CC=CC3)C2=C(C2=CC=C2)N1CCC[PH](=O)(O)(O)O

[13:00:21] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:00:21] Explicit valence for atom # 8 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)CCNC1=C2C(NCC[PH](=O)(O)(O)O)=C2c2[nH]c3ccccc3c2-c2c1c1ccccc1n2CCCP(=O)(O)O
Invalid SMILES: Nc1c2c(NCCC[PH](=O)(O)(O)O)c3c-2n2c(cccc4c5ccccc5n(CCCP(=O)(O)O)c4c1-3)CCCCC2

[13:00:22] Explicit valence for atom # 36 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=CC1C=N1)N3CCC[PH](=O)(O)(O)O

[13:00:22] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1cc(c1NCC[PH](=O)(O)(O)O)-c1[nH]c3ccccc3c1-2

[13:00:22] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c1c1c4ccccc4n(CCC[PH](=O)(O)(O)O)c1c1c4ccccc4n(CCCP(=O)(O)O)c31)C=C2

[13:00:23] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:00:23] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)CN3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c4c(ccn4CCC[PH](=O)(O)(O)O)c4c(c5ccccc5n4CCCP(=O)(O)O)c31)CC=C2

[13:00:23] Explicit valence for atom # 24 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1c3c-2c(n1CCC[PH](=O)(O)(O)O)C(=C1N=C1C1C=CC=CC1)C=CC=C3

[13:00:24] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:00:24] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:00:24] Explicit valence for atom # 36 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=C1CC=NS1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C(N(CCO)C1=CC1)=C1C(NCC[PH](=O)(O)(O)O)=C1c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2cc3c1=C2c1c(c2ccccc2n1CCCP(=O)(O)O)C=C=C1CN(CC[PH](=O)(O)(O)O)C=31

[13:00:25] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:00:25] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1NC1=C1C2=C(C2=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccc2c2c1c1c(NCC[PH](=O)(O)(O)O)c-1cc1c3ccccc3n(CCCP(=O)(O)O)c12

[13:00:25] Explicit valence for atom # 34 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c4c5c(c6c(c(c(c21)C=CP(O)CC5)n3CCC[PH](=O)(O)(O)O)=CCC=6)N4

[13:00:26] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:00:26] Explicit valence for atom # 40 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1C=NC3C=CC=C4NC4=C4C2=C(C1=CC=C3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(c21)=C4N(CCP(=O)(O)O)C1=CC=C1)C=C=CC1C=3N1CC[PH](=O)(O)(O)O

[13:00:27] Explicit valence for atom # 39 P, 7, is greater than permitted

Invalid SMILES: Nc1c2cccc3n(CCCP(=O)(O)O)c-2c-3c2c(c3ccccc3n2CCCP(=O)(O)O)c2c1c1c(n2C[PH](=O)(O)(O)O)C1

[13:00:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:30] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:00:30] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:00:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:30] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:00:30] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:00:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:30] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:00:30] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:00:30] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:00:30] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:00:30] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:00:30] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)C=C1
Invalid SMILES: N#CC1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(c2ccccc2)=CS1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)S1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=C(C(=O)O)C=C1
Invalid SMILES: N#Cc1ccc(C2=CC(=CC=[PH](=O)(O)O)C=C2)cc1
Invalid SMILES: N#CC1=CC=CC(c2ccc(C=[PH](=O)(O)O)cc2)=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2=CC=C(c3ccccc3)C=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CC(c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C2=CC=C=CC=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=c1ccc(C(F)(F)F)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(C2=CC=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: N#CC1=CC=C(C2=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(C#CC=[PH](=O)(O)O)cc2)cc1)C(=O)O
Invalid SMILES: O=P1(O)(O)=CC=C(c2ccc(-c3ccccc3)cc2)C=C1
Invalid SMILES: N#CC1=CC=C(C2=CC=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc([IH]C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#Cc1ccc(=[PH](=O)(O)O)cc(-c2ccccc2)c1
Invalid SMILES: N#Cc1ccc(-c2ccc(=[PH](=O)(O)O)cc(C(=O)O)c2)cc1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C2=CC=C(C(F)(F)F)C=CC=C2)C=C1

[13:00:33] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:00:33] Explicit valence for atom # 30 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=C=C1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)C1C=CCC(=C1)N3CCC[PH](=O)(O)(O)O

[13:00:34] Explicit valence for atom # 30 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCC[PH](=O)(O)(O)O

[13:00:36] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)n1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13

[13:00:39] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13

[13:00:39] Explicit valence for atom # 26 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=CC1

[13:00:41] Explicit valence for atom # 27 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=CC1

[13:00:45] Explicit valence for atom # 36 P, 7, is greater than permitted

Invalid SMILES: O=C(CCCn1c2ccccc2c2cc3c(cc21)Nc1ccccc1N3CCCCCO)OCCC=[PH](=O)(O)O

[13:00:45] Explicit valence for atom # 29 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)C1C=CC(=C1)N3CCC[PH](=O)(O)(O)O

[13:00:46] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)On1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13

[13:00:47] Explicit valence for atom # 31 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCCC[PH](=O)(O)(O)O

[13:00:48] Explicit valence for atom # 25 P, 7, is greater than permitted

Invalid SMILES: N#CC(O)=Cn1c2ccccc2c2cc3c(cc21)c1ccccc1n3P(=O)(=O)(O)O

[13:00:52] Explicit valence for atom # 30 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)-c1cccc(c1)N3CCC[PH](=O)(O)(O)O

[13:00:53] Explicit valence for atom # 26 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=C1

[13:00:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:54] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=[PH](O)(O)=CC=CCc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12

[13:00:54] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12

[13:00:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:00:55] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccc3c4ccccc4[nH]c3c21
Invalid SMILES: O=[PH](O)(O)=CCn1c2c(c3ccccc31)C=Cc1ccccc1N2
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccccc2c2c3ccccc3[nH]c21

[13:00:55] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)[nH]c1c3ccccc3[nH]c21

[13:00:55] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)Oc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12

[13:00:56] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)Oc1ccc2c(c1)[nH]c1c3ccccc3[nH]c21

[13:01:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCCCCCO

[13:01:14] Explicit valence for atom # 26 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c4ccccc4n(CC[PH](=O)(O)(O)O)c3cc21

[13:01:18] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:01:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc4n(C5=CC=CC5)cccc3-4)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(-c2ccc(N(C3=CC=C(c4ccccc4)PC=C3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(N4C=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC=C1)c1ccc(N(C2=CC=C2)c2ccc(-c3ccccc3)cc2)cc1)c1ccccc1
Invalid SMILES: O=P(O)(O)#CC(CO)=C1C=CC(c2ccc(N(C3=CC=C(C4=CC=C(c5ccccc5)CC=C4)CC=C3)c3ccccc3)cc2)=C1

[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccccc2)cc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccc4cc3-c3ccccc3N4)cc2)c2c1=CC=2
Invalid SMILES: O=[PH](O)(O)=CC(=C[IH]c1ccc(-c2ccc(-c3cccc(C4=CC=C=C4)c3)cc2)cc1)N1C=CC=C(O)C1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=CC1)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(N4C=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2c1[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1c2ccccc3n4c(ccc4ccc4ccc-4ccc12)=CC=CCC=CC=3)NC1=CC=CC1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)cc1)c1ccccc1

[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#CC1C=C2C(=CC=C3C=CC3=CC=CC=CC=NSN1)N(C1=CC=C1)c1ccc(cc1)-c1ccc2cc1
Invalid SMILES: O=P(O)(O)#CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCPCOC(=CC=C1C=CC(N(c2ccccc2)c2ccc3cccccc2-3)=C1)c1ccc(N=C2CC=CC2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPC1=CC=C(c2ccc(N(C3=CC=C3)C3=CC=C3)cc2)OCC=C1)c1ccc(N(C2=CC=C=C=C2)c2ccccc2)cc1
Invalid SMILES: O=P(O)(O)#CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4cc3-c3ccccc3N4)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)c2c1C=C2
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(-c2ccc(N(C3=CC=C=C(C4=C=CC=C4)C=C3)C3=CC=CC3)cc2)cc1)C1=CC=C=C1

[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC2=CC=C(C=C1)N1C=CCC=CC=CC=C21
Invalid SMILES: O=C(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(N(C4=CC=C4)C4=CC=CCC=C4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc2ccc2ccccc3cccccc(ccc4ccc4cccccc1=CC1=CC=CC=CC1)n32
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)c2ccccc12
Invalid SMILES: O=C(CCCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21)OCC#P(=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3cc(Cl)ccc3Sc3ccc(Cl)cc32)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3ccccc3Sc3ccccc32)cc1
Invalid SMILES: O=[PH](O)(O)=C1Sc2ccccc2N(c2ccccc2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2c3ccccc3Sc3ccccc32)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)Sc1ccccc1N2c1ccccc1

[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc2c(c1)Sc1ccccc1N2c1ccc(Br)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)N(c1ccccc1)c1ccccc1S2
Invalid SMILES: O=[PH](O)(O)=CSc1ccc2c(c1)N(c1ccccc1)c1ccccc1S2
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)Sc1ccccc1N2c1ccc(F)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)Sc1cc(Cl)ccc1N2c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C(Cl)=C(Cl)C(Cl)=C1Cl
Invalid SMILES: O=[PH]1(O)(O)SC(C(F)(F)F)=C1Cl
Invalid SMILES: O=P(=O)(O)(O)c1ccc(C(F)(F)F)cc1
Invalid SMILES: O=[PH](O)(O)=C1SC(Cl)=C1Cl
Invalid SMILES: N#Cc1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=C1SC(C(F)(F)F)=C1F
Invalid SMILES: O=[PH](O)(O)=C1SC(F)(F)C(F)(F)C1(F)F
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C(F)(F)F)=C1
Invalid SMILES: O=[PH](O)(O)=C1C(F)C(F)(F)C1(F)F
Invalid SMILES: O=[PH](O)(O)=C1C(F)C(F)(F)C(F)(F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)CCN1C=CC=CC1
Invalid SMILES: O=P(=O)(O)(O)c1ccncc1
Invalid SMILES: O=P(=O)(O)(O)CCNc1ncc[nH]1
Invalid SMILES: O=C(O)[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)F)NC(F)(F)C(F)(F)C(F)(F)C(F)(F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)c1cc[nH]c1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(F)C(F)(F)C(F)(F)C(F)(F)F)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(Cl)C(Cl)=C1Cl
Invalid SMILES: O=P(=O)(O)(O)c1ccc(Cl)cc1
Invalid SMILES: O=P(=O)(O)(O)Cn1ccnc1
Invalid SMILES: O=C(O)Nc1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=[N+]([O-])c1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(N(F)CC(F)(F)F)C=C1
Invalid SMILES: Cn1cncc1P(=O)(=O)(O)O
Invalid SMILES: O=[PH](=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1cn(C(F)(F)F)cn1
Invalid SMILES: O=P(=O)(O)(O)c1ncc[nH]1
Invalid SMILES: O=P(=O)(O)(O)c1c[nH]cn1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(Nc2ncc[nH]2)cc1
Invalid SMILES: O=P(=O)(O)(O)CCN(CCO)Cc1nccn1C(F)(F)F
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccncc1
Invalid SMILES: O=[PH](O)(O)=C1C=CN=C1
Invalid SMILES: O=P(=O)(O)(O)CCN1CC=CC1
Invalid SMILES: O=P(=O)(O)(O)CCn1ccnc1
Invalid SMILES: N#CN(F)C1=C(P(=O)(=O)(O)O)C=C1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C=C/C=C/C(F)(F)F)N1
Invalid SMILES: O=P(=O)(O)(O)CNc1ncc[nH]1
Invalid SMILES: O=P(=O)(O)(O)NCCNc1ncc[nH]1
Invalid SMILES: O=P(=O)(O)(O)c1ccccc1
Invalid SMILES: O=C(O)NC1=C(CP(=O)(=O)(O)O)C=C1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1nccn1C(F)(F)F
Invalid SMILES: N#Cc1ccc([PH](=O)(O)(O)O)cc1
Invalid SMILES: O=CN(F)c1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)F)NC(F)(F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)c1cn(C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)C(F)(F)C(F)(F)F)cn1
Invalid SMILES: N#Cc1ccc(CP(=O)(=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccncc1
Invalid SMILES: O=P(=O)(O)(O)c1cc[nH]c1C(F)(F)F
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)F)N=C1
Invalid SMILES: O=[PH](O)(O)(O)CCN1CC=CC1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2cccc(F)c2)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)C(F)(F)C(F)(F)F)N1
Invalid SMILES: Nc1[nH]c(OCP(=O)(=O)(O)O)nc1C(F)(F)F
Invalid SMILES: O=P(=O)(O)(O)c1nc(C(F)(F)F)c[nH]1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccncc1
Invalid SMILES: O=CN(F)C1=C(P(=O)(=O)(O)O)C=C1
Invalid SMILES: O=P(=O)(O)(O)C1=CC=C1
Invalid SMILES: O=P(=O)(O)(O)c1ccccn1
Invalid SMILES: O=C1CCCN1CCP(=O)(=O)(O)O
Invalid SMILES: O=C(CCNc1ncc[nH]1)[PH](=O)(O)(O)Cl
Invalid SMILES: O=P(=O)(O)(O)C1=C(c2ccccc2Nc2cc[nH]c2)C=C1
Invalid SMILES: N#CC1=C(P(=O)(=O)(O)O)C=C1
Invalid SMILES: O=P(=O)(O)(O)CCN1CCOCC1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1nc(O)c(C(F)(F)F)n1C(F)(F)F
Invalid SMILES: Cn1nccc1CN(CCO)CP(=O)(=O)(O)O
Invalid SMILES: O=C(CCN1CC=CC1)[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1ccc(Br)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)c1ccc(C(F)(F)C(F)(F)F)cc1
Invalid SMILES: O=C(c1ccccc1)[PH](=O)(O)(O)O
Invalid SMILES: N#Cc1ccc(C[PH](=O)(O)(O)O)cc1
Invalid SMILES: O=C1NC(C(F)(F)F)=C(P(=O)(=O)(O)O)C1(F)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccccc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc[nH]1
Invalid SMILES: O=P(=O)(O)(O)CCNc1nc(C(F)(F)F)c[nH]1
Invalid SMILES: O=[PH](O)(O)(O)C(O)=C1N=CC(O)=N1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(F)=C1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=N/C=C\c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1
Invalid SMILES: O=[PH]1(O)(O)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccccc1O
Invalid SMILES: O=P(=O)(O)(O)c1cc(O)c(O)c(O)c1
Invalid SMILES: O=[PH](O)(O)=C1C=C=C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=Cc1cc(O)c(O)c(O)c1
Invalid SMILES: O=P(=O)(O)(O)NCc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=C1C(F)=C=C=C1F
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C(Cl)=CC(Cl)=C1Cl
Invalid SMILES: O=[PH](O)(O)=C1C=CC=CC1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccccc1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccccc1O
Invalid SMILES: O=Cc1c(O)c(O)c(O)c(O)c1P(=O)(=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1cc(O)ccc1O
Invalid SMILES: O=P(=O)(O)(O)Nc1c(F)c(F)c(F)c(F)c1F
Invalid SMILES: O=[PH](O)(O)=C1C=CC(F)(F)C=C1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(F)cc1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ncccc1O
Invalid SMILES: O=[PH](O)(O)(O)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=N1

[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2cccs2)s1
Invalid SMILES: O=P(=O)(O)(O)C=Cc1ccc(-c2cccs2)s1

[13:01:20] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C(=Cc1ccc(-c2cccs2)s1)c1cccs1

[13:01:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:22] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=C(O)C(=C/C=C\c1ccc(-c2cccs2)s1)P(=O)(=O)(O)O

[13:01:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCNc1sc(-c2cccs2)cc1C(F)(F)F

[13:01:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C(=Cc1ccc(-c2cccs2)s1)c1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccs2)s1

[13:01:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CC=Cc1ccc(-c2cccs2)s1

[13:01:24] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1cccs1)c1cccs1

[13:01:24] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1c(F)sc(-c2cccs2)c1F

[13:01:25] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:01:25] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C(=Cc1ccc(-c2cccs2)s1)P(=O)(=O)(O)O
Invalid SMILES: O=C(O)c1cc(-c2cccs2)sc1P(=O)(=O)(O)O

[13:01:25] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:01:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=S(=O)(O)c1sc(-c2cccs2)c(P(=O)(=O)(O)O)c1Cl
Invalid SMILES: O=[PH](O)(O)(F)c1ccc(-c2cccs2)s1

[13:01:26] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:01:26] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: O=C(F)c1ccc(C(=C/C=C\C=C\C(F)(F)F)[PH](=O)(O)(O)O)cc1
Invalid SMILES: Nc1sc(-c2cccs2)c(C(=O)O)c1P(=O)(=O)(O)O

[13:01:26] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1sc(-c2sc(F)c(F)c2F)c(F)c1F

[13:01:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:26] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCNc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2cccs2)s1

[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(-c2cccs2)cc1
Invalid SMILES: O=P(=O)(O)(O)/C=C/c1ccc(-c2cccs2)s1

[13:01:27] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 13 C, 4, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 14 C, 4, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 14 C, 4, is greater than permitted
[13:01:27] Explicit valence for atom # 13 C, 4, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 8 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C(=C/C=C\c1ccc(-c2cccs2)s1)[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)CCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C1c2ccccc2-c2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Cc2ccccc21
Invalid SMILES: O=[PH]1(O)(O)c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccc(Br)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Sc2cc(Br)ccc21
Invalid SMILES: O=P(O)(O)CCN1c2ccccc2[CH2+]c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=c1[nH]c2ccccc2c2ccccc12
Invalid SMILES: O=P(O)(O)CCN1c2ccc(Br)cc2[CH2+]c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=C1Nc2ccccc2[SiH-]c2ccccc21
Invalid SMILES: O=[PH](O)(O)=NCN1c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(O)(O)CCN1c2ccc(Br)cc2[CH2+]c2ccc(Br)cc21
Invalid SMILES: O=P(O)(O)CCN1c2ccccc2[CH2+]c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Sc2ccccc21
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2cccc3cccc1c23
Invalid SMILES: O=C1c2ccccc2[PH](=O)(O)(O)c2ccccc21

[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:28] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCCOc1cc2c(c3ccccc13)Sc1ccc(O)cc1S2
Invalid SMILES: O=[PH]1(O)(O)c2ccccc2Sc2c1sc1ccccc21
Invalid SMILES: O=[PH](O)(O)=C1c2c(sc3ccccc23)-c2sc3ccccc3c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2cc(Br)ccc2c2c3cc(S(=O)(=O)O)ccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3ccccc3ccc21
Invalid SMILES: Cn1c2ccccc2c2cc(C=CC=[PH](=O)(O)O)ccc21

[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:32] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1cccc(N(c2ccccc2)c2ccccc2)c1
Invalid SMILES: O=P(=O)(O)(O)CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)CP(=O)(=O)(O)O
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1cccc(N(c2ccccc2)c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)(O)CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(CCCP(=O)(=O)(O)O)N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(CCCP(=O)(=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(C#N)=C(CP(=O)(=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)CC1=C(N(c2ccccc2)c2ccccc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-n2c3ccccc3c3ccccc32)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-n2c3ccccc3c3cc(Br)ccc32)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc2c1c1ccccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)(O)C1CN2CCC(CCO)(CC2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc3c4c(c2)CCCN4CCC3)s1
Invalid SMILES: O=[PH]1(O)(O)CN2CCC(CCO)(CC2)c2cc(-c3cccs3)ccc21
Invalid SMILES: O=P(=O)(O)(O)C1CCCN2CCCC3=C2C(O)(c2cccs2)CCN3CC1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2cc3c4c(c2)CCCN4CCC3)s1

[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH]1(O)(O)CCC2=C(C1)c1ccc(cc1)N2CCC1=CC=C1
Invalid SMILES: O=P(=O)(O)(O)C1C=CC2CCN(C1)C(N1CCC3=CCC1=C3)C2
Invalid SMILES: O=[PH]1(O)(O)CN2CCC(O)(CCO)CC2c2cc(-c3cccs3)ccc21

[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:33] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1cc2c3c(c1)CCCN3CCC2)c1cccs1
Invalid SMILES: O=[PH]1(O)(O)C=C2CCCN3CCCC(=C23)C=C1c1cccs1
Invalid SMILES: O=[PH]1(O)(O)CCN2CCC(O)(CC1)c1cc3ccsc3cc12
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)sc1c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2c(c3ccccc31)-c1ccccc1Sc1ccccc1-2
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)sc1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3sc4ccccc4c3ccc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)oc1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCc1ccc2c(c1)sc1c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccccc2c2sc3ccccc3c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2sc3ccccc3c21
Invalid SMILES: Cn1c2c3ccc(C=C=[PH](=O)(O)O)cc3c1=c1ccccc1=c1ccccc1=2
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c3ccccc4ccccc4c-3c2c1
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccccc3c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccc(O)cc3c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)-c1c-2c2ccccc2c2ccccc12
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc(C3CCCCC3)c3cccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)c2cccc3c(C4CCCCC4)ccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)C(=O)c2ccc(-c3cccc(O)c3)c3cccc1c23
Invalid SMILES: O=C1NC(=O)c2cccc3c(-c4ccc(O)cc4)ccc(c23)C(=O)C1=[PH](=O)(O)O
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc(-c3ccccc3)c3cccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)N(C(F)(F)F)C(=O)c2ccc(-c3ccc(O)cc3)c3cccc1c23
Invalid SMILES: O=C(O)c1ccc2c3c(ccc(CNP(=O)(=O)(O)O)c13)C(=O)N(CCc1ccncc1)C2=O
Invalid SMILES: O=C1c2cccc3cccc(c23)C(NP(=O)(=O)(O)O)C(=O)N1CCc1ccncc1
Invalid SMILES: O=C(O)CNc1cc2c3c(c(NCO)cc4c3c1C(=O)C(=[PH](=O)(O)O)NC4=O)C(=O)N(CO)C2=O
Invalid SMILES: O=[PH](O)(O)=Cc1cccc2c3c(ccc12)=CC=c1ccccc1=c1ccccc1=3
Invalid SMILES: O=C(CCCCC=[PH](=O)(O)O)OC1=CC=c2ccc3c4c(ccc(c24)=C1)=c1ccccc1=CC=3

[13:01:33] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)cc1

[13:01:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)cc1

[13:01:36] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:01:36] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:01:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:36] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:01:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:36] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:01:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: N#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(CP(=O)(=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccc(O)cc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc3c(c2)-c2cc(-c4ccccc4)ccc2-3)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(-c3cccc4nsnc34)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2cccc3nsnc23)cc1
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc(N(c2ccccc2)c2ccc(-c3cccc4nsnc34)cc2)cc1
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc3c4c(ccc1c24)C(=O)N(c1ccccc1)C3=O
Invalid SMILES: COc1ccc(N(c2ccc(C=CC=[PH](=O)(O)O)cc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)c3nsnc23)cc1
Invalid SMILES: COc1ccc(N(c2ccc(C=CC=[PH](=O)(O)O)cc2)c2ccc(-c3ccc(-c4ccccc4)cc3)c3nsnc23)cc1
Invalid SMILES: O=[PH](O)(O)=CCSc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)c3nsnc23)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=CC2)c2ccc(-c3ccc(-c4ccc5[nH]snc4-5)cc3)cc2)=C1
Invalid SMILES: O=c1c(=[PH](=O)(O)O)c(=O)c2ccc3c4ccc5c(=O)n(CO)c(=O)c6ccc(c7ccc1c2c73)c4c65

[13:01:37] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)s3)s2)cc1

[13:01:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:38] Explicit valence for atom # 41 P, 7, is greater than permitted
[13:01:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:38] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:01:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:42] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:01:42] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc3[nH]c4ccc(N(c5ccccc5)c5ccccc5)cc4c3c2)cc1
Invalid SMILES: N#CC(C#N)=Cn1c2ccc(N(c3ccccc3)c3ccccc3)cc2c2cc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)ccc21
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: C=CCN(C1=CC=C1)c1ccc(-c2ccc(-c3ccc(N(C4=CC=CCC4)c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(Oc3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: CCC(C#N)=Cc1ccc(N2C=CC([PH](=O)(O)(O)CC(C)(C)C)=CC=C2c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccc(C4=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=C1SC(=[PH](=O)(O)O)SC1=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C1C(=Cc2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)SC(=[PH](=O)(O)O)N1C(=S)CO
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3cccc(-c4ccccc4)c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-n3c4ccc(-c5ccccc5)cc4c4cc(-c5ccccc5)ccc43)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(-c3ccc4c(c3)sc3cc5ccc3[nH]cccccc3cccccc4n35)cc2)cc1
Invalid SMILES: O=C(C1=CC=C1)C1=CC(NC2=CC=C2)=C2C=C(O1)c1cc(OCCCP(=O)(=O)(O)O)ccc12
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21
Invalid SMILES: O=P(=O)(O)(O)CCCCCn1c2ccccc2c2c3ccccc3ccc21
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)[nH]c1c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=Cc1cc2c(cc1O)[nH]c1ccccc12
Invalid SMILES: O=P(=O)(O)(O)Nc1ccc2c(c1)[nH]c1ccccc12
Invalid SMILES: COc1cc2[nH]c3ccccc3c2cc1PC=CC=[PH](=O)(O)O
Invalid SMILES: O=P1(O)(O)=CC=C(n2c3ccccc3c3ccccc32)C=C1
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2ccccc21
Invalid SMILES: O=P(O)(O)CCN1c2cccc(c2)-c2cc(C=[PH](=O)(O)O)ccc21
Invalid SMILES: O=P(=O)(O)(O)n1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1cc2c(cc1O)[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)[nH]c1ccccc12
Invalid SMILES: O=P(=O)(O)(O)CCCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Br)cc2ncc=2c1
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Cl)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCSc1ccc2c(c1)Nc1cc(Br)ccc1S2
Invalid SMILES: O=P(=O)(O)(O)CCN1c2ccc(Cl)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccc(Br)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(S(=O)(=O)O)cc2Sc2ccc(S(=O)(=O)O)cc21
Invalid SMILES: O=[PH](O)(O)=CN1c2ccccc2Sc2cc(Br)ccc21
Invalid SMILES: O=C(O)c1ccc2c(c1)N(P(=O)(=O)(O)O)c1ccccc1S2
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2ccc(Cl)cc21
Invalid SMILES: O=[PH](O)(O)=CN1c2ccc(Br)cc2Sc2ccc(Cl)cc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2cc(Br)c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=C1Nc2ccc(S(=O)(=O)O)cc2Sc2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3ccccc3Nc3ccccc32)cc1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)n1c2ccccc2c2cc(Cl)ccc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=c1[nH]c2ccc(Br)cc2c2ccc(Br)cc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccc(Br)cc2c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1cc2n[nH]c3ccccc3c-2n1
Invalid SMILES: O=P(O)(O)CCn1c2ccc(P(=O)(=O)(O)O)cc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=C3C(O)=CC(O)=C32)cc1
Invalid SMILES: O=C(C=[PH](=O)(O)O)OCCOC(=O)n1c2ccccc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccc(Br)cc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc(Br)ccc21
Invalid SMILES: N#CC(C#N)=Cc1ccc2c(c1)c1cc(Br)ccc1n2CC=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccc(N(C4=CC=CC4)c4ccccc4)cc3)cc(=[PH](=O)(O)O)s2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C(C(F)(F)F)OC=C2)C2=CC=c3c2cccc3=CC=C2PC=CC3=CC=CC=CCC=CN32)=C1
Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc(-c3ccc([PH](=O)(=O)O)c4nsnc34)cc2)c2ccccc12
Invalid SMILES: O=[PH](O)(O)=c1cc(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)cc(C2=CC=C2)s1
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=C(O)C1=Cc2ccc(c3c(ccc4ccc-4cccc(=CC=CC4=C=C4)n2C2=CCC(=[PH](=O)(O)O)C=C2)C=3)OC1
Invalid SMILES: O=C(O)c1ccc(C#P(=O)(O)O)cc1N(c1ccccc1)c1ccc(-c2ccc(P(=O)(O)O)c3nsnc23)cc1
Invalid SMILES: O=C1C=C2C(N(c3ccccc3)c3ccc(-c4ccc(P(=O)(O)O)c5nsnc45)cc3)=CC=C(C#P(=O)(O)O)C12
Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc(-c3ccc([PH](=O)(=O)O)c4nsnc34)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(F)cc4)cc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2F)c2nsnc12
Invalid SMILES: O=[IH](O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)=C(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC(c4ccc(N=CC5=C=CC5)cc4)C=C3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=Cc1cccs1
Invalid SMILES: O=P(=O)(O)(O)c1cccs1
Invalid SMILES: O=P(=O)(O)(O)c1cscc1Br
Invalid SMILES: O=S(=O)(O)c1ccc(P(=O)(=O)(O)O)s1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C(Cl)(Cl)Cl)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=C/C=C/C(C(F)(F)F)=CS1
Invalid SMILES: O=[PH](O)(O)=CC(C1=CC=C1)=C1C=CC(c2ccc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=CO1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(C2=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccccc2)cc1
Invalid SMILES: N#CCCCCCCCCCC(C#N)C=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N2C=CC=CC2)cc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C(c3ccc(-c4ccccc4)cc3)C2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CC(=CC=C1C=C(O)c2ccc(cc2)O1)C1=CC(c2ccc(-c3ccccc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccc(C4=CC=CC4)cc3)c3ccc(-c4ccccc4)cc3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=CC4)cc3)cc2)cc(C2=CC=C2)c1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(N(C2=CC=C(c3ccccc3)C=CC=C2)c2ccc(C3=CC=C3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccc(C4=CC=C4)cc3)c3ccc(C4=CC=CC4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CCC(C1=C=CC=C1)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)=CO1
Invalid SMILES: O=[PH](O)(O)=CC(=CC=C1C=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1)c1ccc(C2=CCC=C2)cc1
Invalid SMILES: O=C(O)C(=Cc1ccc(N(c2ccc(-c3ccccc3)cc2)c2ccc(-c3ccccc3)cc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C2)c(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=C=C4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(C=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)=CCO1)C1=C=CCC=C1
Invalid SMILES: O=[PH](O)(O)=CC(O)=C1C=CC(N(c2ccc(C3=CC=C(C4=CC=CC4)C3)cc2)c2ccc(-c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(c2ccccc2)=C1)c1ccccc1)C1=CC=CC(N(c2ccccc2)c2ccccc2)C=C1
Invalid SMILES: O=C(O)c1ccc(C(=Cc2ccc(-c3ccc(N(C4=CC=C4)c4ccccc4)cc3)cc2)C=[PH](=O)(O)O)cc1

[13:01:43] Explicit valence for atom # 26 P, 7, is greater than permitted

Invalid SMILES: N#CPC(=Cc1ccc(C2=CC=C(C3=CC=CCC3)C=CC=C2)cc1)C=[PH](=O)(O)O

[13:01:44] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccccc3)=CC(c3ccccc3)=CC=C2)cc1

[13:01:44] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(-c3ccc(C=CC=[PH](=O)(O)O)cc3)s2)s1)C(=O)O

[13:01:45] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1cccc(-c2ccc(C=[PH](=O)(O)O)s2)c1

[13:01:45] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:01:46] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CPC2=CC3=C(C=CC=CC=C2C3)N(c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(c4ccccc4)=CC=CC=C3)c2)cc1

[13:01:47] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C(=C1C=C(C2=CC(=[PH](=O)(O)O)C=C2)C1)c1ccc(-c2ccccc2)s1

[13:01:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:48] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(=CC(F)(F)F)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1-c1ccc(C2=CCC=C2)cc1

[13:01:49] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:01:49] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)s3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC(C2=CC=C(C3=CC=C=C3)[IH]C=C2)=CC(c2cccc(C3=CC=C3)c2)=CC=C1

[13:01:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:50] Explicit valence for atom # 20 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(C3=CC(F)=CC(C4=CC=C4)C=C3)c(F)c2)cc1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(-c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3F)cc2)C=CP1

[13:01:50] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=C(C2=CCC=C2)C=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1

[13:01:51] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CC=CC4)cc3)c2)cc1

[13:01:51] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC=C(c4ccccc4)C=CC3)c2)cc1

[13:01:51] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:01:51] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C1C=CC1=CC=C1C=CC1=C1C(Cl)=C1SC1=C(S(=O)(=O)O)C(Cl)=CC1=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccccc3)c2)cc1

[13:01:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:52] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cccc(C2=CC(c3ccccc3)=CC(c3ccccc3)=CC=C2)c1
Invalid SMILES: O=C(O)C1=CC=C(c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)CC=C1

[13:01:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:52] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(Cl)C(c2ccc(C3=CC=CC(Cl)C=C3)c(F)c2)S1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3cc(F)cs3)c(F)c2)s1

[13:01:52] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(F)c(F)c2)cc1

[13:01:53] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC=C(C4=CC=C=C4)C=CC3)c2)cc1

[13:01:53] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:01:53] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC(=[PH](=O)(O)O)S1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(C3=CC(F)=CC(F)C=C3)c(F)c2)cc1

[13:01:53] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:54] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1cc(-c2ccc(C(F)(F)F)cc2)sc(-c2ccc(C3=CC=C3)s2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CC=C4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC=CC(C4=CC=C4)=CC3)c2)cc1

[13:01:54] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:54] Explicit valence for atom # 18 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CCC=C4)cc3)c2)s1
Invalid SMILES: O=C(O)c1cccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)c1

[13:01:55] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:01:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:55] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1cc(C2=CCC2=CC=CC2C=CCCN2C2=CC=C2)cc(-c2ccc(C=[PH](=O)(O)O)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC=C(C4=CC=C4)C=CC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=C(c2ccc(O)c(Cl)c2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=CC3)=CC(c3ccccc3)=CC=C2)cc1

[13:01:55] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1

[13:01:55] Explicit valence for atom # 15 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(-c3ccc(C=[PH](=O)(O)O)cc3)s2)s1

[13:01:56] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(-c2ccc(-c3ccc(C(=O)O)s3)s2)cc1

[13:01:56] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=C3)=CC(c3ccccc3)=CC=C2)cc1

[13:01:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:56] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C=CC=CC(C4=CC=CCC4)=CC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=C(c3ccc(-c4ccccc4)s3)C2)cc1

[13:01:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:58] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C=CC=CC(c4ccccc4)=CC3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(F)=CC(C4=CC=C4)C=C3)s2)cc1

[13:01:58] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:01:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:58] Explicit valence for atom # 20 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CCC=C(N(c2ccccc2)c2ccc(-c3ccc(C=[PH](=O)(O)O)s3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N(c3ccccc3)c3ccccc3)c2)cc1
Invalid SMILES: O=C(O)C(=O)Sc1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1

[13:01:58] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:01:59] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-n3cccc(O)c4ccc3cc4)c2)cc1

[13:01:59] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(NC2=CC(c3ccc(C4=CC=C4)cc3)C=CC=C2)cc1

[13:02:00] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC=C(PC3=CC=C3)C=CC(C3=CC=CC=CC3)=C2)s1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-c2ccc(-c3cccs3)s2)cc1

[13:02:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cc(C2=CC=CC2)cc(-c2ccc(-c3ccccc3)cc2)c1

[13:02:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:02] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC=CC(c4ccccc4)=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC4=CC=C3C=CC=C4)c2)cc1

[13:02:02] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:02:02] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=C(F)C1=CN(c2ccc(-c3ccc(C=[PH](=O)(O)O)s3)cc2)C=CC=CC=C[IH]1
Invalid SMILES: O=C[IH]C1=CC=C2C=Cc3c(ccc(C(=O)O)ccc(C4=CC(=[PH](=O)(O)O)C=C4)cc32)C1=O

[13:02:03] Explicit valence for atom # 24 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=C(C2=CC=CC(C3=CC=CC3)C=C2)C=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1

[13:02:03] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(F)(F)C=C3)c2)cc1

[13:02:04] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:02:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C=C1C=CC(c2ccc(C=[PH](=O)(O)O)cc2)=CC(C2=CC=C(C3=CC=C=C3)[IH]C=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(PC3=CC=CC3)=CC(c3ccccc3)=CC=C2)cc1

[13:02:04] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(Cl)cc2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CCC=C3)=CC(c3ccccc3)=CC=C2)cc1

[13:02:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC(C2=C(C3=CC=C3)C=CC2)=C(c2ccc(F)cc2)[IH]C=C1

[13:02:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(-c3cccc(F)c3)c(F)c2)s1

[13:02:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(C3=CC=C=C3)c3ccccc3)cc2)S1

[13:02:06] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:02:06] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(-c3ccc(PC=[PH](=O)(O)O)cc3)s2)s1
Invalid SMILES: O=C(O)C1=CN(c2ccc(C3=CC(=[PH](=O)(O)O)S3)cc2)C=CC=C1

[13:02:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(-c4ccccc4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C(F)(F)F)c2)cc1

[13:02:07] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:02:07] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:02:07] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:07] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(C2=CC=C(c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3C3=CC=C3)CC=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(C(=O)O)[IH]C=C(c4ccc(C5=CCC=C5)cc4)C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=CC3)cc(-c3ccc(C4=CC=CC(C5=CC=CC5)C=C4)cc3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC(C5=CC=C(C6=CC=C6)C5)C=C4)=C3)s2)cc1

[13:02:07] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1CC=C(C2=C=CC=C2)C=C(c2ccc(-c3ccc(-c4ccc(-c5ccccc5)cc4)cc3)cc2)S1

[13:02:07] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=C[IH]C(c2ccc(C3=CC=C(c4ccc(C5=CC=C=C5)[pH]4)C=CC3)cc2)=C(C2=CC=CC2)S1

[13:02:08] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:02:08] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:02:08] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1cc(C=[PH](=O)(O)O)cc(-c2ccc(C3=CC=CC(c4ccc(C5=CC=CCC=C5)cc4)C=C3)cc2)c1
Invalid SMILES: O=C(O)C(=C1CC(=[PH](=O)(O)O)S1)c1ccc(-c2ccc(-c3ccccc3)s2)s1
Invalid SMILES: O=C(O)c1ccn(-c2ccc(C3=CP(=O)(O)(O)=CC(c4ccc(C5=CC=C5)cc4)=C3)cc2)c1

[13:02:08] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:08] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:02:08] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(c4ccc(-c5ccccc5)cc4)C=CC=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CC=C(C3=CC=C(C=[PH](=O)(O)O)C=C(c4ccc(C(=O)O)cc4)S3)CP2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=C3)cc(-c3ccc(C4=CC=C(C5=CC=C5)PC=C4)cc3)c2)cc1

[13:02:08] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:02:08] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:02:08] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(F)C(=C1C=C(C2=CC(=[PH](=O)(O)O)C=C2)C1)c1ccc(-c2ccc(Cl)cc2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)c(C3=CC(C4=CC(n5cccc5O)CC=C4)C=C3)s2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3cc(F)cc(-c4ccc(N(C5=CC=C5)C5=CC=CC5)cc4)c3)c2)cc1

[13:02:09] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=CC1=CC=C(c2ccc(-c3ccc(C4C=CC(c5ccc(C=[PH](=O)(O)O)cc5)=C4)cc3F)cc2)C1

[13:02:09] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:09] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:02:09] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccc(C4=CCC=C(C5=CC=C5)PC=C4)cc3)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(-c3cccc(-c4ccc(C=[PH](=O)(O)O)cc4)c3)cc2O)cc1
Invalid SMILES: O=C(O)c1cc(-c2ccc(C=[PH](=O)(O)O)cc2)cc(-c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)c1

[13:02:09] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:02:09] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2ccc(-c3cc(C4=CCC=C4)cc(-c4ccc(C=[PH](=O)(O)O)cc4)c3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(=[PH](=O)(O)O)sc2-c2cccc(-c3ccc(C4=CC=C4)c(F)c3)c2)cc1

[13:02:10] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=CC=CC=C3)cc(-c3ccc(C4=CCC=C4)cc3)c2)cc1

[13:02:10] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:02:10] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:02:10] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:02:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:10] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC=C(n5cccc5)C(F)C=C4)PC=C3)s2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2sc(C=[PH](=O)(O)O)cc2C2=CC(C3=CC=C(c4ccc(C5=CC=C5)cc4)C3)=CC2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(C4=CC=C(C5=CC=C5)C4)C=CC3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc(c1)-c1ccc(cc1)-c1ccc(cc1)-c1ccc(cc1)-c1ccc(cc1)C=CCC=CC=C2
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=CC3=CC(c4ccc(C5=CC=C5)cc4)=C2C=CC=C3O)cc1

[13:02:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:10] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:02:10] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(O)c(-c3ccc(-c4ccc(Cl)cc4)s3)c(C3=CCC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2=CC(c3ccc(C4=CC(C5=CC=C5)PC=C4)c(F)c3)C=C2)=C1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(-c3ccc(C4=CC=C(C5=CC=C5)BC=C4)cc3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(-c4ccc(P)cc4)cc3)cc(-c3cccc(O)c3)c2)cc1

[13:02:11] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(-c2ccc(C(C(=O)O)=C3C=C(C4=CC(=[PH](=O)(O)O)C=C4)C=C3O)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccccc3C3=CC=C(C4=CC=CC4)PC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(F)c2)cc1

[13:02:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C2)cc(-c2ccc(C3=CC(C4=CC=C(C5=CC=C5)C4)C=C3)cc2O)c1

[13:02:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccccc3C3=CCC=C(C4=CC=C4)PC=C3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(C3=CC=CCC=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)c(F)c3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(c4ccc(C5=CC=C5)cc4)PC3)c2)cc1

[13:02:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:12] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cc(C2=CC=C=C2)cc(-c2ccc(C3=CC=C(C4=CCC=C4)C=CC3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(C4=CCC=C4)C=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1
Invalid SMILES: O=P1(O)(O)=CC(c2ccccc2)=CC(c2ccc(N(C3=CC=CC(C4=CC=C4)C=C3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3cccc(-c4ccc(C5=CCC=C5)cc4)c3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC(c4ccc(C5=CC=C5)cc4)C=CC=C3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(C3=CC=C(c4ccc(C5=CC=C5)cc4)C=CC=C3)cc2)c(C2=CC=C2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(F)=C(c3ccc(-c4ccccc4)s3)C2)cc1

[13:02:12] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3cccc(-c4ccccc4)c3)c2)cc1

[13:02:12] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:02:12] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccccc3)c2)cc1C1=CC=C(C2=CC=C(C3=CC=C3)C2)C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=CC3)C=CC(c3ccc(-c4ccc(-c5ccccc5)cc4)cc3)=C2)cc1

[13:02:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:12] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:02:12] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(c2ccc(C3=CC=C3)cc2)SC(C2=CC=C(c3ccccc3)C=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC(C4=CCC=C4)=C3)cc2)c(-c2ccc(C3=CCC=C3)cc2)c1
Invalid SMILES: O=C(O)c1ccc(C2=CP(=O)(O)(O)=CC(C3=CC(C4=CC(c5ccc(C(=O)O)cc5)C=C4)C=C3)=C2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CC(C=[PH](=O)(O)O)=CC=C(c3ccc(-c4ccc(C5=CC=C5)cc4)s3)S2)cc1

[13:02:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:13] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:02:13] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:02:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:13] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=C3)C=CC(c3ccc(C4=CC=C(C5=CC=CCC5)PS4)cc3)=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C3=CC(c4ccc5c(c4)CC5=CC=C4C=CC=C4)=C3)ccc(=[PH](=O)(O)O)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(c4ccc(-n5ccc(O)c5)cc4)=C3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(C4=CC=C4)cc3)cc(-c3ccc(C4=CCC=C4)cc3)c2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC(F)C(F)=C(F)C4=C(F)C4=CC=C4)=CC3)s2)cc1

[13:02:13] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:02:13] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:02:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:13] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=C(C2=CC(c3ccc(C4=CC=C4)cc3)=C2)C=C(c2ccc(C=[PH](=O)(O)O)s2)C=C[IH]1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(F)=CC(F)C3=CC=C3CC3=C(F)C3=CC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(F)=C(c4ccc(C5=CC=C5)cc4)[IH]C=C3)c2)cc1

[13:02:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:13] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:02:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:14] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(F)=C(C4=CC=C(N=C(O)C5=CC=C5)C4)CC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC(F)=C(c4ccc(C5=CC=C5)cc4)C=CC3)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CP(=O)(O)(O)=CC(C3=CC(C4=CC=C(C5=CC=CCC=C5)C(C5=CC=C5)CC4)=CC3)=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(C4=CC=C4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)ccc2C2=CC=C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(C4=CCC=C(C5=CC=C5)C=C4)cc3)c(C3=CC=CCC3)c2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccc(-c4ccc(C5=CC=C=C5)cc4)c(F)c3)c2)cc1

[13:02:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:14] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(C3=CCC=CC3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=C(C4=CC(F)C(F)=C(C5=CC=C5)N4)C=C3)s2)cc1

[13:02:14] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:02:14] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccc(C=[PH](=O)(O)O)cc3)cc(-c3ccc(C4=CC=CC4)cc3)c2)cc1
Invalid SMILES: O=P1(O)(O)=CC(c2ccccc2)=C(c2ccc(N(c3ccccc3)c3ccc(N(C4=CC=C4)c4ccccc4)cc3)cc2)C=C1

[13:02:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:15] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC(c2ccc(N(C3=CC=C=C3)C3=CC=CC3)cc2)=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cc(-c2ccc(N(C3=CC=C3)C3=CCC=C=C3)cc2)cc(-c2ccc(N(C3=CC=C=C3)c3ccccc3)cc2)c1
Invalid SMILES: O=P1(O)(O)(C2=CC=C2)C=CC(c2ccc(N(C3=CC=CC3=CC=C3C=CN3c3ccccc3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=C1SC2=C3C(=CC=c4ccc(n4C4=CC=C4)=CC=CC=CC=C2)CC=CC=C2C=CC=CC=c4ccc(n42)=CC=C31
Invalid SMILES: O=P1(O)(O)=CC(N(C2=CCC=C2)C2=CC=CC2)=C(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)C=C1

[13:02:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:16] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(C3=CCC=C(N(C4=CC=CC4)C4=CC=CC4)C=C3)c3ccccc3)cc2)C=C1c1ccccc1
Invalid SMILES: O=P1(O)(O)=CC=C(C2=CC(N(C=C3CC=CC3)C3=CCC=C3)=CC(c3ccc(N(C4=CC=C=C4)C4=CC(O)C=CC4)cc3)C=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(c3ccccc3)c3ccc(N(C4=CC=C4)C4=CC=CC4)cc3)cc2)C=C(C2=CC=CC2)C1
Invalid SMILES: O=P1(O)(O)=Cc2cccccccc3ccc(ccc4cccccc5c(ccc6ccc6ccc1c24)OC5)n3C1=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC(C1=CC=CC1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(N4C=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=P1(O)(O)=CC2=c3c1ccc1ccc4n1c(cccccc3=CC=c1ccc(n1C1=CC=C1)=CC=CC=CC=C=C2)C=CC=CC=4

[13:02:16] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1cc(-c2cccc(N(C3=CC=CC3)c3ccccc3)c2)cc(-c2ccc(N(C3=CC=C3)c3ccccc3)cc2)s1

[13:02:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:17] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-n4c5ccccc5c5ccccc54)s3)s2)cc1
Invalid SMILES: N#Cc1ccc(C=[PH](=O)(O)O)cc1-c1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)s2)s1

[13:02:17] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-n4c5ccccc5c5ccccc54)cc3)s2)cc1

[13:02:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 38 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:18] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:02:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:19] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:02:19] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC=C2)c(-c2ccc(-c3ccc(-n4c5ccccc5c5ccccc54)s3)s2)c1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC(C3=CCC=C3)C2)C2=CC21
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)CC1=CCC1=CC=C1
Invalid SMILES: O=[PH]1(O)(O)CCC(c2ccc(N(c3ccccc3)c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)CC1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)CC1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCCC2)C2=CC1=CC2
Invalid SMILES: O=C1C(c2ccc(N(c3ccccc3)c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)CCC[PH]1(=O)(O)O
Invalid SMILES: O=[PH]1(O)(O)CCCC(F)(c2ccc(N(c3ccccc3)c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)CC1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCCC2(F)C2=CC=C2)CC1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)C2=CC1=CCc1cccc2c1
Invalid SMILES: O=Cc1ccc(N(c2ccc(C=O)cc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccc(C#P(=O)(O)O)cc5)cc4)CCCCC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)C2=CC=C21
Invalid SMILES: O=[PH](O)(O)=CC(c1ccc(N(C2=C=C2)c2ccccc2)cc1)c1ccc(N(C2=CCC=C2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)CC1=CC1=CC=C1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccccc5)cc4)CCCC3)cc2)cc1
Invalid SMILES: O=Cc1ccc(N(c2ccc(Cl)cc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccc(C#P(=O)(O)O)cc5)cc4)CCCCC3)cc2)cc1
Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccc(C#P(=O)(O)O)cc5)cc4)CCCC3)cc2)cc1
Invalid SMILES: N#CC1=CC(=CC=[PH](=O)(O)O)C=C1
Invalid SMILES: N#CC1=CC=CC(=CC=[PH](=O)(O)O)C=C1
Invalid SMILES: O=[PH](O)(O)=CC=CPc1ccc(Br)cc1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(C(F)(F)F)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C(F)(F)F)C=C1
Invalid SMILES: O=Nc1ccc(/C=C/C=[PH](=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1ccc(Br)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C(F)(F)F)cc1
Invalid SMILES: O=[PH](O)(O)=CC=CPc1ccccc1Br
Invalid SMILES: O=[PH](O)(O)=c1ccc(C(F)(F)F)cc(C(F)(F)F)c1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CS1
Invalid SMILES: N#Cc1ccc(C#P(=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1c(F)c(F)c(F)c(F)c1F
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(Br)cc1
Invalid SMILES: N#CC1=CC(O)=CC(=CC=[PH](=O)(O)O)C=C1
Invalid SMILES: N#CC1=C=CC=CC(C=CC=[PH](=O)(O)O)=C1
Invalid SMILES: O=[PH](O)(O)=C/C=C\c1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(C(F)(F)F)=C1
Invalid SMILES: O=Cc1ccc(C=CC=[PH](=O)(O)O)cc1
Invalid SMILES: N#CC(Cl)=CC=C1C(=CC=[PH](=O)(O)O)C=CC1=CC(=CCO)C(=O)O
Invalid SMILES: N#Cc1ccc(/C=C\C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc(PC=CC=[PH](=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Cl)cc1
Invalid SMILES: O=[PH](O)(O)=CC=CPc1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CPC=CPc1cccc(N(CCO)CCO)c1
Invalid SMILES: N#CC(C#N)=Cc1ccc(/C=C/C=[PH](=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C/C=C\c1c(F)c(F)c(F)c(F)c1F
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C=C2)c2ccc(N(c3ccc(C4=CC=C=C4)cc3)c3ccc(C4=CC=C4)cc3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(C3=CCC=C3)c3nsnc23)cc(-c2ccc(N(C3=CC=C=C3)C3=CC=C3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C=C2)cc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=C1C=C(N(c2ccc(O)cc2)c2ccc(N(C3=CC=C=C3)C3=CC=CC3)cc2)C=C(C2=CC=CCC=C2)CC1
Invalid SMILES: O=CC1=CC(=[PH](=O)(O)O)NC1=CPc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=c1cccc2c3ccc(n12)Cc1c(ccc(=[PH](=O)(O)O)[nH]c1=S)-c1ccc(cc1)N3C1=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)c2cccc(O)c2)cc1)C1=CCC=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1cccc(-c2ccc(N(C3=CC=CC3)c3ccc(C4=CC=C4)cc3)cc2)c1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2CC=CC=C=CC3=CC=C3c3ccc(cc3)N(c3ccc(-c4ccccn4)cc3)c3ccc2cc3)=CC1
Invalid SMILES: CCC(=CC(=C1C=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1)c1ccc(N2C=C=CC=CC=CC=C3C=CC=C32)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=C(O)C1=CC=C2C=CC(O)=CC=C3C=CC3=CC=c3ccccc3=CC=C3C=C(C=C(C=[PH](=O)(O)O)CC=CC=C1)N23
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3ccc4ccccc4cccc(n23)=CC=c2ccc3n2C(=C=CC=CC=C=C1)CC=CC=CC=3
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)C2=CC=C2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CC=CC(c2ccccc2)C=C1)=C1C=CC(N(C2=CC=CC=CC=C2)C2=CC=C2)=CC1)N1C=CC=CC=C=CC1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(N(c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)c2ccc(N(C3=C=CCC3)c3ccccc3)cc2)=C1
Invalid SMILES: O=P1(O)(O)=CC=C(c2ccc(N(C3=CC=C=C3)c3ccc(-c4ccc(N(C5=CC=C5)c5ccccc5O)cc4)cc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(N(CC=[PH](=O)(O)O)C2=CC(C3=CC=C=C3)C=CC=C(c3ccc(N(C4=CC=CC4)c4ccccc4)cc3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C3C=CC(=C3)N(c3ccccc3)c3ccc(cc3)N(c3ccccc3)C3=CC=C(C=CC=CC2C=CC=CCC=C=CC=C1)C3
Invalid SMILES: O=[PH](O)(O)=CC(=CC1=C(O)C1=CC(=CC=C1C=CC=C1O)c1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)c1ccccc1
Invalid SMILES: C=CC(=CC(=C1C=CC(O)=C1)c1ccc(N(C2=CC=C2)C2=CC=CC(c3ccc(N(C4=CCC=C4)C4=CC=C=CC4)cc3)C=C2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(c2ccccc2)c2ccccc2)=C1)c1ccccc1)N(C1=CCC=C1)C1=CC=CC1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)C2=CC(c3ccc(N(C4=CC=C4)C4=CC=CC4)cc3)C=C2)C=CCO1
Invalid SMILES: O=P1(O)(O)=CC=C(N(C2=CC=C=C2)c2ccc(N(C3=CC=CC(C4=CC=C4)C3)c3ccccc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=C3)c3ccc(-c4ccc(N(C5=CC=C5)C5=CC=C5)cc4)cc3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1cccc(N(c2ccccc2)c2ccccc2)c1)c1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)C2=CC=CC2)cc1
Invalid SMILES: O=C1C=CC(N(C2=CC=CC=CC=C2)c2ccc(-n3cccc3)cc2)C=CC(=CC(C=[PH](=O)(O)O)c2ccccc2)O1
Invalid SMILES: O=[PH](O)(O)=CC(=C1C=CC(N(c2ccccc2)c2ccc(O)cc2)=C1)c1ccc(N(C2=CC=CC2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3n2C(=CC=C2C=CC2=CC=C=CC1=CC=C1C=CCC=C1)C=CC=CC=3
Invalid SMILES: O=[PH](O)(O)=CC1=CC=c2ccc3n2C(=CC=c2ccc(n2C2=CC=CCC2)=CC=CC=C=CC1)C=CC=CC=c1ccccc1=CC=3
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C3C=CC(=C3)c3ccc(cc3)N3CC3=CC=CCC2=CC=c2ccc3n2C(=CC=CC=CC=C1)C=CCC=3
Invalid SMILES: O=[PH](O)(O)=Cc1cccccccccc2c3oc(c(n(C4=CC=CC4)c4ccc(cc4)c4cccc(c1)c4)=CC=3)=CC=C2
Invalid SMILES: O=[PH](O)(O)=CC1=CC(=C2C=CC(N(c3ccccc3)c3ccccc3)=C2)C2=CC=C(CC2)C2=CC=C(C=CC3(O)C=C=CN1C=CCC=C3)CC=C2
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC=CC=C2)C2=CC=CC2)=C1)c1ccc(N2C=CC=CC2)cc1)C1=CC=C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C2)c2ccc(N(C3=CC=C=C3)c3ccc(C4=CC=CC4)cc3)cc2)=CC1
Invalid SMILES: O=C(O)C(C=C1C=CC(c2cccc(N(c3ccccc3)c3ccc(N(C4=CC=C=C4)c4ccccc4)cc3)c2)=C1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=CCC=C2)C2=CC=CC2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(C=C1C=CC(N(C2=CC=C(C3=CC=C=C3)C=CC=C2)c2ccc(C3=CC=C=C3)cc2)=C1)C1=CC=C=CC1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(C2=CC(C3=CCC=C3)C=C2)N(c2ccc(N(c3ccccc3)c3ccccc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2cccc(N(C3=CC=C=C3)c3ccc(-c4ccc(-c5ccc(C6=CC=C6)cc5)cc4)cc3)c2)=CC1
Invalid SMILES: N#CC(C#N)C=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: N#C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2C=CC=CC=C=CC=C3C=CC=CC=C4C5=CCC=CC6=CC=C(C=CC2=CC=C3O6)N45)=CC1
Invalid SMILES: O=P(=O)(O)(O)C1=CC=C(N2C=C=CC=CCC=CC=c3ccc(n3C3=CC=CC3)=CC=C3C(OC4=CC=CC4)=CC=C32)C=C(O)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccccc2c(ccc3oc(c1)=C3)OC1=CC=C(Oc3ccccc3)N3C(=CC=CCC=CC=2)C=CC=C13
Invalid SMILES: N#CC[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)C=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1)=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC1=CC(=CC=C(OC2=CC=C(Oc3ccccc3)N(C3=CC=C3)CC=C2)C2=CC=C2)O1)N1C=C=CCCCC=CC1
Invalid SMILES: N#CCCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=C(Oc3ccc(N(C4=CC=C=C4)C4=CC=C4)cc3)N3C=CCC=C=CC=C3C1)O2
Invalid SMILES: O=[PH](O)(O)(c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1)n1cccc1
Invalid SMILES: C=CCCC(=CC1=CC(=CC=C2C=C=CCC=C=C=C3CC=CC=C4C=CCC=C5C=CC(=CC=C6OC3=CC=C6O2)N4N5c2ccccc2)O1)C=[PH](=O)(O)O
Invalid SMILES: N#CC(C#N)C=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Oc1cc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)ccc1O
Invalid SMILES: O=P(=O)(O)(O)Oc1cc(N(c2ccccc2)c2ccccc2)ccc1Oc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(C#N)C=CC1=CC=CC=CC(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)=C1
Invalid SMILES: N#CCCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: O=CC[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P1(O)(O)=CC=C(O)C(N(C2=C=C=CC2)C2=CC=C3OC4=CC=C5OC4=CC=CC5=CC=C4C=CC4=CC=CCC=CC=C32)=C1
Invalid SMILES: N#CCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)CC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C=CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC=C3Oc4ccc(cc4)N(c4ccccc4)C2=CC=CC2=CC=CCC=CC=C(C=CC1O)N23
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1)C=C1C=CC=CC1
Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: N#CCCCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)N(c1ccccc1)c1ccc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: N#CCCCCCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CCC=CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccccccc2cccccc3cccc4c(Oc5ccccc5)ccc4oc(ccc4cc(c1)o4)n23
Invalid SMILES: N#CC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)C=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)CC=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1C#P(=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=CC(=C1C=CC=C1)N(C1=CC=CC=CC=C1)C1=CCC=C1)n1cccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1c2c3ccccccccc(n1-3)C=CC=CC=C1C=CC=CC=c3ccc(n31)=CC2)C1=CC=C=C1
Invalid SMILES: O=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=C3OC4=CC=C(Oc5ccccc5)C(=CC=C4)C3=CC=c3ccc4n3C(=CCC=C=C=CC=C1)C=CC=CC=4)O2
Invalid SMILES: O=CC(=O)C(=O)C=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=c3oc4c5n(c(cccccc3=CC=CC=CC=CC1)C=CC=5)C(Oc1ccccc1)=CC=4)O2
Invalid SMILES: N#CC(=CC(=C1C=CC(N(C2=CC=C2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CCC=C1)C1=CC=CC1)C1=CC=C=C1
Invalid SMILES: N#CCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P1(O)(O)=CC=C(O)C(n2cccccccc3c(Oc4ccc(N(C5=CC=C5)c5ccccc5)cc4)ccc2-3)C=C1
Invalid SMILES: O=P(=O)(O)(O)C(=Cc1cc(O)cc2ccc(Oc3ccccc3)c3ccccccc-3n12)N1C=C=CC1
Invalid SMILES: O=P1(O)(O)=CC(C2=CC=C=C2)=CC(N(C2=CC=C(C3=CC=C3)OC3=CC=C(C=CC=C3)C=C2)c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC1=c2ccc(n2N(C2=CC=C2)C2=CC=CC2)=CC=C2OC3=CC=C(C=CC=CC(O)=CC=C2C=C1)C=CC=C3
Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CCC=C1)=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1
Invalid SMILES: O=P(O)(O)#Cc1cc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(O)CCC=Cc1c(CCC=[PH](=O)(O)O)c(-c2ccccc2)cc2c3cc(-c4ccccc4)ccc3n(-c3ccccc3)c12
Invalid SMILES: O=[PH](O)(O)=CCc1cc2c(cc1-c1ccccc1)c1cc(-c3ccccc3)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc2c(c1)c1cc(-c3ccccc3)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc(-c3ccccc3)cc2c2ccc(-c3ccccc3)cc21
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-n2c3ccc(-c4ccccc4)cc3c3cc(-c4ccccc4)ccc32)cc1
Invalid SMILES: O=Cc1c(CCC=[PH](=O)(O)O)c(-c2ccccc2)cc2c3cc(-c4ccccc4)ccc3n(-c3ccccc3)c12
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1cc(Cl)ccc1n2-c1ccccc1
Invalid SMILES: N#CC(=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1)C(=O)O
Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=P1(O)(O)=Cc2c(n(-c3ccccc3)c3ccccc23)C=C1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(-n2c3ccccc3c3ccccc32)cc1
Invalid SMILES: O=P(O)(O)c1ccc(N2C=CC3=CC4=C2C3=C2C=CC=C[PH]24(=O)O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccc(Cl)cc1
Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)PCC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2c(N(c3ccccc3)c3ccccc3)cccc2[nH]1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#CPC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=CC=CC=C2)C2=CC=CC2)cc1)PC=[PH](=O)(O)O
Invalid SMILES: N#CPC1=CC=C(N(c2ccccc2)c2cccc(C=[PH](=O)(O)O)c2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CBC(C#P(=O)(O)O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#C/C(C#P(=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)C=CC=C1)C1=CC(=[PH](=O)(O)O)C=C1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(F)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=C=C2)c2ccccc2)cc1)C(=O)OCC=[PH](=O)(O)O
Invalid SMILES: N#CC1=C=CC=C(N(C2=CC=C(C(=O)O)OC=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=C(O)C1=Cc2ccc(n(-c3ccc(C=[PH](=O)(O)O)cc3)ccccc2=O)C=C1
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1cccc[pH]c(C2=CC=C=C2)cc1
Invalid SMILES: N#CPC(=Cc1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=C/C(=C\c1ccc(O)cc1)c1ccc(N(C2=CC=C=C2)c2ccccc2)cc1
Invalid SMILES: N#CPN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(C2=CC=C2)cc1
Invalid SMILES: N#CC(=CPc1ccc(N(C2=CC=CC=CC=C2)c2ccccc2)cc1)OCC=[PH](=O)(O)O
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C\c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: O=P(O)(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(O)cc2)cc1
Invalid SMILES: O=C(F)c1ccc(N(C2=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: N#Cc1ccc(=[PH](=O)(O)O)cc(N(C2=CC=C2)c2ccccc2)c1
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=C(C(=O)F)C=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cc1)C(=O)O
Invalid SMILES: N#Cc1ccc(N(C2=CC=C(C(=O)O)C=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C(=O)F)C2=CC(=[PH](=O)(O)O)C=C2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C(C=C(O)O)/C=C\C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CCPC1=CC=CC2=CC=CC=CC(=CC=C3C=CC=CC=CC=CP3)N21
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: N#CPc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=Pc1ccccc2ccc(c1)-c1ccc(cc1)C=CC=CC=CN2c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=CC2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(C3=CC(F)=C3)cc2)[PH]2=CC=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(N(C2=CC=CSC=C2)c2ccc(O)cc2)c1
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(C2=CC=C2)cc1
Invalid SMILES: N#CPC(C#P(=O)(O)O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CCC(C=C(C#N)C#N)=Nc1cc(C=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: N#[PH]c1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(F)c1ccc(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)cccco1
Invalid SMILES: N#CPN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: N#[PH]N(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: Nc1cc(C=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=P(O)(O)Cc1ccc(N(c2ccccc2)c2ccc([PH](=O)(O)(O)O)cc2)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)C1=CCC(=[PH](=O)(O)O)C=C1
Invalid SMILES: N#CN(C1=CC=C(C(=O)O)[IH]C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#Cc1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(C=C(CF)C(=O)O)cc2)cc1
Invalid SMILES: O=C(F)C1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=CC2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)OCC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: Nc1cc(PC=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(N(c2ccccc2)c2ccc(O)cc2)c1
Invalid SMILES: N#[PH]C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C2)c2cccc(C=[PH](=O)(O)O)c2)cccco1
Invalid SMILES: N#CPN(c1ccccc2cc(cc1)C=CC=CC=CP2)c1ccc(PC=[PH](=O)(O)O)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(PC=[PH](=O)(O)O)cc1
Invalid SMILES: O=C(F)c1ccc(N(C2=CC=C=C2)c2ccc(PC=[PH](=O)(O)O)cc2)ccc([PH](=O)O)oc1
Invalid SMILES: O=[PH](O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(O)cc2)cc1

[13:02:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:20] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:20] Explicit valence for atom # 49 P, 7, is greater than permitted
[13:02:21] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:02:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:22] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:02:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:22] Explicit valence for atom # 48 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 31 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 42 P, 7, is greater than permitted
[13:02:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 47 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 2 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 42 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 52 P, 7, is greater than permitted
[13:02:24] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 42 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 42 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 46 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:02:25] Explicit valence for atom # 48 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 2 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 48 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:02:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:02:27] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 31 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:29] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 31 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:30] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:02:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:02:31] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:02:31] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:02:34] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:02:34] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:02:35] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:02:35] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:02:35] Explicit valence for atom # 27 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(CCCCn1ccnc1)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=c1cccc(C(F)(F)F)cc1C(F)(F)F
Invalid SMILES: O=C1CC=CC(=[PH](=O)(O)O)C=CC(C(F)(F)F)=CO1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(S)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(CCO)CCO)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(CCO)CCCCO)cc1
Invalid SMILES: O=[PH](O)(O)(c1nccn1Cc1c[nH]cn1)C(F)(F)F

[13:02:55] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2cccs2)S1

[13:02:58] Explicit valence for atom # 15 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)=Cc1ccc(-c2ccc(C=[PH](=O)(O)O)s2)s1

[13:03:03] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(S)cc1

[13:03:04] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: O=c1ccc(C=[PH](=O)(O)O)c(-c2cccs2)s1

[13:03:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1cccc(-c2cccs2)s1

[13:03:12] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc(-c2cccs2)cc1

[13:03:14] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: N#CC1=CC=C(C=[PH](=O)(O)O)c2ccccc2S1

[13:03:15] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(-c3ccccc3)cc2)c[nH]1

[13:03:17] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccccc1-c1cccs1

[13:03:18] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(PC=[PH](=O)(O)O)s2)s1

[13:03:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CPc1sc(-c2cccs2)cc1O

[13:03:23] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)N=C(c2ccccc2)S1

[13:03:23] Explicit valence for atom # 18 P, 7, is greater than permitted

Invalid SMILES: O=C(Cl)c1cc(-c2ccc(C3=CC=C3)cc2)sc(=[PH](=O)(O)O)c1Cl

[13:03:24] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: Nc1cc(-c2cccs2)sc1C=CC=[PH](=O)(O)O

[13:03:27] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(C=[PH](=O)(O)O)s2)s1

[13:03:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)sc1c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=c1ccc2c3ccc(c2s1)Sc1ccccc1-3
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)sc1c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2sc3c4ccccc4sc3c2c1

[13:03:36] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)sc1c3ccc(Cl)cc3sc21

[13:03:36] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:03:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:37] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:37] Explicit valence for atom # 47 P, 7, is greater than permitted
[13:03:37] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 48 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 46 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 48 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 47 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 49 P, 7, is greater than permitted
[13:03:38] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 48 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 47 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 47 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 38 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 41 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 41 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:03:39] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:40] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 44 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 38 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 38 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 41 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 44 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 31 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 43 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:03:41] Explicit valence for atom # 39 P, 7, is greater than permitted
[13:03:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:42] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:03:42] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:03:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:42] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:03:42] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:03:42] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:03:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 31 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:43] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:44] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:03:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:44] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:44] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc3[nH]c4ccc(-c5ccc([PH](=O)(=O)O)cc5)cc4c3c2)cc1
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc(-c3ccccc3)cc2c2cc(-c3ccccc3)ccc21
Invalid SMILES: O=[PH](O)(O)=CCCCCn1c2ccc(-c3ccccc3)cc2c2cc(-c3ccccc3)ccc21
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: CC(=CC(C1=CC=C=C(C2=CC=C=CC=C2)C=C1)=C1C=CC(c2ccc(N(C3=CC=CCC3)c3ccc(C4=CC=C4)cc3)cc2)=C1)C=[PH](=O)(O)O
Invalid SMILES: C=CC(C=[PH](=O)(O)O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(-c4ccc(N(C5=CC=C=C=C5)C5=CC=CC=CC5)cc4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: CC(=CC1=CC1=CC=c1ccc(=CC=C2C=CC2=CC=CC=C2CC2=CC=C2C=CC(=O)N2C2=CCC=C2)n1C=C=CC1=C=CCS1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC2=CC=c2ccc3n2N2C(=CC=C=CC=CC1)CC=CC=C2CCC=CC=C1C=CC1=CC=3
Invalid SMILES: O=C(O)C1=COC(=CC(=CC=[PH](=O)(O)O)C2=CC(C3=CC=CCC=C3)C=CC=C(c3ccc4n5c(ccccccc35)C4)C=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=CCCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC2=CC=c2ccc3n2N(C=C=CC=c2ccoc2=CC=C2C=CC2=CC=3)CC=CC=CC=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3n2C(=CC=C2CC=CC(N(C4=CC=C4)C4=CC=CC4)=CC=C2C=CC1)C=CC=CC=3
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC2=CC3=CC=CCC=CC=C4C=CC(C=C5C=CC5=CC=C21)N43)C1C=CC=C1)N(C1=C=C=CC=C1)C1=CC=CC1
Invalid SMILES: CC=C1C=C=CC=CC=C2CC=CC=C3C=CC=CC=C4C=CC(C=CC=C5C=CC5=CC=c5ccc(n52)=CC=C2C=C2C=C(C=[PH](=O)(O)O)C=C1)N34
Invalid SMILES: C=CC(=Cc1c(=CC=C2C=C=C=C2)cccccc2n3c(ccc3ccc3cccccc4ccc(ccc5ccc15)n34)=CCC=C2)C=[PH](=O)(O)O
Invalid SMILES: CC(=CC1=CC1=CC=c1ccc2n1C=C=CC=CCC=C=c1ccc(n1-c1ccccc1)=CC=C1C=CC1=CC=C1C=CC1=CC=2)C=[PH](=O)(O)O
Invalid SMILES: CC(=CC(C1=CC=C(c2ccc(N(C3=C=CCC=C=C3)C3CC=C=C=CC3)cc2)C1)=C1C=CC=C(c2cccc(C3=CC=CC3)c2)C=C1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc-2ccc2ccc3n2c(ccc2ccc(cccccc4ccc1C=C=C4)n2C1=CC=C1)C=CCC=C1C=CC1=CC=3
Invalid SMILES: CCC(=CC(C1=CC2C=C=CC=CC=CN(C3=C=CCC=C3)c3ccc(cc3)-c3ccc(cc3)C(=C2)C=C1)=C1C=CC(C(=O)O)=CO1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC1=CC(=C2C=CC(N(C3=CC=C(c4ccccc4)C=CC=C3)c3ccc(N(C4=CCC=C4)c4ccccc4)cc3)=C2)C=CC=C=C=C1
Invalid SMILES: O=[PH](O)(O)=CC=CC1=C(O)C1=CC=c1ccc2ccc3ccc3ccc3ccc3ccc3ccc(cccccccccn12)n3C1=CCC=CC1
Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccc(C=[PH](=O)(O)O)cc5)cc4)cc3)cc2)cc1
Invalid SMILES: C=CC=C=CC(=CC1=CC1=Cc1cccc2ccc3c(ccc4c(ccc(N(C5=CC=C=C5)C5=CC=C5)ccccn12)CO4)C=C3)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC1C=C=CC=CN(C2=CC=C=CCC=C2)c2ccc(cc2)-c2ccc(cc2)N(c2ccccc2)c2ccc(cc2)C2=CCOC(=C1)C=C2
Invalid SMILES: CC(=CC1=C2C=CC(=C2)c2ccc(cc2)N(C2=CC=C2)c2ccc(cc2)N(C2=CC=CCC2)C2=C(C=C=C2)CC=CC=CC=C=C1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=CCC=C=C3)c3ccc(-c4ccc(-c5ccc(C6=CC=C6)cc5)cc4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CC(c2ccc(C3=CC=CCC3)cc2)C=CC1)=C1C=CC(c2ccccc2)=C1)c1ccccc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C(=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1)CC(=O)O
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C=O)C(=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1)CCC=O
Invalid SMILES: N#CC(C(=O)C=O)C(C=O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C4=CC=C(c5ccccc5)C=CC3=CC=C(c3ccccc3)C=C4)cc2)cc1
Invalid SMILES: N#CC(C=O)=CC(C=O)=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)c2)cc1
Invalid SMILES: N#CC(C#N)C(=CC1=CC=C(c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)C1)C(=O)C=O
Invalid SMILES: O=CCC(C=O)=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=CC=[PH](=O)(O)O)cc4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccc(N(C3=CC=CC(c4ccc(C5=CC=C5)cc4)C=C3)c3ccccc3)cc2)S1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=C=C3)c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=CC1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccc(C=O)cc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4C=O)cc3)cc2)cc1
Invalid SMILES: N#CC(=CC1=CC=C(c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)C1)C(=O)C=O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2O)cc1
Invalid SMILES: O=CCOc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)c2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccccc2)cc1N(c1ccc(-c2ccccc2)cc1)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3cccc(-c4ccc(F)cc4)c3)cc2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(C2=CC=C3C=CC(c4ccccc4)=CC=C(C=C2)N3c2ccc(-c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=NN(c2ccccc2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccccc2C(F)(F)c2ccc(F)cc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Cc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(N2c3ccccc3Cc3ccccc32)C=C(Br)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C3=CC2=C(Br)C=C3)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(O)c2c1ccc1cccnc12
Invalid SMILES: O=[PH](O)(O)=Cc1ccnc2cc(Cl)ccc12
Invalid SMILES: O=[PH](O)(O)=CCc1cc2c3ccccc3sc2c2c1[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2c3sc4ccccc4c3ccc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc3c(cc21)sc1ccccc13
Invalid SMILES: O=C=CC1C=C2C(=C1c1c3cc(n1CC[PH](=O)(O)(O)O)-c1c-3n(CCCP(=O)(O)O)c3ccccc13)N2CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3ccc-3c(N3C=CCC=C3)c3cc4n(CCC[PH](=O)(O)(O)O)c3c-4c21
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C13CC=C=CC(C(NCCP(=O)(O)O)=C1c1[nH]c4ccccc4c1-2)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=C1c2c(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c2[nH]c2ccccc23)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=c1c2ccc(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c4ccc4n(CCCP(=O)(O)O)c23)n1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1C(NCC[PH](=O)(O)(O)O)=C1c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CC[PH](=O)(O)(O)O)C3=CC3)c3cc4n(CCCI(=O)(O)O)c3c-4c21
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1C=CC(=C3C=CC=C4C2=C3N4CCC[PH](=O)(O)(O)O)N(C2=C=C2)C1
Invalid SMILES: NC1=C2C(NCC[PH](=O)(O)(O)O)=C2c2[nH]c3ccccc3c2-c2c1c1ccccc1n2CCCP(=O)(O)O
Invalid SMILES: Cn1c2ccccc2c2c1c1c3ccccc3n(C=O)c1c1c3ccccc3n(P(=O)(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(C(=C3CC=N3)N1CCC[PH](=O)(O)(O)O)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CCC3=C1C(NCC[PH](=O)(O)(O)O)=C3c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C1C=CC=CC(=N3)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C=CC=C1C(=C3CN3CCC[PH](=O)(O)(O)O)n3c1c-2c1ccccc13
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c4c(c5c(n4CCC[PH](=O)(O)(O)O)C=C5)c4c(c5ccccc5n4CCCP(=O)(O)O)c31)CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CCc3c-2c2c(n3CCC[PH](=O)(O)(O)O)C=CC(C=C2)C1=C1CN1CCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=C3C=NC(S3)C2=C(C2=CCC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(c21)C(=C1C=CC=C1)N4CCC[PH](=O)(O)(O)O)C1C=C=C1C1(O)C=CC1=N3
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1c3nc(C4C=CC=C4)c-2c(c3=CC2=CC=C2)n1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(c3[nH]c4ccccc4c3-2)C2(C=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CC[PH](=O)(O)(O)O)C=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc2c(c1)[nH]c1c3ccccc3c3c4ccccc([nH]c23)c41
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(C3=CC(=N1)N3CCC[PH](=O)(O)(O)O)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c3c4c(c(c5c(c1=3)=C5NCC[PH](=O)(O)(O)O)NCC=CC=CC=2)c1ccccc1n4CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CCC[PH](=O)(O)(O)O)C=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c1c1c3ccccc3n(CC[PH](=O)(O)(O)O)c1c1c3ccccc3n(CCCP(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(ccn4CCC[PH](=O)(O)(O)O)c21)C1=CC=C(C=CC1)N3C1CCCC1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CC[PH](=O)(O)(O)O)CC=C4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCC=C1NC1=C1c2c(n(CCCP(=O)(O)O)c3ccccc23)C2=C(C=C2C2CCCC=N2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ncccc2c2cccc3c(NCC[PH](=O)(O)(O)O)c-3c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCN1C2=CC=Cc3c1c2c1c(c3N(CC[PH](=O)(O)(O)O)C2C=CC=C2)c2ccccc2n1CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CCP(=O)(O)O)C3=CCC=C3)c3c4c(c21)C(=CC=C3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(ccn3CCC[PH](=O)(O)(O)O)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CCC[PH](=O)(O)(O)O)CC=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccc3cc2c2cc(C4C=CC=C4)c(cc21)n(CC[PH](=O)(O)(O)O)c1ccc3=1
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C(=C1C=CC1)N(CCC[PH](=O)(O)(O)O)C1=C(C=CCC=C1)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c4c5c(n(CCC[PH](=O)(O)(O)O)c4c3n(CCCP(=O)(O)O)c2c2ccccc21)C5
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ncccc5c4c21)C(=C1C=N1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCC=NC1=c2cc3n(CCC[PH](=O)(O)(O)O)c2=C3c2c(c3ccccc3n2CCCP(=O)(O)O)-c2ncccc21
Invalid SMILES: O=c1c2c3[nH]c4ccccc4c3c3c(c4ccccc4n3CCCP(=O)(O)O)c2[nH]c2ccc-2n1CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCN1C(=C2CN2CCC[PH](=O)(O)(O)O)c2c1c1c(c3c4ccccc4n(CCCP(=O)(O)O)c23)N=CCC=C1
Invalid SMILES: O=P(O)(O)CCCN1C2=CC=CC3C(=C4C(=C41)c1c2c2ccccc2n1CCCP(=O)(O)O)C1=NC(CCCC1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCN1C(=C2C=CCC=C2)C1=C1C=CCC=Cc2c3c1n(CCC[PH](=O)(O)(O)O)c2-c1c-3n(CCCP(=O)(O)O)c2ccccc12
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)[PH](=O)(O)(O)CC=CN3
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)[PH](=O)(O)(O)CCN3
Invalid SMILES: O=C1c2c(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c2[nH]c2ccccc23)N1CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(c3ccccc3N(CCCC[PH](=O)(O)(O)O)SN1)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCN1C(=C2C=CC=C2)c2c1c1c3ccccc3n(CC[PH](=O)(O)(O)O)c1c1c3ccccc3n(CCCP(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3ncc(c4[nH]c5ccccc5c4c21)c1c3n1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c1c1c3ccc4c(ccn4CC4=CCC=C4)c1n(CCC[PH](=O)(O)(O)O)c32
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC(C3=C4C=C=CC3N4CC[PH](=O)(O)(O)O)=C(CN1)c1ccccc1-2
Invalid SMILES: O=P(O)(O)CCCN1c2c(c3c(c4ccccc4n3CCC[PH](=O)(O)(O)O)c3c2c2ccccc2n3CCCP(=O)(O)O)C12C=CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=Cc1c-2c(C2=CC=CC3N=CC23)n2c1P(=O)(O)(O)(O)CCC2
Invalid SMILES: O=P(O)(O)CCCNC1=C2C1=C(NCC[PH](=O)(O)(O)O)c1c(n(CCCP(=O)(O)O)c3ccccc13)-c1c2[nH]c2ccccc12
Invalid SMILES: O=P(O)(O)CCCCCn1c2ccc3c2c2c(ccn2CCC[PH](=O)(O)(O)O)c2c(c4ccccc4n2CCCP(=O)(O)O)c31
Invalid SMILES: O=P(O)(O)CCCn1c2cccc3c(C=C4C=CC5C(=C4)N5CC[PH](=O)(O)(O)O)c(c1-3)-c1c-2c2ccccc2n1CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CCC[PH]3=CC=C3)C3=CCC=C=C3)c3c4c(c21)C(=CC=CC3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3[nH]c4c(n(CCC[PH](=O)(O)(O)O)c5ccccc5c3c3[nH]c5ccccc5c3c21)=CC=4
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=CC1C=N1)N3CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1NC3=C(CC=CC3)C2=C(C2=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=[PH](O)CCNC1=C2C(NCC[PH](=O)(O)(O)O)=C2c2[nH]c3ccccc3c2-c2c1c1ccccc1n2CCCP(=O)(O)O
Invalid SMILES: Nc1c2c(NCCC[PH](=O)(O)(O)O)c3c-2n2c(cccc4c5ccccc5n(CCCP(=O)(O)O)c4c1-3)CCCCC2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=CC1C=N1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1cc(c1NCC[PH](=O)(O)(O)O)-c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c1c1c4ccccc4n(CCC[PH](=O)(O)(O)O)c1c1c4ccccc4n(CCCP(=O)(O)O)c31)C=C2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)CN3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c4c(ccn4CCC[PH](=O)(O)(O)O)c4c(c5ccccc5n4CCCP(=O)(O)O)c31)CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1c3c-2c(n1CCC[PH](=O)(O)(O)O)C(=C1N=C1C1C=CC=CC1)C=CC=C3
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=C1CC=NS1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C(N(CCO)C1=CC1)=C1C(NCC[PH](=O)(O)(O)O)=C1c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2cc3c1=C2c1c(c2ccccc2n1CCCP(=O)(O)O)C=C=C1CN(CC[PH](=O)(O)(O)O)C=31
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1NC1=C1C2=C(C2=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccc2c2c1c1c(NCC[PH](=O)(O)(O)O)c-1cc1c3ccccc3n(CCCP(=O)(O)O)c12
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c4c5c(c6c(c(c(c21)C=CP(O)CC5)n3CCC[PH](=O)(O)(O)O)=CCC=6)N4
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1C=NC3C=CC=C4NC4=C4C2=C(C1=CC=C3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(c21)=C4N(CCP(=O)(O)O)C1=CC=C1)C=C=CC1C=3N1CC[PH](=O)(O)(O)O
Invalid SMILES: Nc1c2cccc3n(CCCP(=O)(O)O)c-2c-3c2c(c3ccccc3n2CCCP(=O)(O)O)c2c1c1c(n2C[PH](=O)(O)(O)O)C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)C=C1
Invalid SMILES: N#CC1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(c2ccccc2)=CS1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)S1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=C(C(=O)O)C=C1
Invalid SMILES: N#Cc1ccc(C2=CC(=CC=[PH](=O)(O)O)C=C2)cc1
Invalid SMILES: N#CC1=CC=CC(c2ccc(C=[PH](=O)(O)O)cc2)=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2=CC=C(c3ccccc3)C=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CC(c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C2=CC=C=CC=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=c1ccc(C(F)(F)F)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(C2=CC=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: N#CC1=CC=C(C2=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(C#CC=[PH](=O)(O)O)cc2)cc1)C(=O)O
Invalid SMILES: O=P1(O)(O)=CC=C(c2ccc(-c3ccccc3)cc2)C=C1
Invalid SMILES: N#CC1=CC=C(C2=CC=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc([IH]C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#Cc1ccc(=[PH](=O)(O)O)cc(-c2ccccc2)c1
Invalid SMILES: N#Cc1ccc(-c2ccc(=[PH](=O)(O)O)cc(C(=O)O)c2)cc1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C2=CC=C(C(F)(F)F)C=CC=C2)C=C1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=C=C1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)C1C=CCC(=C1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)n1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=CC1
Invalid SMILES: O=P(O)(O)CCCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=CC1
Invalid SMILES: O=C(CCCn1c2ccccc2c2cc3c(cc21)Nc1ccccc1N3CCCCCO)OCCC=[PH](=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)C1C=CC(=C1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)On1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCCC[PH](=O)(O)(O)O
Invalid SMILES: N#CC(O)=Cn1c2ccccc2c2cc3c(cc21)c1ccccc1n3P(=O)(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)-c1cccc(c1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=[PH](O)(O)=CC=CCc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=[PH](O)(O)=CCc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccc3c4ccccc4[nH]c3c21
Invalid SMILES: O=[PH](O)(O)=CCn1c2c(c3ccccc31)C=Cc1ccccc1N2
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccccc2c2c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)[nH]c1c3ccccc3[nH]c21
Invalid SMILES: O=P(=O)(O)(O)Oc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc2c(c1)[nH]c1c3ccccc3[nH]c21
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCCCCCO
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c4ccccc4n(CC[PH](=O)(O)(O)O)c3cc21
Invalid SMILES: O=C(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc4n(C5=CC=CC5)cccc3-4)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(-c2ccc(N(C3=CC=C(c4ccccc4)PC=C3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(N4C=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC=C1)c1ccc(N(C2=CC=C2)c2ccc(-c3ccccc3)cc2)cc1)c1ccccc1
Invalid SMILES: O=P(O)(O)#CC(CO)=C1C=CC(c2ccc(N(C3=CC=C(C4=CC=C(c5ccccc5)CC=C4)CC=C3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccccc2)cc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccc4cc3-c3ccccc3N4)cc2)c2c1=CC=2
Invalid SMILES: O=[PH](O)(O)=CC(=C[IH]c1ccc(-c2ccc(-c3cccc(C4=CC=C=C4)c3)cc2)cc1)N1C=CC=C(O)C1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=CC1)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(N4C=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2c1[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1c2ccccc3n4c(ccc4ccc4ccc-4ccc12)=CC=CCC=CC=3)NC1=CC=CC1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)cc1)c1ccccc1
Invalid SMILES: O=P(O)(O)#CC1C=C2C(=CC=C3C=CC3=CC=CC=CC=NSN1)N(C1=CC=C1)c1ccc(cc1)-c1ccc2cc1
Invalid SMILES: O=P(O)(O)#CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCPCOC(=CC=C1C=CC(N(c2ccccc2)c2ccc3cccccc2-3)=C1)c1ccc(N=C2CC=CC2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPC1=CC=C(c2ccc(N(C3=CC=C3)C3=CC=C3)cc2)OCC=C1)c1ccc(N(C2=CC=C=C=C2)c2ccccc2)cc1
Invalid SMILES: O=P(O)(O)#CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4cc3-c3ccccc3N4)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)c2c1C=C2
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(-c2ccc(N(C3=CC=C=C(C4=C=CC=C4)C=C3)C3=CC=CC3)cc2)cc1)C1=CC=C=C1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC2=CC=C(C=C1)N1C=CCC=CC=CC=C21
Invalid SMILES: O=C(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(N(C4=CC=C4)C4=CC=CCC=C4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc2ccc2ccccc3cccccc(ccc4ccc4cccccc1=CC1=CC=CC=CC1)n32
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)c2ccccc12
Invalid SMILES: O=C(CCCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21)OCC#P(=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3cc(Cl)ccc3Sc3ccc(Cl)cc32)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3ccccc3Sc3ccccc32)cc1
Invalid SMILES: O=[PH](O)(O)=C1Sc2ccccc2N(c2ccccc2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2c3ccccc3Sc3ccccc32)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)Sc1ccccc1N2c1ccccc1

[13:03:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:45] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C(Cl)=C(Cl)C(Cl)=C1Cl
Invalid SMILES: O=[PH]1(O)(O)SC(C(F)(F)F)=C1Cl

[13:03:46] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(C(F)(F)F)cc1

[13:03:47] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1SC(Cl)=C1Cl

[13:03:48] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(P(=O)(=O)(O)O)cc1

[13:03:48] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1SC(C(F)(F)F)=C1F

[13:03:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:49] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:49] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1SC(F)(F)C(F)(F)C1(F)F
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C(F)(F)F)=C1
Invalid SMILES: O=[PH](O)(O)=C1C(F)C(F)(F)C1(F)F

[13:03:51] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C(F)C(F)(F)C(F)(F)C1(F)F

[13:03:51] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:51] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCN1C=CC=CC1
Invalid SMILES: O=P(=O)(O)(O)c1ccncc1

[13:03:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:52] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCNc1ncc[nH]1
Invalid SMILES: O=C(O)[PH](=O)(O)(O)O

[13:03:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:52] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)F)NC(F)(F)C(F)(F)C(F)(F)C(F)(F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)c1cc[nH]c1

[13:03:52] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(F)C(F)(F)C(F)(F)C(F)(F)F)cc1

[13:03:53] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C1=C(Cl)C(Cl)=C1Cl

[13:03:53] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(Cl)cc1

[13:03:54] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)Cn1ccnc1

[13:03:55] Explicit valence for atom # 8 P, 7, is greater than permitted

Invalid SMILES: O=C(O)Nc1ccc(P(=O)(=O)(O)O)cc1

[13:03:55] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: O=[N+]([O-])c1ccc(P(=O)(=O)(O)O)cc1

[13:03:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:55] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C1=C(N(F)CC(F)(F)F)C=C1
Invalid SMILES: Cn1cncc1P(=O)(=O)(O)O

[13:03:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:55] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1cn(C(F)(F)F)cn1
Invalid SMILES: O=P(=O)(O)(O)c1ncc[nH]1

[13:03:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:56] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1c[nH]cn1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(Nc2ncc[nH]2)cc1
Invalid SMILES: O=P(=O)(O)(O)CCN(CCO)Cc1nccn1C(F)(F)F

[13:03:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:56] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(O)Cc1ccncc1
Invalid SMILES: O=[PH](O)(O)=C1C=CN=C1

[13:03:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:57] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCN1CC=CC1
Invalid SMILES: O=P(=O)(O)(O)CCn1ccnc1

[13:03:57] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: N#CN(F)C1=C(P(=O)(=O)(O)O)C=C1

[13:03:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:57] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C1=C(C=C/C=C/C(F)(F)F)N1
Invalid SMILES: O=P(=O)(O)(O)CNc1ncc[nH]1

[13:03:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:57] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)NCCNc1ncc[nH]1
Invalid SMILES: O=P(=O)(O)(O)c1ccccc1

[13:03:58] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:03:58] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)NC1=C(CP(=O)(=O)(O)O)C=C1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1nccn1C(F)(F)F

[13:03:58] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:03:58] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:03:58] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc([PH](=O)(O)(O)O)cc1
Invalid SMILES: O=CN(F)c1ccc(P(=O)(=O)(O)O)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)F)NC(F)(F)C1(F)F

[13:03:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:59] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:03:59] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:03:59] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1cn(C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)C(F)(F)C(F)(F)F)cn1
Invalid SMILES: N#Cc1ccc(CP(=O)(=O)(O)O)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccncc1
Invalid SMILES: O=P(=O)(O)(O)c1cc[nH]c1C(F)(F)F

[13:03:59] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)F)N=C1

[13:03:59] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(O)CCN1CC=CC1

[13:04:00] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2cccc(F)c2)cc1
Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)C(F)(F)C(F)(F)F)N1

[13:04:00] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:04:00] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: Nc1[nH]c(OCP(=O)(=O)(O)O)nc1C(F)(F)F
Invalid SMILES: O=P(=O)(O)(O)c1nc(C(F)(F)F)c[nH]1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccncc1

[13:04:00] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: O=CN(F)C1=C(P(=O)(=O)(O)O)C=C1

[13:04:01] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C1=CC=C1

[13:04:01] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:01] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:04:01] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccccn1
Invalid SMILES: O=C1CCCN1CCP(=O)(=O)(O)O
Invalid SMILES: O=C(CCNc1ncc[nH]1)[PH](=O)(O)(O)Cl

[13:04:02] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:02] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:04:02] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C1=C(c2ccccc2Nc2cc[nH]c2)C=C1
Invalid SMILES: N#CC1=C(P(=O)(=O)(O)O)C=C1
Invalid SMILES: O=P(=O)(O)(O)CCN1CCOCC1

[13:04:02] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:02] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:04:02] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:04:02] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1nc(O)c(C(F)(F)F)n1C(F)(F)F
Invalid SMILES: Cn1nccc1CN(CCO)CP(=O)(=O)(O)O
Invalid SMILES: O=C(CCN1CC=CC1)[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1ccc(Br)cc1

[13:04:02] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:03] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C1=C(C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)C(F)(F)F)C1(F)F
Invalid SMILES: O=P(=O)(O)(O)c1ccc(C(F)(F)C(F)(F)F)cc1

[13:04:03] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:04:03] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:04:03] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:04:03] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(c1ccccc1)[PH](=O)(O)(O)O
Invalid SMILES: N#Cc1ccc(C[PH](=O)(O)(O)O)cc1
Invalid SMILES: O=C1NC(C(F)(F)F)=C(P(=O)(=O)(O)O)C1(F)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccccc1

[13:04:03] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:03] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:03] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc[nH]1
Invalid SMILES: O=P(=O)(O)(O)CCNc1nc(C(F)(F)F)c[nH]1
Invalid SMILES: O=[PH](O)(O)(O)C(O)=C1N=CC(O)=N1

[13:04:04] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(F)=C1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccccc1O

[13:04:04] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:04] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:04] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=N/C=C\c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1
Invalid SMILES: O=[PH]1(O)(O)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccccc1O

[13:04:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1cc(O)c(O)c(O)c1

[13:04:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=C=C=C1

[13:04:05] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=Cc1cc(O)c(O)c(O)c1

[13:04:05] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)NCc1ccccc1O
Invalid SMILES: O=[PH](O)(O)=C1C(F)=C=C=C1F

[13:04:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC=C1c1ccccc1

[13:04:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C(Cl)=CC(Cl)=C1Cl

[13:04:06] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:07] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC=CC1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(O)cc1

[13:04:07] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccccc1O

[13:04:07] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C=Cc1ccccc1

[13:04:08] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:08] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:04:08] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccccc1O
Invalid SMILES: O=Cc1c(O)c(O)c(O)c(O)c1P(=O)(=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1cc(O)ccc1O

[13:04:08] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)Nc1c(F)c(F)c(F)c(F)c1F

[13:04:09] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(F)(F)C=C1

[13:04:10] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:10] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(F)cc1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ncccc1O

[13:04:10] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(O)c1ccccc1

[13:04:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC=N1

[13:04:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2cccs2)s1
Invalid SMILES: O=P(=O)(O)(O)C=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=P(=O)(O)(O)C(=Cc1ccc(-c2cccs2)s1)c1cccs1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=C(O)C(=C/C=C\c1ccc(-c2cccs2)s1)P(=O)(=O)(O)O

[13:04:11] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:04:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:11] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCNc1sc(-c2cccs2)cc1C(F)(F)F
Invalid SMILES: O=P(=O)(O)(O)C(=Cc1ccc(-c2cccs2)s1)c1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccs2)s1

[13:04:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CC=Cc1ccc(-c2cccs2)s1

[13:04:12] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1cccs1)c1cccs1

[13:04:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:12] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:04:12] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1c(F)sc(-c2cccs2)c1F
Invalid SMILES: O=C(O)C(=Cc1ccc(-c2cccs2)s1)P(=O)(=O)(O)O
Invalid SMILES: O=C(O)c1cc(-c2cccs2)sc1P(=O)(=O)(O)O

[13:04:12] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:04:12] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:12] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: O=S(=O)(O)c1sc(-c2cccs2)c(P(=O)(=O)(O)O)c1Cl
Invalid SMILES: O=[PH](O)(O)(F)c1ccc(-c2cccs2)s1
Invalid SMILES: O=C(F)c1ccc(C(=C/C=C\C=C\C(F)(F)F)[PH](=O)(O)(O)O)cc1
Invalid SMILES: Nc1sc(-c2cccs2)c(C(=O)O)c1P(=O)(=O)(O)O
Invalid SMILES: O=P(=O)(O)(O)c1sc(-c2sc(F)c(F)c2F)c(F)c1F

[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCNc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2cccs2)s1

[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(-c2cccs2)cc1
Invalid SMILES: O=P(=O)(O)(O)/C=C/c1ccc(-c2cccs2)s1
Invalid SMILES: O=C(O)C(=C/C=C\c1ccc(-c2cccs2)s1)[PH](=O)(O)(O)O

[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 13 C, 4, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 14 C, 4, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 14 C, 4, is greater than permitted
[13:04:13] Explicit valence for atom # 13 C, 4, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:04:13] Explicit valence for atom # 8 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C1c2ccccc2-c2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Cc2ccccc21
Invalid SMILES: O=[PH]1(O)(O)c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccc(Br)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Sc2cc(Br)ccc21
Invalid SMILES: O=P(O)(O)CCN1c2ccccc2[CH2+]c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=c1[nH]c2ccccc2c2ccccc12
Invalid SMILES: O=P(O)(O)CCN1c2ccc(Br)cc2[CH2+]c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=C1Nc2ccccc2[SiH-]c2ccccc21
Invalid SMILES: O=[PH](O)(O)=NCN1c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(O)(O)CCN1c2ccc(Br)cc2[CH2+]c2ccc(Br)cc21
Invalid SMILES: O=P(O)(O)CCN1c2ccccc2[CH2+]c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccccc2Nc2ccccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccccc2Sc2ccccc21
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2cccc3cccc1c23
Invalid SMILES: O=C1c2ccccc2[PH](=O)(O)(O)c2ccccc21

[13:04:13] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCCCOc1cc2c(c3ccccc13)Sc1ccc(O)cc1S2
Invalid SMILES: O=[PH]1(O)(O)c2ccccc2Sc2c1sc1ccccc21
Invalid SMILES: O=[PH](O)(O)=C1c2c(sc3ccccc23)-c2sc3ccccc3c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2cc(Br)ccc2c2c3cc(S(=O)(=O)O)ccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3ccccc3ccc21
Invalid SMILES: Cn1c2ccccc2c2cc(C=CC=[PH](=O)(O)O)ccc21

[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)C=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1cccc(N(c2ccccc2)c2ccccc2)c1
Invalid SMILES: O=P(=O)(O)(O)CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)CP(=O)(=O)(O)O
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccccc2)cc1

[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1cccc(N(c2ccccc2)c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)(O)CC=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(CCCP(=O)(=O)(O)O)N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(CCCP(=O)(=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(C#N)=C(CP(=O)(=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(=O)(O)(O)CC1=C(N(c2ccccc2)c2ccccc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-n2c3ccccc3c3ccccc32)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-n2c3ccccc3c3cc(Br)ccc32)cc1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc2c1c1ccccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)(O)C1CN2CCC(CCO)(CC2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc3c4c(c2)CCCN4CCC3)s1
Invalid SMILES: O=[PH]1(O)(O)CN2CCC(CCO)(CC2)c2cc(-c3cccs3)ccc21

[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)C1CCCN2CCCC3=C2C(O)(c2cccs2)CCN3CC1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2cc3c4c(c2)CCCN4CCC3)s1
Invalid SMILES: O=[PH]1(O)(O)CCC2=C(C1)c1ccc(cc1)N2CCC1=CC=C1
Invalid SMILES: O=P(=O)(O)(O)C1C=CC2CCN(C1)C(N1CCC3=CCC1=C3)C2
Invalid SMILES: O=[PH]1(O)(O)CN2CCC(O)(CCO)CC2c2cc(-c3cccs3)ccc21
Invalid SMILES: O=[PH](O)(O)(c1cc2c3c(c1)CCCN3CCC2)c1cccs1
Invalid SMILES: O=[PH]1(O)(O)C=C2CCCN3CCCC(=C23)C=C1c1cccs1
Invalid SMILES: O=[PH]1(O)(O)CCN2CCC(O)(CC1)c1cc3ccsc3cc12
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)sc1c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2c(c3ccccc31)-c1ccccc1Sc1ccccc1-2
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)sc1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2c3sc4ccccc4c3ccc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)oc1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCc1ccc2c(c1)sc1c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccccc2c2sc3ccccc3c21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccccc2c2sc3ccccc3c21
Invalid SMILES: Cn1c2c3ccc(C=C=[PH](=O)(O)O)cc3c1=c1ccccc1=c1ccccc1=2
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c3ccccc4ccccc4c-3c2c1
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccccc3c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCCn1c2ccc3ccccc3c2c2c3ccc(O)cc3c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc2c(c1)-c1c-2c2ccccc2c2ccccc12
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc(C3CCCCC3)c3cccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)c2cccc3c(C4CCCCC4)ccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)C(=O)c2ccc(-c3cccc(O)c3)c3cccc1c23
Invalid SMILES: O=C1NC(=O)c2cccc3c(-c4ccc(O)cc4)ccc(c23)C(=O)C1=[PH](=O)(O)O
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc(-c3ccccc3)c3cccc1c23
Invalid SMILES: O=C1C(=[PH](=O)(O)O)N(C(F)(F)F)C(=O)c2ccc(-c3ccc(O)cc3)c3cccc1c23
Invalid SMILES: O=C(O)c1ccc2c3c(ccc(CNP(=O)(=O)(O)O)c13)C(=O)N(CCc1ccncc1)C2=O
Invalid SMILES: O=C1c2cccc3cccc(c23)C(NP(=O)(=O)(O)O)C(=O)N1CCc1ccncc1

[13:04:15] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)CNc1cc2c3c(c(NCO)cc4c3c1C(=O)C(=[PH](=O)(O)O)NC4=O)C(=O)N(CO)C2=O
Invalid SMILES: O=[PH](O)(O)=Cc1cccc2c3c(ccc12)=CC=c1ccccc1=c1ccccc1=3
Invalid SMILES: O=C(CCCCC=[PH](=O)(O)O)OC1=CC=c2ccc3c4c(ccc(c24)=C1)=c1ccccc1=CC=3
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)cc1

[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:15] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: N#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(CP(=O)(=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1)C(F)(F)F
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccc(O)cc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc3c(c2)-c2cc(-c4ccccc4)ccc2-3)cc1

[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(-c3cccc4nsnc34)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2cccc3nsnc23)cc1
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc(N(c2ccccc2)c2ccc(-c3cccc4nsnc34)cc2)cc1
Invalid SMILES: O=C1NC(=[PH](=O)(O)O)C(=O)c2ccc3c4c(ccc1c24)C(=O)N(c1ccccc1)C3=O
Invalid SMILES: COc1ccc(N(c2ccc(C=CC=[PH](=O)(O)O)cc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1

[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:16] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)c3nsnc23)cc1
Invalid SMILES: COc1ccc(N(c2ccc(C=CC=[PH](=O)(O)O)cc2)c2ccc(-c3ccc(-c4ccccc4)cc3)c3nsnc23)cc1
Invalid SMILES: O=[PH](O)(O)=CCSc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)c3nsnc23)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=CC2)c2ccc(-c3ccc(-c4ccc5[nH]snc4-5)cc3)cc2)=C1
Invalid SMILES: O=c1c(=[PH](=O)(O)O)c(=O)c2ccc3c4ccc5c(=O)n(CO)c(=O)c6ccc(c7ccc1c2c73)c4c65

[13:04:16] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)s3)s2)cc1

[13:04:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 41 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc3[nH]c4ccc(N(c5ccccc5)c5ccccc5)cc4c3c2)cc1
Invalid SMILES: N#CC(C#N)=Cn1c2ccc(N(c3ccccc3)c3ccccc3)cc2c2cc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)ccc21
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: C=CCN(C1=CC=C1)c1ccc(-c2ccc(-c3ccc(N(C4=CC=CCC4)c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(Oc3ccccc3)cc2)cc1

[13:04:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 4 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: CCC(C#N)=Cc1ccc(N2C=CC([PH](=O)(O)(O)CC(C)(C)C)=CC=C2c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Cc1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccc(C4=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=C1SC(=[PH](=O)(O)O)SC1=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1

[13:04:17] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:17] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C1C(=Cc2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)SC(=[PH](=O)(O)O)N1C(=S)CO
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3cccc(-c4ccccc4)c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-n3c4ccc(-c5ccccc5)cc4c4cc(-c5ccccc5)ccc43)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(-c3ccc4c(c3)sc3cc5ccc3[nH]cccccc3cccccc4n35)cc2)cc1
Invalid SMILES: O=C(C1=CC=C1)C1=CC(NC2=CC=C2)=C2C=C(O1)c1cc(OCCCP(=O)(=O)(O)O)ccc12
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccc3ccccc3c2c2c3ccccc3ccc21

[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)CCCCCn1c2ccccc2c2c3ccccc3ccc21
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)[nH]c1c3ccccc3ccc21
Invalid SMILES: O=[PH](O)(O)=Cc1cc2c(cc1O)[nH]c1ccccc12
Invalid SMILES: O=P(=O)(O)(O)Nc1ccc2c(c1)[nH]c1ccccc12
Invalid SMILES: COc1cc2[nH]c3ccccc3c2cc1PC=CC=[PH](=O)(O)O
Invalid SMILES: O=P1(O)(O)=CC=C(n2c3ccccc3c3ccccc32)C=C1
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2ccccc21
Invalid SMILES: O=P(O)(O)CCN1c2cccc(c2)-c2cc(C=[PH](=O)(O)O)ccc21
Invalid SMILES: O=P(=O)(O)(O)n1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1cc2c(cc1O)[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)[nH]c1ccccc12
Invalid SMILES: O=P(=O)(O)(O)CCCn1c2ccccc2c2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Br)cc2ncc=2c1

[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:04:18] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Cl)cc2Oc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCSc1ccc2c(c1)Nc1cc(Br)ccc1S2
Invalid SMILES: O=P(=O)(O)(O)CCN1c2ccc(Cl)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=P(=O)(O)(O)N1c2ccc(Br)cc2Sc2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(S(=O)(=O)O)cc2Sc2ccc(S(=O)(=O)O)cc21
Invalid SMILES: O=[PH](O)(O)=CN1c2ccccc2Sc2cc(Br)ccc21
Invalid SMILES: O=C(O)c1ccc2c(c1)N(P(=O)(=O)(O)O)c1ccccc1S2
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2ccc(Cl)cc21
Invalid SMILES: O=[PH](O)(O)=CN1c2ccc(Br)cc2Sc2ccc(Cl)cc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Sc2cc(Br)c(Br)cc21
Invalid SMILES: O=[PH](O)(O)=C1Nc2ccc(S(=O)(=O)O)cc2Sc2ccccc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3ccccc3Nc3ccccc32)cc1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)n1c2ccccc2c2cc(Cl)ccc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=c1[nH]c2ccc(Br)cc2c2ccc(Br)cc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccc(Br)cc2c2cc(Br)ccc21
Invalid SMILES: O=[PH](O)(O)=C/C=C/c1cc2n[nH]c3ccccc3c-2n1
Invalid SMILES: O=P(O)(O)CCn1c2ccc(P(=O)(=O)(O)O)cc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=C3C(O)=CC(O)=C32)cc1
Invalid SMILES: O=C(C=[PH](=O)(O)O)OCCOC(=O)n1c2ccccc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccc(Br)cc2c2ccc(Br)cc21
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc(Br)ccc21
Invalid SMILES: N#CC(C#N)=Cc1ccc2c(c1)c1cc(Br)ccc1n2CC=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccc(N(C4=CC=CC4)c4ccccc4)cc3)cc(=[PH](=O)(O)O)s2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C(C(F)(F)F)OC=C2)C2=CC=c3c2cccc3=CC=C2PC=CC3=CC=CC=CCC=CN32)=C1
Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc(-c3ccc([PH](=O)(=O)O)c4nsnc34)cc2)c2ccccc12
Invalid SMILES: O=[PH](O)(O)=c1cc(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)cc(C2=CC=C2)s1
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=C(O)C1=Cc2ccc(c3c(ccc4ccc-4cccc(=CC=CC4=C=C4)n2C2=CCC(=[PH](=O)(O)O)C=C2)C=3)OC1
Invalid SMILES: O=C(O)c1ccc(C#P(=O)(O)O)cc1N(c1ccccc1)c1ccc(-c2ccc(P(=O)(O)O)c3nsnc23)cc1
Invalid SMILES: O=C1C=C2C(N(c3ccccc3)c3ccc(-c4ccc(P(=O)(O)O)c5nsnc45)cc3)=CC=C(C#P(=O)(O)O)C12
Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc(-c3ccc([PH](=O)(=O)O)c4nsnc34)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(F)cc4)cc3)cc2)c2nsnc12
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2F)c2nsnc12
Invalid SMILES: O=[IH](O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)=C(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC(c4ccc(N=CC5=C=CC5)cc4)C=C3)cc2)=CC1

[13:04:23] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cccs1

[13:04:24] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1cccs1

[13:04:55] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1cscc1Br

[13:04:57] Explicit valence for atom # 8 P, 7, is greater than permitted

Invalid SMILES: O=S(=O)(O)c1ccc(P(=O)(=O)(O)O)s1

[13:04:58] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(C(Cl)(Cl)Cl)=C1

[13:05:18] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=C/C=C/C(C(F)(F)F)=CS1

[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(C1=CC=C1)=C1C=CC(c2ccc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=CO1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(C2=CC=C2)cc1

[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 30 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccccc2)cc1
Invalid SMILES: N#CCCCCCCCCCC(C#N)C=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N2C=CC=CC2)cc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C(c3ccc(-c4ccccc4)cc3)C2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1

[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CC(=CC=C1C=C(O)c2ccc(cc2)O1)C1=CC(c2ccc(-c3ccccc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccc(C4=CC=CC4)cc3)c3ccc(-c4ccccc4)cc3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=CC4)cc3)cc2)cc(C2=CC=C2)c1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(N(C2=CC=C(c3ccccc3)C=CC=C2)c2ccc(C3=CC=C3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=C1

[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(c3ccc(C4=CC=C4)cc3)c3ccc(C4=CC=CC4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CCC(C1=C=CC=C1)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)=CO1
Invalid SMILES: O=[PH](O)(O)=CC(=CC=C1C=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1)c1ccc(C2=CCC=C2)cc1

[13:05:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:23] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:05:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:23] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C(=Cc1ccc(N(c2ccc(-c3ccccc3)cc2)c2ccc(-c3ccccc3)cc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C2)c(-c2ccc(N(c3ccccc3)c3ccc(C4=CC=C=C4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(C=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)=CCO1)C1=C=CCC=C1
Invalid SMILES: O=[PH](O)(O)=CC(O)=C1C=CC(N(c2ccc(C3=CC=C(C4=CC=CC4)C3)cc2)c2ccc(-c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(c2ccccc2)=C1)c1ccccc1)C1=CC=CC(N(c2ccccc2)c2ccccc2)C=C1
Invalid SMILES: O=C(O)c1ccc(C(=Cc2ccc(-c3ccc(N(C4=CC=C4)c4ccccc4)cc3)cc2)C=[PH](=O)(O)O)cc1

[13:05:23] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:05:23] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[13:05:24] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:05:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:24] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: N#CPC(=Cc1ccc(C2=CC=C(C3=CC=CCC3)C=CC=C2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccccc3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(-c3ccc(C=CC=[PH](=O)(O)O)cc3)s2)s1)C(=O)O

[13:05:25] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:05:25] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:05:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1cccc(-c2ccc(C=[PH](=O)(O)O)s2)c1
Invalid SMILES: O=C(O)C1=CPC2=CC3=C(C=CC=CC=C2C3)N(c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(c4ccccc4)=CC=CC=C3)c2)cc1

[13:05:25] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C(=C1C=C(C2=CC(=[PH](=O)(O)O)C=C2)C1)c1ccc(-c2ccccc2)s1

[13:05:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:25] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(=CC(F)(F)F)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1-c1ccc(C2=CCC=C2)cc1

[13:05:25] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:05:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:25] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)s3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC(C2=CC=C(C3=CC=C=C3)[IH]C=C2)=CC(c2cccc(C3=CC=C3)c2)=CC=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(C3=CC(F)=CC(C4=CC=C4)C=C3)c(F)c2)cc1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(-c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3F)cc2)C=CP1
Invalid SMILES: O=C(O)C1=C(C2=CCC=C2)C=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1

[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 26 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CC=CC4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC=C(c4ccccc4)C=CC3)c2)cc1
Invalid SMILES: O=C1C=CC1=CC=C1C=CC1=C1C(Cl)=C1SC1=C(S(=O)(=O)O)C(Cl)=CC1=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccccc3)c2)cc1

[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cccc(C2=CC(c3ccccc3)=CC(c3ccccc3)=CC=C2)c1
Invalid SMILES: O=C(O)C1=CC=C(c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)CC=C1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(Cl)C(c2ccc(C3=CC=CC(Cl)C=C3)c(F)c2)S1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3cc(F)cs3)c(F)c2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(F)c(F)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC=C(C4=CC=C=C4)C=CC3)c2)cc1
Invalid SMILES: O=C(O)C1=CC(=[PH](=O)(O)O)S1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(C3=CC(F)=CC(F)C=C3)c(F)c2)cc1
Invalid SMILES: O=[PH](O)(O)=c1cc(-c2ccc(C(F)(F)F)cc2)sc(-c2ccc(C3=CC=C3)s2)c1

[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:26] Explicit valence for atom # 18 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CC=C4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC=CC(C4=CC=C4)=CC3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(C4=CCC=C4)cc3)c2)s1
Invalid SMILES: O=C(O)c1cccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)c1

[13:05:27] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1cc(C2=CCC2=CC=CC2C=CCCN2C2=CC=C2)cc(-c2ccc(C=[PH](=O)(O)O)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC=C(C4=CC=C4)C=CC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=C(c2ccc(O)c(Cl)c2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=CC3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccc(-c3ccc(C=[PH](=O)(O)O)cc3)s2)s1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(-c2ccc(-c3ccc(C(=O)O)s3)s2)cc1

[13:05:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=C3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C=CC=CC(C4=CC=CCC4)=CC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=C(c3ccc(-c4ccccc4)s3)C2)cc1

[13:05:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C=CC=CC(c4ccccc4)=CC3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(F)=CC(C4=CC=C4)C=C3)s2)cc1
Invalid SMILES: O=C(O)C1=CCC=C(N(c2ccccc2)c2ccc(-c3ccc(C=[PH](=O)(O)O)s3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N(c3ccccc3)c3ccccc3)c2)cc1
Invalid SMILES: O=C(O)C(=O)Sc1ccc(-c2cccc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-c4ccccc4)s3)s2)s1

[13:05:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:27] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-n3cccc(O)c4ccc3cc4)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(NC2=CC(c3ccc(C4=CC=C4)cc3)C=CC=C2)cc1

[13:05:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC=C(PC3=CC=C3)C=CC(C3=CC=CC=CC3)=C2)s1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-c2ccc(-c3cccs3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc(C2=CC=CC2)cc(-c2ccc(-c3ccccc3)cc2)c1

[13:05:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:28] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:05:28] Explicit valence for atom # 23 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC=CC(c4ccccc4)=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(N3C=CC4=CC=C3C=CC=C4)c2)cc1
Invalid SMILES: O=C(F)C1=CN(c2ccc(-c3ccc(C=[PH](=O)(O)O)s3)cc2)C=CC=CC=C[IH]1
Invalid SMILES: O=C[IH]C1=CC=C2C=Cc3c(ccc(C(=O)O)ccc(C4=CC(=[PH](=O)(O)O)C=C4)cc32)C1=O

[13:05:28] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:05:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=C(C2=CC=CC(C3=CC=CC3)C=C2)C=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(F)(F)C=C3)c2)cc1

[13:05:29] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:05:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C=C1C=CC(c2ccc(C=[PH](=O)(O)O)cc2)=CC(C2=CC=C(C3=CC=C=C3)[IH]C=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(PC3=CC=CC3)=CC(c3ccccc3)=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(Cl)cc2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CCC=C3)=CC(c3ccccc3)=CC=C2)cc1

[13:05:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC(C2=C(C3=CC=C3)C=CC2)=C(c2ccc(F)cc2)[IH]C=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(-c2ccc(-c3cccc(F)c3)c(F)c2)s1
Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(C3=CC=C=C3)c3ccccc3)cc2)S1

[13:05:29] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:05:29] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:05:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(-c3ccc(PC=[PH](=O)(O)O)cc3)s2)s1
Invalid SMILES: O=C(O)C1=CN(c2ccc(C3=CC(=[PH](=O)(O)O)S3)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccc(-c4ccccc4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C(F)(F)F)c2)cc1

[13:05:29] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:05:29] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:05:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:29] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:05:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(C2=CC=C(c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3C3=CC=C3)CC=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(C(=O)O)[IH]C=C(c4ccc(C5=CCC=C5)cc4)C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=CC3)cc(-c3ccc(C4=CC=CC(C5=CC=CC5)C=C4)cc3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC(C5=CC=C(C6=CC=C6)C5)C=C4)=C3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=C1CC=C(C2=C=CC=C2)C=C(c2ccc(-c3ccc(-c4ccc(-c5ccccc5)cc4)cc3)cc2)S1
Invalid SMILES: O=[PH](O)(O)=C1C=C[IH]C(c2ccc(C3=CC=C(c4ccc(C5=CC=C=C5)[pH]4)C=CC3)cc2)=C(C2=CC=CC2)S1
Invalid SMILES: O=C(O)c1cc(C=[PH](=O)(O)O)cc(-c2ccc(C3=CC=CC(c4ccc(C5=CC=CCC=C5)cc4)C=C3)cc2)c1

[13:05:30] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C(=C1CC(=[PH](=O)(O)O)S1)c1ccc(-c2ccc(-c3ccccc3)s2)s1
Invalid SMILES: O=C(O)c1ccn(-c2ccc(C3=CP(=O)(O)(O)=CC(c4ccc(C5=CC=C5)cc4)=C3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(c4ccc(-c5ccccc5)cc4)C=CC=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CC=C(C3=CC=C(C=[PH](=O)(O)O)C=C(c4ccc(C(=O)O)cc4)S3)CP2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=C3)cc(-c3ccc(C4=CC=C(C5=CC=C5)PC=C4)cc3)c2)cc1
Invalid SMILES: O=C(F)C(=C1C=C(C2=CC(=[PH](=O)(O)O)C=C2)C1)c1ccc(-c2ccc(Cl)cc2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)c(C3=CC(C4=CC(n5cccc5O)CC=C4)C=C3)s2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3cc(F)cc(-c4ccc(N(C5=CC=C5)C5=CC=CC5)cc4)c3)c2)cc1

[13:05:30] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=CC1=CC=C(c2ccc(-c3ccc(C4C=CC(c5ccc(C=[PH](=O)(O)O)cc5)=C4)cc3F)cc2)C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccc(C4=CCC=C(C5=CC=C5)PC=C4)cc3)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(-c3cccc(-c4ccc(C=[PH](=O)(O)O)cc4)c3)cc2O)cc1
Invalid SMILES: O=C(O)c1cc(-c2ccc(C=[PH](=O)(O)O)cc2)cc(-c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)c1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(-c3cc(C4=CCC=C4)cc(-c4ccc(C=[PH](=O)(O)O)cc4)c3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(=[PH](=O)(O)O)sc2-c2cccc(-c3ccc(C4=CC=C4)c(F)c3)c2)cc1

[13:05:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:05:30] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(C3=CC=CC=CC=C3)cc(-c3ccc(C4=CCC=C4)cc3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC=C(n5cccc5)C(F)C=C4)PC=C3)s2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2sc(C=[PH](=O)(O)O)cc2C2=CC(C3=CC=C(c4ccc(C5=CC=C5)cc4)C3)=CC2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(C4=CC=C(C5=CC=C5)C4)C=CC3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc(c1)-c1ccc(cc1)-c1ccc(cc1)-c1ccc(cc1)-c1ccc(cc1)C=CCC=CC=C2
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C=CC3=CC(c4ccc(C5=CC=C5)cc4)=C2C=CC=C3O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(O)c(-c3ccc(-c4ccc(Cl)cc4)s3)c(C3=CCC=C3)c2)cc1

[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2=CC(c3ccc(C4=CC(C5=CC=C5)PC=C4)c(F)c3)C=C2)=C1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(-c3ccc(C4=CC=C(C5=CC=C5)BC=C4)cc3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(-c4ccc(P)cc4)cc3)cc(-c3cccc(O)c3)c2)cc1
Invalid SMILES: N#Cc1ccc(-c2ccc(C(C(=O)O)=C3C=C(C4=CC(=[PH](=O)(O)O)C=C4)C=C3O)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3ccccc3C3=CC=C(C4=CC=CC4)PC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(F)c2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C2)cc(-c2ccc(C3=CC(C4=CC=C(C5=CC=C5)C4)C=C3)cc2O)c1

[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3ccccc3C3=CCC=C(C4=CC=C4)PC=C3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(C3=CC=CCC=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)c(F)c3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(c4ccc(C5=CC=C5)cc4)PC3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc(C2=CC=C=C2)cc(-c2ccc(C3=CC=C(C4=CCC=C4)C=CC3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(C4=CCC=C4)C=C3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(C=[PH](=O)(O)O)cc3)c2)cc1
Invalid SMILES: O=P1(O)(O)=CC(c2ccccc2)=CC(c2ccc(N(C3=CC=CC(C4=CC=C4)C=C3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(c3cccc(-c4ccc(C5=CCC=C5)cc4)c3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC(c4ccc(C5=CC=C5)cc4)C=CC=C3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(C3=CC=C(c4ccc(C5=CC=C5)cc4)C=CC=C3)cc2)c(C2=CC=C2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(F)=C(c3ccc(-c4ccccc4)s3)C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(-c3cccc(-c4ccccc4)c3)c2)cc1

[13:05:31] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:31] Explicit valence for atom # 9 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccccc3)c2)cc1C1=CC=C(C2=CC=C(C3=CC=C3)C2)C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=CC3)C=CC(c3ccc(-c4ccc(-c5ccccc5)cc4)cc3)=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(c2ccc(C3=CC=C3)cc2)SC(C2=CC=C(c3ccccc3)C=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(C3=CC(C4=CCC=C4)=C3)cc2)c(-c2ccc(C3=CCC=C3)cc2)c1
Invalid SMILES: O=C(O)c1ccc(C2=CP(=O)(O)(O)=CC(C3=CC(C4=CC(c5ccc(C(=O)O)cc5)C=C4)C=C3)=C2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CC(C=[PH](=O)(O)O)=CC=C(c3ccc(-c4ccc(C5=CC=C5)cc4)s3)S2)cc1

[13:05:32] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC=C3)C=CC(c3ccc(C4=CC=C(C5=CC=CCC5)PS4)cc3)=C2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C3=CC(c4ccc5c(c4)CC5=CC=C4C=CC=C4)=C3)ccc(=[PH](=O)(O)O)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(c4ccc(-n5ccc(O)c5)cc4)=C3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(C4=CC=C4)cc3)cc(-c3ccc(C4=CCC=C4)cc3)c2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=CC(C4=CC(F)C(F)=C(F)C4=C(F)C4=CC=C4)=CC3)s2)cc1
Invalid SMILES: O=C(O)C1=C(C2=CC(c3ccc(C4=CC=C4)cc3)=C2)C=C(c2ccc(C=[PH](=O)(O)O)s2)C=C[IH]1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(F)=CC(F)C3=CC=C3CC3=C(F)C3=CC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)c2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(C3=CC(F)=C(c4ccc(C5=CC=C5)cc4)[IH]C=C3)c2)cc1

[13:05:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cccc(C3=CC(F)=C(C4=CC=C(N=C(O)C5=CC=C5)C4)CC=C3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC(C3=CC(F)=C(c4ccc(C5=CC=C5)cc4)C=CC3)C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(C2=CP(=O)(O)(O)=CC(C3=CC(C4=CC=C(C5=CC=CCC=C5)C(C5=CC=C5)CC4)=CC3)=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccccc3)cc(-c3ccc(C4=CC=C4)cc3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(-c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)ccc2C2=CC=C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(C4=CCC=C(C5=CC=C5)C=C4)cc3)c(C3=CC=CCC3)c2)s1
Invalid SMILES: O=C(O)c1ccc(-c2cc(C=[PH](=O)(O)O)cc(-c3ccc(-c4ccc(C5=CC=C=C5)cc4)c(F)c3)c2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2cc(F)c(-c3ccc(-c4ccccc4)s3)c(C3=CCC=CC3)c2)cc1

[13:05:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:05:32] Explicit valence for atom # 15 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2cc(=[PH](=O)(O)O)cc(C3=C(C4=CC(F)C(F)=C(C5=CC=C5)N4)C=C3)s2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2cc(-c3ccc(C=[PH](=O)(O)O)cc3)cc(-c3ccc(C4=CC=CC4)cc3)c2)cc1
Invalid SMILES: O=P1(O)(O)=CC(c2ccccc2)=C(c2ccc(N(c3ccccc3)c3ccc(N(C4=CC=C4)c4ccccc4)cc3)cc2)C=C1

[13:05:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:33] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC(c2ccc(N(C3=CC=C=C3)C3=CC=CC3)cc2)=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cc(-c2ccc(N(C3=CC=C3)C3=CCC=C=C3)cc2)cc(-c2ccc(N(C3=CC=C=C3)c3ccccc3)cc2)c1
Invalid SMILES: O=P1(O)(O)(C2=CC=C2)C=CC(c2ccc(N(C3=CC=CC3=CC=C3C=CN3c3ccccc3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=C1SC2=C3C(=CC=c4ccc(n4C4=CC=C4)=CC=CC=CC=C2)CC=CC=C2C=CC=CC=c4ccc(n42)=CC=C31

[13:05:33] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC(N(C2=CCC=C2)C2=CC=CC2)=C(c2ccc(N(c3ccccc3)c3ccc(C4=CC=C4)cc3)cc2)C=C1

[13:05:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(C3=CCC=C(N(C4=CC=CC4)C4=CC=CC4)C=C3)c3ccccc3)cc2)C=C1c1ccccc1
Invalid SMILES: O=P1(O)(O)=CC=C(C2=CC(N(C=C3CC=CC3)C3=CCC=C3)=CC(c3ccc(N(C4=CC=C=C4)C4=CC(O)C=CC4)cc3)C=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=C(c2ccc(N(c3ccccc3)c3ccc(N(C4=CC=C4)C4=CC=CC4)cc3)cc2)C=C(C2=CC=CC2)C1
Invalid SMILES: O=P1(O)(O)=Cc2cccccccc3ccc(ccc4cccccc5c(ccc6ccc6ccc1c24)OC5)n3C1=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC(C1=CC=CC1)c1ccc(N(c2ccccc2)c2ccc(-c3ccc(N4C=CC=CC4)cc3)cc2)cc1

[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC2=c3c1ccc1ccc4n1c(cccccc3=CC=c1ccc(n1C1=CC=C1)=CC=CC=CC=C=C2)C=CC=CC=4

[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1cc(-c2cccc(N(C3=CC=CC3)c3ccccc3)c2)cc(-c2ccc(N(C3=CC=C3)c3ccccc3)cc2)s1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-n4c5ccccc5c5ccccc54)s3)s2)cc1
Invalid SMILES: N#Cc1ccc(C=[PH](=O)(O)O)cc1-c1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)s2)s1

[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 38 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:35] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:05:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:05:35] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:05:35] Explicit valence for atom # 34 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(-c3ccc(-n4c5ccccc5c5ccccc54)cc3)s2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C2=CC=C2)c(-c2ccc(-c3ccc(-n4c5ccccc5c5ccccc54)s3)s2)c1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC(C3=CCC=C3)C2)C2=CC21
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)CC1=CCC1=CC=C1
Invalid SMILES: O=[PH]1(O)(O)CCC(c2ccc(N(c3ccccc3)c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)CC1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)CC1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCCC2)C2=CC1=CC2
Invalid SMILES: O=C1C(c2ccc(N(c3ccccc3)c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)CCC[PH]1(=O)(O)O
Invalid SMILES: O=[PH]1(O)(O)CCCC(F)(c2ccc(N(c3ccccc3)c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)CC1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCCC2(F)C2=CC=C2)CC1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)C2=CC1=CCc1cccc2c1
Invalid SMILES: O=Cc1ccc(N(c2ccc(C=O)cc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccc(C#P(=O)(O)O)cc5)cc4)CCCCC3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)C2=CC=C21
Invalid SMILES: O=[PH](O)(O)=CC(c1ccc(N(C2=C=C2)c2ccccc2)cc1)c1ccc(N(C2=CCC=C2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1CCC(C2(c3ccc(N(c4ccccc4)c4ccccc4)cc3)CCCC2)CC1=CC1=CC=C1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccccc5)cc4)CCCC3)cc2)cc1
Invalid SMILES: O=Cc1ccc(N(c2ccc(Cl)cc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccc(C#P(=O)(O)O)cc5)cc4)CCCCC3)cc2)cc1
Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(C3(c4ccc(N(c5ccccc5)c5ccc(C#P(=O)(O)O)cc5)cc4)CCCC3)cc2)cc1

[13:05:35] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: N#CC1=CC(=CC=[PH](=O)(O)O)C=C1

[13:05:38] Explicit valence for atom # 9 P, 7, is greater than permitted

Invalid SMILES: N#CC1=CC=CC(=CC=[PH](=O)(O)O)C=C1

[13:05:44] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=CPc1ccc(Br)cc1

[13:06:05] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CPc1ccc(C(F)(F)F)cc1

[13:06:07] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C(F)(F)F)C=C1

[13:06:11] Explicit valence for atom # 9 P, 7, is greater than permitted

Invalid SMILES: O=Nc1ccc(/C=C/C=[PH](=O)(O)O)cc1

[13:06:13] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C/C=C/c1ccc(Br)cc1

[13:06:16] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(C(F)(F)F)cc1

[13:06:19] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=CPc1ccccc1Br

[13:06:20] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1ccc(C(F)(F)F)cc(C(F)(F)F)c1

[13:06:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CS1

[13:06:34] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(C#P(=O)(O)O)cc1

[13:06:43] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1c(F)c(F)c(F)c(F)c1F

[13:06:43] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(Br)cc1

[13:06:50] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: N#CC1=CC(O)=CC(=CC=[PH](=O)(O)O)C=C1

[13:06:52] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: N#CC1=C=CC=CC(C=CC=[PH](=O)(O)O)=C1

[13:06:57] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C/C=C\c1ccc(O)cc1

[13:06:57] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(C(F)(F)F)=C1

[13:06:59] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:06:59] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(C=CC=[PH](=O)(O)O)cc1
Invalid SMILES: N#CC(Cl)=CC=C1C(=CC=[PH](=O)(O)O)C=CC1=CC(=CCO)C(=O)O

[13:07:05] Explicit valence for atom # 9 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(/C=C\C=[PH](=O)(O)O)cc1

[13:07:10] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)=Cc1ccc(PC=CC=[PH](=O)(O)O)cc1

[13:07:11] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Cl)cc1

[13:07:14] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=CPc1ccc(O)cc1

[13:07:15] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CPC=CPc1cccc(N(CCO)CCO)c1

[13:07:17] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)=Cc1ccc(/C=C/C=[PH](=O)(O)O)cc1

[13:07:20] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C/C=C/c1ccccc1

[13:07:23] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C/C=C\c1c(F)c(F)c(F)c(F)c1F

[13:07:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C=C2)c2ccc(N(c3ccc(C4=CC=C=C4)cc3)c3ccc(C4=CC=C4)cc3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(C3=CCC=C3)c3nsnc23)cc(-c2ccc(N(C3=CC=C=C3)C3=CC=C3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=c1ccc(C2=CC=C=C2)cc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=C1C=C(N(c2ccc(O)cc2)c2ccc(N(C3=CC=C=C3)C3=CC=CC3)cc2)C=C(C2=CC=CCC=C2)CC1

[13:07:25] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:07:25] Explicit valence for atom # 17 P, 7, is greater than permitted

Invalid SMILES: O=CC1=CC(=[PH](=O)(O)O)NC1=CPc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12
Invalid SMILES: O=c1cccc2c3ccc(n12)Cc1c(ccc(=[PH](=O)(O)O)[nH]c1=S)-c1ccc(cc1)N3C1=CC=C1

[13:07:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:26] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)c2cccc(O)c2)cc1)C1=CCC=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1cccc(-c2ccc(N(C3=CC=CC3)c3ccc(C4=CC=C4)cc3)cc2)c1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2CC=CC=C=CC3=CC=C3c3ccc(cc3)N(c3ccc(-c4ccccn4)cc3)c3ccc2cc3)=CC1

[13:07:26] Explicit valence for atom # 49 P, 7, is greater than permitted
[13:07:26] Explicit valence for atom # 33 P, 7, is greater than permitted

Invalid SMILES: CCC(=CC(=C1C=CC(c2ccc(N(C3=CC=CC3)c3ccccc3)cc2)=C1)c1ccc(N2C=C=CC=CC=CC=C3C=CC=C32)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=C(O)C1=CC=C2C=CC(O)=CC=C3C=CC3=CC=c3ccccc3=CC=C3C=C(C=C(C=[PH](=O)(O)O)CC=CC=C1)N23

[13:07:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:27] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3ccc4ccccc4cccc(n23)=CC=c2ccc3n2C(=C=CC=CC=C=C1)CC=CC=CC=3
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)C2=CC=C2)cc1

[13:07:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:27] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CC=CC(c2ccccc2)C=C1)=C1C=CC(N(C2=CC=CC=CC=C2)C2=CC=C2)=CC1)N1C=CC=CC=C=CC1

[13:07:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:28] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(N(c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)c2ccc(N(C3=C=CCC3)c3ccccc3)cc2)=C1
Invalid SMILES: O=P1(O)(O)=CC=C(c2ccc(N(C3=CC=C=C3)c3ccc(-c4ccc(N(C5=CC=C5)c5ccccc5O)cc4)cc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(N(CC=[PH](=O)(O)O)C2=CC(C3=CC=C=C3)C=CC=C(c3ccc(N(C4=CC=CC4)c4ccccc4)cc3)C=C2)cc1

[13:07:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C3C=CC(=C3)N(c3ccccc3)c3ccc(cc3)N(c3ccccc3)C3=CC=C(C=CC=CC2C=CC=CCC=C=CC=C1)C3
Invalid SMILES: O=[PH](O)(O)=CC(=CC1=C(O)C1=CC(=CC=C1C=CC=C1O)c1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)c1ccccc1

[13:07:28] Explicit valence for atom # 48 P, 7, is greater than permitted
[13:07:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:28] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:07:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: C=CC(=CC(=C1C=CC(O)=C1)c1ccc(N(C2=CC=C2)C2=CC=CC(c3ccc(N(C4=CCC=C4)C4=CC=C=CC4)cc3)C=C2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(c2ccccc2)c2ccccc2)=C1)c1ccccc1)N(C1=CCC=C1)C1=CC=CC1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)C2=CC(c3ccc(N(C4=CC=C4)C4=CC=CC4)cc3)C=C2)C=CCO1
Invalid SMILES: O=P1(O)(O)=CC=C(N(C2=CC=C=C2)c2ccc(N(C3=CC=CC(C4=CC=C4)C3)c3ccccc3)cc2)C=C1

[13:07:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:29] Explicit valence for atom # 31 P, 7, is greater than permitted
[13:07:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=C3)c3ccc(-c4ccc(N(C5=CC=C5)C5=CC=C5)cc4)cc3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1cccc(N(c2ccccc2)c2ccccc2)c1)c1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)c1ccc(N(C2=CC=C2)C2=CC=CC2)cc1
Invalid SMILES: O=C1C=CC(N(C2=CC=CC=CC=C2)c2ccc(-n3cccc3)cc2)C=CC(=CC(C=[PH](=O)(O)O)c2ccccc2)O1
Invalid SMILES: O=[PH](O)(O)=CC(=C1C=CC(N(c2ccccc2)c2ccc(O)cc2)=C1)c1ccc(N(C2=CC=CC2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3n2C(=CC=C2C=CC2=CC=C=CC1=CC=C1C=CCC=C1)C=CC=CC=3

[13:07:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC=c2ccc3n2C(=CC=c2ccc(n2C2=CC=CCC2)=CC=CC=C=CC1)C=CC=CC=c1ccccc1=CC=3
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C3C=CC(=C3)c3ccc(cc3)N3CC3=CC=CCC2=CC=c2ccc3n2C(=CC=CC=CC=C1)C=CCC=3
Invalid SMILES: O=[PH](O)(O)=Cc1cccccccccc2c3oc(c(n(C4=CC=CC4)c4ccc(cc4)c4cccc(c1)c4)=CC=3)=CC=C2
Invalid SMILES: O=[PH](O)(O)=CC1=CC(=C2C=CC(N(c3ccccc3)c3ccccc3)=C2)C2=CC=C(CC2)C2=CC=C(C=CC3(O)C=C=CN1C=CCC=C3)CC=C2

[13:07:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:29] Explicit valence for atom # 42 P, 7, is greater than permitted
[13:07:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC=CC=C2)C2=CC=CC2)=C1)c1ccc(N2C=CC=CC2)cc1)C1=CC=C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C2)c2ccc(N(C3=CC=C=C3)c3ccc(C4=CC=CC4)cc3)cc2)=CC1
Invalid SMILES: O=C(O)C(C=C1C=CC(c2cccc(N(c3ccccc3)c3ccc(N(C4=CC=C=C4)c4ccccc4)cc3)c2)=C1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(N(C2=CC=CCC=C2)C2=CC=CC2)cc1

[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(C=C1C=CC(N(C2=CC=C(C3=CC=C=C3)C=CC=C2)c2ccc(C3=CC=C=C3)cc2)=C1)C1=CC=C=CC1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(C2=CC(C3=CCC=C3)C=C2)N(c2ccc(N(c3ccccc3)c3ccccc3)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2cccc(N(C3=CC=C=C3)c3ccc(-c4ccc(-c5ccc(C6=CC=C6)cc5)cc4)cc3)c2)=CC1

[13:07:30] Explicit valence for atom # 47 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 2 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)C=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: N#C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2C=CC=CC=C=CC=C3C=CC=CC=C4C5=CCC=CC6=CC=C(C=CC2=CC=C3O6)N45)=CC1
Invalid SMILES: O=P(=O)(O)(O)C1=CC=C(N2C=C=CC=CCC=CC=c3ccc(n3C3=CC=CC3)=CC=C3C(OC4=CC=CC4)=CC=C32)C=C(O)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccccc2c(ccc3oc(c1)=C3)OC1=CC=C(Oc3ccccc3)N3C(=CC=CCC=CC=2)C=CC=C13
Invalid SMILES: N#CC[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)(c1ccccc1)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)C=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1)=[PH](=O)(O)O

[13:07:30] Explicit valence for atom # 42 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 52 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 42 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=CC1=CC(=CC=C(OC2=CC=C(Oc3ccccc3)N(C3=CC=C3)CC=C2)C2=CC=C2)O1)N1C=C=CCCCC=CC1
Invalid SMILES: N#CCCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=C(Oc3ccc(N(C4=CC=C=C4)C4=CC=C4)cc3)N3C=CCC=C=CC=C3C1)O2
Invalid SMILES: O=[PH](O)(O)(c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1)n1cccc1
Invalid SMILES: C=CCCC(=CC1=CC(=CC=C2C=C=CCC=C=C=C3CC=CC=C4C=CCC=C5C=CC(=CC=C6OC3=CC=C6O2)N4N5c2ccccc2)O1)C=[PH](=O)(O)O
Invalid SMILES: N#CC(C#N)C=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)Oc1cc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)ccc1O
Invalid SMILES: O=P(=O)(O)(O)Oc1cc(N(c2ccccc2)c2ccccc2)ccc1Oc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(C#N)C=CC1=CC=CC=CC(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)=C1
Invalid SMILES: N#CCCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[13:07:30] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:07:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 42 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 3 P, 7, is greater than permitted

Invalid SMILES: N#CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: O=CC[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[13:07:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 46 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC=C(O)C(N(C2=C=C=CC2)C2=CC=C3OC4=CC=C5OC4=CC=CC5=CC=C4C=CC4=CC=CCC=CC=C32)=C1
Invalid SMILES: N#CCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=C(O)CC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C=CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC=C3Oc4ccc(cc4)N(c4ccccc4)C2=CC=CC2=CC=CCC=CC=C(C=CC1O)N23
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1)C=C1C=CC=CC1
Invalid SMILES: N#CC(C#N)=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: N#CCCCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[13:07:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 5 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)N(c1ccccc1)c1ccc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: N#CCCCCCC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CCC=CP[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccccccc2cccccc3cccc4c(Oc5ccccc5)ccc4oc(ccc4cc(c1)o4)n23
Invalid SMILES: N#CC=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(=O)C=P(=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[13:07:31] Explicit valence for atom # 48 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:31] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 2 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 48 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)CC=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1C#P(=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=CC(=C1C=CC=C1)N(C1=CC=CC=CC=C1)C1=CCC=C1)n1cccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1c2c3ccccccccc(n1-3)C=CC=CC=C1C=CC=CC=c3ccc(n31)=CC2)C1=CC=C=C1
Invalid SMILES: O=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=C3OC4=CC=C(Oc5ccccc5)C(=CC=C4)C3=CC=c3ccc4n3C(=CCC=C=C=CC=C1)C=CC=CC=4)O2
Invalid SMILES: O=CC(=O)C(=O)C=Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1OP(=O)(=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1

[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC(=CC=c3oc4c5n(c(cccccc3=CC=CC=CC=CC1)C=CC=5)C(Oc1ccccc1)=CC=4)O2
Invalid SMILES: N#CC(=CC(=C1C=CC(N(C2=CC=C2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CCC=C1)C1=CC=CC1)C1=CC=C=C1
Invalid SMILES: N#CCC=C[PH](=O)(O)(O)c1ccc(N(c2ccccc2)c2ccc(Oc3ccc(N(c4ccccc4)c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=P1(O)(O)=CC=C(O)C(n2cccccccc3c(Oc4ccc(N(C5=CC=C5)c5ccccc5)cc4)ccc2-3)C=C1
Invalid SMILES: O=P(=O)(O)(O)C(=Cc1cc(O)cc2ccc(Oc3ccccc3)c3ccccccc-3n12)N1C=C=CC1
Invalid SMILES: O=P1(O)(O)=CC(C2=CC=C=C2)=CC(N(C2=CC=C(C3=CC=C3)OC3=CC=C(C=CC=C3)C=C2)c2ccccc2)=C1

[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=c2ccc(n2N(C2=CC=C2)C2=CC=CC2)=CC=C2OC3=CC=C(C=CC=CC(O)=CC=C2C=C1)C=CC=C3
Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CCC=C1)=C1C=CC(N(C2=CC=CC2)c2ccccc2)=C1)N(C1=CC=CC1)c1ccccc1
Invalid SMILES: O=P(O)(O)#Cc1cc(Oc2ccc(N(c3ccccc3)c3ccccc3)cc2)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(O)CCC=Cc1c(CCC=[PH](=O)(O)O)c(-c2ccccc2)cc2c3cc(-c4ccccc4)ccc3n(-c3ccccc3)c12
Invalid SMILES: O=[PH](O)(O)=CCc1cc2c(cc1-c1ccccc1)c1cc(-c3ccccc3)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc2c(c1)c1cc(-c3ccccc3)ccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc(-c3ccccc3)cc2c2ccc(-c3ccccc3)cc21
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(-n2c3ccc(-c4ccccc4)cc3c3cc(-c4ccccc4)ccc32)cc1
Invalid SMILES: O=Cc1c(CCC=[PH](=O)(O)O)c(-c2ccccc2)cc2c3cc(-c4ccccc4)ccc3n(-c3ccccc3)c12

[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:32] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1cc(Cl)ccc1n2-c1ccccc1
Invalid SMILES: N#CC(=Cc1ccc2c(c1)c1cc(C=[PH](=O)(O)O)ccc1n2-c1ccccc1)C(=O)O
Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=P1(O)(O)=Cc2c(n(-c3ccccc3)c3ccccc23)C=C1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc2c(c1)c1ccccc1n2-c1ccccc1
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(-n2c3ccccc3c3ccccc32)cc1

[13:07:33] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 19 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)c1ccc(N2C=CC3=CC4=C2C3=C2C=CC=C[PH]24(=O)O)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)c1ccccc1n2-c1ccc(Cl)cc1
Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)PCC=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2c(N(c3ccccc3)c3ccccc3)cccc2[nH]1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#Cc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#CPC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=CC=CC=C2)C2=CC=CC2)cc1)PC=[PH](=O)(O)O
Invalid SMILES: N#CPC1=CC=C(N(c2ccccc2)c2cccc(C=[PH](=O)(O)O)c2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1

[13:07:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CBc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CBC(C#P(=O)(O)O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#C/C(C#P(=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)C=CC=C1)C1=CC(=[PH](=O)(O)O)C=C1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(F)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=C=C2)c2ccccc2)cc1)C(=O)OCC=[PH](=O)(O)O
Invalid SMILES: N#CC1=C=CC=C(N(C2=CC=C(C(=O)O)OC=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=C(O)C1=Cc2ccc(n(-c3ccc(C=[PH](=O)(O)O)cc3)ccccc2=O)C=C1
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1cccc[pH]c(C2=CC=C=C2)cc1
Invalid SMILES: N#CPC(=Cc1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=C/C(=C\c1ccc(O)cc1)c1ccc(N(C2=CC=C=C2)c2ccccc2)cc1

[13:07:33] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:07:33] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 30 P, 7, is greater than permitted

Invalid SMILES: N#CPN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(C2=CC=C2)cc1
Invalid SMILES: N#CC(=CPc1ccc(N(C2=CC=CC=CC=C2)c2ccccc2)cc1)OCC=[PH](=O)(O)O
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C\c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(O)cc2)cc1
Invalid SMILES: O=P(O)(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(O)cc2)cc1
Invalid SMILES: O=C(F)c1ccc(N(C2=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: N#Cc1ccc(=[PH](=O)(O)O)cc(N(C2=CC=C2)c2ccccc2)c1
Invalid SMILES: N#C/C(=C/c1ccc(N(C2=CC=C(C(=O)F)C=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cc1)C(=O)O
Invalid SMILES: N#Cc1ccc(N(C2=CC=C(C(=O)O)C=CC=C2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C(=O)F)C2=CC(=[PH](=O)(O)O)C=C2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C(C=C(O)O)/C=C\C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CCPC1=CC=CC2=CC=CC=CC(=CC=C3C=CC=CC=CC=CP3)N21
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: N#CPc1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=Pc1ccccc2ccc(c1)-c1ccc(cc1)C=CC=CC=CN2c1ccc(C=[PH](=O)(O)O)cc1

[13:07:34] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 16 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=CC2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(C3=CC(F)=C3)cc2)[PH]2=CC=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(N(C2=CC=CSC=C2)c2ccc(O)cc2)c1
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(C2=CC=C2)cc1
Invalid SMILES: N#CPC(C#P(=O)(O)O)=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: N#CCC(C=C(C#N)C#N)=Nc1cc(C=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: N#[PH]c1ccc(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: O=C(F)c1ccc(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)cccco1
Invalid SMILES: N#CPN(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: N#[PH]N(c1ccc(C=[PH](=O)(O)O)cc1)c1ccccoc(-c2ccccc2)cc1
Invalid SMILES: Nc1cc(C=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=P(O)(O)Cc1ccc(N(c2ccccc2)c2ccc([PH](=O)(O)(O)O)cc2)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)C1=CCC(=[PH](=O)(O)O)C=C1
Invalid SMILES: N#CN(C1=CC=C(C(=O)O)[IH]C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#Cc1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(C=C(CF)C(=O)O)cc2)cc1
Invalid SMILES: O=C(F)C1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=CC2)c2ccc(C=[PH](=O)(O)O)cc2)cccco1
Invalid SMILES: N#CPN(C1=CC=C(c2ccccc2)OCC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: Nc1cc(PC=[PH](=O)(O)O)ccc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=[PH](O)(O)=Cc1cccc(N(c2ccccc2)c2ccc(O)cc2)c1
Invalid SMILES: N#[PH]C1=CC=C(N(c2ccccc2)c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C2)c2cccc(C=[PH](=O)(O)O)c2)cccco1
Invalid SMILES: N#CPN(c1ccccc2cc(cc1)C=CC=CC=CP2)c1ccc(PC=[PH](=O)(O)O)cc1
Invalid SMILES: N#CN(C1=CC=C(c2ccccc2)C=CC=C1)c1ccc(PC=[PH](=O)(O)O)cc1
Invalid SMILES: O=C(F)c1ccc(N(C2=CC=C=C2)c2ccc(PC=[PH](=O)(O)O)cc2)ccc([PH](=O)O)oc1
Invalid SMILES: O=[PH](O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(O)cc2)cc1
Invalid SMILES: N#CBC(=Cc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=C/C(=C\c1ccc(O)cc1)c1ccc(N(PC2=CC=C2)c2ccccc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC=C=C2)C2=CC(=[PH](=O)(O)O)C=C2)C=CO1
Invalid SMILES: N#CBN(C1=CC=C(c2cccs2)C=CC=C1)c1ccc(C=[PH](=O)(O)O)cc1
Invalid SMILES: N#Cc1cc(C=[PH](=O)(O)O)cc(N(c2ccccc2)c2ccccc2)c1

[13:07:34] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC=C(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH](=O)O)C=CC=C1
Invalid SMILES: O=C(F)C1=CC=C(N(c2ccc(PC=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)C=CC=C1
Invalid SMILES: O=C(F)C1=CC(c2ccccc2)=CC=C(N(c2ccc(C=[PH](=O)(O)O)cc2)[PH]2=CC=CC=C2)C=C[IH]1
Invalid SMILES: N#C/C(=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1)PC=[PH](=O)(O)O
Invalid SMILES: O=C(O)C1=CC(C2=CC=C2)=CC=C(N(C2=C=C=C2)c2ccc(C=[PH](=O)(O)O)cc2)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(Br)cc1N(c1ccccc1)c1ccccc1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccc(C=[PH](=O)(O)O)cc2)c2ccc([PH](=O)O)cc2)C=CO1
Invalid SMILES: O=C(O)C1=CC=C(N2C3=CC=C(C=CO3)/C=C(/C=[PH](=O)(O)O)PC=C=CC=Cc3ccc2cc3)C=CC=C1
Invalid SMILES: N#C/C(C=[PH](=O)(O)O)=C/c1ccc(N(C2=CC=CC2)c2ccccc2)cc1
Invalid SMILES: O=[PH](O)c1ccc(N(C2=CC=C(C3=CC=C3)C=CC=C2)C2=CC(=[PH](=O)(O)O)C=C2)cc1
Invalid SMILES: N#CPC1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccccc2)c2ccc(PC=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: N#CC1=CC=C(C=[PH](=O)(O)O)C=CC(N(C2=CC=CC2)c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=C(COC(=O)c1ccc(N(c2ccccc2)N(c2ccccc2)c2ccccc2)cc1)OCC=[PH](=O)(O)O
Invalid SMILES: O=P(O)(O)c1ccc(N(C2=CC=NC2=[PH](=O)(O)O)c2ccc(O)cc2)cc1
Invalid SMILES: N#CP/C(C=[PH](=O)(O)O)=C/c1ccc(N(c2ccccc2)c2ccccc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-n2c3ccccc3c3ccccc32)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(-n3c4ccccc4c4ccccc43)cc2)cc1

[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(C2=CC=CC2)c2ccccc2)cc1)c1ccc(-c2cccc(O)c2)cc1
Invalid SMILES: O=Pc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC(c3ccc(C4=CC=C4)cc3)=C2)c2ccc(O)cc2)=C1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C#P(=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccccc1

[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:34] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P1(O)(O)=CC=C(N(C2=CC=CC(c3ccc(O)cc3)C=C2)C2=CC=C(c3ccccc3)OC=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC=C3)cc2)=CC1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=C=C1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(C3=CC=CC3)cc2)=C1

[13:07:35] Explicit valence for atom # 31 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(N(C2=CC=C2)C2=CC(c3ccc(-c4ccccc4)cc3)=CC=C(C=[PH](=O)(O)O)C=C2)cccco1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(c2ccc(O)cc2)c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CCOc1ccc(N(C2=CC=C(c3ccccc3)OC=C2)c2ccc(C3=CC=C3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1

[13:07:35] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 28 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(N(C2=CCC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccccc3)cc2)cccco1
Invalid SMILES: N#Cc1ccc(C(C=[PH](=O)(O)O)=C2C=CC(N(c3ccccc3)c3ccccc3)=CO2)cc1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccccc1
Invalid SMILES: N#Cc1ccc(C(=Cc2ccc(N(c3ccccc3)c3ccccc3)cc2)C=[PH](=O)(O)O)cc1

[13:07:35] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:07:35] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 22 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=C(O)C=[PH](=O)(O)O)C=C2)c2ccc(C3=CC=C3)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(O)cc1
Invalid SMILES: O=[PH](O)(O)=CBc1ccc(N(c2ccccc2)c2ccc(-c3ccccc3)cc2)cc1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(C4=CC=C4)cc3)cc2)C=CO1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(C2=CC=CC2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(PC=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=CC=C(c3ccccc3)OC=C2)c2ccc(C3=CC=C3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=CC(O)C=C1
Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1)C(F)(F)F
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1

[13:07:36] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#CC(=Pc1ccc(-c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1)C(=O)O
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(C2=CC=CCC=C2)c2ccccc2)cc1)c1cccc(O)c1
Invalid SMILES: N#CC(=CC(O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(C=[PH](=O)(O)O)cc3)cc2)=C1)C(=O)O
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(C(=O)O)cc3)cc2)C=CO1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N(C2=C=CC=C2)C2=CC=C(c3ccccc3)OC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(O)cc1)c1ccc(N(C2=CC=C2)C2=CC=CC(c3ccccc3)C=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPC1=CC=C(N(C2=CC=CC=CC=C2)c2ccccc2)OC=C1)c1ccc(C2=CC=C2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(O)cc1)c1ccc(N(C2=CC=C2)c2ccc(C3=CC=C3)cc2)cc1
Invalid SMILES: O=C(O)c1ccc(N(c2ccc(C=[PH](=O)(O)O)cc2)c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)cccco1
Invalid SMILES: O=C(O)C1=CC=C(N(C2=CC(=CC=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(C4=CC=C=C4)cc3)cc2)C=CO1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(N(C2=CC=C2)c2ccc(N(c3ccccc3)c3ccccc3)cc2)=C1

[13:07:36] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 31 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(=[PH](=O)(O)O)ccc3C3=CC=C3)cc2)cc1
Invalid SMILES: N#CC(=CC1=CC=C(c2ccc(N(c3ccccc3)c3ccc(PC=[PH](=O)(O)O)cc3)cc2)C1)C(=O)C=O
Invalid SMILES: O=C(O)C1=CC=C(N(c2ccc(C3=CC=CC(C4=CC=C=C4)C=C3)cc2)c2cccc(=[PH](=O)(O)O)cc2)C=CO1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(N(C3=CC(=C(O)C=[PH](=O)(O)O)C=C3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC=CC(C2=CC=C=C2)C=C1

[13:07:36] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:36] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:07:37] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(CC=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC(c2ccccc2)C=C1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccccc2)c2ccccc2)cc1)c1ccc(C2=CC=C=C2)cc1
Invalid SMILES: O=C(O)c1ccc(N(C2=CCC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccccc3)cc2)cc1

[13:07:37] Explicit valence for atom # 13 P, 7, is greater than permitted

Invalid SMILES: O=C(O)CCn1cc(-c2ccc(C=[PH](=O)(O)O)cc3c4cccn4c4ccc(cc4)c=3c2)ccc1=O

[13:07:40] Explicit valence for atom # 24 P, 7, is greater than permitted

Invalid SMILES: O=C1c2ccc3c4c(ccc1c24)C(=O)N(Cc1ccc(O)cc1)C(=[PH](=O)(O)O)C(=O)N(Cc1ccncc1)C3=O

[13:07:40] Explicit valence for atom # 36 P, 7, is greater than permitted

Invalid SMILES: O=Cn1c(=O)c2ccc3c(=O)n(Cc4ccccc4)c(=O)n(Cc4ccncc4)c(=O)c4c(C=CC=[PH](=O)(O)O)cc(c1=O)c2c34

[13:07:41] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:07:41] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:07:41] Explicit valence for atom # 27 P, 7, is greater than permitted

Invalid SMILES: O=c1c2ccc3c(=O)n(-c4ccc(O)cc4)c2c3ccn1-c1ccc(C(=CC=[PH](=O)(O)O)C2=CC=C2)cc1
Invalid SMILES: O=c1c2ccc3c(=O)n(-c4ccc(O)cc4)c(=O)c-3c3ccc(c(=O)n1CC=[PH](=O)(O)O)c2cc3P
Invalid SMILES: O=c1c2ccc3c(=O)n(-c4cccc(O)c4)c(=O)c4ccc(c(=O)n1CC=[PH](=O)(O)O)c3c24

[13:07:47] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(C(F)(F)F)cn1

[13:07:49] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CN=C1

[13:08:24] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: N#Cc1cccc(=[PH](=O)(O)O)cc1

[13:08:27] Explicit valence for atom # 10 P, 7, is greater than permitted

Invalid SMILES: O=Cc1cncc(C=CC=[PH](=O)(O)O)c1O

[13:08:28] Explicit valence for atom # 7 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(C=[PH](=O)(O)O)cc1

[13:08:45] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(CCCCn1ccnc1)C(F)(F)F

[13:08:46] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=c1cccc(C(F)(F)F)cc1C(F)(F)F

[13:08:56] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: O=C1CC=CC(=[PH](=O)(O)O)C=CC(C(F)(F)F)=CO1

[13:09:02] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(O)Cc1ccc(S)cc1

[13:09:04] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(CCO)CCO)cc1

[13:09:06] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(N(CCO)CCCCO)cc1

[13:09:12] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)(c1nccn1Cc1c[nH]cn1)C(F)(F)F

[13:09:16] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2cccs2)S1

[13:09:17] Explicit valence for atom # 15 P, 7, is greater than permitted

Invalid SMILES: N#CC(C#N)=Cc1ccc(-c2ccc(C=[PH](=O)(O)O)s2)s1

[13:09:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:17] Explicit valence for atom # 6 P, 7, is greater than permitted
[13:09:17] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(=O)(O)(O)c1ccc(S)cc1
Invalid SMILES: O=c1ccc(C=[PH](=O)(O)O)c(-c2cccs2)s1
Invalid SMILES: O=[PH](O)(O)=c1cccc(-c2cccs2)s1

[13:09:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:18] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:09:18] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc(-c2cccs2)cc1
Invalid SMILES: N#CC1=CC=C(C=[PH](=O)(O)O)c2ccccc2S1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccc(-c3ccccc3)cc2)c[nH]1

[13:09:18] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccccc1-c1cccs1

[13:09:18] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(PC=[PH](=O)(O)O)s2)s1

[13:09:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:19] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:19] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:09:19] Explicit valence for atom # 14 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CPc1sc(-c2cccs2)cc1O
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)N=C(c2ccccc2)S1
Invalid SMILES: O=C(Cl)c1cc(-c2ccc(C3=CC=C3)cc2)sc(=[PH](=O)(O)O)c1Cl
Invalid SMILES: Nc1cc(-c2cccs2)sc1C=CC=[PH](=O)(O)O

[13:09:19] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=Cc1ccc(-c2ccc(C=[PH](=O)(O)O)s2)s1

[13:09:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:21] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CPc1ccc2c(c1)sc1c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=c1ccc2c3ccc(c2s1)Sc1ccccc1-3
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)sc1c3ccccc3sc21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2sc3c4ccccc4sc3c2c1

[13:09:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)sc1c3ccc(Cl)cc3sc21

[13:09:22] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:09:22] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:22] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)c1ccc(-c2ccc3[nH]c4ccc(-c5ccc([PH](=O)(=O)O)cc5)cc4c3c2)cc1
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccc(-c3ccccc3)cc2c2cc(-c3ccccc3)ccc21
Invalid SMILES: O=[PH](O)(O)=CCCCCn1c2ccc(-c3ccccc3)cc2c2cc(-c3ccccc3)ccc21

[13:09:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:23] Explicit valence for atom # 47 P, 7, is greater than permitted
[13:09:23] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:09:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:23] Explicit valence for atom # 48 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: CC(=CC(C1=CC=C=C(C2=CC=C=CC=C2)C=C1)=C1C=CC(c2ccc(N(C3=CC=CCC3)c3ccc(C4=CC=C4)cc3)cc2)=C1)C=[PH](=O)(O)O
Invalid SMILES: C=CC(C=[PH](=O)(O)O)=C1C=CC(c2ccc(N(c3ccccc3)c3ccc(-c4ccc(N(C5=CC=C=C=C5)C5=CC=CC=CC5)cc4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: CC(=CC1=CC1=CC=c1ccc(=CC=C2C=CC2=CC=CC=C2CC2=CC=C2C=CC(=O)N2C2=CCC=C2)n1C=C=CC1=C=CCS1)C=[PH](=O)(O)O

[13:09:23] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:23] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:09:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:24] Explicit valence for atom # 46 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC2=CC=c2ccc3n2N2C(=CC=C=CC=CC1)CC=CC=C2CCC=CC=C1C=CC1=CC=3
Invalid SMILES: O=C(O)C1=COC(=CC(=CC=[PH](=O)(O)O)C2=CC(C3=CC=CCC=C3)C=CC=C(c3ccc4n5c(ccccccc35)C4)C=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=CCCc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=CC2=CC=c2ccc3n2N(C=C=CC=c2ccoc2=CC=C2C=CC2=CC=3)CC=CC=CC=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC1=CC2=C(O)C2=CC=c2ccc3n2C(=CC=C2CC=CC(N(C4=CC=C4)C4=CC=CC4)=CC=C2C=CC1)C=CC=CC=3
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC2=CC3=CC=CCC=CC=C4C=CC(C=C5C=CC5=CC=C21)N43)C1C=CC=C1)N(C1=C=C=CC=C1)C1=CC=CC1
Invalid SMILES: CC=C1C=C=CC=CC=C2CC=CC=C3C=CC=CC=C4C=CC(C=CC=C5C=CC5=CC=c5ccc(n52)=CC=C2C=C2C=C(C=[PH](=O)(O)O)C=C1)N34

[13:09:24] Explicit valence for atom # 48 P, 7, is greater than permitted
[13:09:24] Explicit valence for atom # 47 P, 7, is greater than permitted
[13:09:24] Explicit valence for atom # 49 P, 7, is greater than permitted

Invalid SMILES: C=CC(=Cc1c(=CC=C2C=C=C=C2)cccccc2n3c(ccc3ccc3cccccc4ccc(ccc5ccc15)n34)=CCC=C2)C=[PH](=O)(O)O
Invalid SMILES: CC(=CC1=CC1=CC=c1ccc2n1C=C=CC=CCC=C=c1ccc(n1-c1ccccc1)=CC=C1C=CC1=CC=C1C=CC1=CC=2)C=[PH](=O)(O)O
Invalid SMILES: CC(=CC(C1=CC=C(c2ccc(N(C3=C=CCC=C=C3)C3CC=C=C=CC3)cc2)C1)=C1C=CC=C(c2cccc(C3=CC=CC3)c2)C=C1)C=[PH](=O)(O)O

[13:09:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:24] Explicit valence for atom # 48 P, 7, is greater than permitted
[13:09:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:24] Explicit valence for atom # 37 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc-2ccc2ccc3n2c(ccc2ccc(cccccc4ccc1C=C=C4)n2C1=CC=C1)C=CCC=C1C=CC1=CC=3
Invalid SMILES: CCC(=CC(C1=CC2C=C=CC=CC=CN(C3=C=CCC=C3)c3ccc(cc3)-c3ccc(cc3)C(=C2)C=C1)=C1C=CC(C(=O)O)=CO1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=CC1=CC(=C2C=CC(N(C3=CC=C(c4ccccc4)C=CC=C3)c3ccc(N(C4=CCC=C4)c4ccccc4)cc3)=C2)C=CC=C=C=C1
Invalid SMILES: O=[PH](O)(O)=CC=CC1=C(O)C1=CC=c1ccc2ccc3ccc3ccc3ccc3ccc3ccc(cccccccccn12)n3C1=CCC=CC1
Invalid SMILES: O=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc(-c4ccc(N(c5ccccc5)c5ccc(C=[PH](=O)(O)O)cc5)cc4)cc3)cc2)cc1
Invalid SMILES: C=CC=C=CC(=CC1=CC1=Cc1cccc2ccc3c(ccc4c(ccc(N(C5=CC=C=C5)C5=CC=C5)ccccn12)CO4)C=C3)C=[PH](=O)(O)O

[13:09:24] Explicit valence for atom # 47 P, 7, is greater than permitted
[13:09:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 47 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 38 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 41 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 41 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 37 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1C=C=CC=CN(C2=CC=C=CCC=C2)c2ccc(cc2)-c2ccc(cc2)N(c2ccccc2)c2ccc(cc2)C2=CCOC(=C1)C=C2
Invalid SMILES: CC(=CC1=C2C=CC(=C2)c2ccc(cc2)N(C2=CC=C2)c2ccc(cc2)N(C2=CC=CCC2)C2=C(C=C=C2)CC=CC=CC=C=C1)C=[PH](=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=CCC=C=C3)c3ccc(-c4ccc(-c5ccc(C6=CC=C6)cc5)cc4)cc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(C1=CC(c2ccc(C3=CC=CCC3)cc2)C=CC1)=C1C=CC(c2ccccc2)=C1)c1ccccc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C#N)C(=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1)CC(=O)O
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: N#CC(C=O)C(=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1)CCC=O
Invalid SMILES: N#CC(C(=O)C=O)C(C=O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N3C4=CC=C(c5ccccc5)C=CC3=CC=C(c3ccccc3)C=C4)cc2)cc1
Invalid SMILES: N#CC(C=O)=CC(C=O)=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)c2)cc1
Invalid SMILES: N#CC(C#N)C(=CC1=CC=C(c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)C1)C(=O)C=O
Invalid SMILES: O=CCC(C=O)=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=CC=[PH](=O)(O)O)cc4)cc3)c2)cc1

[13:09:25] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 35 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccc(N(C3=CC=CC(c4ccc(C5=CC=C5)cc4)C=C3)c3ccccc3)cc2)S1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(c2ccc(N(C3=CC=C=C3)c3ccc(-c4ccc(C5=CC=C5)cc4)cc3)cc2)=CC1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccc(C=O)cc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4C=O)cc3)cc2)cc1
Invalid SMILES: N#CC(=CC1=CC=C(c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)cc2)C1)C(=O)C=O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccccc4)cc3)cc2O)cc1
Invalid SMILES: O=CCOc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(-c2cccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(C=[PH](=O)(O)O)cc4)cc3)c2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccccc2)cc1N(c1ccc(-c2ccccc2)cc1)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1

[13:09:25] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:09:25] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3cccc(-c4ccc(F)cc4)c3)cc2)cc1
Invalid SMILES: O=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3ccc(-c4ccc(CC=[PH](=O)(O)O)cc4)cc3)cc2)cc1
Invalid SMILES: O=Cc1ccc(C2=CC=C3C=CC(c4ccccc4)=CC=C(C=C2)N3c2ccc(-c3ccc(C=[PH](=O)(O)O)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC1=CC=NN(c2ccccc2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=CCN1c2ccccc2C(F)(F)c2ccc(F)cc21

[13:09:25] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCN1c2ccc(Br)cc2Cc2cc(Br)ccc21

[13:09:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC1=CC=C(N2c3ccccc3Cc3ccccc32)C=C(Br)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2C3=CC2=C(Br)C=C3)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(O)c2c1ccc1cccnc12

[13:09:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccnc2cc(Cl)ccc12
Invalid SMILES: O=[PH](O)(O)=CCc1cc2c3ccccc3sc2c2c1[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2c3sc4ccccc4c3ccc21

[13:09:26] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 44 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 38 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:09:26] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 38 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 41 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 25 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc3c(cc21)sc1ccccc13
Invalid SMILES: O=C=CC1C=C2C(=C1c1c3cc(n1CC[PH](=O)(O)(O)O)-c1c-3n(CCCP(=O)(O)O)c3ccccc13)N2CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3ccc-3c(N3C=CCC=C3)c3cc4n(CCC[PH](=O)(O)(O)O)c3c-4c21
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C13CC=C=CC(C(NCCP(=O)(O)O)=C1c1[nH]c4ccccc4c1-2)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=C1c2c(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c2[nH]c2ccccc23)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=c1c2ccc(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c4ccc4n(CCCP(=O)(O)O)c23)n1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1C(NCC[PH](=O)(O)(O)O)=C1c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CC[PH](=O)(O)(O)O)C3=CC3)c3cc4n(CCCI(=O)(O)O)c3c-4c21
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1C=CC(=C3C=CC=C4C2=C3N4CCC[PH](=O)(O)(O)O)N(C2=C=C2)C1
Invalid SMILES: NC1=C2C(NCC[PH](=O)(O)(O)O)=C2c2[nH]c3ccccc3c2-c2c1c1ccccc1n2CCCP(=O)(O)O
Invalid SMILES: Cn1c2ccccc2c2c1c1c3ccccc3n(C=O)c1c1c3ccccc3n(P(=O)(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(C(=C3CC=N3)N1CCC[PH](=O)(O)(O)O)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CCC3=C1C(NCC[PH](=O)(O)(O)O)=C3c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C1C=CC=CC(=N3)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C=CC=C1C(=C3CN3CCC[PH](=O)(O)(O)O)n3c1c-2c1ccccc13
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c4c(c5c(n4CCC[PH](=O)(O)(O)O)C=C5)c4c(c5ccccc5n4CCCP(=O)(O)O)c31)CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CCc3c-2c2c(n3CCC[PH](=O)(O)(O)O)C=CC(C=C2)C1=C1CN1CCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=C3C=NC(S3)C2=C(C2=CCC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(c21)C(=C1C=CC=C1)N4CCC[PH](=O)(O)(O)O)C1C=C=C1C1(O)C=CC1=N3
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1c3nc(C4C=CC=C4)c-2c(c3=CC2=CC=C2)n1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(c3[nH]c4ccccc4c3-2)C2(C=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CC[PH](=O)(O)(O)O)C=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=[PH](O)(O)=C[IH]c1ccc2c(c1)[nH]c1c3ccccc3c3c4ccccc([nH]c23)c41
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(C3=CC(=N1)N3CCC[PH](=O)(O)(O)O)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c3c4c(c(c5c(c1=3)=C5NCC[PH](=O)(O)(O)O)NCC=CC=CC=2)c1ccccc1n4CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CCC[PH](=O)(O)(O)O)C=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c1c1c3ccccc3n(CC[PH](=O)(O)(O)O)c1c1c3ccccc3n(CCCP(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(ccn4CCC[PH](=O)(O)(O)O)c21)C1=CC=C(C=CC1)N3C1CCCC1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CC[PH](=O)(O)(O)O)CC=C4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCC=C1NC1=C1c2c(n(CCCP(=O)(O)O)c3ccccc23)C2=C(C=C2C2CCCC=N2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ncccc2c2cccc3c(NCC[PH](=O)(O)(O)O)c-3c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCN1C2=CC=Cc3c1c2c1c(c3N(CC[PH](=O)(O)(O)O)C2C=CC=C2)c2ccccc2n1CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CCP(=O)(O)O)C3=CCC=C3)c3c4c(c21)C(=CC=C3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(ccn3CCC[PH](=O)(O)(O)O)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(n3CCC[PH](=O)(O)(O)O)CC=CC4)c3[nH]c4ccccc4c3c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccc3cc2c2cc(C4C=CC=C4)c(cc21)n(CC[PH](=O)(O)(O)O)c1ccc3=1
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C(=C1C=CC1)N(CCC[PH](=O)(O)(O)O)C1=C(C=CCC=C1)c1[nH]c3ccccc3c1-2

[13:09:27] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 44 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 31 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 43 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 8 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 32 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c4c5c(n(CCC[PH](=O)(O)(O)O)c4c3n(CCCP(=O)(O)O)c2c2ccccc21)C5
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ncccc5c4c21)C(=C1C=N1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCC=NC1=c2cc3n(CCC[PH](=O)(O)(O)O)c2=C3c2c(c3ccccc3n2CCCP(=O)(O)O)-c2ncccc21
Invalid SMILES: O=c1c2c3[nH]c4ccccc4c3c3c(c4ccccc4n3CCCP(=O)(O)O)c2[nH]c2ccc-2n1CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCN1C(=C2CN2CCC[PH](=O)(O)(O)O)c2c1c1c(c3c4ccccc4n(CCCP(=O)(O)O)c23)N=CCC=C1
Invalid SMILES: O=P(O)(O)CCCN1C2=CC=CC3C(=C4C(=C41)c1c2c2ccccc2n1CCCP(=O)(O)O)C1=NC(CCCC1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCN1C(=C2C=CCC=C2)C1=C1C=CCC=Cc2c3c1n(CCC[PH](=O)(O)(O)O)c2-c1c-3n(CCCP(=O)(O)O)c2ccccc12
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)[PH](=O)(O)(O)CC=CN3
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)[PH](=O)(O)(O)CCN3
Invalid SMILES: O=C1c2c(c3c4ccccc4n(CCCP(=O)(O)O)c3c3c2[nH]c2ccccc23)N1CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC=C(c3ccccc3N(CCCC[PH](=O)(O)(O)O)SN1)c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCN1C(=C2C=CC=C2)c2c1c1c3ccccc3n(CC[PH](=O)(O)(O)O)c1c1c3ccccc3n(CCCP(=O)(O)O)c21
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3ncc(c4[nH]c5ccccc5c4c21)c1c3n1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c1c1c3ccc4c(ccn4CC4=CCC=C4)c1n(CCC[PH](=O)(O)(O)O)c32
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1=CC(C3=C4C=C=CC3N4CC[PH](=O)(O)(O)O)=C(CN1)c1ccccc1-2
Invalid SMILES: O=P(O)(O)CCCN1c2c(c3c(c4ccccc4n3CCC[PH](=O)(O)(O)O)c3c2c2ccccc2n3CCCP(=O)(O)O)C12C=CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=Cc1c-2c(C2=CC=CC3N=CC23)n2c1P(=O)(O)(O)(O)CCC2
Invalid SMILES: O=P(O)(O)CCCNC1=C2C1=C(NCC[PH](=O)(O)(O)O)c1c(n(CCCP(=O)(O)O)c3ccccc13)-c1c2[nH]c2ccccc12
Invalid SMILES: O=P(O)(O)CCCCCn1c2ccc3c2c2c(ccn2CCC[PH](=O)(O)(O)O)c2c(c4ccccc4n2CCCP(=O)(O)O)c31
Invalid SMILES: O=P(O)(O)CCCn1c2cccc3c(C=C4C=CC5C(=C4)N5CC[PH](=O)(O)(O)O)c(c1-3)-c1c-2c2ccccc2n1CCCP(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c(N(CCC[PH]3=CC=C3)C3=CCC=C=C3)c3c4c(c21)C(=CC=CC3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3[nH]c4c(n(CCC[PH](=O)(O)(O)O)c5ccccc5c3c3[nH]c5ccccc5c3c21)=CC=4
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=CC1C=N1)N3CC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1NC3=C(CC=CC3)C2=C(C2=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=[PH](O)CCNC1=C2C(NCC[PH](=O)(O)(O)O)=C2c2[nH]c3ccccc3c2-c2c1c1ccccc1n2CCCP(=O)(O)O
Invalid SMILES: Nc1c2c(NCCC[PH](=O)(O)(O)O)c3c-2n2c(cccc4c5ccccc5n(CCCP(=O)(O)O)c4c1-3)CCCCC2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=CC1C=N1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1cc(c1NCC[PH](=O)(O)(O)O)-c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c1c1c4ccccc4n(CCC[PH](=O)(O)(O)O)c1c1c4ccccc4n(CCCP(=O)(O)O)c31)C=C2
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)CN3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3c4c(ccn4CCC[PH](=O)(O)(O)O)c4c(c5ccccc5n4CCCP(=O)(O)O)c31)CC=C2
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)-c1c3c-2c(n1CCC[PH](=O)(O)(O)O)C(=C1N=C1C1C=CC=CC1)C=CC=C3
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c21)C(=C1CC=NS1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C(N(CCO)C1=CC1)=C1C(NCC[PH](=O)(O)(O)O)=C1c1[nH]c3ccccc3c1-2
Invalid SMILES: O=P(O)(O)CCCn1c2cc3c1=C2c1c(c2ccccc2n1CCCP(=O)(O)O)C=C=C1CN(CC[PH](=O)(O)(O)O)C=31
Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)CC=C1NC1=C1C2=C(C2=CC=C2)N1CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccc2c2c1c1c(NCC[PH](=O)(O)(O)O)c-1cc1c3ccccc3n(CCCP(=O)(O)O)c12
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c4c5c(c6c(c(c(c21)C=CP(O)CC5)n3CCC[PH](=O)(O)(O)O)=CCC=6)N4

[13:09:27] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 37 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:09:27] Explicit valence for atom # 39 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)CCCn1c2c(c3ccccc31)C1C=NC3C=CC=C4NC4=C4C2=C(C1=CC=C3)N4CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2c3c(c4c(c21)=C4N(CCP(=O)(O)O)C1=CC=C1)C=C=CC1C=3N1CC[PH](=O)(O)(O)O
Invalid SMILES: Nc1c2cccc3n(CCCP(=O)(O)O)c-2c-3c2c(c3ccccc3n2CCCP(=O)(O)O)c2c1c1c(n2C[PH](=O)(O)(O)O)C1

[13:09:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:28] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:09:28] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:09:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:28] Explicit valence for atom # 12 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)C=C1
Invalid SMILES: N#CC1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=C(OCC=[PH](=O)(O)O)c1ccc(-c2ccccc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(c2ccccc2)=CS1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(c2ccccc2)S1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=C(C(=O)O)C=C1

[13:09:28] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:09:28] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:09:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:28] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:28] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(C2=CC(=CC=[PH](=O)(O)O)C=C2)cc1
Invalid SMILES: N#CC1=CC=CC(c2ccc(C=[PH](=O)(O)O)cc2)=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC(c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=C1C=CC(C2=CC=C(c3ccccc3)C=CC=C2)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=CC(c2ccccc2)=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C2=CC=C=CC=C2)C=C1
Invalid SMILES: O=[PH](O)(O)=c1ccc(C(F)(F)F)cc(-c2ccccc2)c1
Invalid SMILES: O=[PH](O)(O)=CC=Cc1ccc(-c2ccccc2)cc1

[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=C(O)C1=CC=C(C2=CC=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: N#CC1=CC=C(C2=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC#Cc1ccc(-c2ccccc2)cc1
Invalid SMILES: O=C(O)c1ccc(-c2ccc(C=[PH](=O)(O)O)cc2)cc1
Invalid SMILES: N#CC(=Cc1ccc(-c2ccc(C#CC=[PH](=O)(O)O)cc2)cc1)C(=O)O
Invalid SMILES: O=P1(O)(O)=CC=C(c2ccc(-c3ccccc3)cc2)C=C1
Invalid SMILES: N#CC1=CC=C(C2=CC=CC(=CC=[PH](=O)(O)O)C=C2)C=CC=C1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc([IH]C=[PH](=O)(O)O)cc2)C=CC=C1

[13:09:29] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 6 P, 7, is greater than permitted

Invalid SMILES: N#Cc1ccc(=[PH](=O)(O)O)cc(-c2ccccc2)c1
Invalid SMILES: N#Cc1ccc(-c2ccc(=[PH](=O)(O)O)cc(C(=O)O)c2)cc1
Invalid SMILES: O=C(O)C1=CC=C(c2ccc(C=[PH](=O)(O)O)cc2)C=CC=C1
Invalid SMILES: O=[PH](O)(O)=CC=C1C=CC=C(C2=CC=C(C(F)(F)F)C=CC=C2)C=C1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=C=C1
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)C1C=CCC(=C1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)n1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=CC1
Invalid SMILES: O=P(O)(O)CCCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=CC1
Invalid SMILES: O=C(CCCn1c2ccccc2c2cc3c(cc21)Nc1ccccc1N3CCCCCO)OCCC=[PH](=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)C1C=CC(=C1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(=O)(O)(O)On1c2ccccc2c2cc3c(cc21)[nH]c1ccccc13
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCCC[PH](=O)(O)(O)O
Invalid SMILES: N#CC(O)=Cn1c2ccccc2c2cc3c(cc21)c1ccccc1n3P(=O)(=O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)-c1cccc(c1)N3CCC[PH](=O)(O)(O)O
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c(cc21)c1c(n3CCC[PH](=O)(O)(O)O)C=C1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12

[13:09:29] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 31 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=[PH](O)(O)=CC=CCc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=[PH](O)(O)=CCc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2ccc3c4ccccc4[nH]c3c21
Invalid SMILES: O=[PH](O)(O)=CCn1c2c(c3ccccc31)C=Cc1ccccc1N2
Invalid SMILES: O=[PH](O)(O)=CCCCn1c2ccccc2c2c3ccccc3[nH]c21
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)[nH]c1c3ccccc3[nH]c21
Invalid SMILES: O=P(=O)(O)(O)Oc1cc2c3ccccc3[nH]c2c2[nH]c3ccccc3c12
Invalid SMILES: O=P(=O)(O)(O)Oc1ccc2c(c1)[nH]c1c3ccccc3[nH]c21
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2cc3c(cc21)c1ccccc1n3CCCCCCO
Invalid SMILES: O=P(O)(O)CCCn1c2ccccc2c2cc3c4ccccc4n(CC[PH](=O)(O)(O)O)c3cc21
Invalid SMILES: O=C(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc4n(C5=CC=CC5)cccc3-4)cc2)cc1
Invalid SMILES: O=P(=O)(O)(O)CCCCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(-c2ccc(N(C3=CC=C(c4ccccc4)PC=C3)c3ccccc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=P(O)(O)#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=C1)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(N4C=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CC(=C1C=CC=C1)c1ccc(N(C2=CC=C2)c2ccc(-c3ccccc3)cc2)cc1)c1ccccc1

[13:09:29] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:29] Explicit valence for atom # 1 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#CC(CO)=C1C=CC(c2ccc(N(C3=CC=C(C4=CC=C(c5ccccc5)CC=C4)CC=C3)c3ccccc3)cc2)=C1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=c1ccc(-c2ccccc2)cc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4)cc3)cc2)c1
Invalid SMILES: O=[PH](O)(O)=CPc1ccc(N(c2ccccc2)c2ccc(-c3ccc4cc3-c3ccccc3N4)cc2)c2c1=CC=2
Invalid SMILES: O=[PH](O)(O)=CC(=C[IH]c1ccc(-c2ccc(-c3cccc(C4=CC=C=C4)c3)cc2)cc1)N1C=CC=C(O)C1
Invalid SMILES: O=[PH](O)(O)=C(C1=CC=CC1)c1ccc(-c2ccc(N(c3ccccc3)c3ccc(N4C=CC=CC4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2c1[nH]c1ccccc12
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1c2ccccc3n4c(ccc4ccc4ccc-4ccc12)=CC=CCC=CC=3)NC1=CC=CC1
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(N(c2ccc(C3=CC=C3)cc2)c2ccc(-c3ccccc3)cc2)cc1)c1ccccc1
Invalid SMILES: O=P(O)(O)#CC1C=C2C(=CC=C3C=CC3=CC=CC=CC=NSN1)N(C1=CC=C1)c1ccc(cc1)-c1ccc2cc1
Invalid SMILES: O=P(O)(O)#CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=CCPCOC(=CC=C1C=CC(N(c2ccccc2)c2ccc3cccccc2-3)=C1)c1ccc(N=C2CC=CC2)cc1
Invalid SMILES: O=[PH](O)(O)=CC(=CPC1=CC=C(c2ccc(N(C3=CC=C3)C3=CC=C3)cc2)OCC=C1)c1ccc(N(C2=CC=C=C=C2)c2ccccc2)cc1

[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 11 P, 7, is greater than permitted

Invalid SMILES: O=P(O)(O)#CC#Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4cc3-c3ccccc3N4)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)c2c1C=C2
Invalid SMILES: O=[PH](O)(O)=CCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21
Invalid SMILES: O=[PH](O)(O)=CC(=Cc1ccc(-c2ccc(N(C3=CC=C=C(C4=C=CC=C4)C=C3)C3=CC=CC3)cc2)cc1)C1=CC=C=C1
Invalid SMILES: O=[PH](O)(O)=CC(=CPc1ccc(N(c2ccccc2)c2ccccc2)cc1)C1=CC2=CC=C(C=C1)N1C=CCC=CC=CC=C21
Invalid SMILES: O=C(O)c1ccc(N(C2=CC(=[PH](=O)(O)O)C=C2)c2ccc(-c3ccc(N(C4=CC=C4)C4=CC=CCC=C4)cc3)cc2)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1cc2cc2ccc2ccccc3cccccc(ccc4ccc4cccccc1=CC1=CC=CC=CC1)n32
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N(c2ccccc2)c2ccc(-c3ccc4[nH]c5ccccc5c4c3)cc2)c2ccccc12
Invalid SMILES: O=C(CCCn1c2ccccc2c2cc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)ccc21)OCC#P(=O)(O)O
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3cc(Cl)ccc3Sc3ccc(Cl)cc32)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc(N2c3ccccc3Sc3ccccc32)cc1
Invalid SMILES: O=[PH](O)(O)=C1Sc2ccccc2N(c2ccccc2)c2ccccc21
Invalid SMILES: O=[PH](O)(O)=C1C=CC(N2c3ccccc3Sc3ccccc32)=C1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)Sc1ccccc1N2c1ccccc1
Invalid SMILES: O=P(=O)(O)(O)c1ccc2c(c1)Sc1ccccc1N2c1ccc(Br)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)N(c1ccccc1)c1ccccc1S2
Invalid SMILES: O=[PH](O)(O)=CSc1ccc2c(c1)N(c1ccccc1)c1ccccc1S2
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)Sc1ccccc1N2c1ccc(F)cc1
Invalid SMILES: O=[PH](O)(O)=Cc1ccc2c(c1)Sc1cc(Cl)ccc1N2c1ccccc1

[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 40 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted
[13:09:30] Explicit valence for atom # 1 P, 7, is greater than permitted

In [5]:
print(df_1.shape)
print(df_2.shape)
print(df_3.shape)
print(df_4.shape)
print(df_5.shape)
print(df_6.shape)
print(df_7.shape)

(103, 6)
(4693, 6)
(24582, 6)
(11075, 6)
(4284, 6)
(13552, 6)
(135149, 6)

In [6]:
sam_substructures_matching = pd.concat([df_2, df_3, df_4, df_5, df_6])
print(sam_substructures_matching.shape)

(58186, 6)

In [7]:
smiles_substructures_matching = sam_substructures_matching.loc[:, ["smiles"]].reset_index(drop=True)
smiles_substructures_matching

                                                  smiles
0      O=C(O)c1ccc2c3c(ccc(C(=O)O)c13)C(=O)N(CCP(=O)(...
1         O=C(O)c1ccc2c3c(cccc13)C(=O)N(CCP(=O)(O)O)C2=O
2      O=C1c2cccc3c(-c4ccc(C(F)(F)F)cc4)ccc(c23)C(=O)...
3      O=C(O)c1ccc2c3c(ccc(C(F)(F)Cl)c13)C(=O)N(CCP(=...
4                 O=C1c2cccc3cccc(c23)C(=O)N1CCP(=O)(O)O
...                                                  ...
58181  O=P(O)(O)CCOc1ccc(OCCOCCOCCOCCOCCOCCOCCOCCOCCO...
58182                     O=P(O)(O)CCOC1=CC=C(F)C(F)C=C1
58183     N#CC(C#N)=C(C(=O)O)c1ccc(C(=O)OCCP(=O)(O)O)cc1
58184  COCCOCCOCCOCCOCCOCCOCCOCCOCCOc1ccc(OCCP(=O)(O)...
58185                   N#CC1=CC=C(P(=O)(O)O)CSC(C#N)=C1

[58186 rows x 1 columns]

In [8]:
sam_structure_matching = smiles_substructures_matching.iloc[smiles_substructures_matching.index[~smiles_substructures_matching.loc[:,"smiles"].isna()],:]
sam_structure_matching

                                                  smiles
0      O=C(O)c1ccc2c3c(ccc(C(=O)O)c13)C(=O)N(CCP(=O)(...
1         O=C(O)c1ccc2c3c(cccc13)C(=O)N(CCP(=O)(O)O)C2=O
2      O=C1c2cccc3c(-c4ccc(C(F)(F)F)cc4)ccc(c23)C(=O)...
3      O=C(O)c1ccc2c3c(ccc(C(F)(F)Cl)c13)C(=O)N(CCP(=...
4                 O=C1c2cccc3cccc(c23)C(=O)N1CCP(=O)(O)O
...                                                  ...
58181  O=P(O)(O)CCOc1ccc(OCCOCCOCCOCCOCCOCCOCCOCCOCCO...
58182                     O=P(O)(O)CCOC1=CC=C(F)C(F)C=C1
58183     N#CC(C#N)=C(C(=O)O)c1ccc(C(=O)OCCP(=O)(O)O)cc1
58184  COCCOCCOCCOCCOCCOCCOCCOCCOCCOc1ccc(OCCP(=O)(O)...
58185                   N#CC1=CC=C(P(=O)(O)O)CSC(C#N)=C1

[58186 rows x 1 columns]

In [9]:
sam_structure_matching = sam_structure_matching.rename(columns={"smiles": "SMILES"})
sam_structure_matching

                                                  SMILES
0      O=C(O)c1ccc2c3c(ccc(C(=O)O)c13)C(=O)N(CCP(=O)(...
1         O=C(O)c1ccc2c3c(cccc13)C(=O)N(CCP(=O)(O)O)C2=O
2      O=C1c2cccc3c(-c4ccc(C(F)(F)F)cc4)ccc(c23)C(=O)...
3      O=C(O)c1ccc2c3c(ccc(C(F)(F)Cl)c13)C(=O)N(CCP(=...
4                 O=C1c2cccc3cccc(c23)C(=O)N1CCP(=O)(O)O
...                                                  ...
58181  O=P(O)(O)CCOc1ccc(OCCOCCOCCOCCOCCOCCOCCOCCOCCO...
58182                     O=P(O)(O)CCOC1=CC=C(F)C(F)C=C1
58183     N#CC(C#N)=C(C(=O)O)c1ccc(C(=O)OCCP(=O)(O)O)cc1
58184  COCCOCCOCCOCCOCCOCCOCCOCCOCCOc1ccc(OCCP(=O)(O)...
58185                   N#CC1=CC=C(P(=O)(O)O)CSC(C#N)=C1

[58186 rows x 1 columns]

In [10]:
sam_structure_matching.to_csv("./sam_structure_matching_0225.csv")

Energy level matching

In [24]:
sam_structure_matching = pd.read_csv("./sam_structure_matching_0225.csv")

In [25]:
from unimol_tools import MolPredict
import os

In [26]:
!pwd

/data/Jn/Screening_flow

In [28]:
homo_weights_path = r"/data/Jn/Unimol/weights_fix_0226/homo/bs_32_lr_1e-4"
input_csv = r"./tmp.csv"

In [29]:
pd.DataFrame(sam_structure_matching.iloc[:,1]).to_csv(input_csv, index=False)

In [30]:
os.environ["CUDA_VISIBLE_DEVICES"] = "2"
homo_clf = MolPredict(load_model=homo_weights_path)

In [31]:
# 基于SMILES的文件输入模式的预测 
homo_pred = homo_clf.predict(data=input_csv)

2026-03-17 13:25:31 | unimol_tools/data/conformer.py | 126 | INFO | Uni-Mol Tools | Start generating conformers...
58186it [47:23, 20.46it/s]
2026-03-17 14:12:56 | unimol_tools/data/conformer.py | 135 | INFO | Uni-Mol Tools | Succeeded in generating conformers for 100.00% of molecules.
2026-03-17 14:12:56 | unimol_tools/data/conformer.py | 142 | INFO | Uni-Mol Tools | Succeeded in generating 3d conformers for 99.03% of molecules.
2026-03-17 14:12:56 | unimol_tools/data/conformer.py | 145 | INFO | Uni-Mol Tools | Failed 3d conformers indices: [236, 335, 377, 563, 595, 2379, 2839, 3540, 3581, 3583, 3603, 3628, 4420, 4425, 4447, 4497, 4575, 4638, 4681, 5691, 5695, 5700, 5701, 5711, 5716, 6447, 6550, 6644, 6795, 6864, 6911, 7009, 7010, 7086, 7243, 7249, 7387, 7441, 7460, 7565, 7605, 7630, 7649, 7715, 7722, 7875, 8000, 8001, 8036, 8102, 8134, 8140, 8146, 8212, 8321, 8377, 8493, 8542, 8548, 8554, 8590, 8596, 8648, 8659, 8685, 8710, 8727, 8731, 8753, 8784, 8970, 9501, 9558, 9610, 9641, 9720, 9746, 9830, 9852, 9943, 9956, 10003, 10087, 10117, 10185, 10187, 10234, 10996, 12185, 12579, 12829, 13252, 13598, 13657, 13854, 13890, 13947, 14359, 14437, 14679, 14768, 14769, 14857, 14892, 15067, 15157, 15261, 15281, 15432, 15460, 15593, 15599, 15616, 15670, 15749, 15760, 15783, 15798, 15799, 15818, 16114, 16128, 16154, 16172, 16320, 16347, 16355, 16368, 16374, 16393, 16412, 16424, 16497, 16502, 16503, 16524, 16555, 16590, 16594, 16632, 16665, 16677, 16686, 16691, 16697, 16700, 16705, 16761, 16768, 16770, 16814, 16933, 16936, 16948, 17282, 17661, 17885, 17977, 18153, 18188, 18350, 18402, 18479, 18506, 19654, 20044, 20209, 20478, 20481, 20827, 21151, 21420, 21535, 21564, 21596, 21928, 22216, 22433, 22510, 22523, 22545, 22580, 22582, 22583, 22584, 22588, 22590, 22591, 22592, 22593, 22594, 22595, 22596, 22598, 22599, 22600, 22601, 22602, 22604, 22605, 22607, 22608, 22616, 22617, 22618, 22620, 22621, 22622, 22624, 22625, 22626, 22627, 22628, 22629, 22630, 22631, 22632, 22633, 22634, 22636, 22637, 22638, 22640, 22641, 22642, 23244, 23249, 24721, 24732, 24733, 24745, 24829, 24889, 24910, 24917, 24939, 25050, 25063, 25116, 25128, 25201, 25228, 25251, 25327, 25397, 25435, 25437, 25448, 25475, 25477, 25557, 25569, 25590, 25747, 25753, 25763, 25767, 25786, 25818, 25823, 25937, 25942, 25946, 25955, 26093, 26174, 26175, 26196, 26234, 28317, 28318, 28322, 28325, 28328, 28337, 28338, 28342, 28343, 28350, 28351, 28353, 28355, 28359, 28380, 28412, 28417, 28424, 28438, 28444, 28497, 28509, 28538, 28580, 28586, 28646, 28682, 28737, 28756, 28758, 28772, 28777, 28781, 28789, 28814, 28827, 28828, 29246, 30070, 30083, 30146, 30269, 30495, 30575, 31033, 31217, 31485, 31525, 31540, 32487, 32507, 32513, 32523, 32526, 32537, 32545, 32561, 32569, 32571, 32577, 32581, 32586, 32589, 32594, 32669, 32746, 33157, 33185, 33413, 33445, 33468, 33957, 33975, 34580, 34647, 35028, 35053, 35244, 35268, 35327, 35330, 35571, 35794, 35847, 35925, 36072, 36083, 36089, 36122, 36186, 36314, 36338, 36363, 36408, 36484, 36505, 36608, 36675, 36680, 36713, 36764, 36789, 36822, 36838, 36880, 36889, 36999, 37001, 37007, 37014, 37107, 37118, 37163, 37164, 37166, 37170, 37187, 37207, 37217, 37221, 37250, 37260, 37324, 37372, 37411, 37426, 37436, 37437, 37457, 37518, 37522, 37532, 37543, 37551, 37603, 37604, 37631, 37646, 37663, 37667, 37668, 37673, 37684, 37727, 37744, 37749, 37759, 37770, 37780, 37781, 37790, 37801, 37804, 37809, 37824, 37839, 37887, 37905, 37924, 37947, 37951, 37964, 37993, 37995, 37999, 38047, 38058, 38059, 38064, 38080, 38096, 38109, 38146, 38154, 38181, 38182, 38203, 38220, 38224, 38225, 38228, 38240, 38255, 38271, 38276, 38282, 38287, 38404, 38459, 38572, 38721, 38741, 38840, 38869, 38923, 39058, 39220, 39223, 39226, 39619, 39785, 39953, 39984, 40038, 40070, 40077, 40183, 40245, 40341, 41020, 41021, 41022, 41024, 41025, 41026, 41027, 41031, 41032, 41033, 42139, 44582, 44583, 44584, 44587, 44593, 44594, 44595, 44597, 44598, 44600, 44601, 44603, 44604, 44605, 44606, 44612, 44627, 44628, 45317, 45965, 45986, 45989, 45992, 45993, 45995, 45996, 45997, 45998, 45999, 46002, 46391, 46411, 46427, 46429, 46582, 46630, 46784, 46919, 46965, 47073, 47270, 47332, 47394, 47402, 47475, 47606, 47638, 47693, 47815, 47859, 47937, 47963, 47979, 48043, 48081, 48103, 48162, 48228, 48369, 48482, 48511, 48557, 48612, 48655, 48701, 48793, 51472, 51710, 51854, 52351, 52962, 53539, 53939, 56185, 56622, 57584]
2026-03-17 14:12:56 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/miniconda3/envs/unimol_fix/lib/python3.10/site-packages/unimol_tools-0.1.2.post2-py3.10.egg/unimol_tools/weights/mol_pre_no_h_220816.pt
2026-03-17 14:12:58 | unimol_tools/models/nnmodel.py | 228 | INFO | Uni-Mol Tools | start predict NNModel:unimolv1
2026-03-17 14:12:58 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/homo/bs_32_lr_1e-4/model_0.pth
2026-03-17 14:12:59 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/homo/bs_32_lr_1e-4/model_0.pth
2026-03-17 14:12:59 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!
2026-03-17 14:13:28 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/homo/bs_32_lr_1e-4/model_1.pth
2026-03-17 14:13:30 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/homo/bs_32_lr_1e-4/model_1.pth
2026-03-17 14:13:30 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!
2026-03-17 14:13:59 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/homo/bs_32_lr_1e-4/model_2.pth
2026-03-17 14:14:00 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/homo/bs_32_lr_1e-4/model_2.pth
2026-03-17 14:14:00 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!
2026-03-17 14:14:28 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/homo/bs_32_lr_1e-4/model_3.pth
2026-03-17 14:14:29 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/homo/bs_32_lr_1e-4/model_3.pth
2026-03-17 14:14:29 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!
2026-03-17 14:14:54 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/homo/bs_32_lr_1e-4/model_4.pth
2026-03-17 14:14:55 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/homo/bs_32_lr_1e-4/model_4.pth
2026-03-17 14:14:55 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!

In [32]:
homo_pred_results = pd.DataFrame({
    "smiles": homo_clf.datahub.data["smiles"],
    "homo_pred": homo_pred.flatten(),
    })
homo_pred_results.head(10)

                                              smiles  homo_pred
0  O=C(O)c1ccc2c3c(ccc(C(=O)O)c13)C(=O)N(CCP(=O)(...  -6.937585
1     O=C(O)c1ccc2c3c(cccc13)C(=O)N(CCP(=O)(O)O)C2=O  -6.785887
2  O=C1c2cccc3c(-c4ccc(C(F)(F)F)cc4)ccc(c23)C(=O)...  -6.560483
3  O=C(O)c1ccc2c3c(ccc(C(F)(F)Cl)c13)C(=O)N(CCP(=...  -7.043255
4             O=C1c2cccc3cccc(c23)C(=O)N1CCP(=O)(O)O  -6.634214
5          O=C1c2cccc3c(O)ccc(c23)C(=O)N1CCP(=O)(O)O  -6.251120
6  O=C(O)c1ccc2c3c(ccc(C(F)(F)F)c13)C(=O)N(CCP(=O...  -7.072617
7  O=C(O)c1ccc2c3c(ccc(F)c13)C(=O)N(CCP(=O)(O)O)C2=O  -6.698513
8  O=C(O)c1ccc2c3c(ccc(C(F)(F)C(F)(F)F)c13)C(=O)N...  -7.080913
9              O=C1c2cccc3cccc(c23)C(=O)N1CP(=O)(O)O  -6.685623

In [35]:
lumo_weights_path = r"/data/Jn/Unimol/weights_fix_0226/lumo/bs_32_lr_1e-4"

In [36]:
lumo_clf = MolPredict(load_model=lumo_weights_path)

In [37]:
lumo_pred = lumo_clf.predict(data=input_csv)

2026-03-17 14:27:57 | unimol_tools/data/conformer.py | 126 | INFO | Uni-Mol Tools | Start generating conformers...
58186it [47:34, 20.38it/s]
2026-03-17 15:15:33 | unimol_tools/data/conformer.py | 135 | INFO | Uni-Mol Tools | Succeeded in generating conformers for 100.00% of molecules.
2026-03-17 15:15:33 | unimol_tools/data/conformer.py | 142 | INFO | Uni-Mol Tools | Succeeded in generating 3d conformers for 99.03% of molecules.
2026-03-17 15:15:33 | unimol_tools/data/conformer.py | 145 | INFO | Uni-Mol Tools | Failed 3d conformers indices: [236, 335, 377, 563, 595, 2379, 2839, 3540, 3581, 3583, 3603, 3628, 4420, 4425, 4447, 4497, 4575, 4638, 4681, 5691, 5695, 5700, 5701, 5711, 5716, 6447, 6550, 6644, 6795, 6864, 6911, 7009, 7010, 7086, 7243, 7249, 7387, 7441, 7460, 7565, 7605, 7630, 7649, 7715, 7722, 7875, 8000, 8001, 8036, 8102, 8134, 8140, 8146, 8212, 8321, 8377, 8493, 8542, 8548, 8554, 8590, 8596, 8648, 8659, 8685, 8710, 8727, 8731, 8753, 8784, 8970, 9501, 9558, 9610, 9641, 9720, 9746, 9830, 9852, 9943, 9956, 10003, 10087, 10117, 10185, 10187, 10234, 10996, 12185, 12579, 12829, 13252, 13598, 13657, 13854, 13890, 13947, 14359, 14437, 14679, 14768, 14769, 14857, 14892, 15067, 15157, 15261, 15281, 15432, 15460, 15593, 15599, 15616, 15670, 15749, 15760, 15783, 15798, 15799, 15818, 16114, 16128, 16154, 16172, 16320, 16347, 16355, 16368, 16374, 16393, 16412, 16424, 16497, 16502, 16503, 16524, 16555, 16590, 16594, 16632, 16665, 16677, 16686, 16691, 16697, 16700, 16705, 16761, 16768, 16770, 16814, 16933, 16936, 16948, 17282, 17661, 17885, 17977, 18153, 18188, 18350, 18402, 18479, 18506, 19654, 20044, 20209, 20478, 20481, 20827, 21151, 21420, 21535, 21564, 21596, 21928, 22216, 22433, 22510, 22523, 22545, 22580, 22582, 22583, 22584, 22588, 22590, 22591, 22592, 22593, 22594, 22595, 22596, 22598, 22599, 22600, 22601, 22602, 22604, 22605, 22607, 22608, 22616, 22617, 22618, 22620, 22621, 22622, 22624, 22625, 22626, 22627, 22628, 22629, 22630, 22631, 22632, 22633, 22634, 22636, 22637, 22638, 22640, 22641, 22642, 23244, 23249, 24721, 24732, 24733, 24745, 24829, 24889, 24910, 24917, 24939, 25050, 25063, 25116, 25128, 25201, 25228, 25251, 25327, 25397, 25435, 25437, 25448, 25475, 25477, 25557, 25569, 25590, 25747, 25753, 25763, 25767, 25786, 25818, 25823, 25937, 25942, 25946, 25955, 26093, 26174, 26175, 26196, 26234, 28317, 28318, 28322, 28325, 28328, 28337, 28338, 28342, 28343, 28350, 28351, 28353, 28355, 28359, 28380, 28412, 28417, 28424, 28438, 28444, 28497, 28509, 28538, 28580, 28586, 28646, 28682, 28737, 28756, 28758, 28772, 28777, 28781, 28789, 28814, 28827, 28828, 29246, 30070, 30083, 30146, 30269, 30495, 30575, 31033, 31217, 31485, 31525, 31540, 32487, 32507, 32513, 32523, 32526, 32537, 32545, 32561, 32569, 32571, 32577, 32581, 32586, 32589, 32594, 32669, 32746, 33157, 33185, 33413, 33445, 33468, 33957, 33975, 34580, 34647, 35028, 35053, 35244, 35268, 35327, 35330, 35571, 35794, 35847, 35925, 36072, 36083, 36089, 36122, 36186, 36314, 36338, 36363, 36408, 36484, 36505, 36608, 36675, 36680, 36713, 36764, 36789, 36822, 36838, 36880, 36889, 36999, 37001, 37007, 37014, 37107, 37118, 37163, 37164, 37166, 37170, 37187, 37207, 37217, 37221, 37250, 37260, 37324, 37372, 37411, 37426, 37436, 37437, 37457, 37518, 37522, 37532, 37543, 37551, 37603, 37604, 37631, 37646, 37663, 37667, 37668, 37673, 37684, 37727, 37744, 37749, 37759, 37770, 37780, 37781, 37790, 37801, 37804, 37809, 37824, 37839, 37887, 37905, 37924, 37947, 37951, 37964, 37993, 37995, 37999, 38047, 38058, 38059, 38064, 38080, 38096, 38109, 38146, 38154, 38181, 38182, 38203, 38220, 38224, 38225, 38228, 38240, 38255, 38271, 38276, 38282, 38287, 38404, 38459, 38572, 38721, 38741, 38840, 38869, 38923, 39058, 39220, 39223, 39226, 39619, 39785, 39953, 39984, 40038, 40070, 40077, 40183, 40245, 40341, 41020, 41021, 41022, 41024, 41025, 41026, 41027, 41031, 41032, 41033, 42139, 44582, 44583, 44584, 44587, 44593, 44594, 44595, 44597, 44598, 44600, 44601, 44603, 44604, 44605, 44606, 44612, 44627, 44628, 45317, 45965, 45986, 45989, 45992, 45993, 45995, 45996, 45997, 45998, 45999, 46002, 46391, 46411, 46427, 46429, 46582, 46630, 46784, 46919, 46965, 47073, 47270, 47332, 47394, 47402, 47475, 47606, 47638, 47693, 47815, 47859, 47937, 47963, 47979, 48043, 48081, 48103, 48162, 48228, 48369, 48482, 48511, 48557, 48612, 48655, 48701, 48793, 51472, 51710, 51854, 52351, 52962, 53539, 53939, 56185, 56622, 57584]
2026-03-17 15:15:33 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/miniconda3/envs/unimol_fix/lib/python3.10/site-packages/unimol_tools-0.1.2.post2-py3.10.egg/unimol_tools/weights/mol_pre_no_h_220816.pt
2026-03-17 15:15:34 | unimol_tools/models/nnmodel.py | 228 | INFO | Uni-Mol Tools | start predict NNModel:unimolv1
2026-03-17 15:15:34 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/lumo/bs_32_lr_1e-4/model_0.pth
2026-03-17 15:15:35 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/lumo/bs_32_lr_1e-4/model_0.pth
2026-03-17 15:15:35 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!
2026-03-17 15:16:01 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/lumo/bs_32_lr_1e-4/model_1.pth
2026-03-17 15:16:02 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/lumo/bs_32_lr_1e-4/model_1.pth
2026-03-17 15:16:02 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!
2026-03-17 15:16:28 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/lumo/bs_32_lr_1e-4/model_2.pth
2026-03-17 15:16:29 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/lumo/bs_32_lr_1e-4/model_2.pth
2026-03-17 15:16:30 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!
2026-03-17 15:16:54 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/lumo/bs_32_lr_1e-4/model_3.pth
2026-03-17 15:16:56 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/lumo/bs_32_lr_1e-4/model_3.pth
2026-03-17 15:16:56 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!
2026-03-17 15:17:26 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/lumo/bs_32_lr_1e-4/model_4.pth
2026-03-17 15:17:27 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/lumo/bs_32_lr_1e-4/model_4.pth
2026-03-17 15:17:27 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!

In [38]:
homo_lumo_pred_results = pd.DataFrame({
    "smiles": homo_clf.datahub.data["smiles"],
    "homo_pred": homo_pred.flatten(),
    "lumo_pred": lumo_pred.flatten()
    })
homo_lumo_pred_results.head(10)

                                              smiles  homo_pred  lumo_pred
0  O=C(O)c1ccc2c3c(ccc(C(=O)O)c13)C(=O)N(CCP(=O)(...  -6.937585  -2.964517
1     O=C(O)c1ccc2c3c(cccc13)C(=O)N(CCP(=O)(O)O)C2=O  -6.785887  -2.929513
2  O=C1c2cccc3c(-c4ccc(C(F)(F)F)cc4)ccc(c23)C(=O)...  -6.560483  -2.603282
3  O=C(O)c1ccc2c3c(ccc(C(F)(F)Cl)c13)C(=O)N(CCP(=...  -7.043255  -3.109828
4             O=C1c2cccc3cccc(c23)C(=O)N1CCP(=O)(O)O  -6.634214  -2.580982
5          O=C1c2cccc3c(O)ccc(c23)C(=O)N1CCP(=O)(O)O  -6.251120  -2.449607
6  O=C(O)c1ccc2c3c(ccc(C(F)(F)F)c13)C(=O)N(CCP(=O...  -7.072617  -3.068961
7  O=C(O)c1ccc2c3c(ccc(F)c13)C(=O)N(CCP(=O)(O)O)C2=O  -6.698513  -2.784639
8  O=C(O)c1ccc2c3c(ccc(C(F)(F)C(F)(F)F)c13)C(=O)N...  -7.080913  -3.095295
9              O=C1c2cccc3cccc(c23)C(=O)N1CP(=O)(O)O  -6.685623  -2.627611

In [39]:
homo_lumo_pred_results.shape

(58186, 3)

In [40]:
!pwd

/data/Jn/Screening_flow

In [41]:
homo_lumo_pred_results.to_csv("./homo_lumo_pred_results_0225.csv")

In [42]:
os.remove(input_csv)

In [43]:
homo_matching = homo_lumo_pred_results[(homo_lumo_pred_results['homo_pred'] >= -5.16) & (homo_lumo_pred_results['homo_pred'] <= -4.96)]

In [44]:
homo_lumo_matching = homo_matching[(homo_matching['lumo_pred']>= -3.43)]
homo_lumo_matching

                                                  smiles  homo_pred  lumo_pred
138    O=C(O)c1ccc2c3c(ccc(P(=O)(O)O)c13)C(=O)N(CC1=C...  -5.063533  -2.783137
170    O=C(O)c1ccc2c3c(ccc(P(=O)(O)O)c13)C(=O)N(CCC1=...  -4.964583  -2.851781
1750   O=C1c2cccc3c(-c4ccc(O)cc4)ccc(c23)C(=O)N1CC=C(...  -5.073866  -2.211550
2124   O=C1c2cc(NCCO)c3c4c(cc(NCCO)c(c24)C(=O)N1CCOCC...  -5.045514  -2.255361
2177   Nc1cc2c3c(c(NCCO)cc4c3c1C(=O)N4CCO)C(=O)N(CCP(...  -5.151244  -2.273200
...                                                  ...        ...        ...
57906                          O=P(O)(O)CCCC1=CC=C(O)CO1  -5.095724   0.004304
57962                            O=P(O)(O)Cc1ccc(O)[nH]1  -5.016892   0.522320
57982                   O=P(O)(O)CCCc1ccc(N(CCO)CCCO)cc1  -5.114193   0.054949
58080              O=P(O)(O)CCCCCCC(=Cc1cc(O)c(O)cc1O)CO  -5.021735  -0.258625
58103      O=C(O)CCCCCC=c1ccc(=CCCPCCCCCCCCP(=O)(O)O)cc1  -5.052477  -1.493995

[6947 rows x 3 columns]

In [45]:
homo_lumo_matching = homo_lumo_matching.rename(columns={"smiles": "SMILES"})

Dipole moment screening

In [46]:
dm_input_csv = r"./dm_tmp.csv"

In [47]:
pd.DataFrame(homo_lumo_matching.iloc[:,0]).to_csv(dm_input_csv, index=False)

In [50]:
dm_weights_path = r"/data/Jn/Unimol/weights_fix_0226/dm/bs_32_lr_1e-4"

In [51]:
dm_clf = MolPredict(load_model=dm_weights_path)

In [52]:
dm_pred = dm_clf.predict(data=dm_input_csv)

2026-03-17 15:18:53 | unimol_tools/data/conformer.py | 126 | INFO | Uni-Mol Tools | Start generating conformers...
6947it [10:58, 10.54it/s]
2026-03-17 15:29:52 | unimol_tools/data/conformer.py | 135 | INFO | Uni-Mol Tools | Succeeded in generating conformers for 100.00% of molecules.
2026-03-17 15:29:52 | unimol_tools/data/conformer.py | 142 | INFO | Uni-Mol Tools | Succeeded in generating 3d conformers for 97.88% of molecules.
2026-03-17 15:29:52 | unimol_tools/data/conformer.py | 145 | INFO | Uni-Mol Tools | Failed 3d conformers indices: [362, 363, 592, 671, 695, 698, 712, 738, 742, 754, 755, 772, 774, 780, 973, 987, 1621, 1836, 1874, 1903, 1932, 1941, 1955, 1985, 1992, 1993, 2063, 2090, 2170, 2182, 2206, 2213, 2259, 2260, 2288, 2306, 2309, 2348, 2367, 2395, 2398, 2399, 2486, 2503, 2548, 2601, 2656, 2658, 2717, 2726, 2728, 2732, 2734, 3192, 3199, 3201, 3209, 3218, 3225, 3243, 3266, 3285, 4062, 4064, 4066, 4068, 4075, 4080, 4089, 4095, 4102, 4115, 4116, 4117, 4381, 4400, 4428, 4502, 4535, 4698, 4703, 4707, 4716, 4720, 4723, 4729, 4732, 4759, 4863, 5121, 5356, 5360, 5432, 5513, 5526, 5530, 5531, 5535, 5538, 5543, 5551, 5552, 5555, 5556, 5564, 5566, 5576, 5584, 5589, 5594, 5598, 5601, 5603, 5604, 5606, 5617, 5621, 5624, 5627, 5630, 5631, 5633, 5640, 5641, 5645, 5646, 5818, 5856, 5865, 5883, 5933, 6163, 6301, 6315, 6334, 6345, 6391, 6419, 6481, 6482, 6483, 6484, 6485, 6486, 6487, 6488, 6489]
2026-03-17 15:29:53 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/miniconda3/envs/unimol_fix/lib/python3.10/site-packages/unimol_tools-0.1.2.post2-py3.10.egg/unimol_tools/weights/mol_pre_all_h_220816.pt
2026-03-17 15:29:54 | unimol_tools/models/nnmodel.py | 228 | INFO | Uni-Mol Tools | start predict NNModel:unimolv1
2026-03-17 15:29:54 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/dm/bs_32_lr_1e-4/model_0.pth
2026-03-17 15:29:55 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/dm/bs_32_lr_1e-4/model_0.pth
2026-03-17 15:29:55 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!
2026-03-17 15:30:02 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/dm/bs_32_lr_1e-4/model_1.pth
2026-03-17 15:30:03 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/dm/bs_32_lr_1e-4/model_1.pth
2026-03-17 15:30:04 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!
2026-03-17 15:30:10 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/dm/bs_32_lr_1e-4/model_2.pth
2026-03-17 15:30:11 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/dm/bs_32_lr_1e-4/model_2.pth
2026-03-17 15:30:11 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!
2026-03-17 15:30:18 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/dm/bs_32_lr_1e-4/model_3.pth
2026-03-17 15:30:19 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/dm/bs_32_lr_1e-4/model_3.pth
2026-03-17 15:30:19 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!
2026-03-17 15:30:26 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/dm/bs_32_lr_1e-4/model_4.pth
2026-03-17 15:30:27 | unimol_tools/models/unimol.py | 130 | INFO | Uni-Mol Tools | Loading pretrained weights from /data/Jn/Unimol/weights_fix_0226/dm/bs_32_lr_1e-4/model_4.pth
2026-03-17 15:30:27 | unimol_tools/tasks/trainer.py | 296 | INFO | Uni-Mol Tools | load model success!

In [53]:
dm_homo_lumo_pred_results = pd.DataFrame({
    "smiles": homo_lumo_matching["SMILES"],
    "homo_pred": homo_lumo_matching["homo_pred"],
    "lumo_pred": homo_lumo_matching["lumo_pred"],
    "dm_pred": dm_pred.flatten(),
    })
dm_homo_lumo_pred_results.head(10)

,smiles,homo_pred,lumo_pred,dm_pred
138,O=C(O)c1ccc2c3c(ccc(P(=O)(O)O)c13)C(=O)N(CC1=C...,-5.063533,-2.783137,3.676657
170,O=C(O)c1ccc2c3c(ccc(P(=O)(O)O)c13)C(=O)N(CCC1=...,-4.964583,-2.851781,3.642118
1750,O=C1c2cccc3c(-c4ccc(O)cc4)ccc(c23)C(=O)N1CC=C(...,-5.073866,-2.211550,7.240410
2124,O=C1c2cc(NCCO)c3c4c(cc(NCCO)c(c24)C(=O)N1CCOCC...,-5.045514,-2.255361,7.431498
2177,Nc1cc2c3c(c(NCCO)cc4c3c1C(=O)N4CCO)C(=O)N(CCP(...,-5.151244,-2.273200,7.616151
2194,O=C1c2cc(NCCO)c3c4c(cc(NCCO)c(c24)C(=O)N1CCOCC...,-5.091817,-2.223890,6.663172
2215,O=C1Nc2cc(NCCO)c3c4c(cc(NCCO)c1c24)C(=O)N(CCOC...,-5.097836,-2.257522,6.295959
2238,Nc1cc2c3c(c(NCCO)cc4c3c1C(=O)N4CCCO)C(=O)N(CCP...,-5.098373,-2.176047,7.367716
2302,Nc1cc2c3c(c(NCCO)cc4c3c1C(=O)N4)C(=O)N(CCP(=O)...,-5.077295,-2.354064,6.552734
2307,O=C1c2cc(NCCO)c3c4c(cc(NC=C(O)O)c(c24)C(=O)N1C...,-5.118326,-2.824351,4.253106

In [54]:
max(dm_homo_lumo_pred_results["dm_pred"])

11.258085250854492

In [55]:
min(dm_homo_lumo_pred_results["dm_pred"])

2.8384170532226562

In [56]:
dm_homo_lumo_pred_results.to_csv("./dm_homo_lumo_pred_results_0225.csv")

In [57]:
dm_homo_lumo_pred_results = pd.read_csv("./dm_homo_lumo_pred_results_0225.csv")

In [58]:
sorted_dm_results = dm_homo_lumo_pred_results.sort_values(by="dm_pred", ascending=False)
sorted_dm_results

,Unnamed: 0,smiles,homo_pred,lumo_pred,dm_pred
726,7855,CCCCC#CC(CCCP(=O)(O)O)CN1C(c2ccccc2)=CC(C(C#N)...,-5.124173,-2.771044,11.258085
2415,16806,O=C1C(=S)c2nsnc2C(=C(O)SCc2ccc(-c3ccc(N(c4cccc...,-5.045094,-2.797921,10.425554
2172,16350,O=NC(=O)N1C(=CC=C2C=CC=Cc3ccc2c(=O)n3-c2ccc(P(...,-5.030794,-2.257223,10.396865
2594,19747,N#CC(C#N)=Cc1ccc2ccc(-c3ccc(N(c4ccccc4)c4ccccc...,-4.973248,-2.512396,10.302239
2699,22223,N#CC(C#N)=CC(C=O)=Cc1ccc(N(CCP(=O)(O)O)c2ccc(O...,-5.089708,-2.643082,10.187170
...,...,...,...,...,...
4229,29104,O=C(OCc1ccc(N2c3cc(Cl)ccc3Sc3ccc(Cl)cc32)cc1)P...,-5.095161,-1.076345,3.062500
6069,39398,O=P(O)(O)c1cc2c([nH]1)c1ccccc1c1c3ccccc3[nH]c21,-5.000973,-0.847813,3.050416
4708,32538,O=P(O)(O)CN1Nc2ncccc2-c2cc3c(ccc4c5cc(Cl)ccc5[...,-5.105772,-1.379298,2.994482
4179,28974,O=C(OCc1ccc(N2c3ccccc3Sc3cc(Cl)ccc32)cc1)P(=O)...,-5.001625,-0.980225,2.922080
6906,55173,O=P(O)(O)CC1=CC=CCN1,-4.967846,-0.220086,2.838417

In [59]:
top_20_dm_index = int(len(sorted_dm_results) * 0.20)

In [60]:
dm_screening = sorted_dm_results.iloc[:top_20_dm_index]

In [61]:
dm_screening

,Unnamed: 0,smiles,homo_pred,lumo_pred,dm_pred
726,7855,CCCCC#CC(CCCP(=O)(O)O)CN1C(c2ccccc2)=CC(C(C#N)...,-5.124173,-2.771044,11.258085
2415,16806,O=C1C(=S)c2nsnc2C(=C(O)SCc2ccc(-c3ccc(N(c4cccc...,-5.045094,-2.797921,10.425554
2172,16350,O=NC(=O)N1C(=CC=C2C=CC=Cc3ccc2c(=O)n3-c2ccc(P(...,-5.030794,-2.257223,10.396865
2594,19747,N#CC(C#N)=Cc1ccc2ccc(-c3ccc(N(c4ccccc4)c4ccccc...,-4.973248,-2.512396,10.302239
2699,22223,N#CC(C#N)=CC(C=O)=Cc1ccc(N(CCP(=O)(O)O)c2ccc(O...,-5.089708,-2.643082,10.187170
...,...,...,...,...,...
3158,24623,O=P(O)(O)c1ccc(N(c2ccc(O)cc2)c2ccc(C3=CC=C(C4=...,-4.990768,-1.179304,6.396222
1192,10820,Nc1ccc(-c2ccc(-c3ccc(N(c4ccc(C(=O)O)cc4)c4ccc(...,-5.007040,-1.244116,6.396145
1717,12513,O=P(O)(O)c1ccc(N(c2ccc(O)cc2)c2ccc(C3=CC(C4=CC...,-5.009473,-0.896719,6.394970
1816,12816,O=P(O)(O)c1ccc(-c2cc(-c3ccc(-n4cccc4)cc3)cc(N(...,-5.061323,-0.954306,6.394267
2215,16426,O=C1SCC(=Cc2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)c(F...,-5.075871,-2.615108,6.392249

Efficiency prediction

In [62]:
import pandas as pd
import warnings
import numpy as np
from sklearn.svm import SVC
from rdkit import Chem
from tqdm import tqdm
import warnings
from data_processing import dataset_process, calculate_ecfp, normalize_predict_sample
warnings.filterwarnings("ignore", category=FutureWarning)

In [63]:
dataset_path = "./SAM_data_PCE_15%_0721.csv"

In [64]:
dataset = pd.read_csv(dataset_path)

In [65]:
# 调用dataset_process函数进行训练数据处理
features_to_include = ['ecfp', 'pvk_ions', 'pvk_bandgap', 'substrate']
processed_data, scaler_dict = dataset_process(dataset, features_to_include)

(157, 2058)
(157, 2060)

In [66]:
processed_data

,smiles,Cs_ratio,FA_ratio,Br_ratio,Bandgap,ITO,FTO,NiO,SnO2,ZnO,...,ECFP_2039,ECFP_2040,ECFP_2041,ECFP_2042,ECFP_2043,ECFP_2044,ECFP_2045,ECFP_2046,ECFP_2047,label
0,O=P(O)(O)CCCCn1c2ccccc2c2c3ccccc3ccc21,0.05,0.8000,0.000,0.21875,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,COC1=CC=C(C=C1)N(C1=CC=C(OC)C=C1)C1=CC=C(C=C1)...,0.05,0.8300,0.375,0.37500,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
2,COC1=CC=C(C=C1)N(C1=CC=C(OC)C=C1)C1=CC=C(C=C1)...,0.05,0.8300,0.375,0.37500,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
3,COC1=CC(=C(OC)C=C1)C1=CC=C(C=C1)N(C1=CC=C(C=C1...,0.05,0.7900,0.400,0.53125,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,N1C2=C(C=CC=N2)C2=C1C1=CC3=C(C=C1C=C2)C1=C(C=C...,0.00,0.0000,0.000,0.31250,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,OP(O)(=O)CCN1C2=C(C=C(C=C2)C2=CC=CC=C2)C2=C1C=...,0.15,0.6500,0.500,0.59375,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,2
153,OP(O)(=O)C(=C\C1=CC=C(C=C1)N1C2=C(SC3=C1C=CC=C...,0.00,1.0000,0.000,0.18750,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,2
154,OP(O)(=O)C(=C\C1=CC=C(C=C1)N1C2=C(SC3=C1C=CC=C...,0.05,0.9025,0.125,0.25000,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,2
155,OP(O)(=O)C(=C\C1=CC=C(C=C1)N1C2=C(SC3=C1C=CC=C...,0.05,0.7315,0.575,0.62500,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,2
156,CC1=CC=C(C=C1)N(C1=CC=C(C)C=C1)C1=CC=C(\C=C(/C...,0.05,0.8000,0.625,0.62500,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,2

In [67]:
#按骨架核心分类
df_copy = processed_data.copy()

df_1 = pd.DataFrame(columns=df_copy.columns)
df_2 = pd.DataFrame(columns=df_copy.columns)
df_3 = pd.DataFrame(columns=df_copy.columns)
df_4 = pd.DataFrame(columns=df_copy.columns)
df_5 = pd.DataFrame(columns=df_copy.columns)
df_6 = pd.DataFrame(columns=df_copy.columns)
df_7 = pd.DataFrame(columns=df_copy.columns)

# 链状
for index, row in df_copy.iterrows():
    smiles = row['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        ring_info = mol.GetRingInfo()
        num_rings = ring_info.NumRings()
        if num_rings == 0:
            df_1 = pd.concat([df_1, pd.DataFrame([row])], ignore_index=True)
            df_copy.drop(index, inplace=True)

# 萘酰胺
patt_1 = Chem.MolFromSmiles('O=C1NC(=O)C2=CC=CC3=C2C1=CC=C3')
for index, row in df_copy.iterrows():
    smiles = row['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol.HasSubstructMatch(patt_1):
        df_2 = pd.concat([df_2, pd.DataFrame([row])], ignore_index=True)
        df_copy.drop(index, inplace=True)

# 三苯胺
patt_2 = Chem.MolFromSmiles('C1=CC=C(C=C1)N(C1=CC=CC=C1)C1=CC=CC=C1')
for index, row in df_copy.iterrows():
    smiles = row['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol.HasSubstructMatch(patt_2):
        df_3 = pd.concat([df_3, pd.DataFrame([row])], ignore_index=True)
        df_copy.drop(index, inplace=True)

# 咔唑
patt_3 = Chem.MolFromSmiles('N1C2=C(C=CC=C2)C2=C1C=CC=C2')
for index, row in df_copy.iterrows():
    smiles = row['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol.HasSubstructMatch(patt_3):
        df_4 = pd.concat([df_4, pd.DataFrame([row])], ignore_index=True)
        df_copy.drop(index, inplace=True)

# 联噻吩
patt_4 = Chem.MolFromSmiles('S1C=CC=C1C1=CC=CS1')
for index, row in df_copy.iterrows():
    smiles = row['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol.HasSubstructMatch(patt_4):
        df_5 = pd.concat([df_5, pd.DataFrame([row])], ignore_index=True)
        df_copy.drop(index, inplace=True)

# 单环
for index, row in df_copy.iterrows():
    smiles = row['smiles']
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        ring_info = mol.GetRingInfo()
        num_rings = ring_info.NumRings()
        if num_rings == 1:
            df_6 = pd.concat([df_6, pd.DataFrame([row])], ignore_index=True)
            df_copy.drop(index, inplace=True)

# 其他
df_7 = df_copy.copy()

In [68]:
print(df_1.shape)
print(df_2.shape)
print(df_3.shape)
print(df_4.shape)
print(df_5.shape)
print(df_6.shape)
print(df_7.shape)

(13, 2060)
(4, 2060)
(45, 2060)
(60, 2060)
(1, 2060)
(23, 2060)
(11, 2060)

In [69]:
dm_screening = dm_screening.reset_index(drop=True)

In [70]:
processed_sam_gen = calculate_ecfp(dm_screening)

In [71]:
processed_sam_gen

,ECFP_0,ECFP_1,ECFP_2,ECFP_3,ECFP_4,ECFP_5,ECFP_6,ECFP_7,ECFP_8,ECFP_9,...,ECFP_2038,ECFP_2039,ECFP_2040,ECFP_2041,ECFP_2042,ECFP_2043,ECFP_2044,ECFP_2045,ECFP_2046,ECFP_2047
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1385,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1386,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1387,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1388,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [72]:
# 获取 processed_sam_gen 的行数
num_samples = processed_sam_gen.shape[0]

# 创建 pvk_substrate_info 字典
pvk_substrate_info = {
    'Cs_ratio': 0.05,
    'FA_ratio': 0.9025,
    'Br_ratio': 0.15,
    'PVK_Eg': 1.56,
    'ITO': 0,
    'FTO': 0,
    'NiO': 1,
    'SnO2': 0,
    'ZnO': 0,
    'TiO2': 0
}

# 将 pvk_substrate_info 重复 num_samples 次，确保行数一致
df_predict_sample = pd.DataFrame([pvk_substrate_info] * num_samples)

df_predict_sample

      Cs_ratio  FA_ratio  Br_ratio  PVK_Eg  ITO  FTO  NiO  SnO2  ZnO  TiO2
0         0.05    0.9025      0.15    1.56    0    0    1     0    0     0
1         0.05    0.9025      0.15    1.56    0    0    1     0    0     0
2         0.05    0.9025      0.15    1.56    0    0    1     0    0     0
3         0.05    0.9025      0.15    1.56    0    0    1     0    0     0
4         0.05    0.9025      0.15    1.56    0    0    1     0    0     0
...        ...       ...       ...     ...  ...  ...  ...   ...  ...   ...
1384      0.05    0.9025      0.15    1.56    0    0    1     0    0     0
1385      0.05    0.9025      0.15    1.56    0    0    1     0    0     0
1386      0.05    0.9025      0.15    1.56    0    0    1     0    0     0
1387      0.05    0.9025      0.15    1.56    0    0    1     0    0     0
1388      0.05    0.9025      0.15    1.56    0    0    1     0    0     0

[1389 rows x 10 columns]

In [73]:
pvk_substrate_info_normalized = normalize_predict_sample(df_predict_sample, scaler_dict)

In [74]:
pvk_substrate_info_normalized

      Cs_ratio  FA_ratio  Br_ratio  Bandgap  ITO  FTO  NiO  SnO2  ZnO  TiO2
0         0.05    0.9025     0.125     0.25  0.0  0.0  1.0   0.0  0.0   0.0
1         0.05    0.9025     0.125     0.25  0.0  0.0  1.0   0.0  0.0   0.0
2         0.05    0.9025     0.125     0.25  0.0  0.0  1.0   0.0  0.0   0.0
3         0.05    0.9025     0.125     0.25  0.0  0.0  1.0   0.0  0.0   0.0
4         0.05    0.9025     0.125     0.25  0.0  0.0  1.0   0.0  0.0   0.0
...        ...       ...       ...      ...  ...  ...  ...   ...  ...   ...
1384      0.05    0.9025     0.125     0.25  0.0  0.0  1.0   0.0  0.0   0.0
1385      0.05    0.9025     0.125     0.25  0.0  0.0  1.0   0.0  0.0   0.0
1386      0.05    0.9025     0.125     0.25  0.0  0.0  1.0   0.0  0.0   0.0
1387      0.05    0.9025     0.125     0.25  0.0  0.0  1.0   0.0  0.0   0.0
1388      0.05    0.9025     0.125     0.25  0.0  0.0  1.0   0.0  0.0   0.0

[1389 rows x 10 columns]

In [75]:
sam_gen_input = pd.concat([pvk_substrate_info_normalized, processed_sam_gen.iloc[:,0:]],axis=1)
sam_gen_input

,Cs_ratio,FA_ratio,Br_ratio,Bandgap,ITO,FTO,NiO,SnO2,ZnO,TiO2,...,ECFP_2038,ECFP_2039,ECFP_2040,ECFP_2041,ECFP_2042,ECFP_2043,ECFP_2044,ECFP_2045,ECFP_2046,ECFP_2047
0,0.05,0.9025,0.125,0.25,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,1,0
1,0.05,0.9025,0.125,0.25,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,0.05,0.9025,0.125,0.25,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,0.05,0.9025,0.125,0.25,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,0.05,0.9025,0.125,0.25,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,0.05,0.9025,0.125,0.25,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1385,0.05,0.9025,0.125,0.25,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1386,0.05,0.9025,0.125,0.25,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1387,0.05,0.9025,0.125,0.25,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1388,0.05,0.9025,0.125,0.25,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [76]:
from sklearn.svm import SVC
# 设置最佳超参数组合
best_params = {
    'C': 50,
    'kernel': 'linear',
    'gamma': 0.0001
}
# 用于存储20次实验中每次新分子的预测结果
new_molecule_predictions_all = []

# 遍历重复实验
for i in tqdm(range(100), desc="Training Progress"):
    dfs = [df_1, df_2, df_3, df_4, df_5, df_6]
    df_test = pd.DataFrame()
    df_train = pd.DataFrame()

    for j, df_sub in enumerate(dfs, start=1):
        if len(df_sub) <= 10:
            test_indices = np.random.choice(df_sub.index, size=1, replace=False)
        elif 10 < len(df_sub) <= 20:
            test_indices = np.random.choice(df_sub.index, size=2, replace=False)
        elif 20 < len(df_sub) <= 30:
            test_indices = np.random.choice(df_sub.index, size=3, replace=False)
        elif 30 < len(df_sub) <= 40:
            test_indices = np.random.choice(df_sub.index, size=4, replace=False)
        elif 40 < len(df_sub) <= 50:
            test_indices = np.random.choice(df_sub.index, size=5, replace=False)
        elif 50 < len(df_sub):
            test_indices = np.random.choice(df_sub.index, size=6, replace=False)
        else:
            test_indices = []

        # 将测试集数据添加到 df_test，保持原始索引号
        df_test = pd.concat([df_test, df_sub.loc[test_indices]], ignore_index=False)

        # 将剩余的数据添加到 df_train，保持原始索引号
        train_indices = df_sub.index.difference(test_indices)
        df_train = pd.concat([df_train, df_sub.loc[train_indices]], ignore_index=False)

    # 分离特征和标签
    df_train_X = df_train.iloc[:, 1:-1].astype(float)
    df_test_X = df_test.iloc[:, 1:-1].astype(float)
    df_train_label = df_train['label'].astype(int)
    df_test_label = df_test['label'].astype(int)

    # 使用最优参数训练模型
    model = SVC(C=best_params['C'],
                kernel=best_params['kernel'],
                gamma=best_params['gamma'])
    model.fit(df_train_X, df_train_label)

    # 在测试集上进行预测
    predictions = model.predict(df_test_X)
    
    # 对新分子进行预测
    new_molecules_X = sam_gen_input.astype(float)  # 假设 sam_gen_input 包含新分子的特征数据
    new_molecule_predictions = model.predict(new_molecules_X)
    
    # 记录每次实验中对新分子的预测结果
    new_molecule_predictions_all.append(new_molecule_predictions)

# 将每次预测结果转换为 NumPy 数组，计算平均值和标准差
new_molecule_predictions_all = np.array(new_molecule_predictions_all)
mean_predictions = np.mean(new_molecule_predictions_all, axis=0)

# 创建 DataFrame 来记录平均值和标准差
df_predictions = pd.DataFrame({
    'Mean_Prediction': mean_predictions,
})

Training Progress: 100%|██████████| 100/100 [00:15<00:00,  6.25it/s]

In [77]:
df_predictions

      Mean_Prediction
0                1.92
1                1.88
2                0.30
3                1.98
4                1.91
...               ...
1384             1.80
1385             1.96
1386             1.70
1387             1.86
1388             1.96

[1389 rows x 1 columns]

In [78]:
sam_gen_pred_efficiency = pd.concat([dm_screening.iloc[:,1:2], df_predictions],axis=1)
sam_gen_pred_efficiency

                                                 smiles  Mean_Prediction
0     CCCCC#CC(CCCP(=O)(O)O)CN1C(c2ccccc2)=CC(C(C#N)...             1.92
1     O=C1C(=S)c2nsnc2C(=C(O)SCc2ccc(-c3ccc(N(c4cccc...             1.88
2     O=NC(=O)N1C(=CC=C2C=CC=Cc3ccc2c(=O)n3-c2ccc(P(...             0.30
3     N#CC(C#N)=Cc1ccc2ccc(-c3ccc(N(c4ccccc4)c4ccccc...             1.98
4     N#CC(C#N)=CC(C=O)=Cc1ccc(N(CCP(=O)(O)O)c2ccc(O...             1.91
...                                                 ...              ...
1384  O=P(O)(O)c1ccc(N(c2ccc(O)cc2)c2ccc(C3=CC=C(C4=...             1.80
1385  Nc1ccc(-c2ccc(-c3ccc(N(c4ccc(C(=O)O)cc4)c4ccc(...             1.96
1386  O=P(O)(O)c1ccc(N(c2ccc(O)cc2)c2ccc(C3=CC(C4=CC...             1.70
1387  O=P(O)(O)c1ccc(-c2cc(-c3ccc(-n4cccc4)cc3)cc(N(...             1.86
1388  O=C1SCC(=Cc2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)c(F...             1.96

[1389 rows x 2 columns]

In [79]:
sorted_pce_results = sam_gen_pred_efficiency.sort_values(by="Mean_Prediction", ascending=False)
sorted_pce_results

                                                 smiles  Mean_Prediction
322   N#CC1=C(C=O)NC2=Nc3ccc4c(N=C(O)C=O)c5c6cc(CO)c...             2.00
1143         O=C/C=C/C=C/C=C/C=CC(Nc1cc[nH]c1)P(=O)(O)O             2.00
1175  COc1ccc(N(c2ccc(C3=CC=CC(c4ccccc4)PC=C3)cc2)c2...             2.00
1173  O=C(O)c1cc(P(=O)(O)O)c2c3c(cc(-c4ccccc4)cc13)N...             2.00
548   CN(C)c1ccc(-c2ccc3c(c2)c2cc(-c4ccccc4)ccc2n3-c...             2.00
...                                                 ...              ...
375   N#CC(=Cc1ccc(C(C#Cc2ccc(N(c3ccccc3)c3ccccc3)cc...             0.10
1310  O=C(O)C#CC(=O)n1c2ccc(N(c3ccccc3)c3ccccc3)cc2c...             0.09
1381  O=P(O)(O)c1ccc(N(c2ccc(O)cc2)c2ccc([PH]3=CC=CC...             0.06
428   O=C1C(=CSc2ccc(N(c3ccccc3)c3ccccc3)cc2)SC(=S)N...             0.04
58    O=C1C2=C(SC(=Cc3ccc(N(c4ccccc4)c4ccccc4)cc3)N(...             0.04

[1389 rows x 2 columns]

In [80]:
top_10_pce_index = int(len(sorted_pce_results) * 0.1)

In [81]:
pce_screening = sorted_pce_results.iloc[:top_10_pce_index]

In [82]:
pce_screening

                                                 smiles  Mean_Prediction
322   N#CC1=C(C=O)NC2=Nc3ccc4c(N=C(O)C=O)c5c6cc(CO)c...              2.0
1143         O=C/C=C/C=C/C=C/C=CC(Nc1cc[nH]c1)P(=O)(O)O              2.0
1175  COc1ccc(N(c2ccc(C3=CC=CC(c4ccccc4)PC=C3)cc2)c2...              2.0
1173  O=C(O)c1cc(P(=O)(O)O)c2c3c(cc(-c4ccccc4)cc13)N...              2.0
548   CN(C)c1ccc(-c2ccc3c(c2)c2cc(-c4ccccc4)ccc2n3-c...              2.0
...                                                 ...              ...
1297  N#CC(C(=O)C=O)C(O)=Cc1ccc(-c2cccc(N(c3ccc(-c4c...              2.0
1361  N#CC(C(=O)C=O)C(O)=Cc1ccc(-c2ccc(N(c3ccc(-c4cc...              2.0
613   N#CC(=Cc1nsc2c(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)...              2.0
1369  O=P(O)(O)c1ccc(-c2ccc3c(c2)c2cc(C4=CC=C4)ccc2n...              2.0
712   O=P(O)(O)c1nsc2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)...              2.0

[138 rows x 2 columns]

In [83]:
pce_screening.shape

(138, 2)

In [ ]:
pce_screening.iloc[:,0:1].to_csv("./pce_screening_0225.csv", index=False)

In [ ]:
def draw_molecule_with_smiles(smiles):
    mol = Chem.MolFromSmiles(smiles)
    img = Draw.MolToImage(mol, size=(300, 300))
    return img

In [ ]:
for index, row in pce_screening.iterrows():
    smiles = row['smiles']
    img = draw_molecule_with_smiles(smiles)
    
    display(img)
    print(f"smiles: {smiles}")

SAScore assessment

In [84]:
sascore = pd.read_excel("./SAScore_for_sas_score_0225.xlsx")

In [85]:
# 目标分子 SMILES 列表
target_smiles = [
    "N#C/C(=C\c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1)P(=O)(O)O", 
    "N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12)P(=O)(O)O",
    "N#CC(=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1)P(=O)(O)O"
]

# 检查每个分子是否存在
for smiles in target_smiles:
    if smiles in sascore['SMILES'].values:
        print(f"{smiles} 存在于数据集中")
    else:
        print(f"{smiles} 不存在于数据集中")

N#C/C(=C\c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1)P(=O)(O)O 存在于数据集中
N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12)P(=O)(O)O 存在于数据集中
N#CC(=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1)P(=O)(O)O 存在于数据集中

In [86]:
sascore

,ID,SMILES,Total Steps,Linear Steps,SAScore,Confidence Score,StartingMaterial,Link,SimiSAScore[Beta],DiffiScore[Beta],CompScore[Beta],FeasibilityScore,EstimatedCost,Remark,FinalStepReactants
0,NaN,N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4...,3.0,2.0,1.73,0.68,"[{""MolPrice"":""38.7576"",""Name"":""4'-BROMO-[1,1'-...",https://pro.chemiscal.com/home?smiles=N%23CC(%...,30.00,35.95,32.98,40.89,¥7507.227420000,NaN,"[""OP(O)(=O)CCCC(=O)CC#N"",""O=Cc1ccc(cc1)-c1ccc(..."
1,NaN,O=CC(C=O)=C1C=CC(c2ccc(N(c3ccc(-c4ccccc4)cc3)c...,NaN,NaN,5.00,NaN,NaN,https://pro.chemiscal.com/home?smiles=O%3dCC(C...,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,NaN,CCCCC(CCCP(=O)(O)O)C(C#N)=C(C#N)C#CC(C#CCOC)c1...,NaN,NaN,5.00,NaN,NaN,https://pro.chemiscal.com/home?smiles=CCCCC(CC...,NaN,NaN,NaN,NaN,NaN,NaN,[]
3,NaN,N#CC(C#N)=CCNc1ccc(C=COCCP(=O)(O)O)s1,6.0,5.0,2.45,0.53,"[{""MolPrice"":""5181.5097"",""Name"":""5-bromothioph...",https://pro.chemiscal.com/home?smiles=N%23CC(C...,55.77,49.98,52.88,59.62,¥50212.251540000,NaN,"[""O=CC=C(C#N)C#N"",""Nc1ccc(C=COCCP(O)(O)=O)s1""]"
4,NaN,O=P(O)(O)c1ccc(N(c2ccc(C3=CC=C(C4=CC=CC4)C=NS3...,NaN,NaN,5.00,NaN,NaN,https://pro.chemiscal.com/home?smiles=O%3dP(O)...,NaN,NaN,NaN,NaN,NaN,NaN,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,NaN,O=P(O)(O)c1ccc(N(c2ccc(O)cc2)c2ccc(C3=CC=C(c4c...,NaN,NaN,5.00,NaN,NaN,https://pro.chemiscal.com/home?smiles=O%3dP(O)...,NaN,NaN,NaN,NaN,NaN,NaN,[]
134,NaN,O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c2...,NaN,NaN,5.00,NaN,NaN,https://pro.chemiscal.com/home?smiles=O%3dP(O)...,NaN,NaN,NaN,NaN,NaN,NaN,[]
135,NaN,CCCCCC(CNc1ccc(-c2ccc(C(=C(C#N)C#N)c3ccc(N(c4c...,NaN,NaN,5.00,NaN,NaN,https://pro.chemiscal.com/home?smiles=CCCCCC(C...,NaN,NaN,NaN,NaN,NaN,NaN,[]
136,NaN,O=C(OCCCP(=O)(O)O)c1ccc2c(c1)Sc1ccccc1N2c1ccccc1,5.0,3.0,2.24,0.61,"[{""MolPrice"":""0.0159"",""Name"":""DMF"",""Smiles"":""C...",https://pro.chemiscal.com/home?smiles=O%3dC(OC...,12.23,34.92,23.58,65.88,¥21697.489440000,NaN,"[""OCCCP(O)(O)=O"",""OC(=O)c1ccc2N(c3ccccc3)c3ccc..."
137,NaN,CCCCCC(CC(CCCC)CCCP(=O)(O)O)C(=O)OCCCC(=O)N(c1...,8.0,5.0,2.83,0.69,"[{""MolPrice"":""0.0605"",""Name"":""heptanoic acid"",...",https://pro.chemiscal.com/home?smiles=CCCCCC(C...,41.95,55.42,48.69,79.09,¥35457.612300000,NaN,"[""CCCCCC(CC(CCCC)CCCP(O)(O)=O)C(O)=O"",""OCCCC(=..."

In [87]:
def process_amount_column(column):
    # 如果是 None 或 'NaN'，替换为 ￥0
    column = column.fillna('￥0').replace('NaN', '￥0')
    # 统一去掉中文或英文的人民币符号
    column = column.str.replace('￥', '', regex=False).str.replace('¥', '', regex=False)
    # 转成 float
    column = column.astype(float)
    return column

In [88]:
sascore['EstimatedCost'] = process_amount_column(sascore['EstimatedCost'])

In [89]:
sascore

,ID,SMILES,Total Steps,Linear Steps,SAScore,Confidence Score,StartingMaterial,Link,SimiSAScore[Beta],DiffiScore[Beta],CompScore[Beta],FeasibilityScore,EstimatedCost,Remark,FinalStepReactants
0,NaN,N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4...,3.0,2.0,1.73,0.68,"[{""MolPrice"":""38.7576"",""Name"":""4'-BROMO-[1,1'-...",https://pro.chemiscal.com/home?smiles=N%23CC(%...,30.00,35.95,32.98,40.89,7507.22742,NaN,"[""OP(O)(=O)CCCC(=O)CC#N"",""O=Cc1ccc(cc1)-c1ccc(..."
1,NaN,O=CC(C=O)=C1C=CC(c2ccc(N(c3ccc(-c4ccccc4)cc3)c...,NaN,NaN,5.00,NaN,NaN,https://pro.chemiscal.com/home?smiles=O%3dCC(C...,NaN,NaN,NaN,NaN,0.00000,NaN,[]
2,NaN,CCCCC(CCCP(=O)(O)O)C(C#N)=C(C#N)C#CC(C#CCOC)c1...,NaN,NaN,5.00,NaN,NaN,https://pro.chemiscal.com/home?smiles=CCCCC(CC...,NaN,NaN,NaN,NaN,0.00000,NaN,[]
3,NaN,N#CC(C#N)=CCNc1ccc(C=COCCP(=O)(O)O)s1,6.0,5.0,2.45,0.53,"[{""MolPrice"":""5181.5097"",""Name"":""5-bromothioph...",https://pro.chemiscal.com/home?smiles=N%23CC(C...,55.77,49.98,52.88,59.62,50212.25154,NaN,"[""O=CC=C(C#N)C#N"",""Nc1ccc(C=COCCP(O)(O)=O)s1""]"
4,NaN,O=P(O)(O)c1ccc(N(c2ccc(C3=CC=C(C4=CC=CC4)C=NS3...,NaN,NaN,5.00,NaN,NaN,https://pro.chemiscal.com/home?smiles=O%3dP(O)...,NaN,NaN,NaN,NaN,0.00000,NaN,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,NaN,O=P(O)(O)c1ccc(N(c2ccc(O)cc2)c2ccc(C3=CC=C(c4c...,NaN,NaN,5.00,NaN,NaN,https://pro.chemiscal.com/home?smiles=O%3dP(O)...,NaN,NaN,NaN,NaN,0.00000,NaN,[]
134,NaN,O=P(O)(O)CCCn1c2ccccc2c2c3c(c4[nH]c5ccccc5c4c2...,NaN,NaN,5.00,NaN,NaN,https://pro.chemiscal.com/home?smiles=O%3dP(O)...,NaN,NaN,NaN,NaN,0.00000,NaN,[]
135,NaN,CCCCCC(CNc1ccc(-c2ccc(C(=C(C#N)C#N)c3ccc(N(c4c...,NaN,NaN,5.00,NaN,NaN,https://pro.chemiscal.com/home?smiles=CCCCCC(C...,NaN,NaN,NaN,NaN,0.00000,NaN,[]
136,NaN,O=C(OCCCP(=O)(O)O)c1ccc2c(c1)Sc1ccccc1N2c1ccccc1,5.0,3.0,2.24,0.61,"[{""MolPrice"":""0.0159"",""Name"":""DMF"",""Smiles"":""C...",https://pro.chemiscal.com/home?smiles=O%3dC(OC...,12.23,34.92,23.58,65.88,21697.48944,NaN,"[""OCCCP(O)(O)=O"",""OC(=O)c1ccc2N(c3ccccc3)c3ccc..."
137,NaN,CCCCCC(CC(CCCC)CCCP(=O)(O)O)C(=O)OCCCC(=O)N(c1...,8.0,5.0,2.83,0.69,"[{""MolPrice"":""0.0605"",""Name"":""heptanoic acid"",...",https://pro.chemiscal.com/home?smiles=CCCCCC(C...,41.95,55.42,48.69,79.09,35457.61230,NaN,"[""CCCCCC(CC(CCCC)CCCP(O)(O)=O)C(O)=O"",""OCCCC(=..."

In [90]:
SAScore_screening = sascore[(sascore['SAScore']<= 3)& (sascore['Confidence Score'] >= 0.6)]

In [91]:
# 目标分子 SMILES 列表
target_smiles = [
    "N#C/C(=C\c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1)P(=O)(O)O", 
    "N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12)P(=O)(O)O",
    "N#CC(=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1)P(=O)(O)O"
]

# 检查每个分子是否存在
for smiles in target_smiles:
    if smiles in SAScore_screening['SMILES'].values:
        print(f"{smiles} 存在于数据集中")
    else:
        print(f"{smiles} 不存在于数据集中")

N#C/C(=C\c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1)P(=O)(O)O 存在于数据集中
N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12)P(=O)(O)O 存在于数据集中
N#CC(=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1)P(=O)(O)O 存在于数据集中

In [92]:
max(SAScore_screening['EstimatedCost'])

127247.57694

In [93]:
cost_screening = SAScore_screening[(SAScore_screening['EstimatedCost']<= 20000)]

In [94]:
# 目标分子 SMILES 列表
target_smiles = [
    "N#C/C(=C\c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1)P(=O)(O)O", 
    "N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12)P(=O)(O)O",
    "N#CC(=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1)P(=O)(O)O"
]

# 检查每个分子是否存在
for smiles in target_smiles:
    if smiles in cost_screening['SMILES'].values:
        print(f"{smiles} 存在于数据集中")
    else:
        print(f"{smiles} 不存在于数据集中")

N#C/C(=C\c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1)P(=O)(O)O 存在于数据集中
N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12)P(=O)(O)O 存在于数据集中
N#CC(=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1)P(=O)(O)O 存在于数据集中

In [95]:
step_screening = cost_screening[(cost_screening['Total Steps']<= 4)]

In [96]:
# 目标分子 SMILES 列表
target_smiles = [
    "N#C/C(=C\c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1)P(=O)(O)O", 
    "N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12)P(=O)(O)O",
    "N#CC(=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1)P(=O)(O)O"
]

# 检查每个分子是否存在
for smiles in target_smiles:
    if smiles in step_screening['SMILES'].values:
        print(f"{smiles} 存在于数据集中")
    else:
        print(f"{smiles} 不存在于数据集中")

N#C/C(=C\c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc1)P(=O)(O)O 存在于数据集中
N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nsnc12)P(=O)(O)O 存在于数据集中
N#CC(=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)c3nsnc23)cc1)P(=O)(O)O 存在于数据集中

In [97]:
step_screening

,ID,SMILES,Total Steps,Linear Steps,SAScore,Confidence Score,StartingMaterial,Link,SimiSAScore[Beta],DiffiScore[Beta],CompScore[Beta],FeasibilityScore,EstimatedCost,Remark,FinalStepReactants
0,NaN,N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4...,3.0,2.0,1.73,0.68,"[{""MolPrice"":""38.7576"",""Name"":""4'-BROMO-[1,1'-...",https://pro.chemiscal.com/home?smiles=N%23CC(%...,30.00,35.95,32.98,40.89,7507.22742,NaN,"[""OP(O)(=O)CCCC(=O)CC#N"",""O=Cc1ccc(cc1)-c1ccc(..."
13,NaN,CCCCOc1ccc(N(c2ccc(C(=O)CCCCOC(=O)CCCCP(=O)(O)...,4.0,3.0,2.00,0.80,"[{""MolPrice"":""0.5537"",""Name"":""4-bromobiphenyl""...",https://pro.chemiscal.com/home?smiles=CCCCOc1c...,41.46,31.50,36.48,46.07,15694.30566,NaN,"[""OC(=O)CCCCP(O)(O)=O"",""CCCCOc1ccc(cc1)N(c1ccc..."
20,NaN,O=P(O)(O)c1ccc2c(c1)Sc1cc(C=C(F)F)ccc1N2c1ccccc1,3.0,3.0,1.73,0.62,"[{""MolPrice"":""26.0968"",""Name"":""10-phenyl-10H-p...",https://pro.chemiscal.com/home?smiles=O%3dP(O)...,30.00,30.30,30.15,40.03,7507.22742,NaN,"[""FC(F)=Cc1ccc2N(c3ccccc3)c3ccc(Br)cc3Sc2c1""]"
27,NaN,N#CC(C#N)=Cc1ccc(P(=O)(O)O)cc1-c1ccc(-c2ccc(N(...,4.0,3.0,2.00,0.63,"[{""MolPrice"":""397.9114"",""Name"":""4-bromo-7-[4-(...",https://pro.chemiscal.com/home?smiles=N%23CC(C...,33.50,34.47,33.99,73.70,10281.48066,NaN,"[""OP(O)(=O)c1ccc(C=C(C#N)C#N)c(Cl)c1"",""CC1(C)O..."
29,NaN,O=P(O)(O)C=Cc1ccc2c(c1)Sc1cc(F)ccc1N2c1ccccc1,3.0,3.0,1.73,0.65,"[{""MolPrice"":""0.1406"",""Name"":""aniline"",""Smiles...",https://pro.chemiscal.com/home?smiles=O%3dP(O)...,30.00,29.71,29.86,64.67,11599.32312,NaN,"[""Nc1ccccc1"",""OP(O)(=O)C=Cc1ccc(Cl)c(Sc2cc(F)c..."
36,NaN,O=P(O)(O)c1ccc2c(c1)Sc1ccccc1N2c1c(F)cccc1F,2.0,2.0,1.41,0.67,"[{""MolPrice"":""122.6604"",""Name"":""3-bromo-10H-ph...",https://pro.chemiscal.com/home?smiles=O%3dP(O)...,30.00,19.97,24.99,36.12,5079.39498,NaN,"[""Fc1cccc(F)c1N1c2ccccc2Sc2cc(Br)ccc12""]"
63,NaN,N#CC(=Cc1ccc(N(c2ccc(O)cc2)c2ccc(-c3ccccc3)cc2...,4.0,3.0,2.00,0.87,"[{""MolPrice"":""1.5072"",""Name"":""4-iodobenzaldehy...",https://pro.chemiscal.com/home?smiles=N%23CC(%...,8.79,31.00,19.90,60.61,9730.09422,NaN,"[""OP(O)(=O)CC#N"",""Oc1ccc(cc1)N(c1ccc(C=O)cc1)c..."
67,NaN,COc1ccc(N(c2ccc(-c3ccccc3)cc2)c2ccc(P(=O)(O)O)...,4.0,3.0,2.00,0.87,"[{""MolPrice"":""0.5537"",""Name"":""4-bromobiphenyl""...",https://pro.chemiscal.com/home?smiles=COc1ccc(...,14.41,28.67,21.54,55.40,19376.47008,NaN,"[""OB(O)c1ccc(cc1)P(O)(O)=O"",""COc1ccc(Nc2ccc(cc..."
74,NaN,N#CC(=Cc1ccc(-c2ccc(N(c3ccc(-c4ccccc4)cc3)c3cc...,3.0,3.0,1.73,0.69,"[{""MolPrice"":""2.2101"",""Name"":""Bisbiphenyl-4-yl...",https://pro.chemiscal.com/home?smiles=N%23CC(%...,12.48,32.94,22.71,44.44,8399.26098,NaN,"[""OP(O)(=O)C(=C)C#N"",""Brc1ccc(cc1)-c1ccc(cc1)N..."
78,NaN,O=C(CCCP(=O)(O)O)OCc1ccc(-c2ccc(N(c3ccccc3)c3c...,4.0,3.0,2.00,0.67,"[{""MolPrice"":""177.9159"",""Name"":""4-phosphonobut...",https://pro.chemiscal.com/home?smiles=O%3dC(CC...,41.72,34.45,38.09,47.62,16648.40628,NaN,"[""OP(O)(=O)CCCC(=O)OCc1ccc(I)cc1"",""OB(O)c1ccc(..."
79,NaN,N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2...,3.0,2.0,1.73,0.60,"[{""MolPrice"":""39.6189"",""Name"":""7-bromo-benzo[c...",https://pro.chemiscal.com/home?smiles=N%23CC(%...,28.63,26.25,27.44,61.57,7266.17628,NaN,"[""OP(O)(=O)CC#N"",""O=Cc1ccc(-c2ccc(cc2)N(c2cccc..."
93,NaN,COc1ccc(N(c2ccc(C=C(C#N)P(=O)(O)O)cc2)c2ccc(-c...,3.0,3.0,1.73,0.95,"[{""MolPrice"":""0.1049"",""Name"":""PhMgBr"",""Smiles""...",https://pro.chemiscal.com/home?smiles=COc1ccc(...,3.10,21.94,12.52,48.12,7398.97092,NaN,"[""Br[Mg]c1ccccc1"",""COc1ccc(cc1)N(c1ccc(OC)cc1)..."
97,NaN,N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccc(-c4ccccc4...,3.0,2.0,1.73,0.80,"[{""MolPrice"":""38.7576"",""Name"":""4'-BROMO-[1,1'-...",https://pro.chemiscal.com/home?smiles=N%23CC(%...,5.52,24.78,15.15,42.72,9818.14284,NaN,"[""OP(O)(=O)CC#N"",""O=Cc1ccc(cc1)-c1ccc(cc1)N(c1..."
102,NaN,N#CC(=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4...,3.0,2.0,1.73,0.62,"[{""MolPrice"":""1.0458"",""Name"":""4,7-dibromobenzo...",https://pro.chemiscal.com/home?smiles=N%23CC(%...,30.00,26.18,28.09,69.16,7273.39338,NaN,"[""OP(O)(=O)CC#N"",""O=Cc1ccc(cc1)-c1ccc(-c2ccc(c..."
110,NaN,N#CC(=Cc1ccc(-c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4...,4.0,3.0,2.00,0.64,"[{""MolPrice"":""1.1493"",""Name"":""5,5'-dibromo-2,2...",https://pro.chemiscal.com/home?smiles=N%23CC(%...,38.67,42.05,40.36,72.34,14984.14302,NaN,"[""OP(O)(=O)CCCC(=CC(=C)C#N)C#N"",""Brc1ccc(s1)-c..."
111,NaN,N#CC(=Cc1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc...,2.0,2.0,1.41,0.80,"[{""MolPrice"":""30.7385"",""Name"":""4'-(diphenylami...",https://pro.chemiscal.com/home?smiles=N%23CC(%...,5.52,17.80,11.66,26.99,6000.29694,NaN,"[""OP(O)(=O)CC#N"",""O=Cc1ccc(cc1)-c1ccc(cc1)N(c1..."
120,NaN,N#C/C(=C/c1ccc(N(c2ccccc2)c2ccc(C3=CC=CC3)cc2)...,4.0,3.0,2.00,0.80,"[{""MolPrice"":""0.1378"",""Name"":""1,4-dibromobenze...",https://pro.chemiscal.com/home?smiles=N%23C%2f...,22.52,32.47,27.49,66.60,12061.21752,NaN,"[""Brc1ccc(cc1)C1=CC=CC1"",""OP(O)(=O)C(=C/c1ccc(..."
125,NaN,N#C/C(=C\c1ccc(N(c2ccccc2)c2ccc(C3=CC=CC3)cc2)...,4.0,3.0,2.00,0.74,"[{""MolPrice"":""0.1378"",""Name"":""1,4-dibromobenze...",https://pro.chemiscal.com/home?smiles=N%23C%2f...,22.52,32.47,27.49,58.12,19402.45164,NaN,"[""Brc1ccc(cc1)C1=CC=CC1"",""OP(O)(=O)C(=C\\c1ccc..."
131,NaN,N#C/C(=C\c1ccc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)...,2.0,2.0,1.41,0.80,"[{""MolPrice"":""30.7385"",""Name"":""4'-(diphenylami...",https://pro.chemiscal.com/home?smiles=N%23C%2f...,5.52,17.80,11.66,46.42,6000.29694,NaN,"[""OP(O)(=O)CC#N"",""O=Cc1ccc(cc1)-c1ccc(cc1)N(c1..."

In [98]:
step_screening.iloc[:,1:2].to_csv("./sas_screening_0225.csv", index=False)

In [ ]:
def draw_molecule_with_smiles(smiles):
    mol = Chem.MolFromSmiles(smiles)
    img = Draw.MolToImage(mol, size=(300, 300))
    return img

In [ ]:
for index, row in step_screening.iterrows():
    smiles = row['SMILES']
    img = draw_molecule_with_smiles(smiles)
    
    display(img)
    print(f"smiles: {smiles}")